<a href="https://colab.research.google.com/github/JORDANSPECTER/unbiased-trades-313-site/blob/main/UnBiased_Trades_AI_Analyzer_v1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [57]:
import json

with open("night_before_plan.json", "w") as f:
    json.dump(night_before_plan, f, indent=4)

In [56]:
print("\n=== LIVE DECISION TEST ===")

print(live_decision(615.12, False, False, False))  # chop
print(live_decision(619.00, True, True, False))   # bullish breakout
print(live_decision(613.20, True, False, True))   # bearish breakdown

=== LIVE DECISION TEST ===
⚠️ No Trade Zone - Wait
🚀 Bullish Breakout - Calls
🔻 Bearish Breakdown - Puts

In [55]:
def live_decision(price, volume, vwap_reclaimed, lower_high):

    state = market_state(price)

    if state == "Chop / no trade zone":
        return "⚠️ No Trade Zone - Wait"

    if price > 618.50:
        if volume and vwap_reclaimed:
            return "🚀 Bullish Breakout - Calls"
        else:
            return "⚠️ Breakout forming - need confirmation"

    if price < 613.75:
        if volume and lower_high:
            return "🔻 Bearish Breakdown - Puts"
        else:
            return "⚠️ Weakness forming - need confirmation"

In [54]:
print(market_state(615.12))
print(market_state(619.00))
print(market_state(613.20))

Chop / no trade zone
Bullish breakout zone
Bearish breakdown zone

In [53]:
def market_state(price):
    if price > 618.50:
        return "Bullish breakout zone"
    elif price < 613.75:
        return "Bearish breakdown zone"
    else:
        return "Chop / no trade zone"

In [52]:
print("=== SCORE TEST ===")
print(score_night_before_setup(night_before_plan))

print("\n=== SUMMARY TEST ===")
print(analyzer_summary(night_before_plan))

print("\n=== LEVEL TEST ===")
print(level_check(615.12))
print(level_check(613.50))

print("\n=== TRIGGER TEST ===")
print(bullish_trigger(618.80, True, True))
print(bearish_trigger(613.40, True, True))

=== SCORE TEST ===
{'score': 7, 'grade': 'B+', 'notes': ['Clear institutional anchor exists.', 'Plan has clean map of support and resistance.', 'Plan includes a no-trade zone, which improves discipline.']}

=== SUMMARY TEST ===
{'bias': 'Bullish but extended', 'market_grade': 'B+', 'most_important_level': 613.75, 'bullish_above': 618.5, 'weak_below': 613.75, 'no_trade_zone': [614.0, 618.0], 'best_bullish_scenario': 'Break above 618.50 with volume or dip into 613.75 that holds and reclaims VWAP.', 'best_bearish_scenario': 'Rejection from 618-620 or a clean loss of 613.75 with volume.', 'main_warning': 'Do not force entries in the middle of the range. Price is near highs and momentum is cooling.'}

=== LEVEL TEST ===
Above key institutional level: bullish thesis still alive
Below key institutional level: weakness beginning

=== TRIGGER TEST ===
A setup bullish trigger confirmed
A setup bearish trigger confirmed

In [51]:
def bullish_trigger(price, volume_confirmed, vwap_reclaimed):
    if price > 618.50 and volume_confirmed and vwap_reclaimed:
        return "A setup bullish trigger confirmed"
    return "No bullish trigger yet"

def bearish_trigger(price, volume_confirmed, lower_high):
    if price < 613.75 and volume_confirmed and lower_high:
        return "A setup bearish trigger confirmed"
    return "No bearish trigger yet"

print(bullish_trigger(618.80, True, True))
print(bearish_trigger(613.40, True, True))
print(bullish_trigger(617.90, True, True))

A setup bullish trigger confirmed
A setup bearish trigger confirmed
No bullish trigger yet

In [50]:
def level_check(current_price, key_level=613.75):
    if current_price > key_level:
        return "Above key institutional level: bullish thesis still alive"
    elif current_price < key_level:
        return "Below key institutional level: weakness beginning"
    else:
        return "At key level: decision point"

print(level_check(615.10))
print(level_check(613.20))
print(level_check(613.75))

Above key institutional level: bullish thesis still alive
Below key institutional level: weakness beginning
At key level: decision point

In [49]:
test_plan = night_before_plan.copy()
test_plan["higher_timeframe_thesis"]["bias"] = "weak"
test_plan["indicator_state"]["macd"]["read"] = "rolling over"
test_plan["indicator_state"]["rsi"]["read"] = "losing momentum"

print(score_night_before_setup(test_plan))

{'score': 7, 'grade': 'B+', 'notes': ['Clear institutional anchor exists.', 'Plan has clean map of support and resistance.', 'Plan includes a no-trade zone, which improves discipline.']}

In [48]:
test_plan = night_before_plan.copy()
test_plan["higher_timeframe_thesis"]["bias"] = "bullish"
test_plan["indicator_state"]["macd"]["read"] = "strong expansion"
test_plan["indicator_state"]["rsi"]["read"] = "strong but healthy"

print(score_night_before_setup(test_plan))

{'score': 9, 'grade': 'A-', 'notes': ['Higher timeframe trend supports upside structure.', 'Clear institutional anchor exists.', 'Plan has clean map of support and resistance.', 'Plan includes a no-trade zone, which improves discipline.']}

In [47]:
def analyzer_summary(plan):
    return {
        "bias": "Bullish but extended",
        "market_grade": plan["market_condition_grade"]["overall_grade"],
        "most_important_level": plan["core_levels"]["most_important_level"]["price"],
        "bullish_above": 618.50,
        "weak_below": 613.75,
        "no_trade_zone": plan["no_trade_zone"]["zone"],
        "best_bullish_scenario": (
            "Break above 618.50 with volume or dip into 613.75 that holds and reclaims VWAP."
        ),
        "best_bearish_scenario": (
            "Rejection from 618-620 or a clean loss of 613.75 with volume."
        ),
        "main_warning": (
            "Do not force entries in the middle of the range. "
            "Price is near highs and momentum is cooling."
        )
    }

summary = analyzer_summary(night_before_plan)
print(summary)

{'bias': 'Bullish but extended', 'market_grade': 'B+', 'most_important_level': 613.75, 'bullish_above': 618.5, 'weak_below': 613.75, 'no_trade_zone': [614.0, 618.0], 'best_bullish_scenario': 'Break above 618.50 with volume or dip into 613.75 that holds and reclaims VWAP.', 'best_bearish_scenario': 'Rejection from 618-620 or a clean loss of 613.75 with volume.', 'main_warning': 'Do not force entries in the middle of the range. Price is near highs and momentum is cooling.'}

In [46]:
result = score_night_before_setup(night_before_plan)
print(result)

{'score': 5, 'grade': 'B', 'notes': ['Higher timeframe trend supports upside structure.', 'Clear institutional anchor exists.', 'Plan has clean map of support and resistance.', 'Plan includes a no-trade zone, which improves discipline.', 'Price is extended, reducing reward-to-risk for fresh longs.', 'Momentum is slowing.', 'RSI is elevated but cooling.']}

In [45]:
def analyzer_summary(plan):
    return {
        "bias": "Bullish but extended",
        "market_grade": plan["market_condition_grade"]["overall_grade"],
        "most_important_level": plan["core_levels"]["most_important_level"]["price"],
        "bullish_above": 618.50,
        "weak_below": 613.75,
        "no_trade_zone": plan["no_trade_zone"]["zone"],
        "best_bullish_scenario": (
            "Break above 618.50 with volume or dip into 613.75 that holds and reclaims VWAP."
        ),
        "best_bearish_scenario": (
            "Rejection from 618-620 or a clean loss of 613.75 with volume."
        ),
        "main_warning": (
            "Do not force entries in the middle of the range. "
            "Price is near highs and momentum is cooling."
        )
    }

In [44]:
def score_night_before_setup(plan):
    score = 0
    notes = []

    # Higher timeframe bias
    if plan["higher_timeframe_thesis"]["bias"] in ["bullish", "bullish but extended"]:
        score += 2
        notes.append("Higher timeframe trend supports upside structure.")

    # Institutional anchor
    if plan["institutional_logic"]["primary_anchor"]:
        score += 3
        notes.append("Clear institutional anchor exists.")

    # Defined support and resistance
    if len(plan["core_levels"]["support_zones"]) > 0 and len(plan["core_levels"]["resistance_zones"]) > 0:
        score += 2
        notes.append("Plan has clean map of support and resistance.")

    # No-trade zone awareness
    if plan.get("no_trade_zone"):
        score += 2
        notes.append("Plan includes a no-trade zone, which improves discipline.")

    # Extension penalty
    if "extended" in plan["higher_timeframe_thesis"]["bias"]:
        score -= 2
        notes.append("Price is extended, reducing reward-to-risk for fresh longs.")

    # Mixed momentum penalty
    macd_read = plan["indicator_state"]["macd"]["read"].lower()
    rsi_read = plan["indicator_state"]["rsi"]["read"].lower()
    if "slowing" in macd_read or "flattening" in macd_read:
        score -= 1
        notes.append("Momentum is slowing.")
    if "cooling" in rsi_read:
        score -= 1
        notes.append("RSI is elevated but cooling.")

    # Final grade
    if score >= 8:
        grade = "A-"
    elif score >= 6:
        grade = "B+"
    elif score >= 4:
        grade = "B"
    else:
        grade = "C"

    return {
        "score": score,
        "grade": grade,
        "notes": notes
    }


result = score_night_before_setup(night_before_plan)
print(result)

{'score': 5, 'grade': 'B', 'notes': ['Higher timeframe trend supports upside structure.', 'Clear institutional anchor exists.', 'Plan has clean map of support and resistance.', 'Plan includes a no-trade zone, which improves discipline.', 'Price is extended, reducing reward-to-risk for fresh longs.', 'Momentum is slowing.', 'RSI is elevated but cooling.']}

In [43]:
night_before_plan = {
    "asset": "QQQ",
    "plan_date": "2026-04-14",
    "timeframe_context": {
        "execution_timeframes": ["1m", "5m"],
        "structure_timeframe": "15m",
        "bias_timeframe": "4H"
    },

    "market_condition_grade": {
        "overall_grade": "B+",
        "trend": "strong",
        "structure": "clean",
        "location": "at resistance",
        "risk_reward": "mid",
        "reason": (
            "Bullish environment overall, but price is extended into resistance/highs. "
            "Not an A environment because upside is no longer cheap and momentum is stretched."
        )
    },

    "core_levels": {
        "most_important_level": {
            "price": 613.75,
            "label": "$1B print / institutional support",
            "meaning": (
                "This is the main line in the sand. "
                "Above this level, institutions may still defend long exposure. "
                "Below this level, weakness begins and bullish thesis degrades."
            )
        },

        "resistance_zones": [
            {
                "zone": [617.50, 617.53],
                "label": "recent sell / first resistance",
                "meaning": "First area where sellers may respond."
            },
            {
                "zone": [618.50, 620.00],
                "label": "major rejection / profit zone",
                "meaning": (
                    "Price is extended near this area. "
                    "Repeated rejection here increases short-term downside risk."
                )
            }
        ],

        "support_zones": [
            {
                "zone": [613.80, 613.75],
                "label": "major support hold zone",
                "meaning": "Primary buyer defense zone."
            },
            {
                "zone": [611.40, 611.40],
                "label": "secondary support",
                "meaning": "First downside target if 613.75 fails."
            },
            {
                "zone": [610.70, 610.20],
                "label": "deep support / dip buy zone",
                "meaning": "If panic flush happens, this is where dips should get bought."
            }
        ]
    },

    "indicator_state": {
        "vwap": {
            "value": 618.38,
            "read": "price slightly below / around VWAP",
            "meaning": (
                "VWAP control is not fully bullish at the moment. "
                "Need reclaim and hold for stronger call bias."
            )
        },
        "bollinger_bands_15m": {
            "lower": 617.51,
            "mid": 617.99,
            "upper": 618.47,
            "read": (
                "Price has been riding upper bands, which shows strength, "
                "but also signals extension near highs."
            )
        },
        "rsi": {
            "value_approx": 62.68,
            "read": "high but cooling",
            "meaning": (
                "Momentum is still elevated, but not fresh. "
                "This supports bullish structure, but warns against chasing."
            )
        },
        "macd": {
            "read": "flattening / momentum slowing",
            "meaning": (
                "Trend is still intact, but immediate upside momentum is cooling. "
                "This increases probability of chop or pullback before continuation."
            )
        },
        "volume": {
            "read": "needs expansion for breakout confidence",
            "meaning": (
                "No strong breakout should be trusted without volume confirmation."
            )
        }
    },

    "higher_timeframe_thesis": {
        "bias": "bullish but extended",
        "reasoning": [
            "Higher highs and higher lows remain intact on 4H view.",
            "Trend is still up.",
            "Price has been riding upper Bollinger Band / momentum remains positive.",
            "However, extension is elevated, so reward-to-risk on new longs is worse at highs.",
            "A reaction, pause, or dip would be normal before continuation."
        ]
    },

    "current_price_action_read": {
        "state": "decision zone",
        "description": [
            "Price is consolidating near highs.",
            "VWAP control is mixed.",
            "Momentum is slowing.",
            "This is not a clean entry zone by itself.",
            "This area is better for waiting than forcing."
        ]
    },

    "no_trade_zone": {
        "zone": [614.00, 618.00],
        "reason": [
            "Chop risk is elevated in this area.",
            "No strong directional edge without volume.",
            "No clear VWAP control.",
            "This is where traders lose money by forcing entries."
        ]
    },

    "bullish_plan": {
        "grade_if_triggered": "A",
        "setup_name": "Break and hold / institutional support defense",
        "entry_triggers": [
            "Break above 618.50 with volume",
            "Dip into 613.75 area and hold",
            "VWAP reclaim followed by hold",
            "Higher low forms after reclaim"
        ],
        "confirmation_requirements": [
            "Strong volume candle",
            "VWAP reclaim and acceptance",
            "Higher low",
            "Momentum re-expands instead of stalling"
        ],
        "targets": [
            {"price": 620.00, "note": "first scale / first upside target"},
            {"price": 622.00, "note": "continuation target if breakout holds"}
        ],
        "invalidation": {
            "price": 613.75,
            "rule": "Bullish thesis weakens materially if this level is lost."
        },
        "reasoning": (
            "Bulls remain in control only if they can reclaim control above resistance "
            "or prove they will defend the institutional support zone."
        )
    },

    "bearish_plan": {
        "grade_if_triggered": "A",
        "setup_name": "Rejection from highs / breakdown from key support",
        "entry_triggers": [
            "Rejects 618.00-620.00 again",
            "Loses 613.75 with volume",
            "VWAP rejection from below",
            "Lower high forms after bounce"
        ],
        "confirmation_requirements": [
            "VWAP rejection",
            "Lower high",
            "RSI and MACD momentum roll over",
            "Volume supports downside move"
        ],
        "targets": [
            {"price": 611.40, "note": "first downside target"},
            {"price": 610.00, "note": "secondary downside target"},
            {"price": 608.00, "note": "panic extension target"}
        ],
        "invalidation": {
            "price": 618.50,
            "rule": "Bearish thesis weakens if price cleanly breaks and holds above this zone."
        },
        "reasoning": (
            "If price cannot sustain highs or loses 613.75, then short-term weakness is likely "
            "because the market is already extended and momentum is cooling."
        )
    },

    "institutional_logic": {
        "primary_anchor": 613.75,
        "anchor_type": "large print / institutional support",
        "ai_interpretation": [
            "Large prints matter more than random price levels.",
            "The analyzer should treat 613.75 as a thesis-defining level.",
            "Price holding above the institutional anchor supports bullish scenarios.",
            "Failure below the anchor increases odds that institutions are no longer defending."
        ]
    },

    "execution_rules": {
        "do_not_chase_highs": True,
        "do_not_buy_inside_no_trade_zone_without_confirmation": True,
        "require_volume_for_breakouts": True,
        "prefer_retests_over_random_entries": True,
        "prioritize_level_reaction_over_prediction": True
    },

    "ai_training_notes": {
        "what_good_night_before_reasoning_looks_like": [
            "Start with higher timeframe bias first.",
            "Identify the most important institutional level.",
            "Separate resistance zones from support zones.",
            "Mark where NOT to trade, not just where to trade.",
            "Define bullish trigger, bearish trigger, and invalidation levels.",
            "Use indicators as confirmation, not the main reason for a trade.",
            "Do not label a setup A-quality unless confirmation exists."
        ],
        "mistakes_ai_should_avoid": [
            "Calling every bullish chart an A setup",
            "Ignoring extension near highs",
            "Buying inside chop without confirmation",
            "Treating RSI alone as a signal",
            "Ignoring VWAP control",
            "Ignoring large-print institutional levels"
        ]
    }
}

In [42]:
from datetime import datetime
import json

# =========================
# BUILD CONTEXT
# =========================

context = MarketContext(
    symbol="QQQ",
    current_price=613.85,
    vwap=613.20,
    rsi=61.5,
    oil_change_dollars=2.35,
    oil_trend="stabilizing",
    macro_headline_bias="neutral",
    big_print_levels=[613.75],
    prior_day_high=614.40,
    prior_day_low=608.90,
    premarket_high=613.95,
    premarket_low=611.80,
    key_supports=[612.50, 611.80],
    key_resistances=[614.40, 615.20]
)

# =========================
# BUILD STRUCTURE
# =========================

structure = StructureState(
    higher_lows=True,
    lower_highs=False,
    above_vwap=True,
    below_vwap=False,
    vwap_reclaimed=True,
    vwap_rejected=False,
    breakout_with_volume=True,
    rejection_at_level=False,
    retest_hold=True,
    failed_bounce=False,
    liquidity_grab_reversal=False
)

# =========================
# RUN DECISION ENGINE
# =========================

decision = make_decision(
    context=context,
    structure=structure,
    candle_time=datetime.now()
)

# =========================
# OUTPUT
# =========================

print(format_discord_alert(decision, context))
print()
print(json.dumps(decision_to_dict(decision), indent=2))

🟢 **QQQ Regime Update**
**Regime:** BULL
**Allowed Direction:** LONG
**Setup:** VWAP_RECLAIM_RETEST
**Confidence:** HIGH
**Grade:** 💎 A+
**Grade Score:** 12
**Entry Valid:** YES
**Stop Reference:** 613.75
**Target Reference:** 613.95

**Reasoning:**
- Price is above VWAP.
- Higher lows support bullish structure.
- VWAP reclaim supports bullish continuation.
- RSI supports bullish momentum.
- Oil strength adds pressure to equities.
- Oil stabilizing may relieve equity pressure.
- Detected setup: VWAP_RECLAIM_RETEST.
- Bull regime aligns with bullish setup.
- Price is holding above VWAP.
- Retest hold confirms buyers defended the level.
- Breakout volume confirms participation.
- Strong regime separation.

{
  "regime": "BULL",
  "allowed_direction": "LONG",
  "setup": "VWAP_RECLAIM_RETEST",
  "confidence": "HIGH",
  "grade": "A+",
  "grade_score": 12,
  "entry_valid": true,
  "stop_level": 613.75,
  "target_level": 613.95,
  "reasoning": [
    "Price is above VWAP.",
    "Higher lows support bullish structure.",
    "VWAP reclaim supports bullish continuation.",
    "RSI supports bullish momentum.",
    "Oil strength adds pressure to equities.",
    "Oil stabilizing may relieve equity pressure.",
    "Detected setup: VWAP_RECLAIM_RETEST.",
    "Bull regime aligns with bullish setup.",
    "Price is holding above VWAP.",
    "Retest hold confirms buyers defended the level.",
    "Breakout volume confirms participation.",
    "Strong regime separation.",
    "Valid setup detected.",
    "Entry confirmation is valid.",
    "Bull setup aligned above VWAP.",
    "Breakout volume supports move.",
    "Retest hold improves setup quality.",
    "Macro/oil conditions support upside.",
    "Signal is outside priority window."
  ]
}

In [40]:
def format_discord_alert(decision: BotDecision, context: MarketContext) -> str:
    emoji = {
        "BULL": "🟢",
        "BEAR": "🔴",
        "CHOP": "🟡"
    }.get(decision.regime, "⚪")

    grade_emoji = {
        "A+": "💎",
        "A": "🔥",
        "B+": "✅",
        "B": "⚠️",
        "AVOID": "⛔"
    }.get(decision.grade, "⚪")

    lines = [
        f"{emoji} **{context.symbol} Regime Update**",
        f"**Regime:** {decision.regime}",
        f"**Allowed Direction:** {decision.allowed_direction}",
        f"**Setup:** {decision.setup or 'None'}",
        f"**Confidence:** {decision.confidence}",
        f"**Grade:** {grade_emoji} {decision.grade}",
        f"**Grade Score:** {decision.grade_score}",
        f"**Entry Valid:** {'YES' if decision.entry_valid else 'NO'}",
    ]

    if decision.stop_level is not None:
        lines.append(f"**Stop Reference:** {decision.stop_level:.2f}")
    if decision.target_level is not None:
        lines.append(f"**Target Reference:** {decision.target_level:.2f}")

    lines.append("")
    lines.append("**Reasoning:**")

    for item in decision.reasoning[:12]:
        lines.append(f"- {item}")

    return "\n".join(lines)

In [39]:
def make_decision(
    context: MarketContext,
    structure: StructureState,
    candle_time: datetime,
) -> BotDecision:
    regime_data = detect_regime(context, structure, candle_time)
    setup = detect_setup(regime_data["regime"], structure)
    entry = confirm_entry(regime_data["regime"], setup, context, structure)
    confidence = confidence_label(regime_data, entry["entry_valid"])

    grade_data = grade_setup(
        regime_data=regime_data,
        setup=setup,
        entry_data=entry,
        context=context,
        structure=structure,
        candle_time=candle_time,
    )

    reasoning = []
    reasoning.extend(regime_data["notes"])

    if setup:
        reasoning.append(f"Detected setup: {setup}.")
    else:
        reasoning.append("No valid setup detected.")

    reasoning.extend(entry["reasons"])
    reasoning.extend(grade_data["grade_notes"])

    return BotDecision(
        regime=regime_data["regime"],
        allowed_direction=regime_data["allowed_direction"],
        setup=setup,
        confidence=confidence,
        grade=grade_data["grade"],
        grade_score=grade_data["score"],
        entry_valid=entry["entry_valid"],
        stop_level=entry["stop_level"],
        target_level=entry["target_level"],
        reasoning=reasoning,
    )

In [33]:
from typing import Dict, Optional
from datetime import datetime


def grade_setup(
    regime_data: Dict[str, object],
    setup: Optional[str],
    entry_data: Dict[str, object],
    context: MarketContext,
    structure: StructureState,
    candle_time: datetime,
) -> Dict[str, object]:
    score = 0
    notes = []

    bull_score = regime_data.get("bull_score", 0)
    bear_score = regime_data.get("bear_score", 0)
    regime = regime_data.get("regime", "CHOP")

    # 1. Regime strength
    spread = abs(bull_score - bear_score)
    if spread >= 5:
        score += 3
        notes.append("Strong regime separation.")
    elif spread >= 3:
        score += 2
        notes.append("Good regime separation.")
    elif spread >= 2:
        score += 1
        notes.append("Moderate regime separation.")
    else:
        notes.append("Weak regime separation.")

    # 2. Valid setup present
    if setup is not None:
        score += 2
        notes.append("Valid setup detected.")
    else:
        notes.append("No clean setup detected.")

    # 3. Entry confirmation
    if entry_data.get("entry_valid", False):
        score += 3
        notes.append("Entry confirmation is valid.")
    else:
        notes.append("Entry confirmation is not valid.")

    # 4. VWAP alignment
    if regime == "BULL" and structure.above_vwap:
        score += 1
        notes.append("Bull setup aligned above VWAP.")
    elif regime == "BEAR" and structure.below_vwap:
        score += 1
        notes.append("Bear setup aligned below VWAP.")
    else:
        notes.append("VWAP alignment is weak or mixed.")

    # 5. Volume / reaction quality
    if structure.breakout_with_volume:
        score += 1
        notes.append("Breakout volume supports move.")
    if structure.retest_hold:
        score += 1
        notes.append("Retest hold improves setup quality.")
    if structure.rejection_at_level:
        score += 1
        notes.append("Rejection at level improves bearish quality.")
    if structure.failed_bounce:
        score += 1
        notes.append("Failed bounce improves bearish quality.")

    # 6. Macro alignment
    if regime == "BULL" and context.oil_trend in ["falling", "stabilizing"]:
        score += 1
        notes.append("Macro/oil conditions support upside.")
    elif regime == "BEAR" and context.oil_change_dollars >= 2 and context.oil_trend == "rising":
        score += 1
        notes.append("Macro/oil conditions support downside.")
    else:
        notes.append("Macro alignment is neutral or mixed.")

    # 7. Institutional time window
    if is_priority_window(candle_time):
        score += 1
        notes.append("Signal is in a priority institutional window.")
    else:
        notes.append("Signal is outside priority window.")

    # 8. Chop penalty
    if regime == "CHOP":
        score -= 3
        notes.append("Chop regime penalty applied.")

    # 9. Direct conflict penalty
    if regime == "BULL" and structure.below_vwap:
        score -= 2
        notes.append("Conflict: bull regime but below VWAP.")
    if regime == "BEAR" and structure.above_vwap:
        score -= 2
        notes.append("Conflict: bear regime but above VWAP.")

    # Final grade mapping
    if not entry_data.get("entry_valid", False) or setup is None:
        if score >= 5:
            grade = "B"
        else:
            grade = "AVOID"
    else:
        if score >= 11:
            grade = "A+"
        elif score >= 9:
            grade = "A"
        elif score >= 7:
            grade = "B+"
        elif score >= 5:
            grade = "B"
        else:
            grade = "AVOID"

    return {
        "grade": grade,
        "score": score,
        "grade_notes": notes,
    }

In [32]:
import requests

# =========================
# DISCORD WEBHOOK FUNCTION
# =========================

def send_to_discord(message: str, webhook_url: str):
    payload = {"content": message}

    try:
        response = requests.post(webhook_url, json=payload)

        print("Status:", response.status_code)

        if response.status_code == 204:
            print("✅ Message sent successfully")
        else:
            print("❌ Failed to send:", response.text)

    except Exception as e:
        print("🚨 Error sending to Discord:", e)


# =========================
# PASTE YOUR WEBHOOK HERE
# =========================

WEBHOOK_URL = "https://discord.com/api/webhooks/1493461086563860570/vEIm69kYdcPEO5Ha7FOloAEjlA1QhXaxz-1HCYO324m2xQyTopFDrVkh_Xv-HqtpMIZR"


# =========================
# SEND ALERT
# =========================

message = format_discord_alert(decision, context)

send_to_discord(message, WEBHOOK_URL)

Status: 204
✅ Message sent successfully

In [31]:
from datetime import datetime

# =========================
# BUILD CONTEXT OBJECT
# =========================

context = MarketContext(
    symbol=symbol,
    current_price=current_price,
    vwap=vwap,
    rsi=rsi,
    oil_change_dollars=oil_change_dollars,
    oil_trend=oil_trend,
    macro_headline_bias=macro_headline_bias,
    big_print_levels=big_print_levels,
    prior_day_high=prior_day_high,
    prior_day_low=prior_day_low,
    premarket_high=premarket_high,
    premarket_low=premarket_low,
    key_supports=key_supports,
    key_resistances=key_resistances
)

# =========================
# BUILD STRUCTURE OBJECT
# =========================

structure = StructureState(
    higher_lows=higher_lows,
    lower_highs=lower_highs,
    above_vwap=above_vwap,
    below_vwap=below_vwap,
    vwap_reclaimed=vwap_reclaimed,
    vwap_rejected=vwap_rejected,
    breakout_with_volume=breakout_with_volume,
    rejection_at_level=rejection_at_level,
    retest_hold=retest_hold,
    failed_bounce=failed_bounce,
    liquidity_grab_reversal=liquidity_grab_reversal
)

# =========================
# RUN DECISION ENGINE
# =========================

decision = make_decision(
    context=context,
    structure=structure,
    candle_time=datetime.now()
)

# =========================
# OUTPUT DISCORD MESSAGE
# =========================

message = format_discord_alert(decision, context)

print("\nDISCORD ALERT PREVIEW:\n")
print(message)

DISCORD ALERT PREVIEW:

🟢 **QQQ Regime Update**
**Regime:** BULL
**Allowed Direction:** LONG
**Setup:** VWAP_RECLAIM_RETEST
**Confidence:** HIGH
**Entry Valid:** YES
**Stop Reference:** 613.75
**Target Reference:** 613.95

**Reasoning:**
- Price is above VWAP.
- Higher lows support bullish structure.
- VWAP reclaim supports bullish continuation.
- RSI supports bullish momentum.
- Oil strength adds pressure to equities.
- Oil stabilizing may relieve equity pressure.
- Detected setup: VWAP_RECLAIM_RETEST.
- Bull regime aligns with bullish setup.
- Price is holding above VWAP.
- Retest hold confirms buyers defended the level.

In [30]:
# =========================
# MARKET INPUT DATA (LIVE SNAPSHOT)
# =========================

symbol = "QQQ"

# Price + Indicators
current_price = 613.85
vwap = 613.20
rsi = 61.5

# Macro / External Factors
oil_change_dollars = 2.35
oil_trend = "stabilizing"  # options: rising / falling / neutral / stabilizing
macro_headline_bias = "neutral"  # options: bullish / bearish / neutral

# Institutional / Liquidity Levels
big_print_levels = [613.75]

# Key Levels
prior_day_high = 614.40
prior_day_low = 608.90
premarket_high = 613.95
premarket_low = 611.80

key_supports = [612.50, 611.80]
key_resistances = [614.40, 615.20]

# =========================
# STRUCTURE / PRICE ACTION STATE
# =========================
# =========================
# DEFINE STRUCTURE VARIABLES
# =========================

higher_lows = True
lower_highs = False
above_vwap = True
below_vwap = False
vwap_reclaimed = True
vwap_rejected = False
breakout_with_volume = True
rejection_at_level = False
retest_hold = True
failed_bounce = False
liquidity_grab_reversal = False
structure_state = {
    "higher_lows": True,
    "lower_highs": False,
    "above_vwap": True,
    "below_vwap": False,
    "vwap_reclaimed": True,
    "vwap_rejected": False,
    "breakout_with_volume": True,
    "rejection_at_level": False,
    "retest_hold": True,
    "failed_bounce": False,
    "liquidity_grab_reversal": False
}

In [41]:
import json
from typing import Dict


def decision_to_dict(decision: BotDecision) -> Dict[str, object]:
    return {
        "regime": decision.regime,
        "allowed_direction": decision.allowed_direction,
        "setup": decision.setup,
        "confidence": decision.confidence,
        "grade": decision.grade,
        "grade_score": decision.grade_score,
        "entry_valid": decision.entry_valid,
        "stop_level": decision.stop_level,
        "target_level": decision.target_level,
        "reasoning": decision.reasoning,
    }

# Convert decision to JSON and print
print(json.dumps(decision_to_dict(decision), indent=2))

{
  "regime": "BULL",
  "allowed_direction": "LONG",
  "setup": "VWAP_RECLAIM_RETEST",
  "confidence": "HIGH",
  "grade": "A+",
  "grade_score": 12,
  "entry_valid": true,
  "stop_level": 613.75,
  "target_level": 613.95,
  "reasoning": [
    "Price is above VWAP.",
    "Higher lows support bullish structure.",
    "VWAP reclaim supports bullish continuation.",
    "RSI supports bullish momentum.",
    "Oil strength adds pressure to equities.",
    "Oil stabilizing may relieve equity pressure.",
    "Bull regime aligns with bullish setup.",
    "Price is holding above VWAP.",
    "Retest hold confirms buyers defended the level.",
    "Breakout volume confirms participation.",
    "Strong regime separation.",
    "Valid setup detected.",
    "Entry confirmation is valid.",
    "Bull setup aligned above VWAP.",
    "Breakout volume supports move.",
    "Retest hold improves setup quality.",
    "Macro/oil conditions support upside.",
    "Signal is outside priority window."
  ]
}

In [38]:
from dataclasses import dataclass
from typing import List, Optional, Dict
from datetime import datetime


# =========================
# DATA STRUCTURES
# =========================

@dataclass
class MarketContext:
    symbol: str
    current_price: float
    vwap: float
    rsi: float
    oil_change_dollars: float
    oil_trend: str
    macro_headline_bias: str
    big_print_levels: List[float]
    prior_day_high: float
    prior_day_low: float
    premarket_high: float
    premarket_low: float
    key_supports: List[float]
    key_resistances: List[float]


@dataclass
class StructureState:
    higher_lows: bool
    lower_highs: bool
    above_vwap: bool
    below_vwap: bool
    vwap_reclaimed: bool
    vwap_rejected: bool
    breakout_with_volume: bool
    rejection_at_level: bool
    retest_hold: bool
    failed_bounce: bool
    liquidity_grab_reversal: bool


@dataclass
@dataclass
class BotDecision:
    regime: str
    allowed_direction: str
    setup: Optional[str]
    confidence: str
    grade: str
    grade_score: int
    entry_valid: bool
    stop_level: Optional[float]
    target_level: Optional[float]
    reasoning: List[str]


# =========================
# HELPER
# =========================

def nearest_level(price: float, levels: List[float]) -> Optional[float]:
    if not levels:
        return None
    return min(levels, key=lambda x: abs(x - price))


# =========================
# REGIME DETECTION
# =========================

def detect_regime(
    context: MarketContext,
    structure: StructureState,
    candle_time: datetime,
) -> Dict[str, object]:
    bull_score = 0
    bear_score = 0
    notes = []

    if structure.above_vwap:
        bull_score += 2
        notes.append("Price is above VWAP.")
    if structure.below_vwap:
        bear_score += 2
        notes.append("Price is below VWAP.")

    if structure.higher_lows:
        bull_score += 2
        notes.append("Higher lows support bullish structure.")
    if structure.lower_highs:
        bear_score += 2
        notes.append("Lower highs support bearish structure.")

    if structure.vwap_reclaimed:
        bull_score += 2
        notes.append("VWAP reclaim supports bullish continuation.")
    if structure.vwap_rejected:
        bear_score += 2
        notes.append("VWAP rejection supports bearish continuation.")

    if context.rsi >= 55 and context.rsi < 75:
        bull_score += 1
        notes.append("RSI supports bullish momentum.")
    elif context.rsi <= 45:
        bear_score += 1
        notes.append("RSI supports bearish pressure.")
    elif context.rsi >= 75:
        notes.append("RSI is elevated; bullish but extended.")

    if context.oil_change_dollars >= 2:
        bear_score += 1
        notes.append("Oil strength adds pressure to equities.")
    if context.oil_trend == "stabilizing":
        bull_score += 1
        notes.append("Oil stabilizing may relieve equity pressure.")

    if context.macro_headline_bias == "bullish":
        bull_score += 1
        notes.append("Macro headlines support bullish bias.")
    elif context.macro_headline_bias == "bearish":
        bear_score += 1
        notes.append("Macro headlines support bearish bias.")

    if bull_score - bear_score >= 2:
        regime = "BULL"
        allowed_direction = "LONG"
    elif bear_score - bull_score >= 2:
        regime = "BEAR"
        allowed_direction = "SHORT"
    else:
        regime = "CHOP"
        allowed_direction = "NEUTRAL"

    return {
        "regime": regime,
        "allowed_direction": allowed_direction,
        "bull_score": bull_score,
        "bear_score": bear_score,
        "notes": notes,
    }


# =========================
# SETUP DETECTION
# =========================

def detect_setup(regime: str, structure: StructureState) -> Optional[str]:
    if regime == "BULL":
        if structure.vwap_reclaimed and structure.retest_hold:
            return "VWAP_RECLAIM_RETEST"
        if structure.breakout_with_volume:
            return "BREAKOUT_WITH_VOLUME"
        if structure.liquidity_grab_reversal:
            return "LIQUIDITY_GRAB_REVERSAL"

    if regime == "BEAR":
        if structure.vwap_rejected and structure.rejection_at_level:
            return "VWAP_REJECTION"
        if structure.failed_bounce:
            return "FAILED_BOUNCE"
        if structure.liquidity_grab_reversal:
            return "LIQUIDITY_GRAB_REVERSAL"

    return None


# =========================
# ENTRY CONFIRMATION
# =========================

def confirm_entry(
    regime: str,
    setup: Optional[str],
    context: MarketContext,
    structure: StructureState,
) -> Dict[str, object]:
    reasons = []
    entry_valid = False
    stop_level = None
    target_level = None

    all_supports = [
        context.prior_day_low,
        context.premarket_low,
        *context.key_supports,
        *context.big_print_levels,
    ]

    all_resistances = [
        context.prior_day_high,
        context.premarket_high,
        *context.key_resistances,
        *context.big_print_levels,
    ]

    if regime == "BULL" and setup:
        if structure.above_vwap and (structure.retest_hold or structure.breakout_with_volume):
            entry_valid = True
            reasons.append("Bull regime aligns with bullish setup.")
            reasons.append("Price is holding above VWAP.")

            if structure.retest_hold:
                reasons.append("Retest hold confirms buyers defended the level.")
            if structure.breakout_with_volume:
                reasons.append("Breakout volume confirms participation.")

            stop_level = nearest_level(context.current_price, all_supports)
            target_level = nearest_level(context.current_price, all_resistances)

    elif regime == "BEAR" and setup:
        if structure.below_vwap and (structure.rejection_at_level or structure.failed_bounce):
            entry_valid = True
            reasons.append("Bear regime aligns with bearish setup.")
            reasons.append("Price is staying below VWAP.")

            if structure.rejection_at_level:
                reasons.append("Rejection at resistance confirms sellers are active.")
            if structure.failed_bounce:
                reasons.append("Failed bounce confirms weak buyer control.")

            stop_level = nearest_level(context.current_price, all_resistances)
            target_level = nearest_level(context.current_price, all_supports)

    else:
        reasons.append("No clean entry because regime and setup are not aligned.")

    return {
        "entry_valid": entry_valid,
        "reasons": reasons,
        "stop_level": stop_level,
        "target_level": target_level,
    }


# =========================
# CONFIDENCE LABEL
# =========================

def confidence_label(regime_data: Dict[str, object], entry_valid: bool) -> str:
    bull_score = regime_data.get("bull_score", 0)
    bear_score = regime_data.get("bear_score", 0)
    spread = abs(bull_score - bear_score)

    if not entry_valid:
        return "LOW"
    if spread >= 4:
        return "HIGH"
    if spread >= 2:
        return "MEDIUM"
    return "LOW"


# =========================
# MAIN DECISION ENGINE
# =========================

def make_decision(
    context: MarketContext,
    structure: StructureState,
    candle_time: datetime,
) -> BotDecision:

    regime_data = detect_regime(context, structure, candle_time)
    setup = detect_setup(regime_data["regime"], structure)
    entry = confirm_entry(regime_data["regime"], setup, context, structure)
    confidence = confidence_label(regime_data, entry["entry_valid"])

    # ✅ ADD THIS
    grading = grade_setup(
        regime_data=regime_data,
        setup=setup,
        entry_data=entry,
        context=context,
        structure=structure,
        candle_time=candle_time,
    )

    reasoning = []
    reasoning.extend(regime_data.get("notes", []))
    reasoning.extend(entry.get("reasons", []))

    # ✅ THIS MUST BE INSIDE FUNCTION
    return BotDecision(
        regime=regime_data["regime"],
        allowed_direction=regime_data["allowed_direction"],
        setup=setup,
        confidence=confidence,
        grade=grading["grade"],
        grade_score=grading["score"],
        entry_valid=entry["entry_valid"],
        stop_level=entry["stop_level"],
        target_level=entry["target_level"],
        reasoning=reasoning + grading["grade_notes"],
    )

# =========================
# DISCORD FORMATTER
# =========================

def format_discord_alert(decision: BotDecision, context: MarketContext) -> str:
    emoji = {
        "BULL": "🟢",
        "BEAR": "🔴",
        "CHOP": "🟡",
    }.get(decision.regime, "⚪")

    lines = [
        f"{emoji} **{context.symbol} Regime Update**",
        f"**Regime:** {decision.regime}",
        f"**Allowed Direction:** {decision.allowed_direction}",
        f"**Setup:** {decision.setup or 'None'}",
        f"**Confidence:** {decision.confidence}",
        f"**Entry Valid:** {'YES' if decision.entry_valid else 'NO'}",
    ]

    if decision.stop_level is not None:
        lines.append(f"**Stop Reference:** {decision.stop_level:.2f}")

    if decision.target_level is not None:
        lines.append(f"**Target Reference:** {decision.target_level:.2f}")

    lines.append("")
    lines.append("**Reasoning:**")

    for item in decision.reasoning[:10]:
        lines.append(f"- {item}")

    return "\n".join(lines)


# =========================
# TEST EXAMPLE
# =========================

context = MarketContext(
    symbol="QQQ",
    current_price=613.85,
    vwap=613.20,
    rsi=61.5,
    oil_change_dollars=2.35,
    oil_trend="stabilizing",
    macro_headline_bias="neutral",
    big_print_levels=[613.75],
    prior_day_high=614.40,
    prior_day_low=608.90,
    premarket_high=613.95,
    premarket_low=611.80,
    key_supports=[612.50, 611.80],
    key_resistances=[614.40, 615.20],
)

structure = StructureState(
    higher_lows=True,
    lower_highs=False,
    above_vwap=True,
    below_vwap=False,
    vwap_reclaimed=True,
    vwap_rejected=False,
    breakout_with_volume=True,
    rejection_at_level=False,
    retest_hold=True,
    failed_bounce=False,
    liquidity_grab_reversal=False,
)

decision = make_decision(
    context=context,
    structure=structure,
    candle_time=datetime.now(),
)

print(format_discord_alert(decision, context))

🟢 **QQQ Regime Update**
**Regime:** BULL
**Allowed Direction:** LONG
**Setup:** VWAP_RECLAIM_RETEST
**Confidence:** HIGH
**Entry Valid:** YES
**Stop Reference:** 613.75
**Target Reference:** 613.95

**Reasoning:**
- Price is above VWAP.
- Higher lows support bullish structure.
- VWAP reclaim supports bullish continuation.
- RSI supports bullish momentum.
- Oil strength adds pressure to equities.
- Oil stabilizing may relieve equity pressure.
- Bull regime aligns with bullish setup.
- Price is holding above VWAP.
- Retest hold confirms buyers defended the level.
- Breakout volume confirms participation.

In [24]:
def format_discord_alert(decision: BotDecision, context: MarketContext) -> str:
    emoji = {
        "BULL": "🟢",
        "BEAR": "🔴",
        "CHOP": "🟡"
    }.get(decision.regime, "⚪")

    lines = [
        f"{emoji} **{context.symbol} Regime Update**",
        f"**Regime:** {decision.regime}",
        f"**Allowed Direction:** {decision.allowed_direction}",
        f"**Setup:** {decision.setup or 'None'}",
        f"**Confidence:** {decision.confidence}",
        f"**Entry Valid:** {'YES' if decision.entry_valid else 'NO'}",
    ]

    if decision.stop_level is not None:
        lines.append(f"**Stop Reference:** {decision.stop_level:.2f}")

    if decision.target_level is not None:
        lines.append(f"**Target Reference:** {decision.target_level:.2f}")

    lines.append("")
    lines.append("**Reasoning:**")

    for item in decision.reasoning[:10]:
        lines.append(f"- {item}")

    return "\n".join(lines)

In [35]:
from dataclasses import dataclass
from typing import Optional, List
from datetime import datetime

# =========================
# DECISION OUTPUT STRUCTURE
# =========================

@dataclass
class BotDecision:
    regime: str
    allowed_direction: str
    setup: Optional[str]
    confidence: str
    entry_valid: bool
    stop_level: Optional[float]
    target_level: Optional[float]
    reasoning: List[str]


# =========================
# MAIN DECISION ENGINE
# =========================

def make_decision(
    context: MarketContext,
    structure: StructureState,
    candle_time: datetime,
) -> BotDecision:

    regime_data = detect_regime(context, structure, candle_time)
    setup = detect_setup(regime_data["regime"], structure)
    entry = confirm_entry(regime_data["regime"], setup, context, structure)
    confidence = confidence_label(regime_data, entry["entry_valid"])
    grading = grade_setup(
    regime_data=regime_data,
    setup=setup,
    entry_data=entry,
    context=context,
    structure=structure,
    candle_time=candle_time,
)

    reasoning = []

    # Add regime reasoning
    reasoning.extend(regime_data.get("notes", []))

    # Add setup reasoning
    if setup:
        reasoning.append(f"Detected setup: {setup}.")
    else:
        reasoning.append("No valid setup detected.")

    # Add entry reasoning
    reasoning.extend(entry.get("reasons", []))

    return BotDecision(
        regime=regime_data["regime"],
        allowed_direction=regime_data["allowed_direction"],
        setup=setup,
        confidence=confidence,
        entry_valid=entry["entry_valid"],
        stop_level=entry["stop_level"],
        target_level=entry["target_level"],
        reasoning=reasoning,
    )

In [19]:
test_regime = {
    "bull_score": 6,
    "bear_score": 2
}

print(confidence_label(test_regime, True))   # HIGH
print(confidence_label(test_regime, False))  # LOW

HIGH
LOW

In [18]:
from typing import Dict

def confidence_label(regime_data: Dict[str, object], entry_valid: bool) -> str:
    bull_score = regime_data.get("bull_score", 0)
    bear_score = regime_data.get("bear_score", 0)
    spread = abs(bull_score - bear_score)

    if not entry_valid:
        return "LOW"

    if spread >= 4:
        return "HIGH"

    if spread >= 2:
        return "MEDIUM"

    return "LOW"

In [23]:
from typing import Optional, Dict, List
from dataclasses import dataclass

# =========================
# DATA STRUCTURES
# =========================

@dataclass
class MarketContext:
    symbol: str
    current_price: float
    prior_day_high: float
    prior_day_low: float
    premarket_high: float
    premarket_low: float
    key_supports: List[float]
    key_resistances: List[float]
    big_print_levels: List[float]


@dataclass
class StructureState:
    above_vwap: bool
    below_vwap: bool
    retest_hold: bool
    breakout_with_volume: bool
    rejection_at_level: bool
    failed_bounce: bool


# =========================
# HELPER FUNCTION
# =========================

def nearest_level(price: float, levels: List[float]) -> Optional[float]:
    if not levels:
        return None
    return min(levels, key=lambda x: abs(x - price))


# =========================
# ENTRY LOGIC
# =========================

def confirm_entry(
    regime: str,
    setup: Optional[str],
    context: MarketContext,
    structure: StructureState,
) -> Dict[str, object]:

    reasons = []
    entry_valid = False
    stop_level = None
    target_level = None

    all_supports = [
        context.prior_day_low,
        context.premarket_low,
        *context.key_supports,
        *context.big_print_levels
    ]

    all_resistances = [
        context.prior_day_high,
        context.premarket_high,
        *context.key_resistances,
        *context.big_print_levels
    ]

    # BULL LOGIC
    if regime == "BULL" and setup:
        if structure.above_vwap and (structure.retest_hold or structure.breakout_with_volume):
            entry_valid = True

            reasons.append("Bull regime aligns with bullish setup.")
            reasons.append("Price holding above VWAP.")

            if structure.retest_hold:
                reasons.append("Retest hold confirmed.")

            if structure.breakout_with_volume:
                reasons.append("Breakout volume confirmed.")

            stop_level = nearest_level(context.current_price, all_supports)
            target_level = nearest_level(context.current_price, all_resistances)

    # BEAR LOGIC
    elif regime == "BEAR" and setup:
        if structure.below_vwap and (structure.rejection_at_level or structure.failed_bounce):
            entry_valid = True

            reasons.append("Bear regime aligns with bearish setup.")
            reasons.append("Price below VWAP.")

            if structure.rejection_at_level:
                reasons.append("Rejection confirms sellers.")

            if structure.failed_bounce:
                reasons.append("Failed bounce confirms weakness.")

            stop_level = nearest_level(context.current_price, all_resistances)
            target_level = nearest_level(context.current_price, all_supports)

    else:
        reasons.append("No clean entry — no alignment.")

    return {
        "entry_valid": entry_valid,
        "reasons": reasons,
        "stop_level": stop_level,
        "target_level": target_level,
    }


# =========================
# TEST BLOCK
# =========================

# TEST BLOCK

context = MarketContext(
    symbol="QQQ",
    current_price=617.39,
    prior_day_high=618.50,
    prior_day_low=613.75,
    premarket_high=618.00,
    premarket_low=614.00,
    key_supports=[613.75, 611.40],
    key_resistances=[617.50, 620.50],
    big_print_levels=[613.75]
)

structure = StructureState(
    above_vwap=True,
    below_vwap=False,
    retest_hold=False,
    breakout_with_volume=False,
    rejection_at_level=True,
    failed_bounce=False
)

result = confirm_entry("BULL", "B_SETUP", context, structure)

print("\nTEST RESULT:")
print(result)

TEST RESULT:
{'entry_valid': False, 'reasons': [], 'stop_level': None, 'target_level': None}

In [9]:
def detect_setup(regime: str, structure: StructureState) -> Optional[str]:
    if regime == "BULL":
        if structure.vwap_reclaimed and structure.retest_hold:
            return "VWAP_RECLAIM_RETEST_CALL"
        if structure.breakout_with_volume:
            return "BREAK_AND_HOLD_CALL"
        if structure.higher_lows and structure.retest_hold:
            return "HIGHER_LOW_RETEST_CALL"

    if regime == "BEAR":
        if structure.vwap_rejected and structure.rejection_at_level:
            return "VWAP_REJECTION_PUT"
        if structure.failed_bounce and structure.lower_highs:
            return "FAILED_BOUNCE_PUT"
        if structure.rejection_at_level:
            return "LEVEL_REJECTION_PUT"

    return None

In [7]:
def detect_regime(context: MarketContext, structure: StructureState, ts: datetime) -> Dict[str, object]:
    bull_score = 0
    bear_score = 0
    notes = []

    # VWAP
    if structure.above_vwap:
        bull_score += 2
        notes.append("Price is above VWAP.")
    if structure.below_vwap:
        bear_score += 2
        notes.append("Price is below VWAP.")
    if structure.vwap_reclaimed:
        bull_score += 2
        notes.append("VWAP reclaim detected.")
    if structure.vwap_rejected:
        bear_score += 2
        notes.append("VWAP rejection detected.")

    # Structure
    if structure.higher_lows:
        bull_score += 2
        notes.append("Higher lows support bullish structure.")
    if structure.lower_highs:
        bear_score += 2
        notes.append("Lower highs support bearish structure.")

    # Setup behavior
    if structure.breakout_with_volume:
        bull_score += 1
        notes.append("Breakout with volume supports continuation.")
    if structure.rejection_at_level:
        bear_score += 1
        notes.append("Rejection at level supports downside pressure.")
    if structure.retest_hold:
        bull_score += 1
        notes.append("Retest hold supports bullish continuation.")
    if structure.failed_bounce:
        bear_score += 1
        notes.append("Failed bounce supports bearish continuation.")

    # Macro overlay
    if context.oil_change_dollars >= 2 and context.oil_trend == "rising":
        bear_score += 2
        notes.append("Oil rising sharply adds pressure to the market.")
    elif context.oil_trend == "stabilizing":
        bull_score += 1
        notes.append("Oil stabilizing may allow market relief.")
    elif context.oil_trend == "falling":
        bull_score += 1
        notes.append("Oil falling reduces macro pressure.")

    if context.macro_headline_bias == "bullish":
        bull_score += 1
        notes.append("Macro headline bias is bullish.")
    elif context.macro_headline_bias == "bearish":
        bear_score += 1
        notes.append("Macro headline bias is bearish.")

    if is_priority_window(ts):
        notes.append("Signal occurred during a priority institutional time window.")

    # Final regime
    if bull_score >= bear_score + 2:
        regime = "BULL"
        allowed_direction = "CALLS_ONLY"
    elif bear_score >= bull_score + 2:
        regime = "BEAR"
        allowed_direction = "PUTS_ONLY"
    else:
        regime = "CHOP"
        allowed_direction = "SCALPS_OR_AVOID"

    notes.append(f"Bull score: {bull_score}")
    notes.append(f"Bear score: {bear_score}")
    notes.append(f"Regime classified as {regime}.")

    return {
        "regime": regime,
        "allowed_direction": allowed_direction,
        "notes": notes,
        "bull_score": bull_score,
        "bear_score": bear_score,
    }

In [6]:
def is_priority_window(ts: datetime) -> bool:
    """
    Priority windows:
    9:30-11:00 and 15:00-16:15
    """
    current = ts.time()
    morning_start = time(9, 30)
    morning_end = time(11, 0)
    power_start = time(15, 0)
    power_end = time(16, 15)

    return (morning_start <= current <= morning_end) or (power_start <= current <= power_end)


def nearest_level(price: float, levels: List[float]) -> Optional[float]:
    clean_levels = [lvl for lvl in levels if lvl is not None]
    if not clean_levels:
      return None
    return min(clean_levels, key=lambda x: abs(x - price))

In [37]:
@dataclass
class Candle:
    timestamp: datetime
    open: float
    high: float
    low: float
    close: float
    volume: float


@dataclass
class MarketContext:
    symbol: str
    current_price: float
    vwap: float
    rsi: float
    oil_change_dollars: float = 0.0
    oil_trend: str = "neutral" # rising, falling, neutral, stabilizing
    macro_headline_bias: str = "neutral" # bullish, bearish, neutral
    big_print_levels: List[float] = field(default_factory=list)
    prior_day_high: Optional[float] = None
    prior_day_low: Optional[float] = None
    premarket_high: Optional[float] = None
    premarket_low: Optional[float] = None
    key_supports: List[float] = field(default_factory=list)
    key_resistances: List[float] = field(default_factory=list)


@dataclass
class StructureState:
    higher_lows: bool = False
    lower_highs: bool = False
    above_vwap: bool = False
    below_vwap: bool = False
    vwap_reclaimed: bool = False
    vwap_rejected: bool = False
    breakout_with_volume: bool = False
    rejection_at_level: bool = False
    retest_hold: bool = False
    failed_bounce: bool = False
    liquidity_grab_reversal: bool = False


return BotDecision(
    regime=regime_data["regime"],
    allowed_direction=regime_data["allowed_direction"],
    setup=setup,
    confidence=confidence,
    grade=grading["grade"],
    grade_score=grading["score"],
    entry_valid=entry["entry_valid"],
    stop_level=entry["stop_level"],
    target_level=entry["target_level"],
    reasoning=reasoning + grading["grade_notes"]
)

SyntaxError: 'return' outside function (4067752486.py, line 44)

In [2]:
from dataclasses import dataclass, field
from typing import List, Optional, Dict
from datetime import datetime, time
import json

In [244]:
import time

last_entry_action = None

while True:
    # Manual master switch
    if not BOT_ENABLED:
        print("🛑 Bot is manually disabled... waiting")
        time.sleep(60)
        continue

    # Market open/close notices
    handle_market_status()

    # Only run alerts during allowed hours
    if not is_trading_time():
        print("Outside trading hours... waiting")
        time.sleep(60)
        continue

    real_price = get_live_price()

    if real_price is not None:
        live_entry = {
            "symbol": "QQQ",
            "price": real_price,
            "score": 8,
            "final_score": 8,
            "decision": "B_SETUP",
            "reaction": "reclaim",
            "positionVsVwap": "above",
            "testCount": "first",
            "patterns": [],
            "regime": "trend_regime",
            "confidence": "MEDIUM_CONFIDENCE",
            "confidence_score": 2,
            "level": "support",
            "session": "open"
        }

        live_result = run_live_entry_check(live_entry)
        row = live_result.iloc[0]

        print("\n--- LIVE UPDATE ---")
        print("EST Time:", get_est_now().strftime("%Y-%m-%d %I:%M:%S %p"))
        print("Price:", row["price"])
        print("Decision:", row["decision"])
        print("Entry Timing:", row["entry_timing"])
        print("Action:", row["action"])
        print("Confidence:", row["confidence"])
        print("Position Size:", row["position_size"])
        print("Stop:", row["stop_loss"])
        print("Trailing Stop:", row["trailing_stop"])
        print("Target:", row["target"])

        # only send real entry alerts
        if row["action"] in ["FULL_SIZE_ENTRY", "NORMAL_ENTRY", "SMALL_SIZE_ENTRY"]:
            if row["action"] != last_entry_action:
                print("New entry action -> sending Discord alert")
                send_live_entry_alert(live_result)
                last_entry_action = row["action"]
            else:
                print("Same entry action -> no alert")
        else:
            print("Not an entry action -> no alert")
            last_entry_action = None

        update_trade_lifecycle(live_result)

    else:
        print("Skipping cycle - price fetch failed")

    time.sleep(10)

Status Code: 200

--- LIVE UPDATE ---
EST Time: 2026-04-13 06:15:19 PM
Price: 617.39
Decision: B_SETUP
Entry Timing: ENTRY_TRIGGER
Action: WAIT
Confidence: MEDIUM_CONFIDENCE
Position Size: 40% size
Stop: Wait
Trailing Stop: Wait
Target: Wait
Not an entry action -> no alert
Status Code: 200

--- LIVE UPDATE ---
EST Time: 2026-04-13 06:15:29 PM
Price: 617.39
Decision: B_SETUP
Entry Timing: ENTRY_TRIGGER
Action: WAIT
Confidence: MEDIUM_CONFIDENCE
Position Size: 40% size
Stop: Wait
Trailing Stop: Wait
Target: Wait
Not an entry action -> no alert
Status Code: 200

--- LIVE UPDATE ---
EST Time: 2026-04-13 06:15:40 PM
Price: 617.39
Decision: B_SETUP
Entry Timing: ENTRY_TRIGGER
Action: WAIT
Confidence: MEDIUM_CONFIDENCE
Position Size: 40% size
Stop: Wait
Trailing Stop: Wait
Target: Wait
Not an entry action -> no alert
Status Code: 200

--- LIVE UPDATE ---
EST Time: 2026-04-13 06:15:50 PM
Price: 617.39
Decision: B_SETUP
Entry Timing: ENTRY_TRIGGER
Action: WAIT
Confidence: MEDIUM_CONFIDENCE
Position Size: 40% size
Stop: Wait
Trailing Stop: Wait
Target: Wait
Not an entry action -> no alert
Status Code: 200

--- LIVE UPDATE ---
EST Time: 2026-04-13 06:16:00 PM
Price: 617.39
Decision: B_SETUP
Entry Timing: ENTRY_TRIGGER
Action: WAIT
Confidence: MEDIUM_CONFIDENCE
Position Size: 40% size
Stop: Wait
Trailing Stop: Wait
Target: Wait
Not an entry action -> no alert
Status Code: 200

--- LIVE UPDATE ---
EST Time: 2026-04-13 06:16:10 PM
Price: 617.39
Decision: B_SETUP
Entry Timing: ENTRY_TRIGGER
Action: WAIT
Confidence: MEDIUM_CONFIDENCE
Position Size: 40% size
Stop: Wait
Trailing Stop: Wait
Target: Wait
Not an entry action -> no alert
Status Code: 200

--- LIVE UPDATE ---
EST Time: 2026-04-13 06:16:20 PM
Price: 617.39
Decision: B_SETUP
Entry Timing: ENTRY_TRIGGER
Action: WAIT
Confidence: MEDIUM_CONFIDENCE
Position Size: 40% size
Stop: Wait
Trailing Stop: Wait
Target: Wait
Not an entry action -> no alert
Status Code: 200

--- LIVE UPDATE ---
EST Time: 2026-04-13 06:16:30 PM
Price: 617.39
Decision: B_SETUP
Entry Timing: ENTRY_TRIGGER
Action: WAIT
Confidence: MEDIUM_CONFIDENCE
Position Size: 40% size
Stop: Wait
Trailing Stop: Wait
Target: Wait
Not an entry action -> no alert
Status Code: 200

--- LIVE UPDATE ---
EST Time: 2026-04-13 06:16:40 PM
Price: 617.39
Decision: B_SETUP
Entry Timing: ENTRY_TRIGGER
Action: WAIT
Confidence: MEDIUM_CONFIDENCE
Position Size: 40% size
Stop: Wait
Trailing Stop: Wait
Target: Wait
Not an entry action -> no alert
Status Code: 200

--- LIVE UPDATE ---
EST Time: 2026-04-13 06:16:50 PM
Price: 617.39
Decision: B_SETUP
Entry Timing: ENTRY_TRIGGER
Action: WAIT
Confidence: MEDIUM_CONFIDENCE
Position Size: 40% size
Stop: Wait
Trailing Stop: Wait
Target: Wait
Not an entry action -> no alert
Status Code: 200

--- LIVE UPDATE ---
EST Time: 2026-04-13 06:17:01 PM
Price: 617.39
Decision: B_SETUP
Entry Timing: ENTRY_TRIGGER
Action: WAIT
Confidence: MEDIUM_CONFIDENCE
Position Size: 40% size
Stop: Wait
Trailing Stop: Wait
Target: Wait
Not an entry action -> no alert
Status Code: 200

--- LIVE UPDATE ---
EST Time: 2026-04-13 06:17:11 PM
Price: 617.39
Decision: B_SETUP
Entry Timing: ENTRY_TRIGGER
Action: WAIT
Confidence: MEDIUM_CONFIDENCE
Position Size: 40% size
Stop: Wait
Trailing Stop: Wait
Target: Wait
Not an entry action -> no alert
Status Code: 200

--- LIVE UPDATE ---
EST Time: 2026-04-13 06:17:21 PM
Price: 617.39
Decision: B_SETUP
Entry Timing: ENTRY_TRIGGER
Action: WAIT
Confidence: MEDIUM_CONFIDENCE
Position Size: 40% size
Stop: Wait
Trailing Stop: Wait
Target: Wait
Not an entry action -> no alert
Status Code: 200

--- LIVE UPDATE ---
EST Time: 2026-04-13 06:17:31 PM
Price: 617.39
Decision: B_SETUP
Entry Timing: ENTRY_TRIGGER
Action: WAIT
Confidence: MEDIUM_CONFIDENCE
Position Size: 40% size
Stop: Wait
Trailing Stop: Wait
Target: Wait
Not an entry action -> no alert
Status Code: 200

--- LIVE UPDATE ---
EST Time: 2026-04-13 06:17:41 PM
Price: 617.39
Decision: B_SETUP
Entry Timing: ENTRY_TRIGGER
Action: WAIT
Confidence: MEDIUM_CONFIDENCE
Position Size: 40% size
Stop: Wait
Trailing Stop: Wait
Target: Wait
Not an entry action -> no alert
Status Code: 200

--- LIVE UPDATE ---
EST Time: 2026-04-13 06:17:51 PM
Price: 617.39
Decision: B_SETUP
Entry Timing: ENTRY_TRIGGER
Action: WAIT
Confidence: MEDIUM_CONFIDENCE
Position Size: 40% size
Stop: Wait
Trailing Stop: Wait
Target: Wait
Not an entry action -> no alert
Status Code: 200

--- LIVE UPDATE ---
EST Time: 2026-04-13 06:18:01 PM
Price: 617.39
Decision: B_SETUP
Entry Timing: ENTRY_TRIGGER
Action: WAIT
Confidence: MEDIUM_CONFIDENCE
Position Size: 40% size
Stop: Wait
Trailing Stop: Wait
Target: Wait
Not an entry action -> no alert
Status Code: 200

--- LIVE UPDATE ---
EST Time: 2026-04-13 06:18:12 PM
Price: 617.39
Decision: B_SETUP
Entry Timing: ENTRY_TRIGGER
Action: WAIT
Confidence: MEDIUM_CONFIDENCE
Position Size: 40% size
Stop: Wait
Trailing Stop: Wait
Target: Wait
Not an entry action -> no alert
Status Code: 200

--- LIVE UPDATE ---
EST Time: 2026-04-13 06:18:22 PM
Price: 617.39
Decision: B_SETUP
Entry Timing: ENTRY_TRIGGER
Action: WAIT
Confidence: MEDIUM_CONFIDENCE
Position Size: 40% size
Stop: Wait
Trailing Stop: Wait
Target: Wait
Not an entry action -> no alert
Status Code: 200

--- LIVE UPDATE ---
EST Time: 2026-04-13 06:18:32 PM
Price: 617.39
Decision: B_SETUP
Entry Timing: ENTRY_TRIGGER
Action: WAIT
Confidence: MEDIUM_CONFIDENCE
Position Size: 40% size
Stop: Wait
Trailing Stop: Wait
Target: Wait
Not an entry action -> no alert
Status Code: 200

--- LIVE UPDATE ---
EST Time: 2026-04-13 06:18:42 PM
Price: 617.39
Decision: B_SETUP
Entry Timing: ENTRY_TRIGGER
Action: WAIT
Confidence: MEDIUM_CONFIDENCE
Position Size: 40% size
Stop: Wait
Trailing Stop: Wait
Target: Wait
Not an entry action -> no alert
Status Code: 200

--- LIVE UPDATE ---
EST Time: 2026-04-13 06:18:52 PM
Price: 617.39
Decision: B_SETUP
Entry Timing: ENTRY_TRIGGER
Action: WAIT
Confidence: MEDIUM_CONFIDENCE
Position Size: 40% size
Stop: Wait
Trailing Stop: Wait
Target: Wait
Not an entry action -> no alert
Status Code: 200

--- LIVE UPDATE ---
EST Time: 2026-04-13 06:19:02 PM
Price: 617.39
Decision: B_SETUP
Entry Timing: ENTRY_TRIGGER
Action: WAIT
Confidence: MEDIUM_CONFIDENCE
Position Size: 40% size
Stop: Wait
Trailing Stop: Wait
Target: Wait
Not an entry action -> no alert
Status Code: 200

--- LIVE UPDATE ---
EST Time: 2026-04-13 06:19:12 PM
Price: 617.39
Decision: B_SETUP
Entry Timing: ENTRY_TRIGGER
Action: WAIT
Confidence: MEDIUM_CONFIDENCE
Position Size: 40% size
Stop: Wait
Trailing Stop: Wait
Target: Wait
Not an entry action -> no alert
Status Code: 200

--- LIVE UPDATE ---
EST Time: 2026-04-13 06:19:23 PM
Price: 617.39
Decision: B_SETUP
Entry Timing: ENTRY_TRIGGER
Action: WAIT
Confidence: MEDIUM_CONFIDENCE
Position Size: 40% size
Stop: Wait
Trailing Stop: Wait
Target: Wait
Not an entry action -> no alert
Status Code: 200

--- LIVE UPDATE ---
EST Time: 2026-04-13 06:19:33 PM
Price: 617.39
Decision: B_SETUP
Entry Timing: ENTRY_TRIGGER
Action: WAIT
Confidence: MEDIUM_CONFIDENCE
Position Size: 40% size
Stop: Wait
Trailing Stop: Wait
Target: Wait
Not an entry action -> no alert
Status Code: 200

--- LIVE UPDATE ---
EST Time: 2026-04-13 06:19:43 PM
Price: 617.39
Decision: B_SETUP
Entry Timing: ENTRY_TRIGGER
Action: WAIT
Confidence: MEDIUM_CONFIDENCE
Position Size: 40% size
Stop: Wait
Trailing Stop: Wait
Target: Wait
Not an entry action -> no alert
Status Code: 200

--- LIVE UPDATE ---
EST Time: 2026-04-13 06:19:53 PM
Price: 617.39
Decision: B_SETUP
Entry Timing: ENTRY_TRIGGER
Action: WAIT
Confidence: MEDIUM_CONFIDENCE
Position Size: 40% size
Stop: Wait
Trailing Stop: Wait
Target: Wait
Not an entry action -> no alert
Status Code: 200

--- LIVE UPDATE ---
EST Time: 2026-04-13 06:20:03 PM
Price: 617.39
Decision: B_SETUP
Entry Timing: ENTRY_TRIGGER
Action: WAIT
Confidence: MEDIUM_CONFIDENCE
Position Size: 40% size
Stop: Wait
Trailing Stop: Wait
Target: Wait
Not an entry action -> no alert
Status Code: 200

--- LIVE UPDATE ---
EST Time: 2026-04-13 06:20:13 PM
Price: 617.39
Decision: B_SETUP
Entry Timing: ENTRY_TRIGGER
Action: WAIT
Confidence: MEDIUM_CONFIDENCE
Position Size: 40% size
Stop: Wait
Trailing Stop: Wait
Target: Wait
Not an entry action -> no alert
Status Code: 200

--- LIVE UPDATE ---
EST Time: 2026-04-13 06:20:23 PM
Price: 617.39
Decision: B_SETUP
Entry Timing: ENTRY_TRIGGER
Action: WAIT
Confidence: MEDIUM_CONFIDENCE
Position Size: 40% size
Stop: Wait
Trailing Stop: Wait
Target: Wait
Not an entry action -> no alert
Status Code: 200

--- LIVE UPDATE ---
EST Time: 2026-04-13 06:20:33 PM
Price: 617.39
Decision: B_SETUP
Entry Timing: ENTRY_TRIGGER
Action: WAIT
Confidence: MEDIUM_CONFIDENCE
Position Size: 40% size
Stop: Wait
Trailing Stop: Wait
Target: Wait
Not an entry action -> no alert
Status Code: 200

--- LIVE UPDATE ---
EST Time: 2026-04-13 06:20:44 PM
Price: 617.39
Decision: B_SETUP
Entry Timing: ENTRY_TRIGGER
Action: WAIT
Confidence: MEDIUM_CONFIDENCE
Position Size: 40% size
Stop: Wait
Trailing Stop: Wait
Target: Wait
Not an entry action -> no alert
Status Code: 200

--- LIVE UPDATE ---
EST Time: 2026-04-13 06:20:54 PM
Price: 617.39
Decision: B_SETUP
Entry Timing: ENTRY_TRIGGER
Action: WAIT
Confidence: MEDIUM_CONFIDENCE
Position Size: 40% size
Stop: Wait
Trailing Stop: Wait
Target: Wait
Not an entry action -> no alert
Status Code: 200

--- LIVE UPDATE ---
EST Time: 2026-04-13 06:21:04 PM
Price: 617.39
Decision: B_SETUP
Entry Timing: ENTRY_TRIGGER
Action: WAIT
Confidence: MEDIUM_CONFIDENCE
Position Size: 40% size
Stop: Wait
Trailing Stop: Wait
Target: Wait
Not an entry action -> no alert
Status Code: 200

--- LIVE UPDATE ---
EST Time: 2026-04-13 06:21:14 PM
Price: 617.39
Decision: B_SETUP
Entry Timing: ENTRY_TRIGGER
Action: WAIT
Confidence: MEDIUM_CONFIDENCE
Position Size: 40% size
Stop: Wait
Trailing Stop: Wait
Target: Wait
Not an entry action -> no alert
Status Code: 200

--- LIVE UPDATE ---
EST Time: 2026-04-13 06:21:24 PM
Price: 617.39
Decision: B_SETUP
Entry Timing: ENTRY_TRIGGER
Action: WAIT
Confidence: MEDIUM_CONFIDENCE
Position Size: 40% size
Stop: Wait
Trailing Stop: Wait
Target: Wait
Not an entry action -> no alert
Status Code: 200

--- LIVE UPDATE ---
EST Time: 2026-04-13 06:21:34 PM
Price: 617.39
Decision: B_SETUP
Entry Timing: ENTRY_TRIGGER
Action: WAIT
Confidence: MEDIUM_CONFIDENCE
Position Size: 40% size
Stop: Wait
Trailing Stop: Wait
Target: Wait
Not an entry action -> no alert
Status Code: 200

--- LIVE UPDATE ---
EST Time: 2026-04-13 06:21:44 PM
Price: 617.39
Decision: B_SETUP
Entry Timing: ENTRY_TRIGGER
Action: WAIT
Confidence: MEDIUM_CONFIDENCE
Position Size: 40% size
Stop: Wait
Trailing Stop: Wait
Target: Wait
Not an entry action -> no alert
Status Code: 200

--- LIVE UPDATE ---
EST Time: 2026-04-13 06:21:55 PM
Price: 617.39
Decision: B_SETUP
Entry Timing: ENTRY_TRIGGER
Action: WAIT
Confidence: MEDIUM_CONFIDENCE
Position Size: 40% size
Stop: Wait
Trailing Stop: Wait
Target: Wait
Not an entry action -> no alert
Status Code: 200

--- LIVE UPDATE ---
EST Time: 2026-04-13 06:22:05 PM
Price: 617.39
Decision: B_SETUP
Entry Timing: ENTRY_TRIGGER
Action: WAIT
Confidence: MEDIUM_CONFIDENCE
Position Size: 40% size
Stop: Wait
Trailing Stop: Wait
Target: Wait
Not an entry action -> no alert
Status Code: 200

--- LIVE UPDATE ---
EST Time: 2026-04-13 06:22:15 PM
Price: 617.39
Decision: B_SETUP
Entry Timing: ENTRY_TRIGGER
Action: WAIT
Confidence: MEDIUM_CONFIDENCE
Position Size: 40% size
Stop: Wait
Trailing Stop: Wait
Target: Wait
Not an entry action -> no alert
Status Code: 200

--- LIVE UPDATE ---
EST Time: 2026-04-13 06:22:25 PM
Price: 617.39
Decision: B_SETUP
Entry Timing: ENTRY_TRIGGER
Action: WAIT
Confidence: MEDIUM_CONFIDENCE
Position Size: 40% size
Stop: Wait
Trailing Stop: Wait
Target: Wait
Not an entry action -> no alert
Status Code: 200

--- LIVE UPDATE ---
EST Time: 2026-04-13 06:22:35 PM
Price: 617.39
Decision: B_SETUP
Entry Timing: ENTRY_TRIGGER
Action: WAIT
Confidence: MEDIUM_CONFIDENCE
Position Size: 40% size
Stop: Wait
Trailing Stop: Wait
Target: Wait
Not an entry action -> no alert
Status Code: 200

--- LIVE UPDATE ---
EST Time: 2026-04-13 06:22:45 PM
Price: 617.39
Decision: B_SETUP
Entry Timing: ENTRY_TRIGGER
Action: WAIT
Confidence: MEDIUM_CONFIDENCE
Position Size: 40% size
Stop: Wait
Trailing Stop: Wait
Target: Wait
Not an entry action -> no alert
Status Code: 200

--- LIVE UPDATE ---
EST Time: 2026-04-13 06:22:55 PM
Price: 617.39
Decision: B_SETUP
Entry Timing: ENTRY_TRIGGER
Action: WAIT
Confidence: MEDIUM_CONFIDENCE
Position Size: 40% size
Stop: Wait
Trailing Stop: Wait
Target: Wait
Not an entry action -> no alert
Status Code: 200

--- LIVE UPDATE ---
EST Time: 2026-04-13 06:23:06 PM
Price: 617.39
Decision: B_SETUP
Entry Timing: ENTRY_TRIGGER
Action: WAIT
Confidence: MEDIUM_CONFIDENCE
Position Size: 40% size
Stop: Wait
Trailing Stop: Wait
Target: Wait
Not an entry action -> no alert
Status Code: 200

--- LIVE UPDATE ---
EST Time: 2026-04-13 06:23:16 PM
Price: 617.39
Decision: B_SETUP
Entry Timing: ENTRY_TRIGGER
Action: WAIT
Confidence: MEDIUM_CONFIDENCE
Position Size: 40% size
Stop: Wait
Trailing Stop: Wait
Target: Wait
Not an entry action -> no alert
Status Code: 200

--- LIVE UPDATE ---
EST Time: 2026-04-13 06:23:26 PM
Price: 617.39
Decision: B_SETUP
Entry Timing: ENTRY_TRIGGER
Action: WAIT
Confidence: MEDIUM_CONFIDENCE
Position Size: 40% size
Stop: Wait
Trailing Stop: Wait
Target: Wait
Not an entry action -> no alert
Status Code: 200

--- LIVE UPDATE ---
EST Time: 2026-04-13 06:23:36 PM
Price: 617.39
Decision: B_SETUP
Entry Timing: ENTRY_TRIGGER
Action: WAIT
Confidence: MEDIUM_CONFIDENCE
Position Size: 40% size
Stop: Wait
Trailing Stop: Wait
Target: Wait
Not an entry action -> no alert
Status Code: 200

--- LIVE UPDATE ---
EST Time: 2026-04-13 06:23:46 PM
Price: 617.39
Decision: B_SETUP
Entry Timing: ENTRY_TRIGGER
Action: WAIT
Confidence: MEDIUM_CONFIDENCE
Position Size: 40% size
Stop: Wait
Trailing Stop: Wait
Target: Wait
Not an entry action -> no alert
Status Code: 200

--- LIVE UPDATE ---
EST Time: 2026-04-13 06:23:56 PM
Price: 617.39
Decision: B_SETUP
Entry Timing: ENTRY_TRIGGER
Action: WAIT
Confidence: MEDIUM_CONFIDENCE
Position Size: 40% size
Stop: Wait
Trailing Stop: Wait
Target: Wait
Not an entry action -> no alert
Status Code: 200

--- LIVE UPDATE ---
EST Time: 2026-04-13 06:24:06 PM
Price: 617.39
Decision: B_SETUP
Entry Timing: ENTRY_TRIGGER
Action: WAIT
Confidence: MEDIUM_CONFIDENCE
Position Size: 40% size
Stop: Wait
Trailing Stop: Wait
Target: Wait
Not an entry action -> no alert
Status Code: 200

--- LIVE UPDATE ---
EST Time: 2026-04-13 06:24:16 PM
Price: 617.39
Decision: B_SETUP
Entry Timing: ENTRY_TRIGGER
Action: WAIT
Confidence: MEDIUM_CONFIDENCE
Position Size: 40% size
Stop: Wait
Trailing Stop: Wait
Target: Wait
Not an entry action -> no alert
Status Code: 200

--- LIVE UPDATE ---
EST Time: 2026-04-13 06:24:26 PM
Price: 617.39
Decision: B_SETUP
Entry Timing: ENTRY_TRIGGER
Action: WAIT
Confidence: MEDIUM_CONFIDENCE
Position Size: 40% size
Stop: Wait
Trailing Stop: Wait
Target: Wait
Not an entry action -> no alert
Status Code: 200

--- LIVE UPDATE ---
EST Time: 2026-04-13 06:24:37 PM
Price: 617.39
Decision: B_SETUP
Entry Timing: ENTRY_TRIGGER
Action: WAIT
Confidence: MEDIUM_CONFIDENCE
Position Size: 40% size
Stop: Wait
Trailing Stop: Wait
Target: Wait
Not an entry action -> no alert
Status Code: 200

--- LIVE UPDATE ---
EST Time: 2026-04-13 06:24:47 PM
Price: 617.39
Decision: B_SETUP
Entry Timing: ENTRY_TRIGGER
Action: WAIT
Confidence: MEDIUM_CONFIDENCE
Position Size: 40% size
Stop: Wait
Trailing Stop: Wait
Target: Wait
Not an entry action -> no alert
Status Code: 200

--- LIVE UPDATE ---
EST Time: 2026-04-13 06:24:57 PM
Price: 617.39
Decision: B_SETUP
Entry Timing: ENTRY_TRIGGER
Action: WAIT
Confidence: MEDIUM_CONFIDENCE
Position Size: 40% size
Stop: Wait
Trailing Stop: Wait
Target: Wait
Not an entry action -> no alert
Status Code: 200

--- LIVE UPDATE ---
EST Time: 2026-04-13 06:25:07 PM
Price: 617.39
Decision: B_SETUP
Entry Timing: ENTRY_TRIGGER
Action: WAIT
Confidence: MEDIUM_CONFIDENCE
Position Size: 40% size
Stop: Wait
Trailing Stop: Wait
Target: Wait
Not an entry action -> no alert
Status Code: 200

--- LIVE UPDATE ---
EST Time: 2026-04-13 06:25:17 PM
Price: 617.39
Decision: B_SETUP
Entry Timing: ENTRY_TRIGGER
Action: WAIT
Confidence: MEDIUM_CONFIDENCE
Position Size: 40% size
Stop: Wait
Trailing Stop: Wait
Target: Wait
Not an entry action -> no alert
Status Code: 200

--- LIVE UPDATE ---
EST Time: 2026-04-13 06:25:27 PM
Price: 617.39
Decision: B_SETUP
Entry Timing: ENTRY_TRIGGER
Action: WAIT
Confidence: MEDIUM_CONFIDENCE
Position Size: 40% size
Stop: Wait
Trailing Stop: Wait
Target: Wait
Not an entry action -> no alert
Status Code: 200

--- LIVE UPDATE ---
EST Time: 2026-04-13 06:25:37 PM
Price: 617.39
Decision: B_SETUP
Entry Timing: ENTRY_TRIGGER
Action: WAIT
Confidence: MEDIUM_CONFIDENCE
Position Size: 40% size
Stop: Wait
Trailing Stop: Wait
Target: Wait
Not an entry action -> no alert
Status Code: 200

--- LIVE UPDATE ---
EST Time: 2026-04-13 06:25:47 PM
Price: 617.39
Decision: B_SETUP
Entry Timing: ENTRY_TRIGGER
Action: WAIT
Confidence: MEDIUM_CONFIDENCE
Position Size: 40% size
Stop: Wait
Trailing Stop: Wait
Target: Wait
Not an entry action -> no alert
Status Code: 200

--- LIVE UPDATE ---
EST Time: 2026-04-13 06:25:58 PM
Price: 617.39
Decision: B_SETUP
Entry Timing: ENTRY_TRIGGER
Action: WAIT
Confidence: MEDIUM_CONFIDENCE
Position Size: 40% size
Stop: Wait
Trailing Stop: Wait
Target: Wait
Not an entry action -> no alert
Status Code: 200

--- LIVE UPDATE ---
EST Time: 2026-04-13 06:26:08 PM
Price: 617.39
Decision: B_SETUP
Entry Timing: ENTRY_TRIGGER
Action: WAIT
Confidence: MEDIUM_CONFIDENCE
Position Size: 40% size
Stop: Wait
Trailing Stop: Wait
Target: Wait
Not an entry action -> no alert
Status Code: 200

--- LIVE UPDATE ---
EST Time: 2026-04-13 06:26:18 PM
Price: 617.39
Decision: B_SETUP
Entry Timing: ENTRY_TRIGGER
Action: WAIT
Confidence: MEDIUM_CONFIDENCE
Position Size: 40% size
Stop: Wait
Trailing Stop: Wait
Target: Wait
Not an entry action -> no alert
Status Code: 200

--- LIVE UPDATE ---
EST Time: 2026-04-13 06:26:28 PM
Price: 617.39
Decision: B_SETUP
Entry Timing: ENTRY_TRIGGER
Action: WAIT
Confidence: MEDIUM_CONFIDENCE
Position Size: 40% size
Stop: Wait
Trailing Stop: Wait
Target: Wait
Not an entry action -> no alert
Status Code: 200

--- LIVE UPDATE ---
EST Time: 2026-04-13 06:26:38 PM
Price: 617.39
Decision: B_SETUP
Entry Timing: ENTRY_TRIGGER
Action: WAIT
Confidence: MEDIUM_CONFIDENCE
Position Size: 40% size
Stop: Wait
Trailing Stop: Wait
Target: Wait
Not an entry action -> no alert
Status Code: 200

--- LIVE UPDATE ---
EST Time: 2026-04-13 06:26:48 PM
Price: 617.39
Decision: B_SETUP
Entry Timing: ENTRY_TRIGGER
Action: WAIT
Confidence: MEDIUM_CONFIDENCE
Position Size: 40% size
Stop: Wait
Trailing Stop: Wait
Target: Wait
Not an entry action -> no alert
Status Code: 200

--- LIVE UPDATE ---
EST Time: 2026-04-13 06:26:58 PM
Price: 617.39
Decision: B_SETUP
Entry Timing: ENTRY_TRIGGER
Action: WAIT
Confidence: MEDIUM_CONFIDENCE
Position Size: 40% size
Stop: Wait
Trailing Stop: Wait
Target: Wait
Not an entry action -> no alert
Status Code: 200

--- LIVE UPDATE ---
EST Time: 2026-04-13 06:27:08 PM
Price: 617.39
Decision: B_SETUP
Entry Timing: ENTRY_TRIGGER
Action: WAIT
Confidence: MEDIUM_CONFIDENCE
Position Size: 40% size
Stop: Wait
Trailing Stop: Wait
Target: Wait
Not an entry action -> no alert
Status Code: 200

--- LIVE UPDATE ---
EST Time: 2026-04-13 06:27:19 PM
Price: 617.39
Decision: B_SETUP
Entry Timing: ENTRY_TRIGGER
Action: WAIT
Confidence: MEDIUM_CONFIDENCE
Position Size: 40% size
Stop: Wait
Trailing Stop: Wait
Target: Wait
Not an entry action -> no alert
Status Code: 200

--- LIVE UPDATE ---
EST Time: 2026-04-13 06:27:29 PM
Price: 617.39
Decision: B_SETUP
Entry Timing: ENTRY_TRIGGER
Action: WAIT
Confidence: MEDIUM_CONFIDENCE
Position Size: 40% size
Stop: Wait
Trailing Stop: Wait
Target: Wait

KeyboardInterrupt:

In [243]:
def turn_bot_on():
    global BOT_ENABLED
    BOT_ENABLED = True
    print("✅ Bot enabled")

def turn_bot_off():
    global BOT_ENABLED
    BOT_ENABLED = False
    print("🛑 Bot disabled")

In [241]:
BOT_ENABLED = True

In [240]:
send_market_status_alert("🚀 AI SYSTEM ACTIVE — MARKET OPEN")
send_market_status_alert("📴 AI SYSTEM PAUSED — MARKET CLOSED")

Status Code: 204
Response:
Status Code: 204
Response:

In [239]:
import time

last_entry_action = None

while True:
    # Handle market open/close alerts
    handle_market_status()

    if not is_trading_time():
        print("Outside trading hours... waiting")
        time.sleep(60)
        continue

    real_price = get_live_price()

    if real_price is not None:
        live_entry = {
            "symbol": "QQQ",
            "price": real_price,
            "score": 8,
            "final_score": 8,
            "decision": "B_SETUP",
            "reaction": "reclaim",
            "positionVsVwap": "above",
            "testCount": "first",
            "patterns": [],
            "regime": "trend_regime",
            "confidence": "MEDIUM_CONFIDENCE",
            "confidence_score": 2,
            "level": "support",
            "session": "open"
        }

        live_result = run_live_entry_check(live_entry)
        row = live_result.iloc[0]

        print("\n--- LIVE UPDATE ---")
        print("EST Time:", get_est_now().strftime("%Y-%m-%d %I:%M:%S %p"))
        print("Price:", row["price"])
        print("Decision:", row["decision"])
        print("Entry Timing:", row["entry_timing"])
        print("Action:", row["action"])
        print("Confidence:", row["confidence"])
        print("Position Size:", row["position_size"])
        print("Stop:", row["stop_loss"])
        print("Trailing Stop:", row["trailing_stop"])
        print("Target:", row["target"])

        # Only send real entry alerts
        if row["action"] in ["FULL_SIZE_ENTRY", "NORMAL_ENTRY", "SMALL_SIZE_ENTRY"]:
            if row["action"] != last_entry_action:
                print("New entry action -> sending Discord alert")
                send_live_entry_alert(live_result)
                last_entry_action = row["action"]
            else:
                print("Same entry action -> no alert")
        else:
            print("Not an entry action -> no alert")
            last_entry_action = None

        update_trade_lifecycle(live_result)

    else:
        print("Skipping cycle - price fetch failed")

    time.sleep(10)

Status Code: 204
Response:
Status Code: 200

--- LIVE UPDATE ---
EST Time: 2026-04-13 06:11:08 PM
Price: 617.39
Decision: B_SETUP
Entry Timing: ENTRY_TRIGGER
Action: WAIT
Confidence: MEDIUM_CONFIDENCE
Position Size: 40% size
Stop: Wait
Trailing Stop: Wait
Target: Wait
Not an entry action -> no alert
Status Code: 200

--- LIVE UPDATE ---
EST Time: 2026-04-13 06:11:18 PM
Price: 617.39
Decision: B_SETUP
Entry Timing: ENTRY_TRIGGER
Action: WAIT
Confidence: MEDIUM_CONFIDENCE
Position Size: 40% size
Stop: Wait
Trailing Stop: Wait
Target: Wait
Not an entry action -> no alert

KeyboardInterrupt:

In [238]:
def handle_market_status():
    global market_status

    now = get_est_now()
    today_str = now.strftime("%Y-%m-%d")
    trading_now = is_trading_time()

    # Market just became active
    if trading_now and not market_status["is_active"]:
        if market_status["last_open_alert_date"] != today_str:
            send_market_status_alert("🚀 AI SYSTEM ACTIVE — MARKET OPEN")
            market_status["last_open_alert_date"] = today_str

        market_status["is_active"] = True

    # Market just became inactive
    elif not trading_now and market_status["is_active"]:
        if market_status["last_close_alert_date"] != today_str:
            send_market_status_alert("📴 AI SYSTEM PAUSED — MARKET CLOSED")
            market_status["last_close_alert_date"] = today_str

        market_status["is_active"] = False

In [237]:
def send_market_status_alert(message):
    send_to_discord(message)

In [236]:
from datetime import datetime
import pytz

def get_est_now():
    est = pytz.timezone("US/Eastern")
    return datetime.now(est)

def is_trading_time():
    now = get_est_now()

    start = now.replace(hour=9, minute=0, second=0, microsecond=0)
    end = now.replace(hour=20, minute=0, second=0, microsecond=0)

    return start <= now <= end

In [235]:
market_status = {
    "is_active": False,
    "last_open_alert_date": None,
    "last_close_alert_date": None
}

In [234]:
import time

last_entry_action = None

while True:
    if not is_trading_time():
        print("Outside trading hours... waiting")
        time.sleep(60)
        continue

    real_price = get_live_price()

    if real_price is not None:
        live_entry = {
            "symbol": "QQQ",
            "price": real_price,
            "score": 8,
            "final_score": 8,
            "decision": "B_SETUP",
            "reaction": "reclaim",
            "positionVsVwap": "above",
            "testCount": "first",
            "patterns": [],
            "regime": "trend_regime",
            "confidence": "MEDIUM_CONFIDENCE",
            "confidence_score": 2,
            "level": "support",
            "session": "open"
        }

        live_result = run_live_entry_check(live_entry)
        row = live_result.iloc[0]

        print("\n--- LIVE UPDATE ---")
        print("Time:", datetime.now())
        print("Price:", row["price"])
        print("Action:", row["action"])

        # ONLY SEND ENTRY ALERTS
        if row["action"] in ["FULL_SIZE_ENTRY", "NORMAL_ENTRY", "SMALL_SIZE_ENTRY"]:
            if row["action"] != last_entry_action:
                send_live_entry_alert(live_result)
                last_entry_action = row["action"]
        else:
            last_entry_action = None

        update_trade_lifecycle(live_result)

    else:
        print("Price fetch failed")

    time.sleep(10)

Status Code: 200

--- LIVE UPDATE ---
Time: 2026-04-13 22:04:39.270042
Price: 617.39
Action: WAIT
Status Code: 200

--- LIVE UPDATE ---
Time: 2026-04-13 22:04:49.376854
Price: 617.39
Action: WAIT
Status Code: 200

--- LIVE UPDATE ---
Time: 2026-04-13 22:04:59.484388
Price: 617.39
Action: WAIT
Status Code: 200

--- LIVE UPDATE ---
Time: 2026-04-13 22:05:09.597480
Price: 617.39
Action: WAIT
Status Code: 200

--- LIVE UPDATE ---
Time: 2026-04-13 22:05:19.728900
Price: 617.39
Action: WAIT
Status Code: 200

--- LIVE UPDATE ---
Time: 2026-04-13 22:05:29.883984
Price: 617.39
Action: WAIT
Status Code: 200

--- LIVE UPDATE ---
Time: 2026-04-13 22:05:40.043999
Price: 617.39
Action: WAIT
Status Code: 200

--- LIVE UPDATE ---
Time: 2026-04-13 22:05:50.206380
Price: 617.39
Action: WAIT
Status Code: 200

--- LIVE UPDATE ---
Time: 2026-04-13 22:06:00.314592
Price: 617.39
Action: WAIT
Status Code: 200

--- LIVE UPDATE ---
Time: 2026-04-13 22:06:10.429746
Price: 617.39
Action: WAIT
Status Code: 200

--- LIVE UPDATE ---
Time: 2026-04-13 22:06:20.531439
Price: 617.39
Action: WAIT
Status Code: 200

--- LIVE UPDATE ---
Time: 2026-04-13 22:06:30.643995
Price: 617.39
Action: WAIT
Status Code: 200

--- LIVE UPDATE ---
Time: 2026-04-13 22:06:40.751443
Price: 617.39
Action: WAIT
Status Code: 200

--- LIVE UPDATE ---
Time: 2026-04-13 22:06:51.051916
Price: 617.39
Action: WAIT
Status Code: 200

--- LIVE UPDATE ---
Time: 2026-04-13 22:07:01.153843
Price: 617.39
Action: WAIT
Status Code: 200

--- LIVE UPDATE ---
Time: 2026-04-13 22:07:11.258105
Price: 617.39
Action: WAIT
Status Code: 200

--- LIVE UPDATE ---
Time: 2026-04-13 22:07:21.386047
Price: 617.39
Action: WAIT
Status Code: 200

--- LIVE UPDATE ---
Time: 2026-04-13 22:07:31.509225
Price: 617.39
Action: WAIT
Status Code: 200

--- LIVE UPDATE ---
Time: 2026-04-13 22:07:41.611287
Price: 617.39
Action: WAIT
Status Code: 200

--- LIVE UPDATE ---
Time: 2026-04-13 22:07:51.735378
Price: 617.39
Action: WAIT
Status Code: 200

--- LIVE UPDATE ---
Time: 2026-04-13 22:08:01.837104
Price: 617.39
Action: WAIT
Status Code: 200

--- LIVE UPDATE ---
Time: 2026-04-13 22:08:11.939420
Price: 617.39
Action: WAIT
Status Code: 200

--- LIVE UPDATE ---
Time: 2026-04-13 22:08:22.072889
Price: 617.39
Action: WAIT
Status Code: 200

--- LIVE UPDATE ---
Time: 2026-04-13 22:08:32.242215
Price: 617.39
Action: WAIT
Status Code: 200

--- LIVE UPDATE ---
Time: 2026-04-13 22:08:42.345070
Price: 617.39
Action: WAIT
Status Code: 200

--- LIVE UPDATE ---
Time: 2026-04-13 22:08:52.450451
Price: 617.39
Action: WAIT
Status Code: 200

--- LIVE UPDATE ---
Time: 2026-04-13 22:09:02.558518
Price: 617.39
Action: WAIT
Status Code: 200

--- LIVE UPDATE ---
Time: 2026-04-13 22:09:12.660795
Price: 617.39
Action: WAIT
Status Code: 200

--- LIVE UPDATE ---
Time: 2026-04-13 22:09:22.799720
Price: 617.39
Action: WAIT
Status Code: 200

--- LIVE UPDATE ---
Time: 2026-04-13 22:09:32.865968
Price: 617.39
Action: WAIT
Status Code: 200

--- LIVE UPDATE ---
Time: 2026-04-13 22:09:42.976620
Price: 617.39
Action: WAIT
Status Code: 200

--- LIVE UPDATE ---
Time: 2026-04-13 22:09:53.095264
Price: 617.39
Action: WAIT
Status Code: 200

--- LIVE UPDATE ---
Time: 2026-04-13 22:10:03.212895
Price: 617.39
Action: WAIT
Status Code: 200

--- LIVE UPDATE ---
Time: 2026-04-13 22:10:13.312015
Price: 617.39
Action: WAIT
Status Code: 200

--- LIVE UPDATE ---
Time: 2026-04-13 22:10:23.436027
Price: 617.39
Action: WAIT

KeyboardInterrupt:

In [233]:
from datetime import datetime
import pytz

def is_trading_time():
    est = pytz.timezone("US/Eastern")
    now = datetime.now(est)

    start = now.replace(hour=9, minute=0, second=0, microsecond=0)
    end = now.replace(hour=20, minute=0, second=0, microsecond=0)

    return start <= now <= end

In [232]:
import time

last_entry_action = None

while True:
    real_price = get_live_price()

    if real_price is not None:
        live_entry = {
            "symbol": "QQQ",
            "price": real_price,
            "score": 8,
            "final_score": 8,
            "decision": "B_SETUP",
            "reaction": "reclaim",
            "positionVsVwap": "above",
            "testCount": "first",
            "patterns": [],
            "regime": "trend_regime",
            "confidence": "MEDIUM_CONFIDENCE",
            "confidence_score": 2,
            "level": "support",
            "session": "open"
        }

        live_result = run_live_entry_check(live_entry)
        row = live_result.iloc[0]

        print("\n--- LIVE UPDATE ---")
        print("Price:", row["price"])
        print("Decision:", row["decision"])
        print("Entry Timing:", row["entry_timing"])
        print("Action:", row["action"])
        print("Confidence:", row["confidence"])
        print("Position Size:", row["position_size"])
        print("Stop:", row["stop_loss"])
        print("Target:", row["target"])
        print("Trailing Stop:", row["trailing_stop"])

        # only send real entry alerts
        if row["action"] in ["FULL_SIZE_ENTRY", "NORMAL_ENTRY", "SMALL_SIZE_ENTRY"]:
            if row["action"] != last_entry_action:
                print("New entry action -> sending Discord alert")
                send_live_entry_alert(live_result)
                last_entry_action = row["action"]
            else:
                print("Same entry action -> no alert")
        else:
            print("Not an entry action -> no alert")
            last_entry_action = None

        update_trade_lifecycle(live_result)

    else:
        print("Skipping cycle - price fetch failed")

    time.sleep(10)

Status Code: 200

--- LIVE UPDATE ---
Price: 617.39
Decision: B_SETUP
Entry Timing: ENTRY_TRIGGER
Action: WAIT
Confidence: MEDIUM_CONFIDENCE
Position Size: 40% size
Stop: Wait
Target: Wait
Trailing Stop: Wait
Not an entry action -> no alert
Status Code: 200

--- LIVE UPDATE ---
Price: 617.39
Decision: B_SETUP
Entry Timing: ENTRY_TRIGGER
Action: WAIT
Confidence: MEDIUM_CONFIDENCE
Position Size: 40% size
Stop: Wait
Target: Wait
Trailing Stop: Wait
Not an entry action -> no alert
Status Code: 200

--- LIVE UPDATE ---
Price: 617.39
Decision: B_SETUP
Entry Timing: ENTRY_TRIGGER
Action: WAIT
Confidence: MEDIUM_CONFIDENCE
Position Size: 40% size
Stop: Wait
Target: Wait
Trailing Stop: Wait
Not an entry action -> no alert
Status Code: 200

--- LIVE UPDATE ---
Price: 617.39
Decision: B_SETUP
Entry Timing: ENTRY_TRIGGER
Action: WAIT
Confidence: MEDIUM_CONFIDENCE
Position Size: 40% size
Stop: Wait
Target: Wait
Trailing Stop: Wait
Not an entry action -> no alert
Status Code: 200

--- LIVE UPDATE ---
Price: 617.39
Decision: B_SETUP
Entry Timing: ENTRY_TRIGGER
Action: WAIT
Confidence: MEDIUM_CONFIDENCE
Position Size: 40% size
Stop: Wait
Target: Wait
Trailing Stop: Wait
Not an entry action -> no alert
Status Code: 200

--- LIVE UPDATE ---
Price: 617.39
Decision: B_SETUP
Entry Timing: ENTRY_TRIGGER
Action: WAIT
Confidence: MEDIUM_CONFIDENCE
Position Size: 40% size
Stop: Wait
Target: Wait
Trailing Stop: Wait
Not an entry action -> no alert
Status Code: 200

--- LIVE UPDATE ---
Price: 617.39
Decision: B_SETUP
Entry Timing: ENTRY_TRIGGER
Action: WAIT
Confidence: MEDIUM_CONFIDENCE
Position Size: 40% size
Stop: Wait
Target: Wait
Trailing Stop: Wait
Not an entry action -> no alert

KeyboardInterrupt:

In [231]:
last_entry_action = None

In [230]:
import time

while True:
    # -------------------------
    # GET LIVE PRICE
    # -------------------------
    real_price = get_live_price()

    if real_price is not None:
        # -------------------------
        # BUILD ENTRY INPUT
        # -------------------------
        live_entry = {
            "symbol": "QQQ",
            "price": real_price,
            "score": 8,
            "final_score": 8,
            "decision": "B_SETUP",
            "reaction": "reclaim",
            "positionVsVwap": "above",
            "testCount": "first",
            "patterns": [],
            "regime": "trend_regime",
            "confidence": "MEDIUM_CONFIDENCE",
            "confidence_score": 2,
            "level": "support",
            "session": "open"
        }

        # -------------------------
        # RUN FULL ENGINE
        # -------------------------
        live_result = run_live_entry_check(live_entry)

        row = live_result.iloc[0]

        # -------------------------
        # PRINT LIVE UPDATE
        # -------------------------
        print("\n--- LIVE UPDATE ---")
        print("Price:", row["price"])
        print("Decision:", row["decision"])
        print("Action:", row["action"])
        print("Confidence:", row["confidence"])
        print("Position Size:", row["position_size"])
        print("Stop:", row["stop_loss"])
        print("Target:", row["target"])
        print("Trailing Stop:", row["trailing_stop"])

        # -------------------------
        # SEND ALERT (ONLY ON ENTRY)
        # -------------------------
        if row["entry_timing"] == "ENTRY_TRIGGER":
            send_live_entry_alert(live_result)

        # -------------------------
        # TRADE LIFECYCLE TRACKING
        # -------------------------
        update_trade_lifecycle(live_result)

    else:
        print("Skipping cycle - price fetch failed")

    # -------------------------
    # LOOP DELAY
    # -------------------------
    time.sleep(10)

Status Code: 200

--- LIVE UPDATE ---
Price: 617.39
Decision: B_SETUP
Action: WAIT
Confidence: MEDIUM_CONFIDENCE
Position Size: 40% size
Stop: Wait
Target: Wait
Trailing Stop: Wait
Status Code: 204
Response:
Status Code: 200

--- LIVE UPDATE ---
Price: 617.39
Decision: B_SETUP
Action: WAIT
Confidence: MEDIUM_CONFIDENCE
Position Size: 40% size
Stop: Wait
Target: Wait
Trailing Stop: Wait
Status Code: 204
Response:
Status Code: 200

--- LIVE UPDATE ---
Price: 617.39
Decision: B_SETUP
Action: WAIT
Confidence: MEDIUM_CONFIDENCE
Position Size: 40% size
Stop: Wait
Target: Wait
Trailing Stop: Wait
Status Code: 204
Response:
Status Code: 200

--- LIVE UPDATE ---
Price: 617.39
Decision: B_SETUP
Action: WAIT
Confidence: MEDIUM_CONFIDENCE
Position Size: 40% size
Stop: Wait
Target: Wait
Trailing Stop: Wait
Status Code: 204
Response:
Status Code: 200

--- LIVE UPDATE ---
Price: 617.39
Decision: B_SETUP
Action: WAIT
Confidence: MEDIUM_CONFIDENCE
Position Size: 40% size
Stop: Wait
Target: Wait
Trailing Stop: Wait
Status Code: 204
Response:
Status Code: 200

--- LIVE UPDATE ---
Price: 617.39
Decision: B_SETUP
Action: WAIT
Confidence: MEDIUM_CONFIDENCE
Position Size: 40% size
Stop: Wait
Target: Wait
Trailing Stop: Wait
Status Code: 204
Response:
Status Code: 200

--- LIVE UPDATE ---
Price: 617.39
Decision: B_SETUP
Action: WAIT
Confidence: MEDIUM_CONFIDENCE
Position Size: 40% size
Stop: Wait
Target: Wait
Trailing Stop: Wait
Status Code: 204
Response:
Status Code: 200

--- LIVE UPDATE ---
Price: 617.39
Decision: B_SETUP
Action: WAIT
Confidence: MEDIUM_CONFIDENCE
Position Size: 40% size
Stop: Wait
Target: Wait
Trailing Stop: Wait
Status Code: 204
Response:
Status Code: 200

--- LIVE UPDATE ---
Price: 617.39
Decision: B_SETUP
Action: WAIT
Confidence: MEDIUM_CONFIDENCE
Position Size: 40% size
Stop: Wait
Target: Wait
Trailing Stop: Wait
Status Code: 204
Response:
Status Code: 200

--- LIVE UPDATE ---
Price: 617.39
Decision: B_SETUP
Action: WAIT
Confidence: MEDIUM_CONFIDENCE
Position Size: 40% size
Stop: Wait
Target: Wait
Trailing Stop: Wait
Status Code: 204
Response:
Status Code: 200

--- LIVE UPDATE ---
Price: 617.39
Decision: B_SETUP
Action: WAIT
Confidence: MEDIUM_CONFIDENCE
Position Size: 40% size
Stop: Wait
Target: Wait
Trailing Stop: Wait
Status Code: 204
Response:
Status Code: 200

--- LIVE UPDATE ---
Price: 617.39
Decision: B_SETUP
Action: WAIT
Confidence: MEDIUM_CONFIDENCE
Position Size: 40% size
Stop: Wait
Target: Wait
Trailing Stop: Wait
Status Code: 204
Response:
Status Code: 200

--- LIVE UPDATE ---
Price: 617.39
Decision: B_SETUP
Action: WAIT
Confidence: MEDIUM_CONFIDENCE
Position Size: 40% size
Stop: Wait
Target: Wait
Trailing Stop: Wait
Status Code: 204
Response:
Status Code: 200

--- LIVE UPDATE ---
Price: 617.39
Decision: B_SETUP
Action: WAIT
Confidence: MEDIUM_CONFIDENCE
Position Size: 40% size
Stop: Wait
Target: Wait
Trailing Stop: Wait
Status Code: 204
Response:
Status Code: 200

--- LIVE UPDATE ---
Price: 617.39
Decision: B_SETUP
Action: WAIT
Confidence: MEDIUM_CONFIDENCE
Position Size: 40% size
Stop: Wait
Target: Wait
Trailing Stop: Wait
Status Code: 204
Response:
Status Code: 200

--- LIVE UPDATE ---
Price: 617.39
Decision: B_SETUP
Action: WAIT
Confidence: MEDIUM_CONFIDENCE
Position Size: 40% size
Stop: Wait
Target: Wait
Trailing Stop: Wait
Status Code: 204
Response:
Status Code: 200

--- LIVE UPDATE ---
Price: 617.39
Decision: B_SETUP
Action: WAIT
Confidence: MEDIUM_CONFIDENCE
Position Size: 40% size
Stop: Wait
Target: Wait
Trailing Stop: Wait
Status Code: 204
Response:
Status Code: 200

--- LIVE UPDATE ---
Price: 617.39
Decision: B_SETUP
Action: WAIT
Confidence: MEDIUM_CONFIDENCE
Position Size: 40% size
Stop: Wait
Target: Wait
Trailing Stop: Wait
Status Code: 204
Response:
Status Code: 200

--- LIVE UPDATE ---
Price: 617.39
Decision: B_SETUP
Action: WAIT
Confidence: MEDIUM_CONFIDENCE
Position Size: 40% size
Stop: Wait
Target: Wait
Trailing Stop: Wait
Status Code: 204
Response:
Status Code: 200

--- LIVE UPDATE ---
Price: 617.39
Decision: B_SETUP
Action: WAIT
Confidence: MEDIUM_CONFIDENCE
Position Size: 40% size
Stop: Wait
Target: Wait
Trailing Stop: Wait
Status Code: 204
Response:
Status Code: 200

--- LIVE UPDATE ---
Price: 617.39
Decision: B_SETUP
Action: WAIT
Confidence: MEDIUM_CONFIDENCE
Position Size: 40% size
Stop: Wait
Target: Wait
Trailing Stop: Wait
Status Code: 204
Response:
Status Code: 200

--- LIVE UPDATE ---
Price: 617.39
Decision: B_SETUP
Action: WAIT
Confidence: MEDIUM_CONFIDENCE
Position Size: 40% size
Stop: Wait
Target: Wait
Trailing Stop: Wait
Status Code: 204
Response:
Status Code: 200

--- LIVE UPDATE ---
Price: 617.39
Decision: B_SETUP
Action: WAIT
Confidence: MEDIUM_CONFIDENCE
Position Size: 40% size
Stop: Wait
Target: Wait
Trailing Stop: Wait
Status Code: 204
Response:
Status Code: 200

--- LIVE UPDATE ---
Price: 617.39
Decision: B_SETUP
Action: WAIT
Confidence: MEDIUM_CONFIDENCE
Position Size: 40% size
Stop: Wait
Target: Wait
Trailing Stop: Wait
Status Code: 204
Response:
Status Code: 200

--- LIVE UPDATE ---
Price: 617.39
Decision: B_SETUP
Action: WAIT
Confidence: MEDIUM_CONFIDENCE
Position Size: 40% size
Stop: Wait
Target: Wait
Trailing Stop: Wait
Status Code: 204
Response:
Status Code: 200

--- LIVE UPDATE ---
Price: 617.39
Decision: B_SETUP
Action: WAIT
Confidence: MEDIUM_CONFIDENCE
Position Size: 40% size
Stop: Wait
Target: Wait
Trailing Stop: Wait
Status Code: 204
Response:
Status Code: 200

--- LIVE UPDATE ---
Price: 617.39
Decision: B_SETUP
Action: WAIT
Confidence: MEDIUM_CONFIDENCE
Position Size: 40% size
Stop: Wait
Target: Wait
Trailing Stop: Wait
Status Code: 204
Response:

KeyboardInterrupt:

In [229]:
def update_trade_lifecycle(live_df):
    global trade_state

    row = live_df.iloc[0]
    price = row["price"]

    # -------------------------
    # ENTER TRADE
    # -------------------------
    if not trade_state["active"] and row["action"] in ["FULL_SIZE_ENTRY", "NORMAL_ENTRY"]:
        trade_state["active"] = True
        trade_state["entry_price"] = price
        trade_state["stop_loss"] = row["stop_loss"]
        trade_state["target"] = row["target"]
        trade_state["r_multiple"] = row["r_multiple"]

        print("🚀 Trade Opened")

    # -------------------------
    # MANAGE ACTIVE TRADE
    # -------------------------
    elif trade_state["active"]:
        entry = trade_state["entry_price"]
        stop = trade_state["stop_loss"]

        if isinstance(stop, (int, float)):
            risk = entry - stop
            move = price - entry
            r_gain = move / risk if risk != 0 else 0

            print(f"📊 Live R Gain: {round(r_gain, 2)}R")

        # Stop hit
        if isinstance(stop, (int, float)) and price <= stop:
            print("❌ Stopped Out")
            trade_state["active"] = False

        # Target hit
        if isinstance(trade_state["target"], (int, float)) and price >= trade_state["target"]:
            print("💰 Target Hit")
            trade_state["active"] = False

    return trade_state

In [228]:
trade_state = {
    "active": False,
    "entry_price": None,
    "stop_loss": None,
    "target": None,
    "r_multiple": None
}

In [227]:
send_live_entry_alert(live_result)

Status Code: 204
Response:

In [225]:
live_result[[
    "symbol",
    "price",
    "entry_price",
    "stop_loss",
    "trailing_stop",
    "target",
    "r_multiple"
]]

  symbol  price  entry_price  stop_loss  trailing_stop  target r_multiple
0    QQQ  611.9        611.9      610.9          610.9   613.9  2R target

In [224]:
live_result = run_live_entry_check(live_entry)

In [222]:
def trailing_stop_logic(row):
    price = row["price"]
    entry = row.get("entry_price", price)
    stop = row["stop_loss"]

    # Only apply to active trades
    if row["action"] not in ["FULL_SIZE_ENTRY", "NORMAL_ENTRY", "SMALL_SIZE_ENTRY"]:
        return stop

    risk = entry - stop if isinstance(stop, (int, float)) else None

    if risk is None or risk == 0:
        return stop

    # Calculate R gained
    move = price - entry
    r_gain = move / risk

    # 1R → breakeven
    if r_gain >= 1:
        stop = entry

    # 2R → trail lock
    if r_gain >= 2:
        stop = round(price - 0.5, 2)

    return stop

In [221]:
send_live_entry_alert(live_result)

Status Code: 204
Response:

In [220]:
live_result = run_live_entry_check(live_entry)

live_result[[
    "symbol",
    "action",
    "position_size",
    "stop_loss",
    "target",
    "r_multiple"
]]

  symbol        action position_size  stop_loss  target r_multiple
0    QQQ  NORMAL_ENTRY      70% size      610.9   613.9  2R target

In [218]:
def trade_levels(row):
    price = row["price"]
    action = row["action"]

    risk_per_share = 1.0

    stop = None
    target = None
    r_multiple = None

    if action in ["FULL_SIZE_ENTRY", "NORMAL_ENTRY", "SMALL_SIZE_ENTRY"]:
        stop = round(price - risk_per_share, 2)
        target = round(price + (2 * risk_per_share), 2)
        r_multiple = "2R target"

    elif action == "TAKE_PROFIT":
        stop = "Trailing active"
        target = "Scaling out"
        r_multiple = "Lock gains"

    elif action == "EXIT_OR_AVOID":
        stop = "No trade"
        target = "No trade"
        r_multiple = "0R"

    else:
        stop = "Wait"
        target = "Wait"
        r_multiple = "N/A"

    return stop, target, r_multiple

In [217]:
send_live_entry_alert(live_result)

KeyError: 'r_multiple'

In [212]:
send_live_entry_alert(live_result)

Status Code: 204
Response:

In [226]:
def send_live_entry_alert(live_df):
    row = live_df.iloc[0]

    message = f"""
🚀 {row['symbol']} Live Entry Alert

Price: {row['price']}

Decision: {row['decision']}
Entry Timing: {row['entry_timing']}
Action: {row['action']}
Position Size: {row['position_size']}

Stop Loss: {row['stop_loss']}
Trailing Stop: {row['trailing_stop']}
Target: {row['target']}
R Profile: {row['r_multiple']}
"""

    send_to_discord(message)

In [210]:
live_result = run_live_entry_check(live_entry)

live_result[[
    "symbol",
    "decision",
    "entry_timing",
    "action",
    "position_size",
    "stop_loss",
    "target"
]]

,symbol,decision,entry_timing,action,position_size,stop_loss,target
0,QQQ,B_SETUP,ENTRY_TRIGGER,NORMAL_ENTRY,70% size,610.9,613.9

In [223]:
def run_live_entry_check(entry_row):
    import pandas as pd

    # Create dataframe
    live_df = pd.DataFrame([entry_row])

    # -------------------------
    # SAFE DEFAULTS
    # -------------------------
    if "patterns" not in live_df.columns:
        live_df["patterns"] = [[] for _ in range(len(live_df))]

    if "regime" not in live_df.columns:
        live_df["regime"] = "mixed_regime"

    if "confidence" not in live_df.columns:
        live_df["confidence"] = "MEDIUM_CONFIDENCE"

    if "confidence_score" not in live_df.columns:
        live_df["confidence_score"] = 1

    # -------------------------
    # CORE LOGIC
    # -------------------------
    live_df["entry_timing"] = live_df.apply(entry_timing_signal, axis=1)
    live_df["action"] = live_df.apply(trade_action, axis=1)
    live_df["position_size"] = live_df.apply(position_size, axis=1)

    # -------------------------
    # ENTRY PRICE (IMPORTANT)
    # -------------------------
    live_df["entry_price"] = live_df["price"]

    # -------------------------
    # STOP / TARGET / R
    # -------------------------
    live_df["stop_loss"], live_df["target"], live_df["r_multiple"] = zip(
        *live_df.apply(trade_levels, axis=1)
    )

    # -------------------------
    # TRAILING STOP (NEW)
    # -------------------------
    live_df["trailing_stop"] = live_df.apply(trailing_stop_logic, axis=1)

    return live_df

In [213]:
def trade_levels(row):
    price = row["price"]
    action = row["action"]

    risk_per_share = 1.0  # your base risk (can make dynamic later)

    stop = None
    target = None
    r_multiple = None

    if action in ["FULL_SIZE_ENTRY", "NORMAL_ENTRY", "SMALL_SIZE_ENTRY"]:
        stop = round(price - risk_per_share, 2)
        target = round(price + (2 * risk_per_share), 2)
        r_multiple = "2R target"

    elif action == "TAKE_PROFIT":
        stop = "Trailing active"
        target = "Scaling out"
        r_multiple = "Lock gains"

    elif action == "EXIT_OR_AVOID":
        stop = "No trade"
        target = "No trade"
        r_multiple = "0R"

    else:
        stop = "Wait"
        target = "Wait"
        r_multiple = "N/A"

    return stop, target, r_multiple

In [207]:
live_result = run_live_entry_check(live_entry)

live_result[["symbol", "decision", "entry_timing", "action", "position_size", "stop_loss", "target"]]

,symbol,decision,entry_timing,action,position_size,stop_loss,target
0,QQQ,B_SETUP,ENTRY_TRIGGER,NORMAL_ENTRY,70% size,610.9,613.9

In [205]:
send_live_entry_alert(live_result)

Status Code: 204
Response:

In [204]:
live_result["stop_loss"], live_result["target"] = zip(*live_result.apply(trade_levels, axis=1))

live_result[["symbol", "action", "position_size", "stop_loss", "target"]]

  symbol        action position_size  stop_loss  target
0    QQQ  NORMAL_ENTRY      70% size      610.9   613.9

In [203]:
def trade_levels(row):
    price = row["price"]
    action = row["action"]

    stop = None
    target = None

    if action in ["FULL_SIZE_ENTRY", "NORMAL_ENTRY", "SMALL_SIZE_ENTRY"]:
        stop = round(price - 1.0, 2)
        target = round(price + 2.0, 2)

    elif action == "TAKE_PROFIT":
        stop = "Trail stop"
        target = "Scale out"

    elif action == "EXIT_OR_AVOID":
        stop = "No trade"
        target = "No trade"

    else:
        stop = "Wait"
        target = "Wait"

    return stop, target

In [202]:
send_live_entry_alert(live_result)

KeyError: 'stop_loss'

In [199]:
Stop Loss: {row['stop_loss']}
Target: {row['target']}

SyntaxError: invalid syntax (1114100709.py, line 1)

In [198]:
df["stop_loss"], df["target"] = zip(*df.apply(trade_levels, axis=1))

In [197]:
def trade_levels(row):
    price = row["price"]
    action = row["action"]
    zone = get_zone_state(price)

    # Default
    stop = None
    target = None

    if action in ["FULL_SIZE_ENTRY", "NORMAL_ENTRY", "SMALL_SIZE_ENTRY"]:
        # Entry logic
        stop = round(price - 1.0, 2)   # adjustable
        target = round(price + 2.0, 2)

    elif action == "TAKE_PROFIT":
        stop = "Trail stop"
        target = "Scale out"

    elif action == "EXIT_OR_AVOID":
        stop = "No trade"
        target = "No trade"

    return stop, target

In [196]:
send_live_entry_alert(live_result)

Status Code: 204
Response:

In [216]:
def send_live_entry_alert(live_df):
    row = live_df.iloc[0]

    message = f"""
🚀 {row['symbol']} Live Entry Alert

Price: {row['price']}

Decision: {row['decision']}
Entry Timing: {row['entry_timing']}
Action: {row['action']}
Position Size: {row['position_size']}

Stop Loss: {row['stop_loss']}
Target: {row['target']}
R Profile: {row['r_multiple']}
"""

    send_to_discord(message)

In [194]:
live_result = run_live_entry_check(live_entry)

live_result[["symbol", "decision", "entry_timing", "action", "position_size"]]

  symbol decision   entry_timing        action position_size
0    QQQ  B_SETUP  ENTRY_TRIGGER  NORMAL_ENTRY      70% size

In [193]:
live_entry = {
    "symbol": "QQQ",
    "score": 8,
    "final_score": 8,
    "decision": "B_SETUP",
    "price": 611.90,
    "reaction": "reclaim",
    "positionVsVwap": "above",
    "testCount": "first",
    "patterns": [],
    "regime": "trend_regime",
    "confidence": "MEDIUM_CONFIDENCE",
    "confidence_score": 2,
    "level": "support",
    "session": "open"
}

In [214]:
def run_live_entry_check(entry_row):
    import pandas as pd

    live_df = pd.DataFrame([entry_row])

    # Safe defaults
    if "patterns" not in live_df.columns:
        live_df["patterns"] = [[] for _ in range(len(live_df))]
    if "regime" not in live_df.columns:
        live_df["regime"] = "mixed_regime"
    if "confidence" not in live_df.columns:
        live_df["confidence"] = "MEDIUM_CONFIDENCE"
    if "confidence_score" not in live_df.columns:
        live_df["confidence_score"] = 1

    live_df["entry_timing"] = live_df.apply(entry_timing_signal, axis=1)
    live_df["action"] = live_df.apply(trade_action, axis=1)
    live_df["position_size"] = live_df.apply(position_size, axis=1)
    live_df["stop_loss"], live_df["target"], live_df["r_multiple"] = zip(*live_df.apply(trade_levels, axis=1))

    return live_df

In [191]:
entry_df["action"] = entry_df.apply(trade_action, axis=1)
entry_df["position_size"] = entry_df.apply(position_size, axis=1)

entry_df[["symbol", "decision", "entry_timing", "action", "position_size"]]

  symbol decision   entry_timing        action position_size
0    QQQ  B_SETUP  ENTRY_TRIGGER  NORMAL_ENTRY      70% size

In [190]:
entry_df["entry_timing"] = entry_df.apply(entry_timing_signal, axis=1)
entry_df[["symbol", "reaction", "positionVsVwap", "testCount", "patterns", "entry_timing"]]

  symbol reaction positionVsVwap testCount patterns   entry_timing
0    QQQ  reclaim          above     first       []  ENTRY_TRIGGER

In [189]:
import pandas as pd

entry_df = pd.DataFrame([entry_test])
entry_df

,symbol,score,price,reaction,positionVsVwap,testCount,patterns,regime,final_score,decision,confidence,level,session,confidence_score
0,QQQ,8,611.9,reclaim,above,first,[],trend_regime,8,B_SETUP,MEDIUM_CONFIDENCE,support,open,2

In [188]:
entry_test = {
    "symbol": "QQQ",
    "score": 8,
    "price": 611.90,
    "reaction": "reclaim",
    "positionVsVwap": "above",
    "testCount": "first",
    "patterns": [],
    "regime": "trend_regime",
    "final_score": 8,
    "decision": "B_SETUP",
    "confidence": "MEDIUM_CONFIDENCE",
    "level": "support",
    "session": "open",
    "confidence_score": 2,
}

In [187]:
update_price_and_run(611.90)

--- LIVE UPDATE ---
Price: 611.9
Decision: WATCH_OR_SMALL_SIZE
Action: REDUCE_OR_TIGHTEN_STOP
Confidence: LOW_CONFIDENCE
Position Size: 10% or no trade
Zone: BELOW_SELL_ZONE
Entry Timing: NO_TRIGGER
No change -> no alert

In [186]:
df["reaction"] = "reclaim"
df["positionVsVwap"] = "above"
df["testCount"] = "first"
df["patterns"] = [[] for _ in range(len(df))]

In [185]:
test_row = df.iloc[0].copy()

test_row["reaction"] = "reclaim"
test_row["positionVsVwap"] = "above"
test_row["testCount"] = "first"
test_row["patterns"] = []   # remove late/extended blockers

print("Test row timing:", entry_timing_signal(test_row))

Test row timing: ENTRY_TRIGGER

In [184]:
print(entry_timing_signal(df.iloc[0]))

NO_TRIGGER

In [183]:
print("patterns:", df.iloc[0]["patterns"])
print("reaction:", df.iloc[0]["reaction"])
print("positionVsVwap:", df.iloc[0]["positionVsVwap"])
print("testCount:", df.iloc[0]["testCount"])

patterns: ['late_entry_risk', 'oil_bullish_impulse', 'momentum_extended']
reaction: reclaim
positionVsVwap: above
testCount: first

In [182]:
df["reaction"] = "reclaim"
df["positionVsVwap"] = "above"
df["testCount"] = "first"

update_price_and_run(611.90)

--- LIVE UPDATE ---
Price: 611.9
Decision: WATCH_OR_SMALL_SIZE
Action: REDUCE_OR_TIGHTEN_STOP
Confidence: LOW_CONFIDENCE
Position Size: 10% or no trade
Zone: BELOW_SELL_ZONE
Entry Timing: NO_TRIGGER
Not actionable -> no alert

In [180]:
df["entry_timing"] = df.apply(entry_timing_signal, axis=1)

df[["symbol", "reaction", "positionVsVwap", "testCount", "entry_timing"]]

  symbol    reaction positionVsVwap testCount entry_timing
0    QQQ  break_hold          above     first   NO_TRIGGER

In [179]:
def entry_timing_signal(row):
    reaction = row.get("reaction", "")
    level = row.get("level", "")
    position_vs_vwap = row.get("positionVsVwap", "")
    test_count = row.get("testCount", "")
    patterns = row.get("patterns", [])

    # Hard blocks
    if "late_entry_risk" in patterns:
        return "NO_TRIGGER"
    if "momentum_extended" in patterns:
        return "NO_TRIGGER"
    if "resistance_trap_risk" in patterns:
        return "NO_TRIGGER"

    # Bullish timing logic
    if reaction in ["reclaim", "break_hold"] and position_vs_vwap == "above" and test_count == "first":
        return "ENTRY_TRIGGER"

    return "WAIT_FOR_CONFIRMATION"

In [178]:
if "positionVsVwap" not in df.columns:
    df["positionVsVwap"] = "above"

if "testCount" not in df.columns:
    df["testCount"] = "first"

In [177]:
print(df.columns.tolist())

['symbol', 'asset_type', 'score', 'grade', 'win_probability', 'summary', 'direction', 'setup_name', 'level', 'reaction', 'position_vs_vwap', 'htf_bias', 'mtf_structure', 'session_phase', 'test_number', 'quality', 'rsi_state', 'macd_state', 'bollinger_context', 'market_sentiment', 'environment', 'oil_trend', 'oil_volatility', 'oil_shock', 'oil_shock_direction', 'oil_shock_strength', 'oil_pct_change', 'oil_velocity_per_min', 'macro_context', 'macro_note', 'mistake_tag', 'trade_management_mistake', 'management_notes', 'confluence_count', 'confluence_factors', 'ai_label', 'patterns', 'pattern_score', 'final_score', 'decision', 'action', 'explanation', 'price', 'reasons', 'avg_win', 'avg_loss', 'ev', 'volatility', 'session', 'regime', 'regime_adjustment', 'confidence_score', 'confidence', 'position_size', 'entry_timing']

In [176]:
df["entry_timing"] = df.apply(entry_timing_signal, axis=1)

df[["symbol", "reaction", "positionVsVwap", "testCount", "entry_timing"]]

KeyError: "['positionVsVwap', 'testCount'] not in index"

In [175]:
def entry_timing_signal(row):
    reaction = row.get("reaction", "")
    level = row.get("level", "")
    position_vs_vwap = row.get("positionVsVwap", "")
    test_count = row.get("testCount", "")
    patterns = row.get("patterns", [])

    # Hard blocks
    if "late_entry_risk" in patterns:
        return "NO_TRIGGER"
    if "momentum_extended" in patterns:
        return "NO_TRIGGER"
    if "resistance_trap_risk" in patterns:
        return "NO_TRIGGER"

    # Bullish timing logic
    if reaction in ["reclaim", "break_hold"] and position_vs_vwap == "above" and test_count == "first":
        return "ENTRY_TRIGGER"

    # Otherwise
    return "WAIT_FOR_CONFIRMATION"

In [174]:
update_price_and_run(613.0)

--- LIVE UPDATE ---
Price: 613.0
Decision: SKIP_OR_EXIT_FAST
Action: EXIT_OR_AVOID
Confidence: LOW_CONFIDENCE
Position Size: 10% or no trade
Zone: ABOVE_SELL_ZONE
No change -> no alert

In [172]:
send_trade_alert(df.iloc[0])

In [171]:
df["final_score"] = 10
df["decision"] = "A_SETUP"
df["action"] = "FULL_SIZE_ENTRY"
df["confidence"] = "HIGH_CONFIDENCE"

df["position_size"] = df.apply(position_size, axis=1)

df[["symbol", "action", "confidence", "position_size"]]

  symbol           action       confidence position_size
0    QQQ  FULL_SIZE_ENTRY  HIGH_CONFIDENCE     100% size

In [170]:
update_price_and_run(611.50)   # below zone
update_price_and_run(612.00)   # near zone
update_price_and_run(612.45)   # inside sell zone
update_price_and_run(613.00)   # above zone

--- LIVE UPDATE ---
Price: 611.5
Decision: SKIP_OR_EXIT_FAST
Action: EXIT_OR_AVOID
Confidence: LOW_CONFIDENCE
Position Size: 10% or no trade
Zone: BELOW_SELL_ZONE
Not actionable -> no alert

--- LIVE UPDATE ---
Price: 612.0
Decision: SKIP_OR_EXIT_FAST
Action: EXIT_OR_AVOID
Confidence: LOW_CONFIDENCE
Position Size: 10% or no trade
Zone: BELOW_SELL_ZONE
No change -> no alert

--- LIVE UPDATE ---
Price: 612.45
Decision: SKIP_OR_EXIT_FAST
Action: TAKE_PROFIT
Confidence: LOW_CONFIDENCE
Position Size: 10% or no trade
Zone: SELL_ZONE
Sending Discord alert...

--- LIVE UPDATE ---
Price: 613.0
Decision: SKIP_OR_EXIT_FAST
Action: EXIT_OR_AVOID
Confidence: LOW_CONFIDENCE
Position Size: 10% or no trade
Zone: ABOVE_SELL_ZONE
Not actionable -> no alert

In [169]:
update_price_and_run(612.45)

--- LIVE UPDATE ---
Price: 612.45
Decision: SKIP_OR_EXIT_FAST
Action: TAKE_PROFIT
Confidence: LOW_CONFIDENCE
Position Size: 10% or no trade
Zone: SELL_ZONE
Sending Discord alert...

In [165]:
def position_size(row):
    score = row.get("final_score", 0)
    confidence = row.get("confidence", "LOW_CONFIDENCE")
    action = row.get("action", "")

    # Strong entries
    if action == "FULL_SIZE_ENTRY":
        return "100% size"

    if action == "NORMAL_ENTRY":
        return "70% size"

    if action == "SMALL_SIZE_ENTRY":
        return "30% size"

    # Confidence fallback
    if confidence == "HIGH_CONFIDENCE":
        return "70% size"

    if confidence == "MEDIUM_CONFIDENCE":
        return "40% size"

    # Default (low confidence or exits)
    return "10% or no trade"

In [164]:
update_price_and_run(611.80)
update_price_and_run(612.00)
update_price_and_run(612.20)
update_price_and_run(612.45)

--- LIVE UPDATE ---
Price: 611.8
Decision: SKIP_OR_EXIT_FAST
Action: EXIT_OR_AVOID
Confidence: LOW_CONFIDENCE
Zone: BELOW_SELL_ZONE
No change -> no alert

--- LIVE UPDATE ---
Price: 612.0
Decision: SKIP_OR_EXIT_FAST
Action: EXIT_OR_AVOID
Confidence: LOW_CONFIDENCE
Zone: BELOW_SELL_ZONE
No change -> no alert

--- LIVE UPDATE ---
Price: 612.2
Decision: SKIP_OR_EXIT_FAST
Action: EXIT_OR_AVOID
Confidence: LOW_CONFIDENCE
Zone: BELOW_SELL_ZONE
No change -> no alert

--- LIVE UPDATE ---
Price: 612.45
Decision: SKIP_OR_EXIT_FAST
Action: TAKE_PROFIT
Confidence: LOW_CONFIDENCE
Zone: SELL_ZONE
Sending Discord alert...

In [163]:
ACTIONABLE = [
    "TAKE_PROFIT",
    "FULL_SIZE_ENTRY",
    "NORMAL_ENTRY",
    "SMALL_SIZE_ENTRY",
]

In [162]:
def trade_action(row):
    patterns = row.get("patterns", [])
    decision = row["decision"]

    # hard profit logic first
    if should_force_take_profit(row):
        return "TAKE_PROFIT"

    # entry logic
    entry = entry_signal(row)
    if entry is not None:
        return entry

    # negative state
    if decision == "SKIP_OR_EXIT_FAST":
        return "EXIT_OR_AVOID"

    if "late_entry_risk" in patterns and "momentum_extended" in patterns:
        return "REDUCE_OR_TIGHTEN_STOP"

    return "WAIT"

In [173]:
def entry_signal(row):
    patterns = row.get("patterns", [])
    regime = row.get("regime", "")
    final_score = row.get("final_score", 0)
    zone = get_zone_state(row["price"])

    # 🚫 HARD BLOCKS (NO ENTRY ALLOWED)
    if "late_entry_risk" in patterns:
        return None

    if "momentum_extended" in patterns:
        return None

    if "resistance_trap_risk" in patterns:
        return None

    if zone in ["SELL_ZONE", "ABOVE_SELL_ZONE"]:
        return None

    # ✅ VALID ENTRY CONDITIONS
    bullish_entry = (
        row["decision"] in ["A_SETUP", "B_SETUP", "WATCH_OR_SMALL_SIZE"]
        and regime in ["trend_regime", "mixed_regime"]
        and final_score >= 6
    )

    if bullish_entry and final_score >= 10:
        return "FULL_SIZE_ENTRY"
    elif bullish_entry and final_score >= 7:
        return "NORMAL_ENTRY"
    elif bullish_entry and final_score >= 6:
        return "SMALL_SIZE_ENTRY"

    return None

In [160]:
while True:
    real_price = get_live_price()

    if real_price is not None:
        update_price_and_run(real_price)

    time.sleep(10)

Status Code: 200

--- LIVE UPDATE ---
Price: 617.39
Decision: SKIP_OR_EXIT_FAST
Action: EXIT_OR_AVOID
Confidence: LOW_CONFIDENCE
Zone: ABOVE_SELL_ZONE
No change -> no alert

KeyboardInterrupt:

In [158]:
update_price_and_run(611.80)
update_price_and_run(612.30)
update_price_and_run(612.45)
update_price_and_run(612.60)

--- LIVE UPDATE ---
Price: 611.8
Decision: SKIP_OR_EXIT_FAST
Action: EXIT_OR_AVOID
Confidence: LOW_CONFIDENCE
Zone: BELOW_SELL_ZONE
Not actionable -> no alert

--- LIVE UPDATE ---
Price: 612.3
Decision: SKIP_OR_EXIT_FAST
Action: EXIT_OR_AVOID
Confidence: LOW_CONFIDENCE
Zone: BELOW_SELL_ZONE
No change -> no alert

--- LIVE UPDATE ---
Price: 612.45
Decision: SKIP_OR_EXIT_FAST
Action: TAKE_PROFIT
Confidence: LOW_CONFIDENCE
Zone: SELL_ZONE
Sending Discord alert...

--- LIVE UPDATE ---
Price: 612.6
Decision: SKIP_OR_EXIT_FAST
Action: EXIT_OR_AVOID
Confidence: LOW_CONFIDENCE
Zone: ABOVE_SELL_ZONE
Not actionable -> no alert

In [181]:
# === ACTIONABLE FILTER ===
ACTIONABLE = ["TAKE_PROFIT", "FULL_SIZE_ENTRY", "NORMAL_ENTRY"]


# === CLEAN TRADE ALERT FUNCTION ===
def send_trade_alert(row):
    import requests

    instruction = build_instruction(row)

    message = f"""
📊 {row['symbol']} AI Alert

Price: {row['price']}

Decision: {row['decision']}
Action: {row['action']}
Confidence: {row['confidence']}

Reason:
{chr(10).join(['• ' + r for r in row['reasons']])}

Zone:
{get_zone_state(row['price'])}

Instruction:
{instruction}
"""

    data = {"content": message}
    requests.post(DISCORD_WEBHOOK_URL, json=data)


# === UPDATED MAIN ENGINE (NO ZONE ALERTS) ===
last_action = None

def update_price_and_run(price):
    global df, last_action

    # safe defaults for missing fields
    if "positionVsVwap" not in df.columns:
        df["positionVsVwap"] = "above"
    if "testCount" not in df.columns:
        df["testCount"] = "first"

    df["price"] = price

    df["patterns"] = df.apply(detect_trade_pattern, axis=1)
    df["pattern_score"] = df["patterns"].apply(score_patterns)

    df["final_score"] = df["score"] + df["pattern_score"]

    df["regime"] = df.apply(detect_regime, axis=1)
    df["regime_adjustment"] = df.apply(regime_score_adjustment, axis=1)
    df["final_score"] = df["final_score"] + df["regime_adjustment"]

    if "decay_penalty" in df.columns:
        df["final_score"] = df["final_score"] + df["decay_penalty"]

    if "macro_score" in df.columns:
        df["final_score"] = df["final_score"] + df["macro_score"]

    df["decision"] = df["final_score"].apply(final_decision)
    df["entry_timing"] = df.apply(entry_timing_signal, axis=1)
    df["action"] = df.apply(trade_action, axis=1)
    df["confidence_score"] = df.apply(calculate_confidence, axis=1)
    df["confidence"] = df["confidence_score"].apply(confidence_label)
    df["position_size"] = df.apply(position_size, axis=1)
    df["reasons"] = df.apply(build_reason, axis=1)

    row = df.iloc[0]
    current_action = row["action"]

    print("\n--- LIVE UPDATE ---")
    print(f"Price: {price}")
    print(f"Decision: {row['decision']}")
    print(f"Action: {current_action}")
    print(f"Confidence: {row['confidence']}")
    print(f"Position Size: {row['position_size']}")
    print(f"Zone: {get_zone_state(price)}")
    print(f"Entry Timing: {row['entry_timing']}")

    if current_action != last_action:
        if current_action in ACTIONABLE:
            print("Sending Discord alert...")
            send_trade_alert(row)
        else:
            print("Not actionable -> no alert")

        last_action = current_action
    else:
        print("No change -> no alert")

In [155]:
update_price_and_run(611.80)   # below zone
update_price_and_run(612.30)   # approaching
update_price_and_run(612.45)   # inside sell zone
update_price_and_run(612.55)   # above zone

--- LIVE UPDATE ---
Price: 611.8
Decision: SKIP_OR_EXIT_FAST
Action: EXIT_OR_AVOID
Confidence: LOW_CONFIDENCE
Zone State: BELOW_SELL_ZONE
No action change -> no Discord alert
Zone changed -> sending zone alert
Status Code: 204
Response:

--- LIVE UPDATE ---
Price: 612.3
Decision: SKIP_OR_EXIT_FAST
Action: EXIT_OR_AVOID
Confidence: LOW_CONFIDENCE
Zone State: BELOW_SELL_ZONE
No action change -> no Discord alert
No zone change -> no zone alert

--- LIVE UPDATE ---
Price: 612.45
Decision: SKIP_OR_EXIT_FAST
Action: TAKE_PROFIT
Confidence: LOW_CONFIDENCE
Zone State: SELL_ZONE
Action changed -> sending Discord alert
Zone changed but cooldown active -> no zone alert

--- LIVE UPDATE ---
Price: 612.55
Decision: SKIP_OR_EXIT_FAST
Action: EXIT_OR_AVOID
Confidence: LOW_CONFIDENCE
Zone State: ABOVE_SELL_ZONE
Action changed but cooldown active -> no Discord alert
Zone changed but cooldown active -> no zone alert

In [154]:
send_trade_alert(df.iloc[0])

In [152]:
def build_instruction(row):
    zone = get_zone_state(row["price"])
    action = row["action"]

    if action == "TAKE_PROFIT":
        return "Pay yourself. Do not overstay the move."

    if action == "EXIT_OR_AVOID":
        return "Stay out. Conditions are not favorable."

    if action == "REDUCE_OR_TIGHTEN_STOP":
        return "Reduce size or tighten stops. Risk increasing."

    if zone == "BELOW_SELL_ZONE":
        return "Below sell zone. Wait for structure to form."

    if zone == "ABOVE_SELL_ZONE":
        return "Above sell zone. No immediate edge."

    return "Wait for better setup."

In [151]:
update_price_and_run(611.90)
update_price_and_run(612.45)
update_price_and_run(612.48)
update_price_and_run(612.60)

--- LIVE UPDATE ---
Price: 611.9
Decision: SKIP_OR_EXIT_FAST
Action: EXIT_OR_AVOID
Confidence: LOW_CONFIDENCE
Zone State: BELOW_SELL_ZONE
Action changed -> sending Discord alert
Status Code: 204
Response:
Zone changed -> sending zone alert
Status Code: 204
Response:

--- LIVE UPDATE ---
Price: 612.45
Decision: SKIP_OR_EXIT_FAST
Action: TAKE_PROFIT
Confidence: LOW_CONFIDENCE
Zone State: SELL_ZONE
Action changed but cooldown active -> no Discord alert
Zone changed but cooldown active -> no zone alert

--- LIVE UPDATE ---
Price: 612.48
Decision: SKIP_OR_EXIT_FAST
Action: TAKE_PROFIT
Confidence: LOW_CONFIDENCE
Zone State: SELL_ZONE
No action change -> no Discord alert
No zone change -> no zone alert

--- LIVE UPDATE ---
Price: 612.6
Decision: SKIP_OR_EXIT_FAST
Action: EXIT_OR_AVOID
Confidence: LOW_CONFIDENCE
Zone State: ABOVE_SELL_ZONE
Action changed but cooldown active -> no Discord alert
Zone changed but cooldown active -> no zone alert

In [149]:
import time

last_action = None
last_price = None
last_zone_state = None

last_action_alert_time = 0
last_zone_alert_time = 0

ACTION_ALERT_COOLDOWN = 60   # seconds
ZONE_ALERT_COOLDOWN = 60     # seconds

In [148]:
import time

while True:
    real_price = get_live_price()

    if real_price is not None:
        update_price_and_run(real_price)
    else:
        print("Skipping cycle because price fetch failed.")

    time.sleep(10)

Status Code: 200

--- LIVE UPDATE ---
Price: 617.39
Decision: SKIP_OR_EXIT_FAST
Action: EXIT_OR_AVOID
Confidence: LOW_CONFIDENCE
Zone State: ABOVE_SELL_ZONE
No action change -> no Discord alert
No zone change -> no zone alert
Status Code: 200

--- LIVE UPDATE ---
Price: 617.39
Decision: SKIP_OR_EXIT_FAST
Action: EXIT_OR_AVOID
Confidence: LOW_CONFIDENCE
Zone State: ABOVE_SELL_ZONE
No action change -> no Discord alert
No zone change -> no zone alert
Status Code: 200

--- LIVE UPDATE ---
Price: 617.39
Decision: SKIP_OR_EXIT_FAST
Action: EXIT_OR_AVOID
Confidence: LOW_CONFIDENCE
Zone State: ABOVE_SELL_ZONE
No action change -> no Discord alert
No zone change -> no zone alert
Status Code: 200

--- LIVE UPDATE ---
Price: 617.39
Decision: SKIP_OR_EXIT_FAST
Action: EXIT_OR_AVOID
Confidence: LOW_CONFIDENCE
Zone State: ABOVE_SELL_ZONE
No action change -> no Discord alert
No zone change -> no zone alert
Status Code: 200

--- LIVE UPDATE ---
Price: 617.39
Decision: SKIP_OR_EXIT_FAST
Action: EXIT_OR_AVOID
Confidence: LOW_CONFIDENCE
Zone State: ABOVE_SELL_ZONE
No action change -> no Discord alert
No zone change -> no zone alert
Status Code: 200

--- LIVE UPDATE ---
Price: 617.39
Decision: SKIP_OR_EXIT_FAST
Action: EXIT_OR_AVOID
Confidence: LOW_CONFIDENCE
Zone State: ABOVE_SELL_ZONE
No action change -> no Discord alert
No zone change -> no zone alert
Status Code: 200

--- LIVE UPDATE ---
Price: 617.39
Decision: SKIP_OR_EXIT_FAST
Action: EXIT_OR_AVOID
Confidence: LOW_CONFIDENCE
Zone State: ABOVE_SELL_ZONE
No action change -> no Discord alert
No zone change -> no zone alert
Status Code: 200

--- LIVE UPDATE ---
Price: 617.39
Decision: SKIP_OR_EXIT_FAST
Action: EXIT_OR_AVOID
Confidence: LOW_CONFIDENCE
Zone State: ABOVE_SELL_ZONE
No action change -> no Discord alert
No zone change -> no zone alert

KeyboardInterrupt:

In [147]:
update_price_and_run(611.90)
update_price_and_run(612.45)
update_price_and_run(612.48)
update_price_and_run(612.60)

--- LIVE UPDATE ---
Price: 611.9
Decision: SKIP_OR_EXIT_FAST
Action: EXIT_OR_AVOID
Confidence: LOW_CONFIDENCE
Zone State: BELOW_SELL_ZONE
Action changed -> sending Discord alert
Status Code: 204
Response:
Zone changed -> sending zone alert
Status Code: 204
Response:

--- LIVE UPDATE ---
Price: 612.45
Decision: SKIP_OR_EXIT_FAST
Action: TAKE_PROFIT
Confidence: LOW_CONFIDENCE
Zone State: SELL_ZONE
Action changed -> sending Discord alert
Status Code: 204
Response:
Zone changed -> sending zone alert
Status Code: 204
Response:

--- LIVE UPDATE ---
Price: 612.48
Decision: SKIP_OR_EXIT_FAST
Action: TAKE_PROFIT
Confidence: LOW_CONFIDENCE
Zone State: SELL_ZONE
No action change -> no Discord alert
No zone change -> no zone alert

--- LIVE UPDATE ---
Price: 612.6
Decision: SKIP_OR_EXIT_FAST
Action: EXIT_OR_AVOID
Confidence: LOW_CONFIDENCE
Zone State: ABOVE_SELL_ZONE
Action changed -> sending Discord alert
Status Code: 204
Response:
Zone changed -> sending zone alert
Status Code: 204
Response:

In [150]:
def update_price_and_run(price):
    global df, last_action, last_price, last_zone_state
    global last_action_alert_time, last_zone_alert_time

    df["price"] = price
    df["patterns"] = df.apply(detect_trade_pattern, axis=1)
    df["pattern_score"] = df["patterns"].apply(score_patterns)

    df["final_score"] = df["score"] + df["pattern_score"]

    df["regime"] = df.apply(detect_regime, axis=1)
    df["regime_adjustment"] = df.apply(regime_score_adjustment, axis=1)
    df["final_score"] = df["final_score"] + df["regime_adjustment"]

    if "decay_penalty" in df.columns:
        df["final_score"] = df["final_score"] + df["decay_penalty"]

    if "macro_score" in df.columns:
        df["final_score"] = df["final_score"] + df["macro_score"]

    df["decision"] = df["final_score"].apply(final_decision)
    df["action"] = df.apply(trade_action, axis=1)
    df["confidence_score"] = df.apply(calculate_confidence, axis=1)
    df["confidence"] = df["confidence_score"].apply(confidence_label)
    df["reasons"] = df.apply(build_reason, axis=1)

    row = df.iloc[0]
    current_action = row["action"]
    current_zone_state = get_zone_state(price)
    now = time.time()

    print("\n--- LIVE UPDATE ---")
    print(f"Price: {price}")
    print(f"Decision: {row['decision']}")
    print(f"Action: {current_action}")
    print(f"Confidence: {row['confidence']}")
    print(f"Zone State: {current_zone_state}")

    # Action-change alert with cooldown
    if current_action != last_action:
        if now - last_action_alert_time >= ACTION_ALERT_COOLDOWN:
            print("Action changed -> sending Discord alert")
            last_action = current_action
            last_action_alert_time = now
            send_trade_alert(row)
        else:
            print("Action changed but cooldown active -> no Discord alert")
            last_action = current_action
    else:
        print("No action change -> no Discord alert")

    # Zone-change alert with cooldown
    if current_zone_state != last_zone_state:
        if now - last_zone_alert_time >= ZONE_ALERT_COOLDOWN:
            print("Zone changed -> sending zone alert")
            last_zone_state = current_zone_state
            last_zone_alert_time = now
            send_zone_alert(row["symbol"], price, current_zone_state)
        else:
            print("Zone changed but cooldown active -> no zone alert")
            last_zone_state = current_zone_state
    else:
        print("No zone change -> no zone alert")

    last_price = price

In [156]:
def send_zone_alert(row["symbol"], price, current_zone_state):
    if zone_state == "SELL_ZONE":
        message = f"""⚠️ {symbol} ENTERED SELL ZONE

Price: {price}
Zone: 612.40–612.50

Instruction:
Take profit / reduce risk. Price has entered your key resistance zone.
"""
    elif zone_state == "BELOW_SELL_ZONE":
        message = f"""ℹ️ {symbol} BELOW SELL ZONE

Price: {price}

Instruction:
Not in the sell zone right now.
"""
    else:
        message = f"""ℹ️ {symbol} ABOVE SELL ZONE

Price: {price}

Instruction:
Price moved above the defined sell zone.
"""
    send_to_discord(message)

SyntaxError: invalid syntax (932492037.py, line 1)

In [144]:
def get_zone_state(price):
    if 612.40 <= price <= 612.50:
        return "SELL_ZONE"
    elif price < 612.40:
        return "BELOW_SELL_ZONE"
    else:
        return "ABOVE_SELL_ZONE"

In [143]:
last_action = None
last_price = None
last_zone_state = None

In [142]:
import time

while True:
    real_price = get_live_price()

    if real_price is not None:
        update_price_and_run(real_price)
    else:
        print("Skipping cycle because price fetch failed.")

    time.sleep(10)

Status Code: 200

--- LIVE UPDATE ---
Price: 617.39
Decision: SKIP_OR_EXIT_FAST
Action: EXIT_OR_AVOID
Confidence: LOW_CONFIDENCE
No action change -> no Discord alert
Status Code: 200

--- LIVE UPDATE ---
Price: 617.39
Decision: SKIP_OR_EXIT_FAST
Action: EXIT_OR_AVOID
Confidence: LOW_CONFIDENCE
No action change -> no Discord alert
Status Code: 200

--- LIVE UPDATE ---
Price: 617.39
Decision: SKIP_OR_EXIT_FAST
Action: EXIT_OR_AVOID
Confidence: LOW_CONFIDENCE
No action change -> no Discord alert
Status Code: 200

--- LIVE UPDATE ---
Price: 617.39
Decision: SKIP_OR_EXIT_FAST
Action: EXIT_OR_AVOID
Confidence: LOW_CONFIDENCE
No action change -> no Discord alert
Status Code: 200

--- LIVE UPDATE ---
Price: 617.39
Decision: SKIP_OR_EXIT_FAST
Action: EXIT_OR_AVOID
Confidence: LOW_CONFIDENCE
No action change -> no Discord alert
Status Code: 200

--- LIVE UPDATE ---
Price: 617.39
Decision: SKIP_OR_EXIT_FAST
Action: EXIT_OR_AVOID
Confidence: LOW_CONFIDENCE
No action change -> no Discord alert
Status Code: 200

--- LIVE UPDATE ---
Price: 617.39
Decision: SKIP_OR_EXIT_FAST
Action: EXIT_OR_AVOID
Confidence: LOW_CONFIDENCE
No action change -> no Discord alert
Status Code: 200

--- LIVE UPDATE ---
Price: 617.39
Decision: SKIP_OR_EXIT_FAST
Action: EXIT_OR_AVOID
Confidence: LOW_CONFIDENCE
No action change -> no Discord alert
Status Code: 200

--- LIVE UPDATE ---
Price: 617.39
Decision: SKIP_OR_EXIT_FAST
Action: EXIT_OR_AVOID
Confidence: LOW_CONFIDENCE
No action change -> no Discord alert
Status Code: 200

--- LIVE UPDATE ---
Price: 617.39
Decision: SKIP_OR_EXIT_FAST
Action: EXIT_OR_AVOID
Confidence: LOW_CONFIDENCE
No action change -> no Discord alert
Status Code: 200

--- LIVE UPDATE ---
Price: 617.39
Decision: SKIP_OR_EXIT_FAST
Action: EXIT_OR_AVOID
Confidence: LOW_CONFIDENCE
No action change -> no Discord alert
Status Code: 200

--- LIVE UPDATE ---
Price: 617.39
Decision: SKIP_OR_EXIT_FAST
Action: EXIT_OR_AVOID
Confidence: LOW_CONFIDENCE
No action change -> no Discord alert
Status Code: 200

--- LIVE UPDATE ---
Price: 617.39
Decision: SKIP_OR_EXIT_FAST
Action: EXIT_OR_AVOID
Confidence: LOW_CONFIDENCE
No action change -> no Discord alert
Status Code: 200

--- LIVE UPDATE ---
Price: 617.39
Decision: SKIP_OR_EXIT_FAST
Action: EXIT_OR_AVOID
Confidence: LOW_CONFIDENCE
No action change -> no Discord alert
Status Code: 200

--- LIVE UPDATE ---
Price: 617.39
Decision: SKIP_OR_EXIT_FAST
Action: EXIT_OR_AVOID
Confidence: LOW_CONFIDENCE
No action change -> no Discord alert
Status Code: 200

--- LIVE UPDATE ---
Price: 617.39
Decision: SKIP_OR_EXIT_FAST
Action: EXIT_OR_AVOID
Confidence: LOW_CONFIDENCE
No action change -> no Discord alert
Status Code: 200

--- LIVE UPDATE ---
Price: 617.39
Decision: SKIP_OR_EXIT_FAST
Action: EXIT_OR_AVOID
Confidence: LOW_CONFIDENCE
No action change -> no Discord alert
Status Code: 200

--- LIVE UPDATE ---
Price: 617.39
Decision: SKIP_OR_EXIT_FAST
Action: EXIT_OR_AVOID
Confidence: LOW_CONFIDENCE
No action change -> no Discord alert
Status Code: 200

--- LIVE UPDATE ---
Price: 617.39
Decision: SKIP_OR_EXIT_FAST
Action: EXIT_OR_AVOID
Confidence: LOW_CONFIDENCE
No action change -> no Discord alert

KeyboardInterrupt:

In [141]:
real_price = get_live_price()
update_price_and_run(real_price)

Status Code: 200

--- LIVE UPDATE ---
Price: 617.39
Decision: SKIP_OR_EXIT_FAST
Action: EXIT_OR_AVOID
Confidence: LOW_CONFIDENCE
Action changed -> sending Discord alert
Status Code: 204
Response:

In [168]:
def send_trade_alert(row):
    import requests

    instruction = build_instruction(row)

    message = f"""
📊 {row['symbol']} AI Alert

Price: {row['price']}

Decision: {row['decision']}
Action: {row['action']}
Confidence: {row['confidence']}
Position Size: {row['position_size']}

Reason:
{chr(10).join(['• ' + r for r in row['reasons']])}

Zone:
{get_zone_state(row['price'])}

Instruction:
{instruction}
"""

    data = {
        "content": message
    }

    requests.post(DISCORD_WEBHOOK_URL, json=data)

In [139]:
last_action = None
last_price = None

def update_price_and_run(price):
    global df, last_action, last_price

    df["price"] = price
    df["patterns"] = df.apply(detect_trade_pattern, axis=1)
    df["pattern_score"] = df["patterns"].apply(score_patterns)

    # rebuild from base score
    df["final_score"] = df["score"] + df["pattern_score"]

    df["regime"] = df.apply(detect_regime, axis=1)
    df["regime_adjustment"] = df.apply(regime_score_adjustment, axis=1)
    df["final_score"] = df["final_score"] + df["regime_adjustment"]

    if "decay_penalty" in df.columns:
        df["final_score"] = df["final_score"] + df["decay_penalty"]

    if "macro_score" in df.columns:
        df["final_score"] = df["final_score"] + df["macro_score"]

    df["decision"] = df["final_score"].apply(final_decision)
    df["action"] = df.apply(trade_action, axis=1)
    df["confidence_score"] = df.apply(calculate_confidence, axis=1)
    df["confidence"] = df["confidence_score"].apply(confidence_label)
    df["reasons"] = df.apply(build_reason, axis=1)

    row = df.iloc[0]
    current_action = row["action"]

    print("\n--- LIVE UPDATE ---")
    print(f"Price: {price}")
    print(f"Decision: {row['decision']}")
    print(f"Action: {current_action}")
    print(f"Confidence: {row['confidence']}")

    if current_action != last_action:
        print("Action changed -> sending Discord alert")
        last_action = current_action
        send_trade_alert(row)
    else:
        print("No action change -> no Discord alert")

    last_price = price

In [138]:
import time

while True:
    real_price = get_live_price()

    if real_price is not None:
        update_price_and_run(real_price)
    else:
        print("Skipping cycle because price fetch failed.")

    time.sleep(10)

Status Code: 200

--- LIVE UPDATE ---
Price: 617.51
Decision: SKIP_OR_EXIT_FAST
Action: EXIT_OR_AVOID
Confidence: LOW_CONFIDENCE
No action change -> no Discord alert
Status Code: 200

--- LIVE UPDATE ---
Price: 617.51
Decision: SKIP_OR_EXIT_FAST
Action: EXIT_OR_AVOID
Confidence: LOW_CONFIDENCE
No action change -> no Discord alert
Status Code: 200

--- LIVE UPDATE ---
Price: 617.51
Decision: SKIP_OR_EXIT_FAST
Action: EXIT_OR_AVOID
Confidence: LOW_CONFIDENCE
No action change -> no Discord alert
Status Code: 200

--- LIVE UPDATE ---
Price: 617.51
Decision: SKIP_OR_EXIT_FAST
Action: EXIT_OR_AVOID
Confidence: LOW_CONFIDENCE
No action change -> no Discord alert
Status Code: 200

--- LIVE UPDATE ---
Price: 617.51
Decision: SKIP_OR_EXIT_FAST
Action: EXIT_OR_AVOID
Confidence: LOW_CONFIDENCE
No action change -> no Discord alert
Status Code: 200

--- LIVE UPDATE ---
Price: 617.51
Decision: SKIP_OR_EXIT_FAST
Action: EXIT_OR_AVOID
Confidence: LOW_CONFIDENCE
No action change -> no Discord alert
Status Code: 200

--- LIVE UPDATE ---
Price: 617.51
Decision: SKIP_OR_EXIT_FAST
Action: EXIT_OR_AVOID
Confidence: LOW_CONFIDENCE
No action change -> no Discord alert
Status Code: 200

--- LIVE UPDATE ---
Price: 617.51
Decision: SKIP_OR_EXIT_FAST
Action: EXIT_OR_AVOID
Confidence: LOW_CONFIDENCE
No action change -> no Discord alert
Status Code: 200

--- LIVE UPDATE ---
Price: 617.39
Decision: SKIP_OR_EXIT_FAST
Action: EXIT_OR_AVOID
Confidence: LOW_CONFIDENCE
No action change -> no Discord alert
Status Code: 200

--- LIVE UPDATE ---
Price: 617.39
Decision: SKIP_OR_EXIT_FAST
Action: EXIT_OR_AVOID
Confidence: LOW_CONFIDENCE
No action change -> no Discord alert
Status Code: 200

--- LIVE UPDATE ---
Price: 617.39
Decision: SKIP_OR_EXIT_FAST
Action: EXIT_OR_AVOID
Confidence: LOW_CONFIDENCE
No action change -> no Discord alert
Status Code: 200

--- LIVE UPDATE ---
Price: 617.39
Decision: SKIP_OR_EXIT_FAST
Action: EXIT_OR_AVOID
Confidence: LOW_CONFIDENCE
No action change -> no Discord alert
Status Code: 200

--- LIVE UPDATE ---
Price: 617.39
Decision: SKIP_OR_EXIT_FAST
Action: EXIT_OR_AVOID
Confidence: LOW_CONFIDENCE
No action change -> no Discord alert
Status Code: 200

--- LIVE UPDATE ---
Price: 617.39
Decision: SKIP_OR_EXIT_FAST
Action: EXIT_OR_AVOID
Confidence: LOW_CONFIDENCE
No action change -> no Discord alert
Status Code: 200

--- LIVE UPDATE ---
Price: 617.39
Decision: SKIP_OR_EXIT_FAST
Action: EXIT_OR_AVOID
Confidence: LOW_CONFIDENCE
No action change -> no Discord alert

KeyboardInterrupt:

In [137]:
real_price = get_live_price()
update_price_and_run(real_price)

Status Code: 200

--- LIVE UPDATE ---
Price: 617.51
Decision: SKIP_OR_EXIT_FAST
Action: EXIT_OR_AVOID
Confidence: LOW_CONFIDENCE
No action change -> no Discord alert

In [136]:
real_price = get_live_price()
update_price_and_run(real_price)

Status Code: 200

--- LIVE UPDATE ---
Price: 617.51
Decision: SKIP_OR_EXIT_FAST
Action: EXIT_OR_AVOID
Confidence: LOW_CONFIDENCE
No action change -> no Discord alert

In [134]:
def send_trade_alert(row):
    reasons = build_reason(row)
    reason_text = "\n".join([f"- {r}" for r in reasons])

    message = f"""📊 {row['symbol']} AI Alert

Price: {row.get('price', 'N/A')}
Decision: {row['decision']}
Action: {row['action']}
Confidence: {row.get('confidence', 'N/A')}

Reason:
{reason_text}
"""
    send_to_discord(message)

In [133]:
last_action = None
last_price = None

def update_price_and_run(price):
    global df, last_action, last_price

    df["price"] = price
    df["patterns"] = df.apply(detect_trade_pattern, axis=1)
    df["pattern_score"] = df["patterns"].apply(score_patterns)

    # rebuild score from base
    df["final_score"] = df["score"] + df["pattern_score"]

    df["regime"] = df.apply(detect_regime, axis=1)
    df["regime_adjustment"] = df.apply(regime_score_adjustment, axis=1)
    df["final_score"] = df["final_score"] + df["regime_adjustment"]

    if "decay_penalty" in df.columns:
        df["final_score"] = df["final_score"] + df["decay_penalty"]

    if "macro_score" in df.columns:
        df["final_score"] = df["final_score"] + df["macro_score"]

    df["decision"] = df["final_score"].apply(final_decision)
    df["action"] = df.apply(trade_action, axis=1)
    df["confidence_score"] = df.apply(calculate_confidence, axis=1)
    df["confidence"] = df["confidence_score"].apply(confidence_label)
    df["reasons"] = df.apply(build_reason, axis=1)

    row = df.iloc[0]
    current_action = row["action"]

    print("\n--- LIVE UPDATE ---")
    print(f"Price: {price}")
    print(f"Decision: {row['decision']}")
    print(f"Action: {current_action}")
    print(f"Confidence: {row['confidence']}")

    # only send if action changed
    if current_action != last_action:
        print("Action changed -> sending Discord alert")
        last_action = current_action
        send_trade_alert(row)
    else:
        print("No action change -> no Discord alert")

    last_price = price

In [131]:
import time

while True:
    real_price = get_live_price()

    if real_price is not None:
        update_price_and_run(real_price)
    else:
        print("Skipping cycle because price fetch failed.")

    time.sleep(10)

Status Code: 200

--- LIVE UPDATE ---
Price: 617.51
Decision: SKIP_OR_EXIT_FAST
Action: EXIT_OR_AVOID
Confidence: LOW_CONFIDENCE
Status Code: 200

--- LIVE UPDATE ---
Price: 617.51
Decision: SKIP_OR_EXIT_FAST
Action: EXIT_OR_AVOID
Confidence: LOW_CONFIDENCE
Status Code: 200

--- LIVE UPDATE ---
Price: 617.51
Decision: SKIP_OR_EXIT_FAST
Action: EXIT_OR_AVOID
Confidence: LOW_CONFIDENCE
Status Code: 200

--- LIVE UPDATE ---
Price: 617.51
Decision: SKIP_OR_EXIT_FAST
Action: EXIT_OR_AVOID
Confidence: LOW_CONFIDENCE
Status Code: 200

--- LIVE UPDATE ---
Price: 617.51
Decision: SKIP_OR_EXIT_FAST
Action: EXIT_OR_AVOID
Confidence: LOW_CONFIDENCE
Status Code: 200

--- LIVE UPDATE ---
Price: 617.51
Decision: SKIP_OR_EXIT_FAST
Action: EXIT_OR_AVOID
Confidence: LOW_CONFIDENCE
Status Code: 200

--- LIVE UPDATE ---
Price: 617.51
Decision: SKIP_OR_EXIT_FAST
Action: EXIT_OR_AVOID
Confidence: LOW_CONFIDENCE
Status Code: 200

--- LIVE UPDATE ---
Price: 617.51
Decision: SKIP_OR_EXIT_FAST
Action: EXIT_OR_AVOID
Confidence: LOW_CONFIDENCE
Status Code: 200

--- LIVE UPDATE ---
Price: 617.51
Decision: SKIP_OR_EXIT_FAST
Action: EXIT_OR_AVOID
Confidence: LOW_CONFIDENCE
Status Code: 200

--- LIVE UPDATE ---
Price: 617.51
Decision: SKIP_OR_EXIT_FAST
Action: EXIT_OR_AVOID
Confidence: LOW_CONFIDENCE
Status Code: 200

--- LIVE UPDATE ---
Price: 617.51
Decision: SKIP_OR_EXIT_FAST
Action: EXIT_OR_AVOID
Confidence: LOW_CONFIDENCE
Status Code: 200

--- LIVE UPDATE ---
Price: 617.51
Decision: SKIP_OR_EXIT_FAST
Action: EXIT_OR_AVOID
Confidence: LOW_CONFIDENCE
Status Code: 200

--- LIVE UPDATE ---
Price: 617.51
Decision: SKIP_OR_EXIT_FAST
Action: EXIT_OR_AVOID
Confidence: LOW_CONFIDENCE
Status Code: 200

--- LIVE UPDATE ---
Price: 617.51
Decision: SKIP_OR_EXIT_FAST
Action: EXIT_OR_AVOID
Confidence: LOW_CONFIDENCE
Status Code: 200

--- LIVE UPDATE ---
Price: 617.51
Decision: SKIP_OR_EXIT_FAST
Action: EXIT_OR_AVOID
Confidence: LOW_CONFIDENCE
Status Code: 200

--- LIVE UPDATE ---
Price: 617.51
Decision: SKIP_OR_EXIT_FAST
Action: EXIT_OR_AVOID
Confidence: LOW_CONFIDENCE
Status Code: 200

--- LIVE UPDATE ---
Price: 617.51
Decision: SKIP_OR_EXIT_FAST
Action: EXIT_OR_AVOID
Confidence: LOW_CONFIDENCE
Status Code: 200

--- LIVE UPDATE ---
Price: 617.51
Decision: SKIP_OR_EXIT_FAST
Action: EXIT_OR_AVOID
Confidence: LOW_CONFIDENCE
Status Code: 200

--- LIVE UPDATE ---
Price: 617.51
Decision: SKIP_OR_EXIT_FAST
Action: EXIT_OR_AVOID
Confidence: LOW_CONFIDENCE
Status Code: 200

--- LIVE UPDATE ---
Price: 617.51
Decision: SKIP_OR_EXIT_FAST
Action: EXIT_OR_AVOID
Confidence: LOW_CONFIDENCE

KeyboardInterrupt:

In [130]:
real_price = get_live_price()

if real_price is not None:
    update_price_and_run(real_price)
else:
    print("Price fetch failed, not running analyzer.")

Status Code: 200

--- LIVE UPDATE ---
Price: 617.51
Decision: SKIP_OR_EXIT_FAST
Action: EXIT_OR_AVOID
Confidence: LOW_CONFIDENCE

In [129]:
price = get_live_price()
print("Live QQQ Price:", price)

Status Code: 200
Live QQQ Price: 617.51

In [128]:
import requests

def get_live_price():
    url = "https://query1.finance.yahoo.com/v8/finance/chart/QQQ?interval=1m&range=1d"
    headers = {
        "User-Agent": "Mozilla/5.0"
    }

    response = requests.get(url, headers=headers, timeout=10)

    print("Status Code:", response.status_code)

    if response.status_code != 200:
        print("Bad response text:", response.text[:300])
        return None

    try:
        data = response.json()
    except Exception as e:
        print("JSON error:", e)
        print("Raw response:", response.text[:300])
        return None

    try:
        result = data["chart"]["result"][0]
        closes = result["indicators"]["quote"][0]["close"]
        valid_closes = [x for x in closes if x is not None]

        if not valid_closes:
            print("No valid close prices found.")
            return None

        return round(valid_closes[-1], 2)

    except Exception as e:
        print("Parsing error:", e)
        print("Parsed JSON keys:", list(data.keys()) if isinstance(data, dict) else type(data))
        return None

In [127]:
price = get_live_price()
print("Live QQQ Price:", price)

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

In [126]:
import requests

def get_live_price():
    url = "https://query1.finance.yahoo.com/v8/finance/chart/QQQ?interval=1m&range=1d"
    response = requests.get(url, timeout=10)
    data = response.json()

    result = data["chart"]["result"][0]
    closes = result["indicators"]["quote"][0]["close"]

    valid_closes = [x for x in closes if x is not None]
    return round(valid_closes[-1], 2)

In [125]:
send_trade_alert(df.iloc[0])

Status Code: 204
Response:

In [124]:
def send_trade_alert(row):
    reasons = build_reason(row)
    reason_text = "\n".join([f"- {r}" for r in reasons])

    message = f"""📊 {row['symbol']} Trade Alert

Price: {row.get('price', 'N/A')}
Decision: {row['decision']}
Action: {row['action']}
Confidence: {row.get('confidence', 'N/A')}

Reason:
{reason_text}
"""
    send_to_discord(message)

In [122]:
send_to_discord("🔥 UnBiased AI webhook test")

Status Code: 204
Response:

In [121]:
import requests

def send_to_discord(message):
    data = {"content": message}
    response = requests.post(DISCORD_WEBHOOK_URL, json=data)
    print("Status Code:", response.status_code)
    print("Response:", response.text)

In [245]:
DISCORD_WEBHOOK_URL = "https://discord.com/api/webhooks/1493316667256737997/ZZ_P06TrVr3xHKtDsiMBIPsTMfXagXJTl6xIFXqPkZdJGYK1Wg_JfqAi36lGgp5K0j_J"

In [118]:
import time

In [117]:
import random

def get_live_price():
    # Simulated live price (for now)
    return round(611 + random.uniform(-1, 1.5), 2)

In [119]:
while True:
    price = get_live_price()
    update_price_and_run(price)
    time.sleep(5)  # waits 5 seconds between updates

--- LIVE UPDATE ---
Price: 610.74
Decision: SKIP_OR_EXIT_FAST
Action: EXIT_OR_AVOID
Confidence: LOW_CONFIDENCE
Status Code: 204
Response:
Alert sent to Discord successfully.

--- LIVE UPDATE ---
Price: 612.23
Decision: SKIP_OR_EXIT_FAST
Action: EXIT_OR_AVOID
Confidence: LOW_CONFIDENCE

--- LIVE UPDATE ---
Price: 611.04
Decision: SKIP_OR_EXIT_FAST
Action: EXIT_OR_AVOID
Confidence: LOW_CONFIDENCE

--- LIVE UPDATE ---
Price: 610.73
Decision: SKIP_OR_EXIT_FAST
Action: EXIT_OR_AVOID
Confidence: LOW_CONFIDENCE

--- LIVE UPDATE ---
Price: 610.78
Decision: SKIP_OR_EXIT_FAST
Action: EXIT_OR_AVOID
Confidence: LOW_CONFIDENCE

--- LIVE UPDATE ---
Price: 610.13
Decision: SKIP_OR_EXIT_FAST
Action: EXIT_OR_AVOID
Confidence: LOW_CONFIDENCE

--- LIVE UPDATE ---
Price: 611.75
Decision: SKIP_OR_EXIT_FAST
Action: EXIT_OR_AVOID
Confidence: LOW_CONFIDENCE

--- LIVE UPDATE ---
Price: 612.42
Decision: SKIP_OR_EXIT_FAST
Action: TAKE_PROFIT
Confidence: LOW_CONFIDENCE
Status Code: 204
Response:
Alert sent to Discord successfully.

--- LIVE UPDATE ---
Price: 610.79
Decision: SKIP_OR_EXIT_FAST
Action: EXIT_OR_AVOID
Confidence: LOW_CONFIDENCE
Status Code: 204
Response:
Alert sent to Discord successfully.

--- LIVE UPDATE ---
Price: 611.47
Decision: SKIP_OR_EXIT_FAST
Action: EXIT_OR_AVOID
Confidence: LOW_CONFIDENCE

--- LIVE UPDATE ---
Price: 610.81
Decision: SKIP_OR_EXIT_FAST
Action: EXIT_OR_AVOID
Confidence: LOW_CONFIDENCE

--- LIVE UPDATE ---
Price: 612.21
Decision: SKIP_OR_EXIT_FAST
Action: EXIT_OR_AVOID
Confidence: LOW_CONFIDENCE

--- LIVE UPDATE ---
Price: 612.2
Decision: SKIP_OR_EXIT_FAST
Action: EXIT_OR_AVOID
Confidence: LOW_CONFIDENCE

--- LIVE UPDATE ---
Price: 610.97
Decision: SKIP_OR_EXIT_FAST
Action: EXIT_OR_AVOID
Confidence: LOW_CONFIDENCE

--- LIVE UPDATE ---
Price: 611.0
Decision: SKIP_OR_EXIT_FAST
Action: EXIT_OR_AVOID
Confidence: LOW_CONFIDENCE

--- LIVE UPDATE ---
Price: 610.9
Decision: SKIP_OR_EXIT_FAST
Action: EXIT_OR_AVOID
Confidence: LOW_CONFIDENCE

--- LIVE UPDATE ---
Price: 610.44
Decision: SKIP_OR_EXIT_FAST
Action: EXIT_OR_AVOID
Confidence: LOW_CONFIDENCE

--- LIVE UPDATE ---
Price: 611.42
Decision: SKIP_OR_EXIT_FAST
Action: EXIT_OR_AVOID
Confidence: LOW_CONFIDENCE

--- LIVE UPDATE ---
Price: 611.79
Decision: SKIP_OR_EXIT_FAST
Action: EXIT_OR_AVOID
Confidence: LOW_CONFIDENCE

--- LIVE UPDATE ---
Price: 610.14
Decision: SKIP_OR_EXIT_FAST
Action: EXIT_OR_AVOID
Confidence: LOW_CONFIDENCE

--- LIVE UPDATE ---
Price: 612.48
Decision: SKIP_OR_EXIT_FAST
Action: TAKE_PROFIT
Confidence: LOW_CONFIDENCE
Status Code: 204
Response:
Alert sent to Discord successfully.

--- LIVE UPDATE ---
Price: 610.04
Decision: SKIP_OR_EXIT_FAST
Action: EXIT_OR_AVOID
Confidence: LOW_CONFIDENCE
Status Code: 204
Response:
Alert sent to Discord successfully.

--- LIVE UPDATE ---
Price: 611.42
Decision: SKIP_OR_EXIT_FAST
Action: EXIT_OR_AVOID
Confidence: LOW_CONFIDENCE

--- LIVE UPDATE ---
Price: 610.51
Decision: SKIP_OR_EXIT_FAST
Action: EXIT_OR_AVOID
Confidence: LOW_CONFIDENCE

--- LIVE UPDATE ---
Price: 611.67
Decision: SKIP_OR_EXIT_FAST
Action: EXIT_OR_AVOID
Confidence: LOW_CONFIDENCE

--- LIVE UPDATE ---
Price: 612.5
Decision: SKIP_OR_EXIT_FAST
Action: TAKE_PROFIT
Confidence: LOW_CONFIDENCE
Status Code: 204
Response:
Alert sent to Discord successfully.

--- LIVE UPDATE ---
Price: 611.19
Decision: SKIP_OR_EXIT_FAST
Action: EXIT_OR_AVOID
Confidence: LOW_CONFIDENCE
Status Code: 204
Response:
Alert sent to Discord successfully.

KeyboardInterrupt:

In [115]:
update_price_and_run(611.90)
update_price_and_run(612.30)
update_price_and_run(612.45)
update_price_and_run(612.50)

--- LIVE UPDATE ---
Price: 611.9
Decision: SKIP_OR_EXIT_FAST
Action: EXIT_OR_AVOID
Confidence: LOW_CONFIDENCE
Status Code: 204
Response:
Alert sent to Discord successfully.

--- LIVE UPDATE ---
Price: 612.3
Decision: SKIP_OR_EXIT_FAST
Action: EXIT_OR_AVOID
Confidence: LOW_CONFIDENCE

--- LIVE UPDATE ---
Price: 612.45
Decision: SKIP_OR_EXIT_FAST
Action: TAKE_PROFIT
Confidence: LOW_CONFIDENCE
Status Code: 204
Response:
Alert sent to Discord successfully.

--- LIVE UPDATE ---
Price: 612.5
Decision: SKIP_OR_EXIT_FAST
Action: TAKE_PROFIT
Confidence: LOW_CONFIDENCE

In [114]:
def send_trade_alert(row):
    message = f"""
🚨 UnBiased AI Alert

Symbol: {row['symbol']}
Price: {row['price']}

Decision: {row['decision']}
Action: {row['action']}
Confidence: {row['confidence']}

Context:
{row.get('explanation', 'No explanation provided')}
"""

    send_to_discord(message)

In [113]:
last_action = None  # prevents duplicate alerts

def update_price_and_run(price):
    global df, last_action

    # Update price
    df["price"] = price

    # Recalculate everything
    df["patterns"] = df.apply(detect_trade_pattern, axis=1)
    df["pattern_score"] = df["patterns"].apply(score_patterns)

    df["final_score"] = df["score"] + df["pattern_score"]

    df["regime"] = df.apply(detect_regime, axis=1)
    df["regime_adjustment"] = df.apply(regime_score_adjustment, axis=1)
    df["final_score"] = df["final_score"] + df["regime_adjustment"]

    df["decision"] = df["final_score"].apply(final_decision)
    df["action"] = df.apply(trade_action, axis=1)

    df["confidence_score"] = df.apply(calculate_confidence, axis=1)
    df["confidence"] = df["confidence_score"].apply(confidence_label)

    row = df.iloc[0]

    current_action = row["action"]

    print("\n--- LIVE UPDATE ---")
    print(f"Price: {price}")
    print(f"Decision: {row['decision']}")
    print(f"Action: {current_action}")
    print(f"Confidence: {row['confidence']}")

    # Only alert if action changed
    if current_action != last_action:
        last_action = current_action
        send_trade_alert(row)

In [112]:
df["confidence"] = df["confidence_score"].apply(confidence_label)

df[["symbol", "final_score", "confidence_score", "confidence"]]

  symbol  final_score  confidence_score      confidence
0    QQQ            3                -5  LOW_CONFIDENCE

In [111]:
def confidence_label(score):
    if score >= 4:
        return "HIGH_CONFIDENCE"
    elif score >= 1:
        return "MEDIUM_CONFIDENCE"
    else:
        return "LOW_CONFIDENCE"

In [110]:
df["confidence_score"] = df.apply(calculate_confidence, axis=1)

df[["symbol", "final_score", "confidence_score"]]

  symbol  final_score  confidence_score
0    QQQ            3                -5

In [109]:
def calculate_confidence(row):
    score = row["final_score"]
    regime = row["regime"]
    patterns = row.get("patterns", [])

    confidence = 0

    # Score contribution
    if score >= 10:
        confidence += 3
    elif score >= 7:
        confidence += 2
    elif score >= 4:
        confidence += 1
    else:
        confidence -= 1

    # Regime contribution
    if regime == "trend_regime":
        confidence += 2
    elif regime == "mixed_regime":
        confidence += 0
    else:
        confidence -= 2

    # Pattern penalties
    if "late_entry_risk" in patterns:
        confidence -= 1
    if "momentum_extended" in patterns:
        confidence -= 1
    if "resistance_trap_risk" in patterns:
        confidence -= 2

    return confidence

In [108]:
df["action"] = df.apply(trade_action, axis=1)

df[["symbol", "regime", "final_score", "decision", "action"]]

  symbol        regime  final_score           decision         action
0    QQQ  mixed_regime            3  SKIP_OR_EXIT_FAST  EXIT_OR_AVOID

In [107]:
def trade_action(row):
    decision = row["decision"]
    patterns = row.get("patterns", [])

    # Hard exit takes priority
    if should_force_take_profit(row):
        return "TAKE_PROFIT"

    # Strong negative state
    if decision == "SKIP_OR_EXIT_FAST":
        return "EXIT_OR_AVOID"

    # Caution state
    if "late_entry_risk" in patterns and "momentum_extended" in patterns:
        return "REDUCE_OR_TIGHTEN_STOP"

    # Normal logic
    if decision == "A_SETUP":
        return "FULL_ENTRY"
    elif decision == "B_SETUP":
        return "NORMAL_ENTRY"
    elif decision == "WATCH_OR_SMALL_SIZE":
        return "SMALL_SIZE_OR_WAIT"
    else:
        return "AVOID_OR_EXIT"

In [106]:
df["decision"] = df["final_score"].apply(final_decision)
df["action"] = df.apply(trade_action, axis=1)

df[["symbol", "regime", "final_score", "decision", "action"]]

  symbol        regime  final_score           decision                  action
0    QQQ  mixed_regime            3  SKIP_OR_EXIT_FAST  REDUCE_OR_TIGHTEN_STOP

In [105]:
df["regime_adjustment"] = df.apply(regime_score_adjustment, axis=1)
df["final_score"] = df["final_score"] + df["regime_adjustment"]

df[["symbol", "regime", "regime_adjustment", "final_score"]]

  symbol        regime  regime_adjustment  final_score
0    QQQ  mixed_regime                 -1            3

In [104]:
def regime_score_adjustment(row):
    if row["regime"] == "trend_regime":
        return 2
    elif row["regime"] == "chop_regime":
        return -2
    else:
        return -1

In [103]:
df["regime"] = df.apply(detect_regime, axis=1)

df[[
    "symbol",
    "volatility",
    "mtf_structure",
    "session",
    "regime"
]]

  symbol volatility mtf_structure session        regime
0    QQQ     medium  higher_highs    late  mixed_regime

In [102]:
defaults = {
    "volatility": "medium",
    "session": "late",
    "mtf_structure": "higher_highs",
    "quality": "B",
    "level": "resistance",
    "reaction": "break_hold",
    "rsi_state": "elevated",
    "session_phase": "late_morning",
    "oil_pct_change": 0.0,
    "oil_velocity_per_min": 0.0,
}

for col, default_value in defaults.items():
    if col not in df.columns:
        df[col] = default_value

print("Missing fields patched.")
print(df.columns.tolist())

Missing fields patched.
['symbol', 'asset_type', 'score', 'grade', 'win_probability', 'summary', 'direction', 'setup_name', 'level', 'reaction', 'position_vs_vwap', 'htf_bias', 'mtf_structure', 'session_phase', 'test_number', 'quality', 'rsi_state', 'macd_state', 'bollinger_context', 'market_sentiment', 'environment', 'oil_trend', 'oil_volatility', 'oil_shock', 'oil_shock_direction', 'oil_shock_strength', 'oil_pct_change', 'oil_velocity_per_min', 'macro_context', 'macro_note', 'mistake_tag', 'trade_management_mistake', 'management_notes', 'confluence_count', 'confluence_factors', 'ai_label', 'patterns', 'pattern_score', 'final_score', 'decision', 'action', 'explanation', 'price', 'reasons', 'avg_win', 'avg_loss', 'ev', 'volatility', 'session', 'regime']

In [101]:
df["regime"] = df.apply(detect_regime, axis=1)

df[["symbol", "volatility", "mtf_structure", "regime"]]

  symbol volatility mtf_structure        regime
0    QQQ     medium  higher_highs  mixed_regime

In [100]:
def detect_regime(row):
    if row["volatility"] == "high" and row["mtf_structure"] in ["higher_highs", "lower_lows"]:
        return "trend_regime"
    elif row["volatility"] == "low":
        return "chop_regime"
    else:
        return "mixed_regime"

In [99]:
if "volatility" not in df.columns:
    df["volatility"] = "medium"

if "session" not in df.columns:
    df["session"] = "late"

if "mtf_structure" not in df.columns:
    df["mtf_structure"] = "higher_highs"

In [98]:
print(df.columns.tolist())

['symbol', 'asset_type', 'score', 'grade', 'win_probability', 'summary', 'direction', 'setup_name', 'level', 'reaction', 'position_vs_vwap', 'htf_bias', 'mtf_structure', 'session_phase', 'test_number', 'quality', 'rsi_state', 'macd_state', 'bollinger_context', 'market_sentiment', 'environment', 'oil_trend', 'oil_volatility', 'oil_shock', 'oil_shock_direction', 'oil_shock_strength', 'oil_pct_change', 'oil_velocity_per_min', 'macro_context', 'macro_note', 'mistake_tag', 'trade_management_mistake', 'management_notes', 'confluence_count', 'confluence_factors', 'ai_label', 'patterns', 'pattern_score', 'final_score', 'decision', 'action', 'explanation', 'price', 'reasons', 'avg_win', 'avg_loss', 'ev']

In [97]:
df["regime"] = df.apply(detect_regime, axis=1)

df[["symbol", "volatility", "mtf_structure", "regime"]]

KeyError: 'volatility'

In [96]:
def detect_regime(row):
    if row["volatility"] == "high" and row["mtf_structure"] in ["higher_highs", "lower_lows"]:
        return "trend_regime"
    elif row["volatility"] == "low":
        return "chop_regime"
    else:
        return "mixed_regime"

In [95]:
# You can tweak these later based on real data
df["avg_win"] = 1.5
df["avg_loss"] = 1.0

df["ev"] = df.apply(lambda row: calculate_ev(
    row["win_probability"],
    row["avg_win"],
    row["avg_loss"]
), axis=1)

df[["symbol", "win_probability", "avg_win", "avg_loss", "ev"]]

  symbol  win_probability  avg_win  avg_loss   ev
0    QQQ               68      1.5       1.0  0.7

In [94]:
def calculate_ev(win_prob, avg_win, avg_loss):
    return (win_prob/100 * avg_win) - ((1 - win_prob/100) * avg_loss)

In [93]:
# You can tweak these later based on real data
df["avg_win"] = 1.5
df["avg_loss"] = 1.0

df["ev"] = df.apply(lambda row: calculate_ev(
    row["win_probability"],
    row["avg_win"],
    row["avg_loss"]
), axis=1)

df[["symbol", "win_probability", "avg_win", "avg_loss", "ev"]]

NameError: name 'calculate_ev' is not defined

In [92]:
send_trade_alert(df.iloc[0])

Status Code: 204
Response:
Alert sent to Discord successfully.

In [91]:
send_trade_alert(df.iloc[0])

Status Code: 204
Response:
Alert sent to Discord successfully.

In [87]:
def send_trade_alert(row):
    reasons = build_reason(row)
    reason_text = "\n".join([f"- {r}" for r in reasons])

    message = f"""📊 {row['symbol']} Trade Alert

Price: {row.get('price', 'N/A')}
Decision: {row['decision']}
Action: {row['action']}

Reason:
{reason_text}

Instruction:
{"Pay yourself here. Do not overstay the move." if row["action"] == "TAKE_PROFIT" else "Manage risk and stay patient."}
"""
    send_to_discord(message)

In [86]:
send_to_discord("🔥 TEST FROM AI (CHECK)")

Status Code: 204
Response:
Alert sent to Discord successfully.

In [85]:
import requests

def send_to_discord(message):
    data = {"content": message}
    response = requests.post(DISCORD_WEBHOOK_URL, json=data)

    print("Status Code:", response.status_code)
    print("Response:", response.text)

    if response.status_code == 204:
        print("Alert sent to Discord successfully.")
    else:
        print("Discord webhook failed.")

In [84]:
DISCORD_WEBHOOK_URL = "https://discord.com/api/webhooks/1493316667256737997/ZZ_P06TrVr3xHKtDsiMBIPsTMfXagXJTl6xIFXqPkZdJGYK1Wg_JfqAi36lGgp5K0j_J"

In [83]:
send_to_discord("🔥 TEST FROM AI (CHECK)")

Sending to Discord...
Status Code: 401

In [82]:
import requests

def send_to_discord(message):
    print("Sending to Discord...")  # debug line
    data = {"content": message}
    response = requests.post(DISCORD_WEBHOOK_URL, json=data)
    print("Status Code:", response.status_code)

In [81]:
send_to_discord("🔥 Test message from UnBiased AI")

In [79]:
import requests

def send_to_discord(message):
    data = {
        "content": message
    }
    requests.post(DISCORD_WEBHOOK_URL, json=data)

In [78]:
send_to_discord("🔥 Test message from UnBiased AI")

NameError: name 'send_to_discord' is not defined

In [77]:
DISCORD_WEBHOOK_URL = "https://discord.com/api/webhooks/1493316667256737997/ZZ_P06TrVr3xHKtDsiMBIPsTMfXagxJTl6xIFXqPkZdJGYK1Wg_JfqAi36lGgp5K0j_J"

In [76]:
DISCORD_WEBHOOK_URL = https://discord.com/api/webhooks/1493316667256737997/ZZ_P06TrVr3xHKtDsiMBIPsTMfXagXJTl6xIFXqPkZdJGYK1Wg_JfqAi36lGgp5K0j_J

SyntaxError: invalid syntax (960729785.py, line 1)

In [75]:
print(generate_signal(df.iloc[0]))

📊 QQQ Trade Signal

Decision: WATCH_OR_SMALL_SIZE
Action: REDUCE_OR_TIGHTEN_STOP

Reason:
- Momentum is extended
- Late timing increases stall risk
- Oil shock already fueled the move

Instruction:
Pay yourself here. Do not overstay the move.

In [73]:
df["reasons"] = df.apply(build_reason, axis=1)

df[["symbol", "price", "decision", "action", "reasons"]]

,symbol,price,decision,action,reasons
0,QQQ,611.9,WATCH_OR_SMALL_SIZE,REDUCE_OR_TIGHTEN_STOP,"[Momentum is extended, Late timing increases s..."

In [72]:
def build_reason(row):
    reasons = []

    price = row.get("price", 0)
    rsi_state = row.get("rsi_state", "")
    patterns = row.get("patterns", [])
    session_phase = row.get("session_phase", "")
    oil_pct_change = row.get("oil_pct_change", 0)

    in_sell_zone = 612.40 <= price <= 612.50
    momentum_extended = rsi_state == "elevated" or "momentum_extended" in patterns
    late_timing = session_phase in ["late_morning", "midday"]
    oil_shock = oil_pct_change <= -2

    if in_sell_zone:
        reasons.append("Price is in sell zone (612.40–612.50)")

    if momentum_extended:
        reasons.append("Momentum is extended")

    if late_timing:
        reasons.append("Late timing increases stall risk")

    if oil_shock:
        reasons.append("Oil shock already fueled the move")

    return reasons

In [71]:
update_price_and_check(612.45)  # should TAKE_PROFIT
update_price_and_check(611.90)  # should NOT force exit

  symbol   price  final_score             decision       action
0    QQQ  612.45            4  WATCH_OR_SMALL_SIZE  TAKE_PROFIT

⚠️ QQQ TAKE PROFIT ALERT

Price: 612.45
Decision: WATCH_OR_SMALL_SIZE
Action: TAKE_PROFIT

Reason:
- Price is in sell zone (612.40–612.50)
- Momentum is extended
- Late timing increases stall risk
- Oil shock already fueled the move

Instruction:
Pay yourself here. Do not overstay the move.

  symbol  price  final_score             decision                  action
0    QQQ  611.9            4  WATCH_OR_SMALL_SIZE  REDUCE_OR_TIGHTEN_STOP

⚠️ QQQ TAKE PROFIT ALERT

Price: 611.9
Decision: WATCH_OR_SMALL_SIZE
Action: REDUCE_OR_TIGHTEN_STOP

Reason:
- Price is in sell zone (612.40–612.50)
- Momentum is extended
- Late timing increases stall risk
- Oil shock already fueled the move

Instruction:
Pay yourself here. Do not overstay the move.

In [70]:
df["action"] = df.apply(trade_action, axis=1)

In [67]:
update_price_and_check(612.50)

  symbol  price  final_score             decision       action
0    QQQ  612.5            4  WATCH_OR_SMALL_SIZE  TAKE_PROFIT

⚠️ QQQ TAKE PROFIT ALERT

Price: 612.5
Decision: WATCH_OR_SMALL_SIZE
Action: TAKE_PROFIT

Reason:
- Price is in sell zone (612.40–612.50)
- Momentum is extended
- Late timing increases stall risk
- Oil shock already fueled the move

Instruction:
Pay yourself here. Do not overstay the move.

In [66]:
update_price_and_check(611.90)

  symbol  price  final_score             decision       action
0    QQQ  611.9            4  WATCH_OR_SMALL_SIZE  TAKE_PROFIT

⚠️ QQQ TAKE PROFIT ALERT

Price: 611.9
Decision: WATCH_OR_SMALL_SIZE
Action: TAKE_PROFIT

Reason:
- Price is in sell zone (612.40–612.50)
- Momentum is extended
- Late timing increases stall risk
- Oil shock already fueled the move

Instruction:
Pay yourself here. Do not overstay the move.

In [65]:
update_price_and_check(612.45)

  symbol   price  final_score             decision       action
0    QQQ  612.45            4  WATCH_OR_SMALL_SIZE  TAKE_PROFIT

⚠️ QQQ TAKE PROFIT ALERT

Price: 612.45
Decision: WATCH_OR_SMALL_SIZE
Action: TAKE_PROFIT

Reason:
- Price is in sell zone (612.40–612.50)
- Momentum is extended
- Late timing increases stall risk
- Oil shock already fueled the move

Instruction:
Pay yourself here. Do not overstay the move.

In [64]:
def update_price_and_check(new_price):
    df["price"] = new_price
    df["action"] = df.apply(trade_action, axis=1)

    print(df[["symbol", "price", "final_score", "decision", "action"]])
    print(generate_live_exit_alert(df.iloc[0]))

In [63]:
print(generate_live_exit_alert(df.iloc[0]))

⚠️ QQQ TAKE PROFIT ALERT

Price: 612.45
Decision: WATCH_OR_SMALL_SIZE
Action: TAKE_PROFIT

Reason:
- Price is in sell zone (612.40–612.50)
- Momentum is extended
- Late timing increases stall risk
- Oil shock already fueled the move

Instruction:
Pay yourself here. Do not overstay the move.

In [62]:
def generate_live_exit_alert(row):
    return f"""
⚠️ {row['symbol']} TAKE PROFIT ALERT

Price: {row['price']}
Decision: {row['decision']}
Action: {row['action']}

Reason:
- Price is in sell zone (612.40–612.50)
- Momentum is extended
- Late timing increases stall risk
- Oil shock already fueled the move

Instruction:
Pay yourself here. Do not overstay the move.
"""

In [61]:
df["action"] = df.apply(trade_action, axis=1)
df[["symbol", "price", "final_score", "decision", "action"]]

  symbol   price  final_score             decision       action
0    QQQ  612.45            4  WATCH_OR_SMALL_SIZE  TAKE_PROFIT

In [69]:
def trade_action(row):
    decision = row["decision"]
    patterns = row["patterns"]

    # 🎯 HARD EXIT
    if should_force_take_profit(row):
        return "TAKE_PROFIT"

    # ⚠️ SOFT RISK (NOT forced exit)
    if "late_entry_risk" in patterns and "momentum_extended" in patterns:
        return "REDUCE_OR_TIGHTEN_STOP"

    # Normal logic
    if decision == "A_SETUP":
        return "FULL_SIZE_ENTRY"
    elif decision == "B_SETUP":
        return "NORMAL_ENTRY"
    elif decision == "WATCH_OR_SMALL_SIZE":
        return "SMALL_SIZE_OR_WAIT"
    else:
        return "AVOID_OR_EXIT"

In [68]:
def should_force_take_profit(row):
    level = row.get("level", "")
    rsi_state = row.get("rsi_state", "")
    patterns = row.get("patterns", [])
    session_phase = row.get("session_phase", "")
    oil_pct_change = row.get("oil_pct_change", 0)
    oil_velocity = row.get("oil_velocity_per_min", 0)
    price = row.get("price", 0)

    # Conditions
    momentum_extended = rsi_state == "elevated" or "momentum_extended" in patterns
    late_timing = session_phase in ["late_morning", "midday"]
    oil_shock = oil_pct_change <= -2 and oil_velocity <= -0.1

    # 🎯 SNIPER SELL ZONE (PRIMARY EXIT)
    in_sell_zone = 612.40 <= price <= 612.50

    if in_sell_zone and momentum_extended:
        return True

    # ⚠️ Only warn conditions (NOT forced exit)
    return False

In [58]:
df["price"] = 612.45

In [57]:
df["action"] = df.apply(trade_action, axis=1)
df[["symbol", "final_score", "decision", "action"]]

  symbol  final_score             decision       action
0    QQQ            4  WATCH_OR_SMALL_SIZE  TAKE_PROFIT

In [56]:
df["price"] = 612.45

In [54]:
price = row.get("price", 0)

in_sell_zone = 612.40 <= price <= 612.50

if in_sell_zone and momentum_extended:
    return True

SyntaxError: 'return' outside function (496280530.py, line 6)

In [55]:
def should_force_take_profit(row):
    level = row.get("level", "")
    rsi_state = row.get("rsi_state", "")
    patterns = row.get("patterns", [])
    session_phase = row.get("session_phase", "")
    oil_pct_change = row.get("oil_pct_change", 0)
    oil_velocity = row.get("oil_velocity_per_min", 0)
    price = row.get("price", 0)

    # Core conditions
    in_resistance_zone = level == "resistance"
    momentum_extended = rsi_state == "elevated" or "momentum_extended" in patterns
    late_timing = session_phase in ["late_morning", "midday"]

    # Oil shock
    oil_shock = oil_pct_change <= -2 and oil_velocity <= -0.1

    # 🎯 Price sell zone (your sniper level)
    in_sell_zone = 612.40 <= price <= 612.50

    # 🔥 RULES

    # Classic late-cycle exit
    if in_resistance_zone and momentum_extended and late_timing:
        return True

    # Oil-driven move exhaustion
    if oil_shock and momentum_extended and late_timing:
        return True

    # 🎯 SNIPER EXIT (your exact level)
    if in_sell_zone and momentum_extended:
        return True

    return False

In [52]:
df["action"] = df.apply(trade_action, axis=1)

df[["symbol", "final_score", "decision", "action"]]

  symbol  final_score             decision       action
0    QQQ            4  WATCH_OR_SMALL_SIZE  TAKE_PROFIT

In [50]:
def should_force_take_profit(row):
    level = row.get("level", "")
    rsi_state = row.get("rsi_state", "")
    patterns = row.get("patterns", [])
    session_phase = row.get("session_phase", "")

    # Define resistance zone
    in_resistance_zone = level == "resistance"

    # Define extended momentum
    momentum_extended = rsi_state == "elevated" or "momentum_extended" in patterns

    # Define late timing
    late_timing = session_phase in ["late_morning", "midday"]

    if in_resistance_zone and momentum_extended and late_timing:
        return True

    return False

In [49]:
if price_in_resistance_zone and rsi > 65 and macd_extended:
    action = "FORCE_TAKE_PROFIT"

NameError: name 'price_in_resistance_zone' is not defined

In [48]:
pre_df = pd.DataFrame([pre_trade])

pre_df["patterns"] = pre_df.apply(detect_trade_pattern, axis=1)
pre_df["pattern_score"] = pre_df["patterns"].apply(score_patterns)
pre_df["score"] = 8  # your manual base grade
pre_df["final_score"] = pre_df["score"] + pre_df["pattern_score"]
pre_df["decision"] = pre_df["final_score"].apply(final_decision)
pre_df["action"] = pre_df.apply(trade_action, axis=1)
pre_df["explanation"] = pre_df.apply(explain_trade, axis=1)

print(generate_signal(pre_df.iloc[0]))

📊 QQQ Trade Signal

Decision: WATCH_OR_SMALL_SIZE
Action: TAKE_PROFIT

Context:
Oil drop creating bullish tailwind | Late in move | At resistance cluster | Momentum already extended

In [47]:
pre_trade = {
    "symbol": "QQQ",
    "level": "resistance",
    "reaction": "break_hold",
    "rsi_state": "elevated",
    "oil_pct_change": -3.2,
    "oil_velocity_per_min": -0.15,
    "session_phase": "late_morning"
}

In [74]:
def generate_signal(row):
    reasons = build_reason(row)

    reason_text = "\n".join([f"- {r}" for r in reasons])

    return f"""
📊 {row['symbol']} Trade Signal

Decision: {row['decision']}
Action: {row['action']}

Reason:
{reason_text}

Instruction:
Pay yourself here. Do not overstay the move.
"""

In [45]:
def explain_trade(row):
    explanation = []

    if "oil_bullish_impulse" in row["patterns"]:
        explanation.append("Oil drop creating bullish tailwind")

    if "late_entry_risk" in row["patterns"]:
        explanation.append("Late in move")

    if "resistance_trap_risk" in row["patterns"]:
        explanation.append("At resistance cluster")

    if "momentum_extended" in row["patterns"]:
        explanation.append("Momentum already extended")

    return " | ".join(explanation)

df["explanation"] = df.apply(explain_trade, axis=1)

df[["symbol", "decision", "action", "explanation"]]

,symbol,decision,action,explanation
0,QQQ,WATCH_OR_SMALL_SIZE,TAKE_PROFIT,Oil drop creating bullish tailwind | Late in m...

In [51]:
def trade_action(row):
    decision = row["decision"]

    if should_force_take_profit(row):
        return "TAKE_PROFIT"

    if decision == "A_SETUP":
        return "FULL_SIZE_ENTRY"
    elif decision == "B_SETUP":
        return "NORMAL_ENTRY"
    elif decision == "WATCH_OR_SMALL_SIZE":
        return "SMALL_SIZE_OR_WAIT"
    else:
        return "AVOID_OR_EXIT"

In [43]:
df["pattern_score"] = df["patterns"].apply(score_patterns)
df["final_score"] = df["score"] + df["pattern_score"]

def final_decision(score):
    if score >= 10:
        return "A_SETUP"
    elif score >= 7:
        return "B_SETUP"
    elif score >= 4:
        return "WATCH_OR_SMALL_SIZE"
    else:
        return "SKIP_OR_EXIT_FAST"

df["decision"] = df["final_score"].apply(final_decision)

df[["symbol", "score", "patterns", "pattern_score", "final_score", "decision"]]

,symbol,score,patterns,pattern_score,final_score,decision
0,QQQ,8,"[late_entry_risk, oil_bullish_impulse, resista...",-4,4,WATCH_OR_SMALL_SIZE

In [42]:
def score_patterns(patterns):
    weights = {
        "oil_bullish_impulse": 3,
        "late_entry_risk": -2,
        "resistance_trap_risk": -3,
        "momentum_extended": -2,
    }

    total = 0
    for p in patterns:
        total += weights.get(p, 0)

    return total

In [41]:
df["patterns"] = df.apply(detect_trade_pattern, axis=1)
df[["symbol", "score", "grade", "patterns"]]

  symbol  score grade                                           patterns
0    QQQ      8    B+  [late_entry_risk, oil_bullish_impulse, resista...

In [40]:
def detect_trade_pattern(row):
    patterns = []

    # pull values safely
    level = row.get("level", "")
    reaction = row.get("reaction", "")
    rsi_state = row.get("rsi_state", "")
    oil_pct_change = row.get("oil_pct_change", 0)
    oil_velocity_per_min = row.get("oil_velocity_per_min", 0)
    session_phase = row.get("session_phase", "")
    summary = str(row.get("summary", "")).lower()

    # Late entry pattern
    if session_phase == "late_morning" or "late_morning" in summary:
        patterns.append("late_entry_risk")

    # Oil shock pattern
    if oil_pct_change <= -2 and oil_velocity_per_min <= -0.1:
        patterns.append("oil_bullish_impulse")

    # Resistance trap
    if level == "resistance" and reaction == "break_hold":
        patterns.append("resistance_trap_risk")

    # Extended momentum
    if rsi_state == "elevated":
        patterns.append("momentum_extended")

    return patterns

In [39]:
print(df.columns.tolist())

['symbol', 'asset_type', 'score', 'grade', 'win_probability', 'summary', 'direction', 'setup_name', 'level', 'reaction', 'position_vs_vwap', 'htf_bias', 'mtf_structure', 'session_phase', 'test_number', 'quality', 'rsi_state', 'macd_state', 'bollinger_context', 'market_sentiment', 'environment', 'oil_trend', 'oil_volatility', 'oil_shock', 'oil_shock_direction', 'oil_shock_strength', 'oil_pct_change', 'oil_velocity_per_min', 'macro_context', 'macro_note', 'mistake_tag', 'trade_management_mistake', 'management_notes', 'confluence_count', 'confluence_factors', 'ai_label']

In [38]:
df["patterns"] = df.apply(detect_trade_pattern, axis=1)
df[["symbol", "score", "grade", "patterns"]]

KeyError: 'trade_window'

In [35]:
df["patterns"] = df.apply(detect_trade_pattern, axis=1)
df[["symbol", "score", "grade", "patterns"]]

KeyError: 'session'

In [37]:
def detect_trade_pattern(row):
    patterns = []

    # Late entry pattern
    if row["trade_window"] == "off_hours" and row["rsi"] >= 60:
        patterns.append("late_entry_risk")

    # Oil shock pattern (YOUR EDGE)
    if row["oil_pct_change"] <= -2 and row["oil_velocity_per_min"] <= -0.1:
        patterns.append("oil_bullish_impulse")

    # Resistance trap
    if row["level"] == "resistance" and row["reaction"] == "break_hold":
        patterns.append("resistance_trap_risk")

    # Extended momentum
    if row["rsi"] >= 65:
        patterns.append("momentum_extended")

    return patterns

In [33]:
from google.colab import files
files.download("unbiased_trades_training_data.csv")

In [32]:
df.to_csv("unbiased_trades_training_data.csv", index=False)
print("Saved to unbiased_trades_training_data.csv")

Saved to unbiased_trades_training_data.csv

In [ ]:
import pandas as pd

df = pd.DataFrame(training_rows)
df

,symbol,asset_type,score,grade,win_probability,summary,direction,setup_name,level,reaction,...,oil_pct_change,oil_velocity_per_min,macro_context,macro_note,mistake_tag,trade_management_mistake,management_notes,confluence_count,confluence_factors,ai_label
0,QQQ,index,8,B+,68,QQQ call setup | reaction=break_hold | level=r...,call,QQQ oil-shock bullish continuation into resist...,resistance,break_hold,...,-3.49,-0.175,bullish_for_qqq,Fast downside oil shock supports upside impuls...,none,failed_to_sell_into_resistance,Late-morning continuation risk | RSI elevated ...,5,"oil_shock, bullish_structure, above_vwap, dark...",bullish_macro_correct_but_late_cycle_hold_error

In [ ]:
row = result_to_training_row(result, ai_label)
training_rows.append(row)
print("Saved rows:", len(training_rows))
print(training_rows[-1])

Saved rows: 1
{'symbol': 'QQQ', 'asset_type': 'index', 'score': 8, 'grade': 'B+', 'win_probability': 68, 'summary': 'QQQ call setup | reaction=break_hold | level=resistance | session=late_morning | grade=B+', 'direction': 'call', 'setup_name': 'QQQ oil-shock bullish continuation into resistance', 'level': 'resistance', 'reaction': 'break_hold', 'position_vs_vwap': 'above', 'htf_bias': 'bullish', 'mtf_structure': 'higher_highs', 'session_phase': 'late_morning', 'test_number': 'late_cycle_continuation', 'quality': 'A', 'rsi_state': 'elevated', 'macd_state': 'mature_bullish', 'bollinger_context': 'near_upper_band', 'market_sentiment': 'risk_on', 'environment': 'trend_day', 'oil_trend': 'down_fast', 'oil_volatility': 'high', 'oil_shock': True, 'oil_shock_direction': 'down', 'oil_shock_strength': 'strong', 'oil_pct_change': -3.49, 'oil_velocity_per_min': -0.175, 'macro_context': 'bullish_for_qqq', 'macro_note': 'Fast downside oil shock supports upside impulse in QQQ.', 'mistake_tag': 'none', 'trade_management_mistake': 'failed_to_sell_into_resistance', 'management_notes': 'Late-morning continuation risk | RSI elevated | MACD mature, not fresh | Price extended near upper band | Failed to sell into known resistance cluster', 'confluence_count': 5, 'confluence_factors': 'oil_shock, bullish_structure, above_vwap, dark_pool_support, risk_on', 'ai_label': 'bullish_macro_correct_but_late_cycle_hold_error'}

In [ ]:
training_rows = []

In [ ]:
def result_to_training_row(result, ai_label):
    trade = result["trade"]
    oil_shock = result["oil_shock"]
    oil_context = result["oil_context"]

    return {
        "symbol": result["symbol"],
        "asset_type": result["asset_type"],
        "score": result["score"],
        "grade": result["grade"],
        "win_probability": result["win_probability"],
        "summary": result["summary"],

        "direction": trade.get("direction"),
        "setup_name": trade.get("setup_name"),
        "level": trade.get("level"),
        "reaction": trade.get("reaction"),
        "position_vs_vwap": trade.get("position_vs_vwap"),
        "htf_bias": trade.get("htf_bias"),
        "mtf_structure": trade.get("mtf_structure"),
        "session_phase": trade.get("session_phase"),
        "test_number": trade.get("test_number"),
        "quality": trade.get("quality"),

        "rsi_state": trade.get("rsi_state"),
        "macd_state": trade.get("macd_state"),
        "bollinger_context": trade.get("bollinger_context"),

        "market_sentiment": trade.get("market_sentiment"),
        "environment": trade.get("environment"),
        "oil_trend": trade.get("oil_trend"),
        "oil_volatility": trade.get("oil_volatility"),

        "oil_shock": oil_shock.get("oil_shock"),
        "oil_shock_direction": oil_shock.get("shock_direction"),
        "oil_shock_strength": oil_shock.get("shock_strength"),
        "oil_pct_change": oil_shock.get("pct_change"),
        "oil_velocity_per_min": oil_shock.get("velocity_per_min"),
        "macro_context": oil_context.get("macro_context"),
        "macro_note": oil_context.get("macro_note"),

        "mistake_tag": trade.get("mistake_tag"),
        "trade_management_mistake": trade.get("trade_management_mistake"),
        "management_notes": " | ".join(result.get("management_notes", [])),

        "confluence_count": len(trade.get("confluence_factors", [])),
        "confluence_factors": ", ".join(trade.get("confluence_factors", [])),

        "ai_label": ai_label
    }

In [ ]:
ai_label = "bullish_macro_correct_but_late_cycle_hold_error"
print(ai_label)

bullish_macro_correct_but_late_cycle_hold_error

In [ ]:
force_exit = should_force_profit_take(
    price=612.45,
    rsi_value=68,
    macd_extended=True,
    time_phase="late_morning"
)

print("FORCE PROFIT TAKE:", force_exit)

FORCE PROFIT TAKE: True

In [ ]:
def should_force_profit_take(price, rsi_value, macd_extended, time_phase, sell_zone_low=612.40, sell_zone_high=612.50):
    in_sell_zone = sell_zone_low <= price <= sell_zone_high

    if in_sell_zone and rsi_value >= 65 and macd_extended and time_phase == "late_morning":
        return True

    return False

In [ ]:
result = full_analysis_with_oil_context(
    qqq_trade_today,
    oil_start=102.83,
    oil_end=99.24,
    oil_minutes=20
)

print_trade_result(result)

TRADE REVIEW
--------------------------------------------------
Symbol: QQQ
Asset Type: index
Score: 8
Grade: B+
Win Probability: 68%
Summary: QQQ call setup | reaction=break_hold | level=resistance | session=late_morning | grade=B+
--------------------------------------------------
OIL CONTEXT
Shock: True
Direction: down
Strength: strong
Percent Change: -3.49%
Velocity per Minute: -0.175%
Macro Context: bullish_for_qqq
Macro Note: Fast downside oil shock supports upside impulse in QQQ.
--------------------------------------------------
MANAGEMENT NOTES
- Late-morning continuation risk
- RSI elevated
- MACD mature, not fresh
- Price extended near upper band
- Failed to sell into known resistance cluster
--------------------------------------------------
TRADE DETAILS
Direction: call
Level: resistance
Reaction: break_hold
VWAP Position: above
HTF Bias: bullish
MTF Structure: higher_highs
Session: late_morning
Quality: A
RSI State: elevated
MACD State: mature_bullish
Bollinger Context: near_upper_band
Mistake Tag: none
Trade Management Mistake: failed_to_sell_into_resistance
Confluence: oil_shock, bullish_structure, above_vwap, dark_pool_support, risk_on

In [ ]:
qqq_trade_today = {
    "symbol": "QQQ",
    "asset_type": get_asset_type("QQQ"),
    "direction": "call",
    "contract": "QQQ 613C 0DTE",
    "entry_price_option": 0.76,
    "option_price_snapshot": 0.57,
    "underlying_price_snapshot": 611.77,

    "setup_name": "QQQ oil-shock bullish continuation into resistance",
    "level": "resistance",
    "reaction": "break_hold",
    "position_vs_vwap": "above",
    "htf_bias": "bullish",
    "mtf_structure": "higher_highs",
    "session_phase": "late_morning",
    "test_number": "late_cycle_continuation",
    "quality": "A",

    "rsi_state": "elevated",
    "macd_state": "mature_bullish",
    "bollinger_context": "near_upper_band",

    "market_sentiment": "risk_on",
    "environment": "trend_day",
    "oil_trend": "down_fast",
    "oil_volatility": "high",

    "mistake_tag": "none",
    "trade_management_mistake": "failed_to_sell_into_resistance",

    "dark_pool_support_levels": [609.80, 610.20, 610.70, 611.00, 611.08, 611.40, 611.56],
    "dark_pool_resistance_levels": [611.56, 612.74, 613.21],
    "sell_zone": [612.40, 612.50],

    "confluence_factors": [
        "oil_shock",
        "bullish_structure",
        "above_vwap",
        "dark_pool_support",
        "risk_on"
    ]
}

In [ ]:
def print_trade_result(result):
    print("TRADE REVIEW")
    print("-" * 50)
    print(f"Symbol: {result['symbol']}")
    print(f"Asset Type: {result['asset_type']}")
    print(f"Score: {result['score']}")
    print(f"Grade: {result['grade']}")
    print(f"Win Probability: {result['win_probability']}%")
    print(f"Summary: {result['summary']}")
    print("-" * 50)

    print("OIL CONTEXT")
    print(f"Shock: {result['oil_shock']['oil_shock']}")
    print(f"Direction: {result['oil_shock']['shock_direction']}")
    print(f"Strength: {result['oil_shock']['shock_strength']}")
    print(f"Percent Change: {result['oil_shock']['pct_change']}%")
    print(f"Velocity per Minute: {result['oil_shock']['velocity_per_min']}%")
    print(f"Macro Context: {result['oil_context']['macro_context']}")
    print(f"Macro Note: {result['oil_context']['macro_note']}")
    print("-" * 50)

    print("MANAGEMENT NOTES")
    if result["management_notes"]:
        for note in result["management_notes"]:
            print(f"- {note}")
    else:
        print("- None")
    print("-" * 50)

    trade = result["trade"]
    print("TRADE DETAILS")
    print(f"Direction: {trade['direction']}")
    print(f"Level: {trade['level']}")
    print(f"Reaction: {trade['reaction']}")
    print(f"VWAP Position: {trade['position_vs_vwap']}")
    print(f"HTF Bias: {trade['htf_bias']}")
    print(f"MTF Structure: {trade['mtf_structure']}")
    print(f"Session: {trade['session_phase']}")
    print(f"Quality: {trade['quality']}")
    print(f"RSI State: {trade['rsi_state']}")
    print(f"MACD State: {trade['macd_state']}")
    print(f"Bollinger Context: {trade['bollinger_context']}")
    print(f"Mistake Tag: {trade['mistake_tag']}")
    print(f"Trade Management Mistake: {trade['trade_management_mistake']}")
    print(f"Confluence: {', '.join(trade['confluence_factors'])}")

In [ ]:
def full_analysis_with_oil_context(trade, oil_start, oil_end, oil_minutes):
    score = 0

    # Base quality
    if trade.get("quality") == "A":
        score += 3
    elif trade.get("quality") == "B":
        score += 2
    else:
        score += 1

    # Direction + structure
    if trade.get("htf_bias") == "bullish" and trade.get("reaction") in ["break_hold", "reclaim"]:
        score += 2
    if trade.get("htf_bias") == "bearish" and trade.get("reaction") in ["break_hold", "rejection"]:
        score += 2

    if trade.get("mtf_structure") in ["higher_highs", "lower_lows"]:
        score += 2

    if trade.get("position_vs_vwap") == "above" and trade.get("htf_bias") == "bullish":
        score += 2
    if trade.get("position_vs_vwap") == "below" and trade.get("htf_bias") == "bearish":
        score += 2

    # Test count
    if trade.get("test_number") == "first":
        score += 3
    elif trade.get("test_number") == "second":
        score += 1
    elif trade.get("test_number") == "late_cycle_continuation":
        score += 0

    # Confluence
    score += min(len(trade.get("confluence_factors", [])), 3)

    # Best session windows
    if trade.get("session_phase") in ["open", "power_hour"]:
        score += 2

    # Oil context
    oil_shock = detect_oil_shock(oil_start, oil_end, oil_minutes)
    oil_context = oil_to_qqq_context(oil_shock)
    score += oil_context["qqq_bias_boost"]

    # Mistakes + timing penalties
    mgmt_penalty, mgmt_notes = management_penalty(trade)
    score -= mgmt_penalty

    if trade.get("mistake_tag") == "late_entry":
        score -= 1
    if trade.get("mistake_tag") == "chasing":
        score -= 2
    if trade.get("mistake_tag") == "overtrade":
        score -= 2

    # Grade bands
    if score >= 12:
        grade = "A"
        win_probability = 80
    elif score >= 8:
        grade = "B+"
        win_probability = 68
    elif score >= 5:
        grade = "B"
        win_probability = 58
    else:
        grade = "C"
        win_probability = 45

    summary = (
        f"{trade.get('symbol')} {trade.get('direction')} setup | "
        f"reaction={trade.get('reaction')} | "
        f"level={trade.get('level')} | "
        f"session={trade.get('session_phase')} | "
        f"grade={grade}"
    )

    return {
        "symbol": trade.get("symbol"),
        "asset_type": trade.get("asset_type"),
        "score": score,
        "grade": grade,
        "win_probability": win_probability,
        "summary": summary,
        "oil_shock": oil_shock,
        "oil_context": oil_context,
        "management_notes": mgmt_notes,
        "trade": trade
    }

In [ ]:
def management_penalty(trade):
    penalty = 0
    notes = []

    if trade.get("session_phase") == "late_morning":
        penalty += 1
        notes.append("Late-morning continuation risk")

    if trade.get("rsi_state") == "elevated":
        penalty += 1
        notes.append("RSI elevated")

    if trade.get("macd_state") == "mature_bullish":
        penalty += 1
        notes.append("MACD mature, not fresh")

    if trade.get("bollinger_context") == "near_upper_band":
        penalty += 1
        notes.append("Price extended near upper band")

    if trade.get("trade_management_mistake") == "failed_to_sell_into_resistance":
        penalty += 2
        notes.append("Failed to sell into known resistance cluster")

    return penalty, notes

In [ ]:
def oil_to_qqq_context(oil_shock_info):
    if not oil_shock_info["oil_shock"]:
        return {
            "qqq_bias_boost": 0,
            "macro_context": "normal",
            "macro_note": "No abnormal oil shock detected."
        }

    if oil_shock_info["shock_direction"] == "down":
        return {
            "qqq_bias_boost": 3 if oil_shock_info["shock_strength"] == "extreme" else 2,
            "macro_context": "bullish_for_qqq",
            "macro_note": "Fast downside oil shock supports upside impulse in QQQ."
        }

    if oil_shock_info["shock_direction"] == "up":
        return {
            "qqq_bias_boost": -3 if oil_shock_info["shock_strength"] == "extreme" else -2,
            "macro_context": "bearish_for_qqq",
            "macro_note": "Fast upside oil shock pressures QQQ."
        }

    return {
        "qqq_bias_boost": 0,
        "macro_context": "neutral",
        "macro_note": "Oil move did not add directional context."
    }

In [ ]:
def detect_oil_shock(start_price, end_price, minutes, shock_threshold_pct=2.5):
    if start_price <= 0 or minutes <= 0:
        return {
            "oil_shock": False,
            "pct_change": 0.0,
            "velocity_per_min": 0.0,
            "shock_direction": "none",
            "shock_strength": "none"
        }

    pct_change = ((end_price - start_price) / start_price) * 100
    velocity_per_min = pct_change / minutes

    oil_shock = minutes <= 20 and abs(pct_change) >= shock_threshold_pct

    if pct_change < 0:
        shock_direction = "down"
    elif pct_change > 0:
        shock_direction = "up"
    else:
        shock_direction = "flat"

    if abs(pct_change) >= 4:
        shock_strength = "extreme"
    elif abs(pct_change) >= 2.5:
        shock_strength = "strong"
    elif abs(pct_change) >= 1.0:
        shock_strength = "moderate"
    else:
        shock_strength = "light"

    return {
        "oil_shock": oil_shock,
        "pct_change": round(pct_change, 2),
        "velocity_per_min": round(velocity_per_min, 3),
        "shock_direction": shock_direction,
        "shock_strength": shock_strength
    }

In [ ]:
def get_asset_type(symbol):
    if symbol in ["SPY", "QQQ", "IWM", "DIA"]:
        return "index"
    elif symbol in ["AAPL", "TSLA", "META", "NVDA"]:
        return "stock"
    elif symbol in ["CL", "USO", "WTI", "BRENT", "OIL"]:
        return "oil"
    else:
        return "unknown"

In [ ]:
show_dashboard()

--- TRADE DASHBOARD ---

  symbol  score grade  win_prob session htf_bias    reaction quality  \
0    QQQ     14     A        78    late  bullish  break_hold       A

  oil_trend mistake  confluence_count
0      down    none                 2

Average Score: 14.0
Win Prob Avg: 78.0

By Session:
session
late    14.0
Name: score, dtype: float64

By HTF Bias:
htf_bias
bullish    14.0
Name: score, dtype: float64

Mistake Impact:
mistake
none    14.0
Name: score, dtype: float64

In [ ]:
def show_dashboard():
    df = pd.DataFrame(trade_log)

    print("\n--- TRADE DASHBOARD ---\n")
    print(df)

    print("\nAverage Score:", df["score"].mean())
    print("Win Prob Avg:", df["win_prob"].mean())

    print("\nBy Session:")
    print(df.groupby("session")["score"].mean())

    print("\nBy HTF Bias:")
    print(df.groupby("htf_bias")["score"].mean())

    print("\nMistake Impact:")
    print(df.groupby("mistake")["score"].mean())

In [ ]:
log_trade(result)

In [ ]:
print_trade_result(result)

TRADE REVIEW
----------------------------------------
Symbol: QQQ
Asset Type: index
Score: 14
Grade: A
Win Probability: 78%
Summary: QQQ expansion breakout setup with break_hold at resistance | HTF bias: bullish | Session: late
----------------------------------------
DETAILS
Level: resistance
Reaction: break_hold
VWAP: above
HTF Bias: bullish
MTF Structure: higher_highs
Session: late
Quality: A
Oil Trend: down
Mistake Tag: none
Confluence: breakout, macro_alignment

In [ ]:
import pandas as pd

trade_log = []

def log_trade(result):
    trade = result["trade"]

    entry = {
        "symbol": result["symbol"],
        "score": result["score"],
        "grade": result["grade"],
        "win_prob": result["win_probability"],
        "session": trade["session"],
        "htf_bias": trade["htf_bias"],
        "reaction": trade["reaction"],
        "quality": trade["quality"],
        "oil_trend": trade["oil_trend"],
        "mistake": trade["mistake_tag"],
        "confluence_count": len(trade["confluence_factors"])
    }

    trade_log.append(entry)

In [ ]:
result = quick_run(
    "QQQ",
    "resistance",
    "break_hold",
    "above",
    63,
    "high",
    "clean",
    "first",
    "QQQ after-hours break",
    timeframe="5m",
    htf_bias="bullish",
    mtf_structure="higher_highs",
    session="late",
    volatility="medium",
    move_type="expansion breakout",
    quality="A",
    oil_trend="down",
    oil_volatility="low",
    macro_event="none",
    market_sentiment="risk_on",
    sector_strength="strong",
    trade_window="off_hours",
    environment="trend_day",
    stop_type="below_structure",
    execution_discipline="medium",
    mistake_tag="none",
    confluence_factors=["breakout", "macro_alignment"]
)

print_trade_result(result)

TRADE REVIEW
----------------------------------------
Symbol: QQQ
Asset Type: index
Score: 14
Grade: A
Win Probability: 78%
Summary: QQQ expansion breakout setup with break_hold at resistance | HTF bias: bullish | Session: late
----------------------------------------
DETAILS
Level: resistance
Reaction: break_hold
VWAP: above
HTF Bias: bullish
MTF Structure: higher_highs
Session: late
Quality: A
Oil Trend: down
Mistake Tag: none
Confluence: breakout, macro_alignment

In [ ]:
def print_trade_result(result):
    print("TRADE REVIEW")
    print("-" * 40)
    print(f"Symbol: {result['symbol']}")
    print(f"Asset Type: {result['asset_type']}")
    print(f"Score: {result['score']}")
    print(f"Grade: {result['grade']}")
    print(f"Win Probability: {result['win_probability']}%")
    print(f"Summary: {result['summary']}")
    print("-" * 40)

    trade = result["trade"]
    print("DETAILS")
    print(f"Level: {trade['level']}")
    print(f"Reaction: {trade['reaction']}")
    print(f"VWAP: {trade['vwap']}")
    print(f"HTF Bias: {trade['htf_bias']}")
    print(f"MTF Structure: {trade['mtf_structure']}")
    print(f"Session: {trade['session']}")
    print(f"Quality: {trade['quality']}")
    print(f"Oil Trend: {trade['oil_trend']}")
    print(f"Mistake Tag: {trade['mistake_tag']}")
    print(f"Confluence: {', '.join(trade['confluence_factors'])}")

In [ ]:
quick_run(
    "QQQ",
    "resistance",
    "break_hold",
    "above",
    63,
    "high",
    "clean",
    "first",
    "QQQ after-hours break",
    timeframe="5m",
    htf_bias="bullish",
    mtf_structure="higher_highs",
    session="late",
    volatility="medium",
    move_type="expansion breakout",
    quality="A",
    oil_trend="down",
    oil_volatility="low",
    macro_event="none",
    market_sentiment="risk_on",
    sector_strength="strong",
    trade_window="off_hours",
    environment="trend_day",
    stop_type="below_structure",
    execution_discipline="medium",
    mistake_tag="none",
    confluence_factors=["breakout", "macro_alignment"]
)

{'symbol': 'QQQ',
 'asset_type': 'index',
 'score': 14,
 'grade': 'A',
 'win_probability': 78,
 'summary': 'QQQ expansion breakout setup with break_hold at resistance | HTF bias: bullish | Session: late',
 'trade': {'symbol': 'QQQ',
  'asset_type': 'index',
  'level': 'resistance',
  'reaction': 'break_hold',
  'vwap': 'above',
  'rsi': 63,
  'volume': 'high',
  'market': 'clean',
  'test': 'first',
  'key_level': 'QQQ after-hours break',
  'timeframe': '5m',
  'htf_bias': 'bullish',
  'mtf_structure': 'higher_highs',
  'session': 'late',
  'volatility': 'medium',
  'quality': 'A',
  'move_type': 'expansion breakout',
  'oil_trend': 'down',
  'oil_volatility': 'low',
  'macro_event': 'none',
  'market_sentiment': 'risk_on',
  'sector_strength': 'strong',
  'trade_window': 'off_hours',
  'environment': 'trend_day',
  'stop_type': 'below_structure',
  'execution_discipline': 'medium',
  'mistake_tag': 'none',
  'confluence_factors': ['breakout', 'macro_alignment']}}

In [ ]:
def full_analysis(trade):
    score = 0

    # Quality
    if trade.get("quality") == "A":
        score += 3
    elif trade.get("quality") == "B":
        score += 2
    else:
        score += 1

    # HTF + reaction alignment
    if trade.get("htf_bias") == "bullish" and trade.get("reaction") in ["break_hold", "reclaim"]:
        score += 2
    if trade.get("htf_bias") == "bearish" and trade.get("reaction") in ["break_hold", "rejection"]:
        score += 2

    # Structure
    if trade.get("mtf_structure") in ["higher_highs", "lower_lows"]:
        score += 2

    # First test matters more
    if trade.get("test") == "first":
        score += 3
    elif trade.get("test") == "second":
        score += 1

    # Confluence
    confluence = trade.get("confluence_factors", [])
    score += min(len(confluence), 3)

    # Session weighting
    if trade.get("session") in ["open", "power_hour"]:
        score += 2

    # Volatility
    if trade.get("volatility") == "high":
        score += 1

    # Execution
    if trade.get("execution_discipline") == "high":
        score += 1

    # Oil alignment
    if trade.get("htf_bias") == "bullish" and trade.get("oil_trend") == "down":
        score += 2
    if trade.get("htf_bias") == "bearish" and trade.get("oil_trend") == "up":
        score += 2

    # Mistakes subtract
    if trade.get("mistake_tag") == "late_entry":
        score -= 1
    if trade.get("mistake_tag") == "chasing":
        score -= 2
    if trade.get("mistake_tag") == "overtrade":
        score -= 2

    # Grade
    if score >= 10:
        grade = "A"
        win_probability = 78
    elif score >= 7:
        grade = "B"
        win_probability = 63
    else:
        grade = "C"
        win_probability = 46

    # Summary
    summary = (
        f"{trade.get('symbol')} {trade.get('move_type')} setup with "
        f"{trade.get('reaction')} at {trade.get('level')} | "
        f"HTF bias: {trade.get('htf_bias')} | "
        f"Session: {trade.get('session')}"
    )

    return {
        "symbol": trade.get("symbol"),
        "asset_type": trade.get("asset_type"),
        "score": score,
        "grade": grade,
        "win_probability": win_probability,
        "summary": summary,
        "trade": trade,
    }

In [ ]:
quick_run(
    "QQQ",
    "resistance",
    "break_hold",
    "above",
    63,
    "high",
    "clean",
    "first",
    "QQQ after-hours break",
    timeframe="5m",
    htf_bias="bullish",
    mtf_structure="higher_highs",
    session="late",
    volatility="medium",
    move_type="expansion breakout",
    quality="A",
    oil_trend="down",
    oil_volatility="low",
    macro_event="none",
    market_sentiment="risk_on",
    sector_strength="strong",
    trade_window="off_hours",
    environment="trend_day",
    stop_type="below_structure",
    execution_discipline="medium",
    mistake_tag="none",
    confluence_factors=["breakout", "macro_alignment"]
)

NameError: name 'full_analysis' is not defined

In [ ]:
def get_asset_type(symbol):
    if symbol in ["SPY", "QQQ", "IWM", "DIA"]:
        return "index"
    elif symbol in ["AAPL", "TSLA", "META", "NVDA"]:
        return "stock"
    elif symbol in ["CL", "USO"]:
        return "oil"
    else:
        return "unknown"

In [ ]:
quick_run(
    "QQQ",
    "resistance",
    "break_hold",
    "above",
    63,
    "high",
    "clean",
    "first",
    "QQQ after-hours break",
    timeframe="5m",
    htf_bias="bullish",
    mtf_structure="higher_highs",
    session="late",
    volatility="medium",
    move_type="expansion breakout",
    quality="A",
    oil_trend="down",
    oil_volatility="low",
    macro_event="none",
    market_sentiment="risk_on",
    sector_strength="strong",
    trade_window="off_hours",
    environment="trend_day",
    stop_type="below_structure",
    execution_discipline="medium",
    mistake_tag="none",
    confluence_factors=["breakout", "macro_alignment"]
)

NameError: name 'get_asset_type' is not defined

In [ ]:
quick_run(
    "QQQ",
    "resistance",
    "break_hold",
    "above",
    63,
    "high",
    "clean",
    "first",
    "QQQ after-hours break",
    timeframe="5m",
    htf_bias="bullish",
    mtf_structure="higher_highs",
    session="late",
    volatility="medium",
    move_type="expansion breakout",
    quality="A",
    oil_trend="down",
    oil_volatility="low",
    macro_event="none",
    market_sentiment="risk_on",
    sector_strength="strong",
    trade_window="off_hours",
    environment="trend_day",
    stop_type="below_structure",
    execution_discipline="medium",
    mistake_tag="none",
    confluence_factors=["breakout", "macro_alignment"]
)

{'symbol': 'QQQ',
 'asset_type': 'index',
 'setup_grade': 'A',
 'score': 9,
 'summary': 'QQQ expansion breakout setup with break_hold at resistance',
 'bias': 'bullish',
 'structure': 'higher_highs',
 'session': 'late',
 'quality': 'A',
 'confluence_factors': ['breakout', 'macro_alignment'],
 'raw_trade': {'symbol': 'QQQ',
  'asset_type': 'index',
  'level': 'resistance',
  'reaction': 'break_hold',
  'vwap': 'above',
  'rsi': 63,
  'volume': 'high',
  'market': 'clean',
  'test': 'first',
  'key_level': 'QQQ after-hours break',
  'timeframe': '5m',
  'htf_bias': 'bullish',
  'mtf_structure': 'higher_highs',
  'session': 'late',
  'volatility': 'medium',
  'quality': 'A',
  'move_type': 'expansion breakout',
  'oil_trend': 'down',
  'oil_volatility': 'low',
  'macro_event': 'none',
  'market_sentiment': 'risk_on',
  'sector_strength': 'strong',
  'trade_window': 'off_hours',
  'environment': 'trend_day',
  'stop_type': 'below_structure',
  'execution_discipline': 'medium',
  'mistake_tag': 'none',
  'confluence_factors': ['breakout', 'macro_alignment']}}

In [ ]:
def full_analysis(trade):
    score = 0

    if trade.get("quality") == "A":
        score += 3
    elif trade.get("quality") == "B":
        score += 2
    else:
        score += 1

    if trade.get("htf_bias") == "bullish" and trade.get("reaction") in ["break_hold", "reclaim"]:
        score += 2

    if trade.get("mtf_structure") in ["higher_highs", "lower_lows"]:
        score += 2

    if trade.get("confluence_factors"):
        score += len(trade["confluence_factors"])

    setup_grade = "A" if score >= 8 else "B" if score >= 5 else "C"

    return {
        "symbol": trade.get("symbol"),
        "asset_type": trade.get("asset_type"),
        "setup_grade": setup_grade,
        "score": score,
        "summary": f"{trade.get('symbol')} {trade.get('move_type')} setup with {trade.get('reaction')} at {trade.get('level')}",
        "bias": trade.get("htf_bias"),
        "structure": trade.get("mtf_structure"),
        "session": trade.get("session"),
        "quality": trade.get("quality"),
        "confluence_factors": trade.get("confluence_factors", []),
        "raw_trade": trade,
    }

In [ ]:
def get_asset_type(symbol):
    if symbol in ["SPY", "QQQ", "IWM"]:
        return "index"
    elif symbol in ["AAPL", "TSLA", "META", "NVDA"]:
        return "stock"
    elif symbol in ["BTC", "ETH"]:
        return "crypto"
    elif symbol in ["CL", "USO", "OIL"]:
        return "commodity"
    else:
        return "unknown"

In [ ]:
quick_run(
    "QQQ",
    "resistance",
    "break_hold",
    "above",
    63,
    "high",
    "clean",
    "first",
    "QQQ after-hours break",
    timeframe="5m",
    htf_bias="bullish",
    mtf_structure="higher_highs",
    session="late",
    volatility="medium",
    move_type="expansion breakout",
    quality="A",
    oil_trend="down",
    oil_volatility="low",
    macro_event="none",
    market_sentiment="risk_on",
    sector_strength="strong",
    trade_window="off_hours",
    environment="trend_day",
    stop_type="below_structure",
    execution_discipline="medium",
    mistake_tag="none",
    confluence_factors=["breakout", "macro_alignment"]
)

NameError: name 'full_analysis' is not defined

In [ ]:
quick_run(
    "QQQ",
    "support",
    "retest_hold",
    "above",
    58,
    "high",
    "clean",
    "first",
    "QQQ intraday support",
    timeframe="5m",
    htf_bias="bullish",
    mtf_structure="higher_lows",
    session="midday",
    volatility="medium",
    move_type="trend continuation",
    quality="A",
    oil_trend="flat",
    oil_volatility="low",
    macro_event="none",
    market_sentiment="neutral",
    sector_strength="strong",
    trade_window="priority_midday",
    environment="trend_day",
    stop_type="below_vwap",
    execution_discipline="high",
    mistake_tag="none",
    confluence_factors=["vwap_hold", "higher_lows"]
)

=== FULL ANALYSIS ===

--- FINAL OUTPUT ---
BIAS : CALL
SETUP_TYPE : Retest Hold
GRADE : A+
KEY_LEVEL : QQQ intraday support
ENTRY_TRIGGER : Retest bounce confirms
INVALIDATION : Loss of support / retest low
TARGETS : Next resistance / next key level
CONFIDENCE : 100
REASONS : ['Retest held at support', 'Bullish VWAP control', 'Bullish momentum', 'Volume confirmation', 'First test of level', 'Higher timeframe bullish bias', 'Bullish multi-timeframe structure']
RISKS : []
FINAL_DECISION : CALL

PATTERN MATCH:
MATCHED SETUP: hood_call_a1
CATEGORY: A_plus
MATCH SCORE: 9

=== PERFORMANCE TRACKING ===

A_plus
Wins: 1
Losses: 0
Win Rate: 100.0 %

B_setups
Wins: 0
Losses: 0
Win Rate: 0 %

No_trade
Wins: 0
Losses: 0
Win Rate: 0 %

=== ADJUSTED CONFIDENCE ===
Base Confidence: 100
Category: A_plus
Category Win Rate: 100.0
Setup Type: Retest Hold
Setup Win Rate: 100.0
Setup Sample Size: 9
Deep Pattern Signature: asset=index | timeframe=5m | htf=bullish | structure=higher_lows | session=midday | volatility=medium | move_type=trend continuation | oil=flat | oil_volatility=low | macro=none | sentiment=neutral | sector=strong | trade_window=priority_midday | environment=trend_day | stop_type=below_vwap | execution=high | mistake=none | reaction=retest_hold | vwap=above | volume=high | market=clean | test=first | level=support | confluence=vwap_hold,higher_lows
Deep Pattern Win Rate: 0
Deep Pattern Sample Size: 0
Trade Window: priority_midday
Execution Discipline: high
Environment: trend_day
Mistake Tag: none
Adjusted Confidence: 100

FINAL CONFIDENCE (ADJUSTED): 100

✅ TRADE ALLOWED

=== POSITION SIZING ===
Grade: A+
Confidence: 100
Trade Window: priority_midday
Execution Discipline: high
Mistake Tag: none
Risk Per Trade: 3.25%
Recommended Size: FULL SIZE
FINAL POSITION SIZE: FULL SIZE

In [ ]:
quick_run(
    "QQQ",
    "resistance",
    "break_hold",
    "above",
    65,
    "high",
    "clean",
    "first",
    "QQQ 500 resistance break",
    timeframe="5m",
    htf_bias="bullish",
    mtf_structure="higher_highs",
    session="open",
    volatility="high",
    move_type="expansion breakout",
    quality="A+",
    oil_trend="down",
    oil_volatility="low",
    macro_event="none",
    market_sentiment="risk_on",
    sector_strength="strong",
    trade_window="priority_morning",
    environment="trend_day",
    stop_type="below_structure",
    execution_discipline="high",
    mistake_tag="none",
    confluence_factors=["vwap_hold", "higher_highs", "macro_alignment"]
)

=== FULL ANALYSIS ===

--- FINAL OUTPUT ---
BIAS : CALL
SETUP_TYPE : Break and Hold
GRADE : A+
KEY_LEVEL : QQQ 500 resistance break
ENTRY_TRIGGER : Break above resistance holds with continuation
INVALIDATION : Loss of breakout level / loss of VWAP
TARGETS : Next resistance / extension target
CONFIDENCE : 100
REASONS : ['Break and hold above resistance', 'Bullish VWAP control', 'Bullish momentum', 'Volume confirmation', 'First test of level', 'Higher timeframe bullish bias', 'Bullish multi-timeframe structure', 'Momentum-friendly session', 'High-volatility breakout environment', 'Expansion breakout / squeeze behavior']
RISKS : []
FINAL_DECISION : CALL

PATTERN MATCH:
MATCHED SETUP: qqq_break_hold_a1
CATEGORY: A_plus
MATCH SCORE: 12

=== PERFORMANCE TRACKING ===

A_plus
Wins: 1
Losses: 0
Win Rate: 100.0 %

B_setups
Wins: 0
Losses: 0
Win Rate: 0 %

No_trade
Wins: 0
Losses: 0
Win Rate: 0 %

=== ADJUSTED CONFIDENCE ===
Base Confidence: 100
Category: A_plus
Category Win Rate: 100.0
Setup Type: Break and Hold
Setup Win Rate: 100.0
Setup Sample Size: 3
Deep Pattern Signature: asset=index | timeframe=5m | htf=bullish | structure=higher_highs | session=open | volatility=high | move_type=expansion breakout | oil=down | oil_volatility=low | macro=none | sentiment=risk_on | sector=strong | trade_window=priority_morning | environment=trend_day | stop_type=below_structure | execution=high | mistake=none | reaction=break_hold | vwap=above | volume=high | market=clean | test=first | level=resistance | confluence=vwap_hold,higher_highs,macro_alignment
Deep Pattern Win Rate: 0
Deep Pattern Sample Size: 0
Trade Window: priority_morning
Execution Discipline: high
Environment: trend_day
Mistake Tag: none
Adjusted Confidence: 100

FINAL CONFIDENCE (ADJUSTED): 100

✅ TRADE ALLOWED

=== POSITION SIZING ===
Grade: A+
Confidence: 100
Trade Window: priority_morning
Execution Discipline: high
Mistake Tag: none
Risk Per Trade: 3.75%
Recommended Size: FULL SIZE
FINAL POSITION SIZE: FULL SIZE

In [ ]:
quick_run(
    "QQQ",
    "resistance",
    "break_hold",
    "above",
    65,
    "high",
    "clean",
    "first",
    "QQQ 500 resistance break",
    timeframe="5m",
    htf_bias="bullish",
    mtf_structure="higher_highs",
    session="open",
    volatility="high",
    move_type="expansion breakout",
    quality="A+",
    oil_trend="down",
    oil_volatility="low",
    macro_event="none",
    market_sentiment="risk_on",
    sector_strength="strong",
    trade_window="priority_morning",
    environment="trend_day",
    stop_type="below_structure",
    execution_discipline="high",
    mistake_tag="none",
    confluence_factors=["vwap_hold", "higher_highs", "macro_alignment"]
)

=== FULL ANALYSIS ===

=== BEST MATCH ===
NAME: qqq_break_hold_a1
CATEGORY: A_plus
MATCH SCORE: 12

--- FINAL OUTPUT ---
BIAS : CALL
SETUP_TYPE : Break and Hold
GRADE : A+
KEY_LEVEL : QQQ 500 resistance break
ENTRY_TRIGGER : Break above resistance holds with continuation
INVALIDATION : Loss of breakout level / loss of VWAP
TARGETS : Next resistance / extension target
CONFIDENCE : 100
REASONS : ['Break and hold above resistance', 'Bullish VWAP control', 'Bullish momentum', 'Volume confirmation', 'First test of level', 'Higher timeframe bullish bias', 'Bullish multi-timeframe structure', 'Momentum-friendly session', 'High-volatility breakout environment', 'Expansion breakout / squeeze behavior']
RISKS : []
FINAL_DECISION : CALL

PATTERN MATCH:
MATCHED SETUP: qqq_break_hold_a1
CATEGORY: A_plus
MATCH SCORE: 12

=== PERFORMANCE TRACKING ===

A_plus
Wins: 1
Losses: 0
Win Rate: 100.0 %

B_setups
Wins: 0
Losses: 0
Win Rate: 0 %

No_trade
Wins: 0
Losses: 0
Win Rate: 0 %

=== ADJUSTED CONFIDENCE ===
Base Confidence: 100
Category: A_plus
Category Win Rate: 100.0
Setup Type: Break and Hold
Setup Win Rate: 100.0
Setup Sample Size: 3
Deep Pattern Signature: asset=index | timeframe=5m | htf=bullish | structure=higher_highs | session=open | volatility=high | move_type=expansion breakout | oil=down | oil_volatility=low | macro=none | sentiment=risk_on | sector=strong | trade_window=priority_morning | environment=trend_day | stop_type=below_structure | execution=high | mistake=none | reaction=break_hold | vwap=above | volume=high | market=clean | test=first | level=resistance | confluence=vwap_hold,higher_highs,macro_alignment
Deep Pattern Win Rate: 0
Deep Pattern Sample Size: 0
Adjusted Confidence: 100

FINAL CONFIDENCE (ADJUSTED): 100

✅ TRADE ALLOWED

=== POSITION SIZING ===
Grade: A+
Confidence: 100
Risk Per Trade: 3%
Recommended Size: FULL SIZE
FINAL POSITION SIZE: FULL SIZE

In [ ]:
backfill_one_line(
    symbol="AMZN",
    level="support",
    reaction="retest_hold",
    vwap="above",
    rsi=62,
    volume="expansion",
    market="trend",
    test="first",
    key_level="trend pullback continuation",
    result_text="win",
    pnl=140,
    notes="Strong trend continuation, pullback held, volume confirmed expansion",
    timeframe="5m",
    htf_bias="bullish",
    mtf_structure="higher_lows",
    session="intraday",
    volatility="controlled_expansion",
    move_type="trend_continuation",
    quality="A+",
    macro_event="AI_infrastructure_rotation",
    market_sentiment="risk_on",
    sector_strength="tech_leading"
)

=== PERFORMANCE TRACKING ===

A_plus
Wins: 1
Losses: 0
Win Rate: 100.0 %

B_setups
Wins: 0
Losses: 0
Win Rate: 0 %

No_trade
Wins: 0
Losses: 0
Win Rate: 0 %

=== ADJUSTED CONFIDENCE ===
Base Confidence: 80
Category: A_plus
Category Win Rate: 100.0
Setup Type: Retest Hold
Setup Win Rate: 100.0
Setup Sample Size: 8
Deep Pattern Signature: asset=stock | timeframe=5m | htf=bullish | structure=higher_lows | session=intraday | volatility=controlled_expansion | move_type=trend_continuation | oil=unknown | oil_volatility=unknown | macro=AI_infrastructure_rotation | sentiment=risk_on | sector=tech_leading | dark_pool_bias=unknown | dark_pool_level=unknown | dark_pool_size=unknown | reaction=retest_hold | vwap=above | volume=expansion | market=trend | test=first | level=support
Deep Pattern Win Rate: 0
Deep Pattern Sample Size: 0
Adjusted Confidence: 100

=== POSITION SIZING ===
Grade: B
Confidence: 100
Risk Per Trade: 1%
Recommended Size: SMALL SIZE
✅ Trade logged and saved

{'timestamp': '2026-04-13T00:25:49',
 'symbol': 'AMZN',
 'bias': 'CALL',
 'setup_type': 'Retest Hold',
 'grade': 'B',
 'key_level': 'trend pullback continuation',
 'adjusted_confidence': 100,
 'position_size': 'SMALL SIZE',
 'result': 'win',
 'pnl': 140,
 'notes': 'Strong trend continuation, pullback held, volume confirmed expansion',
 'trade_input': {'symbol': 'AMZN',
  'asset_type': 'stock',
  'level': 'support',
  'reaction': 'retest_hold',
  'vwap': 'above',
  'rsi': 62,
  'volume': 'expansion',
  'market': 'trend',
  'test': 'first',
  'key_level': 'trend pullback continuation',
  'timeframe': '5m',
  'htf_bias': 'bullish',
  'mtf_structure': 'higher_lows',
  'session': 'intraday',
  'volatility': 'controlled_expansion',
  'quality': 'A+',
  'move_type': 'trend_continuation',
  'oil_trend': 'unknown',
  'oil_volatility': 'unknown',
  'macro_event': 'AI_infrastructure_rotation',
  'market_sentiment': 'risk_on',
  'sector_strength': 'tech_leading',
  'dark_pool_bias': 'unknown',
  'dark_pool_level': 'unknown',
  'dark_pool_size': 'unknown'},
 'pattern_signature': 'asset=stock | timeframe=5m | htf=bullish | structure=higher_lows | session=intraday | volatility=controlled_expansion | move_type=trend_continuation | oil=unknown | oil_volatility=unknown | macro=AI_infrastructure_rotation | sentiment=risk_on | sector=tech_leading | dark_pool_bias=unknown | dark_pool_level=unknown | dark_pool_size=unknown | reaction=retest_hold | vwap=above | volume=expansion | market=trend | test=first | level=support'}

In [ ]:
backfill_one_line(
    symbol="AMZN",
    level="support",
    reaction="retest_hold",
    vwap="above",
    rsi=62,
    volume="expansion",
    market="trend",
    test="first",
    key_level="trend pullback continuation",

    timeframe="5m",
    htf_bias="bullish",
    mtf_structure="higher_lows",
    session="intraday",
    volatility="controlled_expansion",
    move_type="trend continuation",
    quality="A+",

    macro_event="AI_infrastructure_rotation",
    market_sentiment="risk_on",
    sector_strength="tech_leading",

    result_text="WIN - strong trend continuation, pullback held, volume confirmed expansion",
    pnl=140
)

=== PERFORMANCE TRACKING ===

A_plus
Wins: 1
Losses: 0
Win Rate: 100.0 %

B_setups
Wins: 0
Losses: 0
Win Rate: 0 %

No_trade
Wins: 0
Losses: 0
Win Rate: 0 %

=== ADJUSTED CONFIDENCE ===
Base Confidence: 80
Category: A_plus
Category Win Rate: 100.0
Setup Type: Retest Hold
Setup Win Rate: 100.0
Setup Sample Size: 8
Deep Pattern Signature: asset=stock | timeframe=5m | htf=bullish | structure=higher_lows | session=intraday | volatility=controlled_expansion | move_type=trend continuation | oil=unknown | oil_volatility=unknown | macro=AI_infrastructure_rotation | sentiment=risk_on | sector=tech_leading | dark_pool_bias=unknown | dark_pool_level=unknown | dark_pool_size=unknown | reaction=retest_hold | vwap=above | volume=expansion | market=trend | test=first | level=support
Deep Pattern Win Rate: 0
Deep Pattern Sample Size: 0
Adjusted Confidence: 100

=== POSITION SIZING ===
Grade: B
Confidence: 100
Risk Per Trade: 1%
Recommended Size: SMALL SIZE
✅ Trade logged and saved

{'timestamp': '2026-04-13T00:19:29',
 'symbol': 'AMZN',
 'bias': 'CALL',
 'setup_type': 'Retest Hold',
 'grade': 'B',
 'key_level': 'trend pullback continuation',
 'adjusted_confidence': 100,
 'position_size': 'SMALL SIZE',
 'result': 'WIN - strong trend continuation, pullback held, volume confirmed expansion',
 'pnl': 140,
 'notes': '',
 'trade_input': {'symbol': 'AMZN',
  'asset_type': 'stock',
  'level': 'support',
  'reaction': 'retest_hold',
  'vwap': 'above',
  'rsi': 62,
  'volume': 'expansion',
  'market': 'trend',
  'test': 'first',
  'key_level': 'trend pullback continuation',
  'timeframe': '5m',
  'htf_bias': 'bullish',
  'mtf_structure': 'higher_lows',
  'session': 'intraday',
  'volatility': 'controlled_expansion',
  'quality': 'A+',
  'move_type': 'trend continuation',
  'oil_trend': 'unknown',
  'oil_volatility': 'unknown',
  'macro_event': 'AI_infrastructure_rotation',
  'market_sentiment': 'risk_on',
  'sector_strength': 'tech_leading',
  'dark_pool_bias': 'unknown',
  'dark_pool_level': 'unknown',
  'dark_pool_size': 'unknown'},
 'pattern_signature': 'asset=stock | timeframe=5m | htf=bullish | structure=higher_lows | session=intraday | volatility=controlled_expansion | move_type=trend continuation | oil=unknown | oil_volatility=unknown | macro=AI_infrastructure_rotation | sentiment=risk_on | sector=tech_leading | dark_pool_bias=unknown | dark_pool_level=unknown | dark_pool_size=unknown | reaction=retest_hold | vwap=above | volume=expansion | market=trend | test=first | level=support'}

In [ ]:
learned_pattern_breakdown()
journal_summary()
setup_breakdown()

=== DEEP PATTERN STATS ===

asset=unknown | timeframe=unknown | htf=unknown | structure=unknown | session=unknown | volatility=unknown | move_type=unknown | reaction=unknown | vwap=unknown | volume=unknown | market=unknown | test=unknown | level=unknown
Wins: 2
Losses: 0
Win Rate: 100.0 %
Sample Size: 2
PnL: 491.0

asset=unknown | timeframe=5m | htf=unknown | structure=unknown | session=open | volatility=medium | move_type=unknown | reaction=retest_hold | vwap=above | volume=high | market=clean | test=first | level=support
Wins: 3
Losses: 0
Win Rate: 100.0 %
Sample Size: 3
PnL: 625.5

asset=unknown | timeframe=5m | htf=unknown | structure=unknown | session=open | volatility=medium | move_type=unknown | reaction=retest_hold | vwap=above | volume=low | market=clean | test=second | level=support
Wins: 0
Losses: 1
Win Rate: 0.0 %
Sample Size: 1
PnL: -95.0

asset=stock | timeframe=5m | htf=bullish | structure=higher_lows | session=open | volatility=high | move_type=unknown | reaction=retest_hold | vwap=above | volume=high | market=clean | test=first | level=support
Wins: 2
Losses: 0
Win Rate: 100.0 %
Sample Size: 2
PnL: 360.0

asset=stock | timeframe=5m | htf=bullish | structure=higher_lows | session=open | volatility=high | move_type=unknown | reaction=retest_hold | vwap=above | volume=low | market=clean | test=second | level=support
Wins: 0
Losses: 2
Win Rate: 0.0 %
Sample Size: 2
PnL: -190.0

asset=index | timeframe=5m | htf=bearish | structure=lower_highs | session=open | volatility=medium | move_type=unknown | reaction=rejection | vwap=below | volume=high | market=clean | test=second | level=resistance
Wins: 0
Losses: 1
Win Rate: 0.0 %
Sample Size: 1
PnL: -110.0

asset=index | timeframe=5m | htf=neutral | structure=sideways | session=midday | volatility=medium | move_type=unknown | reaction=retest_hold | vwap=above | volume=low | market=chop | test=second | level=support
Wins: 0
Losses: 1
Win Rate: 0.0 %
Sample Size: 1
PnL: -40.0

asset=stock | timeframe=5m | htf=bullish | structure=higher_highs | session=open | volatility=high | move_type=unknown | reaction=break_hold | vwap=above | volume=high | market=clean | test=first | level=resistance
Wins: 1
Losses: 0
Win Rate: 100.0 %
Sample Size: 1
PnL: 10448.59

asset=stock | timeframe=5m | htf=bullish | structure=higher_highs | session=open | volatility=high | move_type=expansion breakout | reaction=break_hold | vwap=above | volume=high | market=clean | test=first | level=resistance
Wins: 2
Losses: 0
Win Rate: 100.0 %
Sample Size: 2
PnL: 20897.18

asset=index | timeframe=5m | htf=bullish | structure=higher_lows | session=midday | volatility=increasing | move_type=expansion breakout | reaction=reclaim | vwap=above | volume=building | market=transition | test=first | level=support
Wins: 2
Losses: 0
Win Rate: 100.0 %
Sample Size: 2
PnL: 3100.0

asset=index | timeframe=5m | htf=bullish | structure=higher_lows | session=midday | volatility=high | move_type=expansion breakout | reaction=retest_hold | vwap=above | volume=high | market=clean | test=first | level=support
Wins: 1
Losses: 0
Win Rate: 100.0 %
Sample Size: 1
PnL: 1550.0

asset=index | timeframe=5m | htf=neutral | structure=sideways | session=midday | volatility=medium | move_type=failed breakdown | reaction=rejection | vwap=below | volume=low | market=chop | test=second | level=resistance
Wins: 0
Losses: 1
Win Rate: 0.0 %
Sample Size: 1
PnL: -153.0

=== JOURNAL SUMMARY ===
Total Trades: 19
Wins: 13
Losses: 6
Breakevens: 0
Win Rate: 68.42 %
Total PnL: 36884.270000000004

=== SETUP BREAKDOWN ===

Retest Hold
Wins: 8
Losses: 0
Breakevens: 0
Win Rate: 100.0 %
PnL: 3026.5

No Trade
Wins: 0
Losses: 5
Breakevens: 0
Win Rate: 0.0 %
PnL: -478.0

Rejection
Wins: 0
Losses: 1
Breakevens: 0
Win Rate: 0.0 %
PnL: -110.0

Break and Hold
Wins: 3
Losses: 0
Breakevens: 0
Win Rate: 100.0 %
PnL: 31345.77

None
Wins: 2
Losses: 0
Breakevens: 0
Win Rate: 100.0 %
PnL: 3100.0

{'Retest Hold': {'wins': 8, 'losses': 0, 'breakevens': 0, 'pnl': 3026.5},
 'No Trade': {'wins': 0, 'losses': 5, 'breakevens': 0, 'pnl': -478.0},
 'Rejection': {'wins': 0, 'losses': 1, 'breakevens': 0, 'pnl': -110.0},
 'Break and Hold': {'wins': 3, 'losses': 0, 'breakevens': 0, 'pnl': 31345.77},
 'None': {'wins': 2, 'losses': 0, 'breakevens': 0, 'pnl': 3100.0}}

In [ ]:
backfill_one_line(
    "QQQ",
    "rejection",
    "resistance",
    "below",
    48,
    "low",
    "chop",
    "second",
    "QQQ consolidation chop zone before level hit",
    "loss",
    -153,
    "Entered puts inside chop/consolidation instead of waiting for level interaction. Oil had already dumped and was stabilizing, so the macro pressure was already priced in. QQQ was range-bound around VWAP with no clean breakdown, no strong volume expansion, and no real follow-through. Premature entry in dead zone.",
    timeframe="5m",
    htf_bias="neutral",
    mtf_structure="sideways",
    session="midday",
    volatility="medium",
    move_type="failed breakdown",
    quality="C",
    oil_trend="stabilizing",
    oil_volatility="moderate",
    macro_event="oil_move_already_priced_in",
    market_sentiment="neutral",
    sector_strength="tech_mixed",
    dark_pool_bias="neutral",
    dark_pool_level="no clear level respected",
    dark_pool_size="small"
)

=== PERFORMANCE TRACKING ===

A_plus
Wins: 1
Losses: 0
Win Rate: 100.0 %

B_setups
Wins: 0
Losses: 0
Win Rate: 0 %

No_trade
Wins: 0
Losses: 0
Win Rate: 0 %

=== ADJUSTED CONFIDENCE ===
Base Confidence: 20
Category: B_setups
Category Win Rate: 0
Setup Type: No Trade
Setup Win Rate: 0.0
Setup Sample Size: 4
Deep Pattern Signature: asset=index | timeframe=5m | htf=neutral | structure=sideways | session=midday | volatility=medium | move_type=failed breakdown | oil=stabilizing | oil_volatility=moderate | macro=oil_move_already_priced_in | sentiment=neutral | sector=tech_mixed | dark_pool_bias=neutral | dark_pool_level=no clear level respected | dark_pool_size=small | reaction=rejection | vwap=below | volume=low | market=chop | test=second | level=resistance
Deep Pattern Win Rate: 0
Deep Pattern Sample Size: 0
Adjusted Confidence: 0

=== POSITION SIZING ===
Grade: C
Confidence: 0
Risk Per Trade: 0%
Recommended Size: NO TRADE
✅ Trade logged and saved

{'timestamp': '2026-04-12T23:47:14',
 'symbol': 'QQQ',
 'bias': 'NO TRADE',
 'setup_type': 'No Trade',
 'grade': 'C',
 'key_level': 'QQQ consolidation chop zone before level hit',
 'adjusted_confidence': 0,
 'position_size': 'NO TRADE',
 'result': 'loss',
 'pnl': -153,
 'notes': 'Entered puts inside chop/consolidation instead of waiting for level interaction. Oil had already dumped and was stabilizing, so the macro pressure was already priced in. QQQ was range-bound around VWAP with no clean breakdown, no strong volume expansion, and no real follow-through. Premature entry in dead zone.',
 'trade_input': {'symbol': 'QQQ',
  'asset_type': 'index',
  'level': 'resistance',
  'reaction': 'rejection',
  'vwap': 'below',
  'rsi': 48,
  'volume': 'low',
  'market': 'chop',
  'test': 'second',
  'key_level': 'QQQ consolidation chop zone before level hit',
  'timeframe': '5m',
  'htf_bias': 'neutral',
  'mtf_structure': 'sideways',
  'session': 'midday',
  'volatility': 'medium',
  'quality': 'C',
  'move_type': 'failed breakdown',
  'oil_trend': 'stabilizing',
  'oil_volatility': 'moderate',
  'macro_event': 'oil_move_already_priced_in',
  'market_sentiment': 'neutral',
  'sector_strength': 'tech_mixed',
  'dark_pool_bias': 'neutral',
  'dark_pool_level': 'no clear level respected',
  'dark_pool_size': 'small'},
 'pattern_signature': 'asset=index | timeframe=5m | htf=neutral | structure=sideways | session=midday | volatility=medium | move_type=failed breakdown | oil=stabilizing | oil_volatility=moderate | macro=oil_move_already_priced_in | sentiment=neutral | sector=tech_mixed | dark_pool_bias=neutral | dark_pool_level=no clear level respected | dark_pool_size=small | reaction=rejection | vwap=below | volume=low | market=chop | test=second | level=resistance'}

In [ ]:
backfill_one_line(
    "SPY",
    "retest_hold",
    "support",
    "above",
    55,
    "high",
    "clean",
    "first",
    "VWAP reclaim + compression breakout",
    "win",
    1550,
    "Bearish open shifted into exhaustion. VWAP reclaim confirmed. Higher lows formed. Compression before breakout. Entered before expansion. Oil pressure slowed. Sold into strength near resistance.",
    timeframe="5m",
    htf_bias="bullish",
    mtf_structure="higher_lows",
    session="midday",
    volatility="high",
    move_type="expansion breakout",
    quality="A+",
    oil_trend="slowing",
    oil_volatility="moderate",
    macro_event="geopolitical_oil_spike_cooling",
    market_sentiment="risk_on_shift",
    sector_strength="tech_leading",
    dark_pool_bias="bullish",
    dark_pool_level="631.99 support cluster / 650 target cluster",
    dark_pool_size="large"
)

=== PERFORMANCE TRACKING ===

A_plus
Wins: 1
Losses: 0
Win Rate: 100.0 %

B_setups
Wins: 0
Losses: 0
Win Rate: 0 %

No_trade
Wins: 0
Losses: 0
Win Rate: 0 %

=== ADJUSTED CONFIDENCE ===
Base Confidence: 100
Category: A_plus
Category Win Rate: 100.0
Setup Type: Retest Hold
Setup Win Rate: 100.0
Setup Sample Size: 7
Deep Pattern Signature: asset=index | timeframe=5m | htf=bullish | structure=higher_lows | session=midday | volatility=high | move_type=expansion breakout | oil=slowing | oil_volatility=moderate | macro=geopolitical_oil_spike_cooling | sentiment=risk_on_shift | sector=tech_leading | dark_pool_bias=bullish | dark_pool_level=631.99 support cluster / 650 target cluster | dark_pool_size=large | reaction=retest_hold | vwap=above | volume=high | market=clean | test=first | level=support
Deep Pattern Win Rate: 0
Deep Pattern Sample Size: 0
Adjusted Confidence: 100

=== POSITION SIZING ===
Grade: A+
Confidence: 100
Risk Per Trade: 3%
Recommended Size: FULL SIZE
✅ Trade logged and saved

{'timestamp': '2026-04-12T23:29:08',
 'symbol': 'SPY',
 'bias': 'CALL',
 'setup_type': 'Retest Hold',
 'grade': 'A+',
 'key_level': 'VWAP reclaim + compression breakout',
 'adjusted_confidence': 100,
 'position_size': 'FULL SIZE',
 'result': 'win',
 'pnl': 1550,
 'notes': 'Bearish open shifted into exhaustion. VWAP reclaim confirmed. Higher lows formed. Compression before breakout. Entered before expansion. Oil pressure slowed. Sold into strength near resistance.',
 'trade_input': {'symbol': 'SPY',
  'asset_type': 'index',
  'level': 'support',
  'reaction': 'retest_hold',
  'vwap': 'above',
  'rsi': 55,
  'volume': 'high',
  'market': 'clean',
  'test': 'first',
  'key_level': 'VWAP reclaim + compression breakout',
  'timeframe': '5m',
  'htf_bias': 'bullish',
  'mtf_structure': 'higher_lows',
  'session': 'midday',
  'volatility': 'high',
  'quality': 'A+',
  'move_type': 'expansion breakout',
  'oil_trend': 'slowing',
  'oil_volatility': 'moderate',
  'macro_event': 'geopolitical_oil_spike_cooling',
  'market_sentiment': 'risk_on_shift',
  'sector_strength': 'tech_leading',
  'dark_pool_bias': 'bullish',
  'dark_pool_level': '631.99 support cluster / 650 target cluster',
  'dark_pool_size': 'large'},
 'pattern_signature': 'asset=index | timeframe=5m | htf=bullish | structure=higher_lows | session=midday | volatility=high | move_type=expansion breakout | oil=slowing | oil_volatility=moderate | macro=geopolitical_oil_spike_cooling | sentiment=risk_on_shift | sector=tech_leading | dark_pool_bias=bullish | dark_pool_level=631.99 support cluster / 650 target cluster | dark_pool_size=large | reaction=retest_hold | vwap=above | volume=high | market=clean | test=first | level=support'}

In [ ]:
backfill_one_line(
    "SPY",
    "reclaim",
    "support",
    "above",
    55,
    "building",
    "transition",
    "first",
    "VWAP reclaim + compression breakout",
    "win",
    1550,
    "Bearish open shifted into exhaustion. VWAP reclaim confirmed. Higher lows formed. Compression before breakout. Entered before expansion. Oil pressure slowed. Sold into strength near resistance.",
    timeframe="5m",
    htf_bias="bullish",
    mtf_structure="higher_lows",
    session="midday",
    volatility="increasing",
    move_type="expansion breakout",
    quality="A+",
    oil_trend="slowing",
    oil_volatility="moderate",
    macro_event="geopolitical_oil_spike_cooling",
    market_sentiment="risk_on_shift",
    sector_strength="tech_leading",
    dark_pool_bias="bullish",
    dark_pool_level="631.99 support cluster / 650 target cluster",
    dark_pool_size="large"
)

=== PERFORMANCE TRACKING ===

A_plus
Wins: 1
Losses: 0
Win Rate: 100.0 %

B_setups
Wins: 0
Losses: 0
Win Rate: 0 %

No_trade
Wins: 0
Losses: 0
Win Rate: 0 %

=== ADJUSTED CONFIDENCE ===
Base Confidence: 50
Category: A_plus
Category Win Rate: 100.0
Setup Type: None
Setup Win Rate: 100.0
Setup Sample Size: 1
Deep Pattern Signature: asset=index | timeframe=5m | htf=bullish | structure=higher_lows | session=midday | volatility=increasing | move_type=expansion breakout | oil=slowing | oil_volatility=moderate | macro=geopolitical_oil_spike_cooling | sentiment=risk_on_shift | sector=tech_leading | dark_pool_bias=bullish | dark_pool_level=631.99 support cluster / 650 target cluster | dark_pool_size=large | reaction=reclaim | vwap=above | volume=building | market=transition | test=first | level=support
Deep Pattern Win Rate: 0
Deep Pattern Sample Size: 0
Adjusted Confidence: 60

=== POSITION SIZING ===
Grade: C
Confidence: 60
Risk Per Trade: 0%
Recommended Size: NO TRADE
✅ Trade logged and saved

{'timestamp': '2026-04-12T23:26:31',
 'symbol': 'SPY',
 'bias': 'NO TRADE',
 'setup_type': 'None',
 'grade': 'C',
 'key_level': 'VWAP reclaim + compression breakout',
 'adjusted_confidence': 60,
 'position_size': 'NO TRADE',
 'result': 'win',
 'pnl': 1550,
 'notes': 'Bearish open shifted into exhaustion. VWAP reclaim confirmed. Higher lows formed. Compression before breakout. Entered before expansion. Oil pressure slowed. Sold into strength near resistance.',
 'trade_input': {'symbol': 'SPY',
  'asset_type': 'index',
  'level': 'support',
  'reaction': 'reclaim',
  'vwap': 'above',
  'rsi': 55,
  'volume': 'building',
  'market': 'transition',
  'test': 'first',
  'key_level': 'VWAP reclaim + compression breakout',
  'timeframe': '5m',
  'htf_bias': 'bullish',
  'mtf_structure': 'higher_lows',
  'session': 'midday',
  'volatility': 'increasing',
  'quality': 'A+',
  'move_type': 'expansion breakout',
  'oil_trend': 'slowing',
  'oil_volatility': 'moderate',
  'macro_event': 'geopolitical_oil_spike_cooling',
  'market_sentiment': 'risk_on_shift',
  'sector_strength': 'tech_leading',
  'dark_pool_bias': 'bullish',
  'dark_pool_level': '631.99 support cluster / 650 target cluster',
  'dark_pool_size': 'large'},
 'pattern_signature': 'asset=index | timeframe=5m | htf=bullish | structure=higher_lows | session=midday | volatility=increasing | move_type=expansion breakout | oil=slowing | oil_volatility=moderate | macro=geopolitical_oil_spike_cooling | sentiment=risk_on_shift | sector=tech_leading | dark_pool_bias=bullish | dark_pool_level=631.99 support cluster / 650 target cluster | dark_pool_size=large | reaction=reclaim | vwap=above | volume=building | market=transition | test=first | level=support'}

In [ ]:
learned_pattern_breakdown()
journal_summary()
setup_breakdown()

=== DEEP PATTERN STATS ===

asset=unknown | timeframe=unknown | htf=unknown | structure=unknown | session=unknown | volatility=unknown | move_type=unknown | reaction=unknown | vwap=unknown | volume=unknown | market=unknown | test=unknown | level=unknown
Wins: 2
Losses: 0
Win Rate: 100.0 %
Sample Size: 2
PnL: 491.0

asset=unknown | timeframe=5m | htf=unknown | structure=unknown | session=open | volatility=medium | move_type=unknown | reaction=retest_hold | vwap=above | volume=high | market=clean | test=first | level=support
Wins: 3
Losses: 0
Win Rate: 100.0 %
Sample Size: 3
PnL: 625.5

asset=unknown | timeframe=5m | htf=unknown | structure=unknown | session=open | volatility=medium | move_type=unknown | reaction=retest_hold | vwap=above | volume=low | market=clean | test=second | level=support
Wins: 0
Losses: 1
Win Rate: 0.0 %
Sample Size: 1
PnL: -95.0

asset=stock | timeframe=5m | htf=bullish | structure=higher_lows | session=open | volatility=high | move_type=unknown | reaction=retest_hold | vwap=above | volume=high | market=clean | test=first | level=support
Wins: 2
Losses: 0
Win Rate: 100.0 %
Sample Size: 2
PnL: 360.0

asset=stock | timeframe=5m | htf=bullish | structure=higher_lows | session=open | volatility=high | move_type=unknown | reaction=retest_hold | vwap=above | volume=low | market=clean | test=second | level=support
Wins: 0
Losses: 2
Win Rate: 0.0 %
Sample Size: 2
PnL: -190.0

asset=index | timeframe=5m | htf=bearish | structure=lower_highs | session=open | volatility=medium | move_type=unknown | reaction=rejection | vwap=below | volume=high | market=clean | test=second | level=resistance
Wins: 0
Losses: 1
Win Rate: 0.0 %
Sample Size: 1
PnL: -110.0

asset=index | timeframe=5m | htf=neutral | structure=sideways | session=midday | volatility=medium | move_type=unknown | reaction=retest_hold | vwap=above | volume=low | market=chop | test=second | level=support
Wins: 0
Losses: 1
Win Rate: 0.0 %
Sample Size: 1
PnL: -40.0

asset=stock | timeframe=5m | htf=bullish | structure=higher_highs | session=open | volatility=high | move_type=unknown | reaction=break_hold | vwap=above | volume=high | market=clean | test=first | level=resistance
Wins: 1
Losses: 0
Win Rate: 100.0 %
Sample Size: 1
PnL: 10448.59

asset=stock | timeframe=5m | htf=bullish | structure=higher_highs | session=open | volatility=high | move_type=expansion breakout | reaction=break_hold | vwap=above | volume=high | market=clean | test=first | level=resistance
Wins: 2
Losses: 0
Win Rate: 100.0 %
Sample Size: 2
PnL: 20897.18

asset=index | timeframe=5m | htf=bullish | structure=higher_lows | session=midday | volatility=increasing | move_type=expansion breakout | reaction=reclaim | vwap=above | volume=building | market=transition | test=first | level=support
Wins: 1
Losses: 0
Win Rate: 100.0 %
Sample Size: 1
PnL: 1550.0

=== JOURNAL SUMMARY ===
Total Trades: 16
Wins: 11
Losses: 5
Breakevens: 0
Win Rate: 68.75 %
Total PnL: 33937.270000000004

=== SETUP BREAKDOWN ===

Retest Hold
Wins: 7
Losses: 0
Breakevens: 0
Win Rate: 100.0 %
PnL: 1476.5

No Trade
Wins: 0
Losses: 4
Breakevens: 0
Win Rate: 0.0 %
PnL: -325.0

Rejection
Wins: 0
Losses: 1
Breakevens: 0
Win Rate: 0.0 %
PnL: -110.0

Break and Hold
Wins: 3
Losses: 0
Breakevens: 0
Win Rate: 100.0 %
PnL: 31345.77

None
Wins: 1
Losses: 0
Breakevens: 0
Win Rate: 100.0 %
PnL: 1550.0

{'Retest Hold': {'wins': 7, 'losses': 0, 'breakevens': 0, 'pnl': 1476.5},
 'No Trade': {'wins': 0, 'losses': 4, 'breakevens': 0, 'pnl': -325.0},
 'Rejection': {'wins': 0, 'losses': 1, 'breakevens': 0, 'pnl': -110.0},
 'Break and Hold': {'wins': 3, 'losses': 0, 'breakevens': 0, 'pnl': 31345.77},
 'None': {'wins': 1, 'losses': 0, 'breakevens': 0, 'pnl': 1550.0}}

In [ ]:
backfill_one_line(
    "SPY",
    "reclaim",
    "support",
    "above",
    55,
    "building",
    "transition",
    "first",
    "VWAP reclaim + compression breakout",
    "win",
    1550,
    "Bearish open shifted into exhaustion. VWAP reclaim confirmed. Higher lows formed. Compression before breakout. Entered on confirmation before expansion. Oil pressure stopped increasing. Sold into strength near prior resistance as momentum slowed.",
    timeframe="5m",
    htf_bias="bullish",
    mtf_structure="higher_lows",
    session="midday",
    volatility="increasing",
    quality="A+",
    move_type="expansion breakout",
    oil_trend="slowing",
    oil_volatility="moderate",
    macro_event="geopolitical_oil_spike_cooling",
    market_sentiment="risk_on_shift",
    sector_strength="tech_leading",
    dark_pool_bias="bullish",
    dark_pool_level="631.99 support cluster / 650 target cluster",
    dark_pool_size="large"
)

=== PERFORMANCE TRACKING ===

A_plus
Wins: 1
Losses: 0
Win Rate: 100.0 %

B_setups
Wins: 0
Losses: 0
Win Rate: 0 %

No_trade
Wins: 0
Losses: 0
Win Rate: 0 %

=== ADJUSTED CONFIDENCE ===
Base Confidence: 50
Category: A_plus
Category Win Rate: 100.0
Setup Type: None
Setup Win Rate: 0
Setup Sample Size: 0
Deep Pattern Signature: asset=index | timeframe=5m | htf=bullish | structure=higher_lows | session=midday | volatility=increasing | move_type=expansion breakout | oil=slowing | oil_volatility=moderate | macro=geopolitical_oil_spike_cooling | sentiment=risk_on_shift | sector=tech_leading | dark_pool_bias=bullish | dark_pool_level=631.99 support cluster / 650 target cluster | dark_pool_size=large | reaction=reclaim | vwap=above | volume=building | market=transition | test=first | level=support
Deep Pattern Win Rate: 0
Deep Pattern Sample Size: 0
Adjusted Confidence: 60

=== POSITION SIZING ===
Grade: C
Confidence: 60
Risk Per Trade: 0%
Recommended Size: NO TRADE
✅ Trade logged and saved

{'timestamp': '2026-04-12T23:19:26',
 'symbol': 'SPY',
 'bias': 'NO TRADE',
 'setup_type': 'None',
 'grade': 'C',
 'key_level': 'VWAP reclaim + compression breakout',
 'adjusted_confidence': 60,
 'position_size': 'NO TRADE',
 'result': 'win',
 'pnl': 1550,
 'notes': 'Bearish open shifted into exhaustion. VWAP reclaim confirmed. Higher lows formed. Compression before breakout. Entered on confirmation before expansion. Oil pressure stopped increasing. Sold into strength near prior resistance as momentum slowed.',
 'trade_input': {'symbol': 'SPY',
  'asset_type': 'index',
  'level': 'support',
  'reaction': 'reclaim',
  'vwap': 'above',
  'rsi': 55,
  'volume': 'building',
  'market': 'transition',
  'test': 'first',
  'key_level': 'VWAP reclaim + compression breakout',
  'timeframe': '5m',
  'htf_bias': 'bullish',
  'mtf_structure': 'higher_lows',
  'session': 'midday',
  'volatility': 'increasing',
  'quality': 'A+',
  'move_type': 'expansion breakout',
  'oil_trend': 'slowing',
  'oil_volatility': 'moderate',
  'macro_event': 'geopolitical_oil_spike_cooling',
  'market_sentiment': 'risk_on_shift',
  'sector_strength': 'tech_leading',
  'dark_pool_bias': 'bullish',
  'dark_pool_level': '631.99 support cluster / 650 target cluster',
  'dark_pool_size': 'large'},
 'pattern_signature': 'asset=index | timeframe=5m | htf=bullish | structure=higher_lows | session=midday | volatility=increasing | move_type=expansion breakout | oil=slowing | oil_volatility=moderate | macro=geopolitical_oil_spike_cooling | sentiment=risk_on_shift | sector=tech_leading | dark_pool_bias=bullish | dark_pool_level=631.99 support cluster / 650 target cluster | dark_pool_size=large | reaction=reclaim | vwap=above | volume=building | market=transition | test=first | level=support'}

In [ ]:
quick_run(
    "SPY",
    "support",
    "reclaim",
    "above",
    55,
    "building",
    "transition",
    "first",
    "VWAP reclaim + compression breakout",
    timeframe="5m",
    htf_bias="bullish",
    mtf_structure="higher_lows",
    session="midday",
    volatility="increasing",
    move_type="expansion breakout",
    quality="A+",
    oil_trend="slowing",
    oil_volatility="moderate",
    macro_event="geopolitical_oil_spike_cooling",
    market_sentiment="risk_on_shift",
    sector_strength="tech_leading",
    dark_pool_bias="bullish",
    dark_pool_level="631.99 support cluster / 650 target cluster",
    dark_pool_size="large"
)

=== FULL ANALYSIS ===

=== BEST MATCH ===
NAME: spy_transition_breakout_a1
CATEGORY: A_plus
MATCH SCORE: 12

--- FINAL OUTPUT ---
BIAS : NO TRADE
SETUP_TYPE : None
GRADE : C
KEY_LEVEL : VWAP reclaim + compression breakout
ENTRY_TRIGGER : None
INVALIDATION : None
TARGETS : None
CONFIDENCE : 50
REASONS : ['Bullish VWAP control', 'Bullish momentum', 'First test of level', 'Higher timeframe bullish bias']
RISKS : ['No strong volume confirmation']
FINAL_DECISION : NO TRADE

PATTERN MATCH:
MATCHED SETUP: spy_transition_breakout_a1
CATEGORY: A_plus
MATCH SCORE: 12

=== PERFORMANCE TRACKING ===

A_plus
Wins: 1
Losses: 0
Win Rate: 100.0 %

B_setups
Wins: 0
Losses: 0
Win Rate: 0 %

No_trade
Wins: 0
Losses: 0
Win Rate: 0 %

=== ADJUSTED CONFIDENCE ===
Base Confidence: 50
Category: A_plus
Category Win Rate: 100.0
Setup Type: None
Setup Win Rate: 0
Setup Sample Size: 0
Deep Pattern Signature: asset=index | timeframe=5m | htf=bullish | structure=higher_lows | session=midday | volatility=increasing | move_type=expansion breakout | oil=slowing | oil_volatility=moderate | macro=geopolitical_oil_spike_cooling | sentiment=risk_on_shift | sector=tech_leading | dark_pool_bias=bullish | dark_pool_level=631.99 support cluster / 650 target cluster | dark_pool_size=large | reaction=reclaim | vwap=above | volume=building | market=transition | test=first | level=support
Deep Pattern Win Rate: 0
Deep Pattern Sample Size: 0
Adjusted Confidence: 60

FINAL CONFIDENCE (ADJUSTED): 60

✅ TRADE ALLOWED

=== POSITION SIZING ===
Grade: C
Confidence: 60
Risk Per Trade: 0%
Recommended Size: NO TRADE
FINAL POSITION SIZE: NO TRADE

In [ ]:
saved_trades["A_plus"]["spy_transition_breakout_a1"] = {
    "symbol": "SPY",
    "asset_type": "index",
    "level": "support",
    "reaction": "reclaim",
    "vwap": "above",
    "rsi": 55,
    "volume": "building",
    "market": "transition",
    "test": "first",
    "key_level": "VWAP reclaim + compression breakout",
    "timeframe": "5m",
    "htf_bias": "bullish",
    "mtf_structure": "higher_lows",
    "session": "midday",
    "volatility": "increasing",
    "quality": "A+",
    "move_type": "expansion breakout",
    "oil_trend": "slowing",
    "oil_volatility": "moderate",
    "macro_event": "geopolitical_oil_spike_cooling",
    "market_sentiment": "risk_on_shift",
    "sector_strength": "tech_leading",
    "dark_pool_bias": "bullish",
    "dark_pool_level": "631.99 support cluster / 650 target cluster",
    "dark_pool_size": "large"
}

In [ ]:
quick_run(
    "SPY",
    "resistance",
    "break_hold",
    "above",
    65,
    "high",
    "clean",
    "first",
    "SPY resistance break",

    timeframe="5m",
    htf_bias="bullish",
    mtf_structure="higher_highs",
    session="open",
    volatility="high",
    move_type="expansion breakout",
    quality="A+",

    oil_trend="down",
    oil_volatility="low",
    macro_event="none",
    market_sentiment="risk_on",
    sector_strength="strong",

    dark_pool_bias="bullish",
    dark_pool_level="key support",
    dark_pool_size="large"
)

=== FULL ANALYSIS ===

=== BEST MATCH ===
NAME: qqq_break_hold_a1
CATEGORY: A_plus
MATCH SCORE: 12

--- FINAL OUTPUT ---
BIAS : CALL
SETUP_TYPE : Break and Hold
GRADE : A+
KEY_LEVEL : SPY resistance break
ENTRY_TRIGGER : Break above resistance holds with continuation
INVALIDATION : Loss of breakout level / loss of VWAP
TARGETS : Next resistance / extension target
CONFIDENCE : 100
REASONS : ['Break and hold above resistance', 'Bullish VWAP control', 'Bullish momentum', 'Volume confirmation', 'First test of level', 'Higher timeframe bullish bias', 'Bullish multi-timeframe structure', 'Momentum-friendly session', 'High-volatility breakout environment', 'Expansion breakout / squeeze behavior']
RISKS : []
FINAL_DECISION : CALL

PATTERN MATCH:
MATCHED SETUP: qqq_break_hold_a1
CATEGORY: A_plus
MATCH SCORE: 12

=== PERFORMANCE TRACKING ===

A_plus
Wins: 1
Losses: 0
Win Rate: 100.0 %

B_setups
Wins: 0
Losses: 0
Win Rate: 0 %

No_trade
Wins: 0
Losses: 0
Win Rate: 0 %

=== ADJUSTED CONFIDENCE ===
Base Confidence: 100
Category: A_plus
Category Win Rate: 100.0
Setup Type: Break and Hold
Setup Win Rate: 100.0
Setup Sample Size: 3
Deep Pattern Signature: asset=index | timeframe=5m | htf=bullish | structure=higher_highs | session=open | volatility=high | move_type=expansion breakout | oil=down | oil_volatility=low | macro=none | sentiment=risk_on | sector=strong | dark_pool_bias=bullish | dark_pool_level=key support | dark_pool_size=large | reaction=break_hold | vwap=above | volume=high | market=clean | test=first | level=resistance
Deep Pattern Win Rate: 0
Deep Pattern Sample Size: 0
Adjusted Confidence: 100

FINAL CONFIDENCE (ADJUSTED): 100

✅ TRADE ALLOWED

=== POSITION SIZING ===
Grade: A+
Confidence: 100
Risk Per Trade: 3%
Recommended Size: FULL SIZE
FINAL POSITION SIZE: FULL SIZE

In [ ]:
saved_trades["A_plus"]["spy_break_hold_a1"] = {
    "symbol": "SPY",
    "asset_type": "index",
    "level": "resistance",
    "reaction": "break_hold",
    "vwap": "above",
    "rsi": 65,
    "volume": "high",
    "market": "clean",
    "test": "first",
    "key_level": "SPY resistance break",
    "timeframe": "5m",
    "htf_bias": "bullish",
    "mtf_structure": "higher_highs",
    "session": "open",
    "volatility": "high",
    "quality": "A+",
    "move_type": "expansion breakout",

    # MACRO
    "oil_trend": "down",
    "oil_volatility": "low",
    "macro_event": "none",
    "market_sentiment": "risk_on",
    "sector_strength": "strong",

    # DARK POOL
    "dark_pool_bias": "bullish",
    "dark_pool_level": "key support",
    "dark_pool_size": "large"
}

In [ ]:
quick_run(
    "QQQ",
    "resistance",
    "break_hold",
    "above",
    65,
    "high",
    "clean",
    "first",
    "QQQ 500 resistance break",
    timeframe="5m",
    htf_bias="bullish",
    mtf_structure="higher_highs",
    session="open",
    volatility="high",
    move_type="expansion breakout",
    quality="A+",
    oil_trend="down",
    oil_volatility="low",
    macro_event="none",
    market_sentiment="risk_on",
    sector_strength="strong",
    dark_pool_bias="bullish",
    dark_pool_level="498.50",
    dark_pool_size="large"
)

=== FULL ANALYSIS ===

=== BEST MATCH ===
NAME: qqq_break_hold_a1
CATEGORY: A_plus
MATCH SCORE: 12

--- FINAL OUTPUT ---
BIAS : CALL
SETUP_TYPE : Break and Hold
GRADE : A+
KEY_LEVEL : QQQ 500 resistance break
ENTRY_TRIGGER : Break above resistance holds with continuation
INVALIDATION : Loss of breakout level / loss of VWAP
TARGETS : Next resistance / extension target
CONFIDENCE : 100
REASONS : ['Break and hold above resistance', 'Bullish VWAP control', 'Bullish momentum', 'Volume confirmation', 'First test of level', 'Higher timeframe bullish bias', 'Bullish multi-timeframe structure', 'Momentum-friendly session', 'High-volatility breakout environment', 'Expansion breakout / squeeze behavior']
RISKS : []
FINAL_DECISION : CALL

PATTERN MATCH:
MATCHED SETUP: qqq_break_hold_a1
CATEGORY: A_plus
MATCH SCORE: 12

=== PERFORMANCE TRACKING ===

A_plus
Wins: 1
Losses: 0
Win Rate: 100.0 %

B_setups
Wins: 0
Losses: 0
Win Rate: 0 %

No_trade
Wins: 0
Losses: 0
Win Rate: 0 %

=== ADJUSTED CONFIDENCE ===
Base Confidence: 100
Category: A_plus
Category Win Rate: 100.0
Setup Type: Break and Hold
Setup Win Rate: 100.0
Setup Sample Size: 3
Deep Pattern Signature: asset=index | timeframe=5m | htf=bullish | structure=higher_highs | session=open | volatility=high | move_type=expansion breakout | oil=down | oil_volatility=low | macro=none | sentiment=risk_on | sector=strong | dark_pool_bias=bullish | dark_pool_level=498.50 | dark_pool_size=large | reaction=break_hold | vwap=above | volume=high | market=clean | test=first | level=resistance
Deep Pattern Win Rate: 0
Deep Pattern Sample Size: 0
Adjusted Confidence: 100

FINAL CONFIDENCE (ADJUSTED): 100

✅ TRADE ALLOWED

=== POSITION SIZING ===
Grade: A+
Confidence: 100
Risk Per Trade: 3%
Recommended Size: FULL SIZE
FINAL POSITION SIZE: FULL SIZE

In [ ]:
quick_run(
    "QQQ",
    "resistance",
    "break_hold",
    "above",
    65,
    "high",
    "clean",
    "first",
    "QQQ 500 resistance break",

    timeframe="5m",
    htf_bias="bullish",
    mtf_structure="higher_highs",
    session="open",
    volatility="high",
    move_type="expansion breakout",
    quality="A+",

    oil_trend="down",
    oil_volatility="low",
    macro_event="none",
    market_sentiment="risk_on",
    sector_strength="strong"
)

=== FULL ANALYSIS ===

=== BEST MATCH ===
NAME: qqq_break_hold_a1
CATEGORY: A_plus
MATCH SCORE: 12

--- FINAL OUTPUT ---
BIAS : CALL
SETUP_TYPE : Break and Hold
GRADE : A+
KEY_LEVEL : QQQ 500 resistance break
ENTRY_TRIGGER : Break above resistance holds with continuation
INVALIDATION : Loss of breakout level / loss of VWAP
TARGETS : Next resistance / extension target
CONFIDENCE : 100
REASONS : ['Break and hold above resistance', 'Bullish VWAP control', 'Bullish momentum', 'Volume confirmation', 'First test of level', 'Higher timeframe bullish bias', 'Bullish multi-timeframe structure', 'Momentum-friendly session', 'High-volatility breakout environment', 'Expansion breakout / squeeze behavior']
RISKS : []
FINAL_DECISION : CALL

PATTERN MATCH:
MATCHED SETUP: qqq_break_hold_a1
CATEGORY: A_plus
MATCH SCORE: 12

=== PERFORMANCE TRACKING ===

A_plus
Wins: 1
Losses: 0
Win Rate: 100.0 %

B_setups
Wins: 0
Losses: 0
Win Rate: 0 %

No_trade
Wins: 0
Losses: 0
Win Rate: 0 %

=== ADJUSTED CONFIDENCE ===
Base Confidence: 100
Category: A_plus
Category Win Rate: 100.0
Setup Type: Break and Hold
Setup Win Rate: 100.0
Setup Sample Size: 3
Deep Pattern Signature: asset=index | timeframe=5m | htf=bullish | structure=higher_highs | session=open | volatility=high | move_type=expansion breakout | oil=down | oil_volatility=low | macro=none | sentiment=risk_on | sector=strong | macro_bias=unknown | reaction=break_hold | vwap=above | volume=high | market=clean | test=first | level=resistance
Deep Pattern Win Rate: 0
Deep Pattern Sample Size: 0
Adjusted Confidence: 100

FINAL CONFIDENCE (ADJUSTED): 100

✅ TRADE ALLOWED

=== POSITION SIZING ===
Grade: A+
Confidence: 100
Risk Per Trade: 3%
Recommended Size: FULL SIZE
FINAL POSITION SIZE: FULL SIZE

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
saved_trades["A_plus"]["qqq_break_hold_a1"] = {
    "symbol": "QQQ",
    "asset_type": "index",
    "level": "resistance",
    "reaction": "break_hold",
    "vwap": "above",
    "rsi": 65,
    "volume": "high",
    "market": "clean",
    "test": "first",
    "key_level": "QQQ 500 resistance break",
    "timeframe": "5m",
    "htf_bias": "bullish",
    "mtf_structure": "higher_highs",
    "session": "open",
    "volatility": "high",
    "quality": "A+",
    "move_type": "expansion breakout",
    "oil_trend": "down",
    "oil_volatility": "low",
    "macro_event": "none",
    "market_sentiment": "risk_on",
    "sector_strength": "strong"
}

In [ ]:
quick_run(
    "QQQ",
    "resistance",
    "break_hold",
    "above",
    65,
    "high",
    "clean",
    "first",
    "QQQ 500 resistance break",

    timeframe="5m",
    htf_bias="bullish",
    mtf_structure="higher_highs",
    session="open",
    volatility="high",
    move_type="expansion breakout",
    quality="A+",

    oil_trend="down",
    oil_volatility="low",
    macro_event="none",
    market_sentiment="risk_on",
    sector_strength="strong"
)

=== FULL ANALYSIS ===

=== BEST MATCH ===
NAME: qqq_break_hold_a1
CATEGORY: A_plus
MATCH SCORE: 12

--- FINAL OUTPUT ---
BIAS : CALL
SETUP_TYPE : Break and Hold
GRADE : A+
KEY_LEVEL : QQQ 500 resistance break
ENTRY_TRIGGER : Break above resistance holds with continuation
INVALIDATION : Loss of breakout level / loss of VWAP
TARGETS : Next resistance / extension target
CONFIDENCE : 100
REASONS : ['Break and hold above resistance', 'Bullish VWAP control', 'Bullish momentum', 'Volume confirmation', 'First test of level', 'Higher timeframe bullish bias', 'Bullish multi-timeframe structure', 'Momentum-friendly session', 'High-volatility breakout environment', 'Expansion breakout / squeeze behavior']
RISKS : []
FINAL_DECISION : CALL

PATTERN MATCH:
MATCHED SETUP: qqq_break_hold_a1
CATEGORY: A_plus
MATCH SCORE: 12

=== PERFORMANCE TRACKING ===

A_plus
Wins: 1
Losses: 0
Win Rate: 100.0 %

B_setups
Wins: 0
Losses: 0
Win Rate: 0 %

No_trade
Wins: 0
Losses: 0
Win Rate: 0 %

=== ADJUSTED CONFIDENCE ===
Base Confidence: 100
Category: A_plus
Category Win Rate: 100.0
Setup Type: Break and Hold
Setup Win Rate: 100.0
Setup Sample Size: 3
Deep Pattern Signature: asset=index | timeframe=5m | htf=bullish | structure=higher_highs | session=open | volatility=high | move_type=expansion breakout | oil=down | oil_volatility=low | macro=none | sentiment=risk_on | sector=strong | macro_bias=unknown | reaction=break_hold | vwap=above | volume=high | market=clean | test=first | level=resistance
Deep Pattern Win Rate: 0
Deep Pattern Sample Size: 0
Adjusted Confidence: 100

FINAL CONFIDENCE (ADJUSTED): 100

✅ TRADE ALLOWED

=== POSITION SIZING ===
Grade: A+
Confidence: 100
Risk Per Trade: 3%
Recommended Size: FULL SIZE
FINAL POSITION SIZE: FULL SIZE

In [ ]:
saved_trades["A_plus"]["qqq_break_hold_a1"] = {
    "symbol": "QQQ",
    "asset_type": "index",
    "level": "resistance",
    "reaction": "break_hold",
    "vwap": "above",
    "rsi": 65,
    "volume": "high",
    "market": "clean",
    "test": "first",
    "key_level": "QQQ 500 resistance break",
    "timeframe": "5m",
    "htf_bias": "bullish",
    "mtf_structure": "higher_highs",
    "session": "open",
    "volatility": "high",
    "quality": "A+",
    "move_type": "expansion breakout",
    "oil_trend": "down",
    "oil_volatility": "low",
    "macro_event": "none",
    "market_sentiment": "risk_on",
    "sector_strength": "strong"
}

In [ ]:
quick_run(
    "QQQ",
    "resistance",
    "break_hold",
    "above",
    65,
    "high",
    "clean",
    "first",
    "QQQ 500 resistance break",

    timeframe="5m",
    htf_bias="bullish",
    mtf_structure="higher_highs",
    session="open",
    volatility="high",
    move_type="expansion breakout",
    quality="A+",

    oil_trend="down",
    oil_volatility="low",
    macro_event="none",
    market_sentiment="risk_on",
    sector_strength="strong"
)

=== FULL ANALYSIS ===

=== BEST MATCH ===
NAME: hood_break_hold_a1
CATEGORY: A_plus
MATCH SCORE: 11

--- FINAL OUTPUT ---
BIAS : CALL
SETUP_TYPE : Break and Hold
GRADE : A+
KEY_LEVEL : QQQ 500 resistance break
ENTRY_TRIGGER : Break above resistance holds with continuation
INVALIDATION : Loss of breakout level / loss of VWAP
TARGETS : Next resistance / extension target
CONFIDENCE : 100
REASONS : ['Break and hold above resistance', 'Bullish VWAP control', 'Bullish momentum', 'Volume confirmation', 'First test of level', 'Higher timeframe bullish bias', 'Bullish multi-timeframe structure', 'Momentum-friendly session', 'High-volatility breakout environment', 'Expansion breakout / squeeze behavior']
RISKS : []
FINAL_DECISION : CALL

PATTERN MATCH:
MATCHED SETUP: hood_break_hold_a1
CATEGORY: A_plus
MATCH SCORE: 11

=== PERFORMANCE TRACKING ===

A_plus
Wins: 1
Losses: 0
Win Rate: 100.0 %

B_setups
Wins: 0
Losses: 0
Win Rate: 0 %

No_trade
Wins: 0
Losses: 0
Win Rate: 0 %

=== ADJUSTED CONFIDENCE ===
Base Confidence: 100
Category: A_plus
Category Win Rate: 100.0
Setup Type: Break and Hold
Setup Win Rate: 100.0
Setup Sample Size: 3
Deep Pattern Signature: asset=index | timeframe=5m | htf=bullish | structure=higher_highs | session=open | volatility=high | move_type=expansion breakout | oil=down | oil_volatility=low | macro=none | sentiment=risk_on | sector=strong | macro_bias=unknown | reaction=break_hold | vwap=above | volume=high | market=clean | test=first | level=resistance
Deep Pattern Win Rate: 0
Deep Pattern Sample Size: 0
Adjusted Confidence: 100

FINAL CONFIDENCE (ADJUSTED): 100

✅ TRADE ALLOWED

=== POSITION SIZING ===
Grade: A+
Confidence: 100
Risk Per Trade: 3%
Recommended Size: FULL SIZE
FINAL POSITION SIZE: FULL SIZE

In [ ]:
quick_run(
    "QQQ",
    "resistance",
    "break_hold",
    "above",
    65,
    "high",
    "clean",
    "first",
    "QQQ 500 resistance break",

    timeframe="5m",
    htf_bias="bullish",
    mtf_structure="higher_highs",
    session="open",
    volatility="high",
    move_type="expansion breakout",
    quality="A+",

    oil_trend="down",
    oil_volatility="low",
    macro_event="none",
    market_sentiment="risk_on",
    sector_strength="strong"
)

TypeError: quick_run() got an unexpected keyword argument 'move_type'

In [ ]:
quick_run(
    "QQQ",
    "resistance",
    "break_hold",
    "above",
    64,
    "high",
    "clean",
    "first",
    "QQQ 500 resistance break",

    timeframe="5m",
    htf_bias="bullish",
    mtf_structure="higher_highs",
    session="open",
    volatility="high",
    move_type="expansion breakout",
    quality="A+",

    oil_trend="down",
    oil_volatility="low",
    macro_event="none",
    market_sentiment="risk_on",
    sector_strength="strong"
)

TypeError: quick_run() got an unexpected keyword argument 'oil_trend'

In [ ]:
def macro_bias(oil_trend, macro_event, market_sentiment):
    oil_trend = str(oil_trend).lower()
    macro_event = str(macro_event).lower()
    market_sentiment = str(market_sentiment).lower()

    if oil_trend == "up" and macro_event in ["war", "geopolitical", "conflict"] and market_sentiment == "fear":
        return "bearish_qqq"
    elif oil_trend == "down" and market_sentiment in ["risk_on", "bullish"]:
        return "bullish_qqq"
    else:
        return "neutral"

In [ ]:
learned_pattern_breakdown()
journal_summary()
setup_breakdown()

=== DEEP PATTERN STATS ===

asset=unknown | timeframe=unknown | htf=unknown | structure=unknown | session=unknown | volatility=unknown | move_type=unknown | reaction=unknown | vwap=unknown | volume=unknown | market=unknown | test=unknown | level=unknown
Wins: 2
Losses: 0
Win Rate: 100.0 %
Sample Size: 2
PnL: 491.0

asset=unknown | timeframe=5m | htf=unknown | structure=unknown | session=open | volatility=medium | move_type=unknown | reaction=retest_hold | vwap=above | volume=high | market=clean | test=first | level=support
Wins: 3
Losses: 0
Win Rate: 100.0 %
Sample Size: 3
PnL: 625.5

asset=unknown | timeframe=5m | htf=unknown | structure=unknown | session=open | volatility=medium | move_type=unknown | reaction=retest_hold | vwap=above | volume=low | market=clean | test=second | level=support
Wins: 0
Losses: 1
Win Rate: 0.0 %
Sample Size: 1
PnL: -95.0

asset=stock | timeframe=5m | htf=bullish | structure=higher_lows | session=open | volatility=high | move_type=unknown | reaction=retest_hold | vwap=above | volume=high | market=clean | test=first | level=support
Wins: 2
Losses: 0
Win Rate: 100.0 %
Sample Size: 2
PnL: 360.0

asset=stock | timeframe=5m | htf=bullish | structure=higher_lows | session=open | volatility=high | move_type=unknown | reaction=retest_hold | vwap=above | volume=low | market=clean | test=second | level=support
Wins: 0
Losses: 2
Win Rate: 0.0 %
Sample Size: 2
PnL: -190.0

asset=index | timeframe=5m | htf=bearish | structure=lower_highs | session=open | volatility=medium | move_type=unknown | reaction=rejection | vwap=below | volume=high | market=clean | test=second | level=resistance
Wins: 0
Losses: 1
Win Rate: 0.0 %
Sample Size: 1
PnL: -110.0

asset=index | timeframe=5m | htf=neutral | structure=sideways | session=midday | volatility=medium | move_type=unknown | reaction=retest_hold | vwap=above | volume=low | market=chop | test=second | level=support
Wins: 0
Losses: 1
Win Rate: 0.0 %
Sample Size: 1
PnL: -40.0

asset=stock | timeframe=5m | htf=bullish | structure=higher_highs | session=open | volatility=high | move_type=unknown | reaction=break_hold | vwap=above | volume=high | market=clean | test=first | level=resistance
Wins: 1
Losses: 0
Win Rate: 100.0 %
Sample Size: 1
PnL: 10448.59

asset=stock | timeframe=5m | htf=bullish | structure=higher_highs | session=open | volatility=high | move_type=expansion breakout | reaction=break_hold | vwap=above | volume=high | market=clean | test=first | level=resistance
Wins: 2
Losses: 0
Win Rate: 100.0 %
Sample Size: 2
PnL: 20897.18

=== JOURNAL SUMMARY ===
Total Trades: 15
Wins: 10
Losses: 5
Breakevens: 0
Win Rate: 66.67 %
Total PnL: 32387.27

=== SETUP BREAKDOWN ===

Retest Hold
Wins: 7
Losses: 0
Breakevens: 0
Win Rate: 100.0 %
PnL: 1476.5

No Trade
Wins: 0
Losses: 4
Breakevens: 0
Win Rate: 0.0 %
PnL: -325.0

Rejection
Wins: 0
Losses: 1
Breakevens: 0
Win Rate: 0.0 %
PnL: -110.0

Break and Hold
Wins: 3
Losses: 0
Breakevens: 0
Win Rate: 100.0 %
PnL: 31345.77

{'Retest Hold': {'wins': 7, 'losses': 0, 'breakevens': 0, 'pnl': 1476.5},
 'No Trade': {'wins': 0, 'losses': 4, 'breakevens': 0, 'pnl': -325.0},
 'Rejection': {'wins': 0, 'losses': 1, 'breakevens': 0, 'pnl': -110.0},
 'Break and Hold': {'wins': 3, 'losses': 0, 'breakevens': 0, 'pnl': 31345.77}}

In [ ]:
cleanup_old_journal_defaults()

✅ Cleanup complete. Fields updated: 35

In [ ]:
def cleanup_old_journal_defaults(
    default_timeframe="5m",
    default_session="open",
    default_volatility="medium",
    default_move_type="unknown"
):
    global trade_journal
    updated = 0

    for t in trade_journal:
        trade_input = t.get("trade_input", {})

        if not trade_input:
            continue

        symbol = trade_input.get("symbol", t.get("symbol", ""))
        symbol_upper = str(symbol).upper()

        if "asset_type" not in trade_input or not trade_input.get("asset_type"):
            if symbol_upper in ["QQQ", "SPY", "IWM", "DIA"]:
                trade_input["asset_type"] = "index"
            elif symbol_upper:
                trade_input["asset_type"] = "stock"
            else:
                trade_input["asset_type"] = "unknown"
            updated += 1

        if "timeframe" not in trade_input or not trade_input.get("timeframe"):
            trade_input["timeframe"] = default_timeframe
            updated += 1

        if "session" not in trade_input or not trade_input.get("session"):
            trade_input["session"] = default_session
            updated += 1

        if "volatility" not in trade_input or not trade_input.get("volatility"):
            trade_input["volatility"] = default_volatility
            updated += 1

        if "move_type" not in trade_input or not trade_input.get("move_type"):
            trade_input["move_type"] = default_move_type
            updated += 1

        if "htf_bias" not in trade_input or not trade_input.get("htf_bias"):
            trade_input["htf_bias"] = "unknown"
            updated += 1

        if "mtf_structure" not in trade_input or not trade_input.get("mtf_structure"):
            trade_input["mtf_structure"] = "unknown"
            updated += 1

        if "market" not in trade_input or not trade_input.get("market"):
            trade_input["market"] = "unknown"
            updated += 1

        if "test" not in trade_input or not trade_input.get("test"):
            trade_input["test"] = "unknown"
            updated += 1

        if "level" not in trade_input or not trade_input.get("level"):
            trade_input["level"] = "unknown"
            updated += 1

        if "reaction" not in trade_input or not trade_input.get("reaction"):
            trade_input["reaction"] = "unknown"
            updated += 1

        if "vwap" not in trade_input or not trade_input.get("vwap"):
            trade_input["vwap"] = "unknown"
            updated += 1

        if "volume" not in trade_input or not trade_input.get("volume"):
            trade_input["volume"] = "unknown"
            updated += 1

        if "key_level" not in trade_input or not trade_input.get("key_level"):
            trade_input["key_level"] = t.get("key_level", "unknown")
            updated += 1

        t["trade_input"] = trade_input
        t["pattern_signature"] = pattern_signature(trade_input)

    import json
    with open("trade_journal.json", "w") as f:
        json.dump(trade_journal, f, indent=4)

    print(f"✅ Cleanup complete. Fields updated: {updated}")

In [ ]:
learned_pattern_breakdown()
journal_summary()
setup_breakdown()

=== DEEP PATTERN STATS ===

asset=unknown | timeframe=unknown | htf=unknown | structure=unknown | session=unknown | volatility=unknown | move_type=unknown | reaction=unknown | vwap=unknown | volume=unknown | market=unknown | test=unknown | level=unknown
Wins: 2
Losses: 0
Win Rate: 100.0 %
Sample Size: 2
PnL: 491.0

asset=unknown | timeframe=unknown | htf=unknown | structure=unknown | session=unknown | volatility=unknown | move_type=unknown | reaction=retest_hold | vwap=above | volume=high | market=clean | test=first | level=support
Wins: 3
Losses: 0
Win Rate: 100.0 %
Sample Size: 3
PnL: 625.5

asset=unknown | timeframe=unknown | htf=unknown | structure=unknown | session=unknown | volatility=unknown | move_type=unknown | reaction=retest_hold | vwap=above | volume=low | market=clean | test=second | level=support
Wins: 0
Losses: 1
Win Rate: 0.0 %
Sample Size: 1
PnL: -95.0

asset=stock | timeframe=5m | htf=bullish | structure=higher_lows | session=open | volatility=high | move_type=unknown | reaction=retest_hold | vwap=above | volume=high | market=clean | test=first | level=support
Wins: 2
Losses: 0
Win Rate: 100.0 %
Sample Size: 2
PnL: 360.0

asset=stock | timeframe=5m | htf=bullish | structure=higher_lows | session=open | volatility=high | move_type=unknown | reaction=retest_hold | vwap=above | volume=low | market=clean | test=second | level=support
Wins: 0
Losses: 2
Win Rate: 0.0 %
Sample Size: 2
PnL: -190.0

asset=index | timeframe=5m | htf=bearish | structure=lower_highs | session=open | volatility=medium | move_type=unknown | reaction=rejection | vwap=below | volume=high | market=clean | test=second | level=resistance
Wins: 0
Losses: 1
Win Rate: 0.0 %
Sample Size: 1
PnL: -110.0

asset=index | timeframe=5m | htf=neutral | structure=sideways | session=midday | volatility=medium | move_type=unknown | reaction=retest_hold | vwap=above | volume=low | market=chop | test=second | level=support
Wins: 0
Losses: 1
Win Rate: 0.0 %
Sample Size: 1
PnL: -40.0

asset=stock | timeframe=5m | htf=bullish | structure=higher_highs | session=open | volatility=high | move_type=unknown | reaction=break_hold | vwap=above | volume=high | market=clean | test=first | level=resistance
Wins: 1
Losses: 0
Win Rate: 100.0 %
Sample Size: 1
PnL: 10448.59

asset=stock | timeframe=5m | htf=bullish | structure=higher_highs | session=open | volatility=high | move_type=expansion breakout | reaction=break_hold | vwap=above | volume=high | market=clean | test=first | level=resistance
Wins: 2
Losses: 0
Win Rate: 100.0 %
Sample Size: 2
PnL: 20897.18

=== JOURNAL SUMMARY ===
Total Trades: 15
Wins: 10
Losses: 5
Breakevens: 0
Win Rate: 66.67 %
Total PnL: 32387.27

=== SETUP BREAKDOWN ===

Retest Hold
Wins: 7
Losses: 0
Breakevens: 0
Win Rate: 100.0 %
PnL: 1476.5

No Trade
Wins: 0
Losses: 4
Breakevens: 0
Win Rate: 0.0 %
PnL: -325.0

Rejection
Wins: 0
Losses: 1
Breakevens: 0
Win Rate: 0.0 %
PnL: -110.0

Break and Hold
Wins: 3
Losses: 0
Breakevens: 0
Win Rate: 100.0 %
PnL: 31345.77

{'Retest Hold': {'wins': 7, 'losses': 0, 'breakevens': 0, 'pnl': 1476.5},
 'No Trade': {'wins': 0, 'losses': 4, 'breakevens': 0, 'pnl': -325.0},
 'Rejection': {'wins': 0, 'losses': 1, 'breakevens': 0, 'pnl': -110.0},
 'Break and Hold': {'wins': 3, 'losses': 0, 'breakevens': 0, 'pnl': 31345.77}}

In [ ]:
learned_pattern_breakdown()
journal_summary()
setup_breakdown()

=== DEEP PATTERN STATS ===

reaction=retest_hold | vwap=above | volume=high | market=clean | test=first | level=support
Wins: 3
Losses: 0
Win Rate: 100.0 %
Sample Size: 3
PnL: 625.5

reaction=retest_hold | vwap=above | volume=low | market=clean | test=second | level=support
Wins: 0
Losses: 1
Win Rate: 0.0 %
Sample Size: 1
PnL: -95.0

asset=stock | reaction=retest_hold | vwap=above | volume=high | market=clean | test=first | level=support
Wins: 2
Losses: 0
Win Rate: 100.0 %
Sample Size: 2
PnL: 360.0

asset=stock | reaction=retest_hold | vwap=above | volume=low | market=clean | test=second | level=support
Wins: 0
Losses: 2
Win Rate: 0.0 %
Sample Size: 2
PnL: -190.0

asset=index | reaction=rejection | vwap=below | volume=high | market=clean | test=second | level=resistance
Wins: 0
Losses: 1
Win Rate: 0.0 %
Sample Size: 1
PnL: -110.0

asset=index | reaction=retest_hold | vwap=above | volume=low | market=chop | test=second | level=support
Wins: 0
Losses: 1
Win Rate: 0.0 %
Sample Size: 1
PnL: -40.0

asset=stock | timeframe=5m | htf=bullish | structure=higher_highs | session=open | volatility=high | move_type= | reaction=break_hold | vwap=above | volume=high | market=clean | test=first | level=resistance
Wins: 1
Losses: 0
Win Rate: 100.0 %
Sample Size: 1
PnL: 10448.59

asset=stock | timeframe=5m | htf=bullish | structure=higher_highs | session=open | volatility=high | move_type=expansion breakout | reaction=break_hold | vwap=above | volume=high | market=clean | test=first | level=resistance
Wins: 2
Losses: 0
Win Rate: 100.0 %
Sample Size: 2
PnL: 20897.18

=== JOURNAL SUMMARY ===
Total Trades: 15
Wins: 10
Losses: 5
Breakevens: 0
Win Rate: 66.67 %
Total PnL: 32387.27

=== SETUP BREAKDOWN ===

Retest Hold
Wins: 7
Losses: 0
Breakevens: 0
Win Rate: 100.0 %
PnL: 1476.5

No Trade
Wins: 0
Losses: 4
Breakevens: 0
Win Rate: 0.0 %
PnL: -325.0

Rejection
Wins: 0
Losses: 1
Breakevens: 0
Win Rate: 0.0 %
PnL: -110.0

Break and Hold
Wins: 3
Losses: 0
Breakevens: 0
Win Rate: 100.0 %
PnL: 31345.77

{'Retest Hold': {'wins': 7, 'losses': 0, 'breakevens': 0, 'pnl': 1476.5},
 'No Trade': {'wins': 0, 'losses': 4, 'breakevens': 0, 'pnl': -325.0},
 'Rejection': {'wins': 0, 'losses': 1, 'breakevens': 0, 'pnl': -110.0},
 'Break and Hold': {'wins': 3, 'losses': 0, 'breakevens': 0, 'pnl': 31345.77}}

In [ ]:
learned_pattern_breakdown()
journal_summary()
setup_breakdown()

=== DEEP PATTERN STATS ===

reaction=retest_hold | vwap=above | volume=high | market=clean | test=first | level=support
Wins: 3
Losses: 0
Win Rate: 100.0 %
Sample Size: 3
PnL: 625.5

reaction=retest_hold | vwap=above | volume=low | market=clean | test=second | level=support
Wins: 0
Losses: 1
Win Rate: 0.0 %
Sample Size: 1
PnL: -95.0

asset=stock | reaction=retest_hold | vwap=above | volume=high | market=clean | test=first | level=support
Wins: 2
Losses: 0
Win Rate: 100.0 %
Sample Size: 2
PnL: 360.0

asset=stock | reaction=retest_hold | vwap=above | volume=low | market=clean | test=second | level=support
Wins: 0
Losses: 2
Win Rate: 0.0 %
Sample Size: 2
PnL: -190.0

asset=index | reaction=rejection | vwap=below | volume=high | market=clean | test=second | level=resistance
Wins: 0
Losses: 1
Win Rate: 0.0 %
Sample Size: 1
PnL: -110.0

asset=index | reaction=retest_hold | vwap=above | volume=low | market=chop | test=second | level=support
Wins: 0
Losses: 1
Win Rate: 0.0 %
Sample Size: 1
PnL: -40.0

asset=stock | timeframe=5m | htf=bullish | structure=higher_highs | session=open | volatility=high | move_type= | reaction=break_hold | vwap=above | volume=high | market=clean | test=first | level=resistance
Wins: 1
Losses: 0
Win Rate: 100.0 %
Sample Size: 1
PnL: 10448.59

asset=stock | timeframe=5m | htf=bullish | structure=higher_highs | session=open | volatility=high | move_type=expansion breakout | reaction=break_hold | vwap=above | volume=high | market=clean | test=first | level=resistance
Wins: 2
Losses: 0
Win Rate: 100.0 %
Sample Size: 2
PnL: 20897.18

=== JOURNAL SUMMARY ===
Total Trades: 15
Wins: 10
Losses: 5
Breakevens: 0
Win Rate: 66.67 %
Total PnL: 32387.27

=== SETUP BREAKDOWN ===

Retest Hold
Wins: 7
Losses: 0
Breakevens: 0
Win Rate: 100.0 %
PnL: 1476.5

No Trade
Wins: 0
Losses: 4
Breakevens: 0
Win Rate: 0.0 %
PnL: -325.0

Rejection
Wins: 0
Losses: 1
Breakevens: 0
Win Rate: 0.0 %
PnL: -110.0

Break and Hold
Wins: 3
Losses: 0
Breakevens: 0
Win Rate: 100.0 %
PnL: 31345.77

{'Retest Hold': {'wins': 7, 'losses': 0, 'breakevens': 0, 'pnl': 1476.5},
 'No Trade': {'wins': 0, 'losses': 4, 'breakevens': 0, 'pnl': -325.0},
 'Rejection': {'wins': 0, 'losses': 1, 'breakevens': 0, 'pnl': -110.0},
 'Break and Hold': {'wins': 3, 'losses': 0, 'breakevens': 0, 'pnl': 31345.77}}

In [ ]:
def backfill_one_line(
    symbol,
    reaction,
    level,
    vwap,
    rsi,
    volume,
    market,
    test,
    key_level,
    result_text,
    pnl,
    notes="",
    timeframe="5m",
    htf_bias="neutral",
    mtf_structure="neutral",
    session="open",
    volatility="medium",
    quality="B",
    move_type="unknown",
    oil_trend="unknown",
    oil_volatility="unknown",
    macro_event="none",
    market_sentiment="neutral",
    sector_strength="neutral",

    # NEW DETAIL FIELDS
    trade_window="unknown",
    environment="unknown",
    stop_type="unknown",
    execution_discipline="unknown",
    mistake_tag="none",
    confluence_factors=None
):
    return backfill_trade(
        symbol=symbol,
        level=level,
        reaction=reaction,
        vwap=vwap,
        rsi=rsi,
        volume=volume,
        market=market,
        test=test,
        key_level=key_level,
        result_text=result_text,
        pnl=pnl,
        notes=notes,
        timeframe=timeframe,
        htf_bias=htf_bias,
        mtf_structure=mtf_structure,
        session=session,
        volatility=volatility,
        quality=quality,
        move_type=move_type,
        oil_trend=oil_trend,
        oil_volatility=oil_volatility,
        macro_event=macro_event,
        market_sentiment=market_sentiment,
        sector_strength=sector_strength,
        trade_window=trade_window,
        environment=environment,
        stop_type=stop_type,
        execution_discipline=execution_discipline,
        mistake_tag=mistake_tag,
        confluence_factors=confluence_factors
    )

In [ ]:
def backfill_one_line(
    symbol,
    reaction,
    level,
    vwap,
    rsi,
    volume,
    market,
    test,
    key_level,
    result_text,
    pnl,
    notes="",
    timeframe="5m",
    htf_bias="neutral",
    mtf_structure="neutral",
    session="open",
    volatility="medium",
    quality="B",
    move_type="unknown"
):
    return backfill_trade(
        symbol=symbol,
        level=level,
        reaction=reaction,
        vwap=vwap,
        rsi=rsi,
        volume=volume,
        market=market,
        test=test,
        key_level=key_level,
        result_text=result_text,
        pnl=pnl,
        notes=notes,
        timeframe=timeframe,
        htf_bias=htf_bias,
        mtf_structure=mtf_structure,
        session=session,
        volatility=volatility,
        quality=quality,
        move_type=move_type
    )

In [ ]:
def quick_run(
    symbol,
    level,
    reaction,
    vwap,
    rsi,
    volume,
    market,
    test,
    key_level,
    timeframe=None,
    htf_bias=None,
    mtf_structure=None,
    session=None,
    volatility=None,
    move_type=None,
    quality=None,
    oil_trend=None,
    oil_volatility=None,
    macro_event=None,
    market_sentiment=None,
    sector_strength=None,

    # NEW DETAIL FIELDS
    trade_window=None,
    environment=None,
    stop_type=None,
    execution_discipline=None,
    mistake_tag=None,
    confluence_factors=None
):
    trade = {
        "symbol": symbol,
        "asset_type": get_asset_type(symbol),
        "level": level,
        "reaction": reaction,
        "vwap": vwap,
        "rsi": rsi,
        "volume": volume,
        "market": market,
        "test": test,
        "key_level": key_level,
        "timeframe": timeframe,
        "htf_bias": htf_bias,
        "mtf_structure": mtf_structure,
        "session": session,
        "volatility": volatility,
        "quality": quality,
        "move_type": move_type,
        "oil_trend": oil_trend,
        "oil_volatility": oil_volatility,
        "macro_event": macro_event,
        "market_sentiment": market_sentiment,
        "sector_strength": sector_strength,

        # NEW DETAIL FIELDS
        "trade_window": trade_window,
        "environment": environment,
        "stop_type": stop_type,
        "execution_discipline": execution_discipline,
        "mistake_tag": mistake_tag,
        "confluence_factors": confluence_factors or []
    }

    return full_analysis(trade)

In [ ]:
quick_run(
    "HOOD",
    "resistance",
    "break_hold",
    "above",
    65,
    "high",
    "clean",
    "first",
    "HOOD 130 resistance break",

    timeframe="5m",
    htf_bias="bullish",
    mtf_structure="higher_highs",
    session="open",
    volatility="high",
    move_type="expansion breakout",
    quality="A+"
)

=== FULL ANALYSIS ===

=== BEST MATCH ===
NAME: hood_break_hold_a1
CATEGORY: A_plus
MATCH SCORE: 12

--- FINAL OUTPUT ---
BIAS : CALL
SETUP_TYPE : Break and Hold
GRADE : A+
KEY_LEVEL : HOOD 130 resistance break
ENTRY_TRIGGER : Break above resistance holds with continuation
INVALIDATION : Loss of breakout level / loss of VWAP
TARGETS : Next resistance / extension target
CONFIDENCE : 100
REASONS : ['Break and hold above resistance', 'Bullish VWAP control', 'Bullish momentum', 'Volume confirmation', 'First test of level', 'Higher timeframe bullish bias', 'Bullish multi-timeframe structure', 'Momentum-friendly session', 'High-volatility breakout environment', 'Expansion breakout / squeeze behavior']
RISKS : []
FINAL_DECISION : CALL

PATTERN MATCH:
MATCHED SETUP: hood_break_hold_a1
CATEGORY: A_plus
MATCH SCORE: 12

=== PERFORMANCE TRACKING ===

A_plus
Wins: 1
Losses: 0
Win Rate: 100.0 %

B_setups
Wins: 0
Losses: 0
Win Rate: 0 %

No_trade
Wins: 0
Losses: 0
Win Rate: 0 %

KeyError: 'setup_type'

In [ ]:
learned_pattern_breakdown()
journal_summary()
setup_breakdown()

=== DEEP PATTERN STATS ===

reaction=retest_hold | vwap=above | volume=high | market=clean | test=first | level=support
Wins: 3
Losses: 0
Win Rate: 100.0 %
Sample Size: 3
PnL: 625.5

reaction=retest_hold | vwap=above | volume=low | market=clean | test=second | level=support
Wins: 0
Losses: 1
Win Rate: 0.0 %
Sample Size: 1
PnL: -95.0

asset=stock | reaction=retest_hold | vwap=above | volume=high | market=clean | test=first | level=support
Wins: 2
Losses: 0
Win Rate: 100.0 %
Sample Size: 2
PnL: 360.0

asset=stock | reaction=retest_hold | vwap=above | volume=low | market=clean | test=second | level=support
Wins: 0
Losses: 2
Win Rate: 0.0 %
Sample Size: 2
PnL: -190.0

asset=index | reaction=rejection | vwap=below | volume=high | market=clean | test=second | level=resistance
Wins: 0
Losses: 1
Win Rate: 0.0 %
Sample Size: 1
PnL: -110.0

asset=index | reaction=retest_hold | vwap=above | volume=low | market=chop | test=second | level=support
Wins: 0
Losses: 1
Win Rate: 0.0 %
Sample Size: 1
PnL: -40.0

asset=stock | timeframe=5m | htf=bullish | structure=higher_highs | session=open | volatility=high | move_type= | reaction=break_hold | vwap=above | volume=high | market=clean | test=first | level=resistance
Wins: 1
Losses: 0
Win Rate: 100.0 %
Sample Size: 1
PnL: 10448.59

asset=stock | timeframe=5m | htf=bullish | structure=higher_highs | session=open | volatility=high | move_type=expansion breakout | reaction=break_hold | vwap=above | volume=high | market=clean | test=first | level=resistance
Wins: 1
Losses: 0
Win Rate: 100.0 %
Sample Size: 1
PnL: 10448.59

=== JOURNAL SUMMARY ===
Total Trades: 14
Wins: 9
Losses: 5
Breakevens: 0
Win Rate: 64.29 %
Total PnL: 21938.68

=== SETUP BREAKDOWN ===

Retest Hold
Wins: 7
Losses: 0
Breakevens: 0
Win Rate: 100.0 %
PnL: 1476.5

No Trade
Wins: 0
Losses: 4
Breakevens: 0
Win Rate: 0.0 %
PnL: -325.0

Rejection
Wins: 0
Losses: 1
Breakevens: 0
Win Rate: 0.0 %
PnL: -110.0

Break and Hold
Wins: 2
Losses: 0
Breakevens: 0
Win Rate: 100.0 %
PnL: 20897.18

{'Retest Hold': {'wins': 7, 'losses': 0, 'breakevens': 0, 'pnl': 1476.5},
 'No Trade': {'wins': 0, 'losses': 4, 'breakevens': 0, 'pnl': -325.0},
 'Rejection': {'wins': 0, 'losses': 1, 'breakevens': 0, 'pnl': -110.0},
 'Break and Hold': {'wins': 2, 'losses': 0, 'breakevens': 0, 'pnl': 20897.18}}

In [ ]:
learned_pattern_breakdown()
journal_summary()
setup_breakdown()

=== DEEP PATTERN STATS ===

reaction=retest_hold | vwap=above | volume=high | market=clean | test=first | level=support
Wins: 3
Losses: 0
Win Rate: 100.0 %
Sample Size: 3
PnL: 625.5

reaction=retest_hold | vwap=above | volume=low | market=clean | test=second | level=support
Wins: 0
Losses: 1
Win Rate: 0.0 %
Sample Size: 1
PnL: -95.0

asset=stock | reaction=retest_hold | vwap=above | volume=high | market=clean | test=first | level=support
Wins: 2
Losses: 0
Win Rate: 100.0 %
Sample Size: 2
PnL: 360.0

asset=stock | reaction=retest_hold | vwap=above | volume=low | market=clean | test=second | level=support
Wins: 0
Losses: 2
Win Rate: 0.0 %
Sample Size: 2
PnL: -190.0

asset=index | reaction=rejection | vwap=below | volume=high | market=clean | test=second | level=resistance
Wins: 0
Losses: 1
Win Rate: 0.0 %
Sample Size: 1
PnL: -110.0

asset=index | reaction=retest_hold | vwap=above | volume=low | market=chop | test=second | level=support
Wins: 0
Losses: 1
Win Rate: 0.0 %
Sample Size: 1
PnL: -40.0

asset=stock | timeframe=5m | htf=bullish | structure=higher_highs | session=open | volatility=high | move_type= | reaction=break_hold | vwap=above | volume=high | market=clean | test=first | level=resistance
Wins: 1
Losses: 0
Win Rate: 100.0 %
Sample Size: 1
PnL: 10448.59

asset=stock | timeframe=5m | htf=bullish | structure=higher_highs | session=open | volatility=high | move_type=expansion breakout | reaction=break_hold | vwap=above | volume=high | market=clean | test=first | level=resistance
Wins: 1
Losses: 0
Win Rate: 100.0 %
Sample Size: 1
PnL: 10448.59

=== JOURNAL SUMMARY ===
Total Trades: 14
Wins: 9
Losses: 5
Breakevens: 0
Win Rate: 64.29 %
Total PnL: 21938.68

KeyError: 'setup_type'

In [ ]:
import json

with open("trade_journal.json", "r") as f:
    trade_journal = json.load(f)

print("✅ Journal reloaded")
print("Trades in memory:", len(trade_journal))

✅ Journal reloaded
Trades in memory: 14

In [ ]:
learned_pattern_breakdown()
journal_summary()
setup_breakdown()

=== DEEP PATTERN STATS ===

reaction=retest_hold | vwap=above | volume=high | market=clean | test=first | level=support
Wins: 3
Losses: 0
Win Rate: 100.0 %
Sample Size: 3
PnL: 625.5

reaction=retest_hold | vwap=above | volume=low | market=clean | test=second | level=support
Wins: 0
Losses: 1
Win Rate: 0.0 %
Sample Size: 1
PnL: -95.0

=== JOURNAL SUMMARY ===
Total Trades: 5
Wins: 4
Losses: 1
Breakevens: 0
Win Rate: 80.0 %
Total PnL: 776.0

=== SETUP BREAKDOWN ===

Retest Hold
Wins: 4
Losses: 0
Breakevens: 0
Win Rate: 100.0 %
PnL: 871.0

No Trade
Wins: 0
Losses: 1
Breakevens: 0
Win Rate: 0.0 %
PnL: -95.0

{'Retest Hold': {'wins': 4, 'losses': 0, 'breakevens': 0, 'pnl': 871.0},
 'No Trade': {'wins': 0, 'losses': 1, 'breakevens': 0, 'pnl': -95.0}}

In [ ]:
def backfill_trade(
    symbol,
    level,
    reaction,
    vwap,
    rsi,
    volume,
    market,
    test,
    key_level,
    result_text,
    pnl,
    notes="",
    timeframe="5m",
    htf_bias="neutral",
    mtf_structure="neutral",
    session="open",
    volatility="medium",
    quality="B",
    move_type="unknown",
    oil_trend="unknown",
    oil_volatility="unknown",
    macro_event="none",
    market_sentiment="neutral",
    sector_strength="neutral",

    # NEW DETAIL FIELDS
    trade_window="unknown",
    environment="unknown",
    stop_type="unknown",
    execution_discipline="unknown",
    mistake_tag="none",
    confluence_factors=None
):
    trade_input = {
        "symbol": symbol,
        "asset_type": get_asset_type(symbol),
        "level": level,
        "reaction": reaction,
        "vwap": vwap,
        "rsi": rsi,
        "volume": volume,
        "market": market,
        "test": test,
        "key_level": key_level,
        "timeframe": timeframe,
        "htf_bias": htf_bias,
        "mtf_structure": mtf_structure,
        "session": session,
        "volatility": volatility,
        "quality": quality,
        "move_type": move_type,
        "oil_trend": oil_trend,
        "oil_volatility": oil_volatility,
        "macro_event": macro_event,
        "market_sentiment": market_sentiment,
        "sector_strength": sector_strength,

        # NEW DETAIL FIELDS
        "trade_window": trade_window,
        "environment": environment,
        "stop_type": stop_type,
        "execution_discipline": execution_discipline,
        "mistake_tag": mistake_tag,
        "confluence_factors": confluence_factors or []
    }

    return log_from_analysis(
        symbol,
        trade_input,
        result_text,
        pnl,
        notes
    )

In [ ]:
backfill_trade(
    symbol="HOOD",
    level="resistance",
    reaction="break_hold",
    vwap="above",
    rsi=65,
    volume="high",
    market="clean",
    test="first",
    key_level="HOOD 130 resistance break",
    result_text="win",
    pnl=10448.59,
    notes="Break and Hold CALL. Expansion breakout from consolidation. Strong bullish trend, VWAP support, scaled out into exhaustion and VWAP loss.",
    timeframe="5m",
    htf_bias="bullish",
    mtf_structure="higher_highs",
    session="open",
    volatility="high",
    quality="A+",
    move_type="expansion breakout"
)

TypeError: backfill_trade() got an unexpected keyword argument 'move_type'

In [ ]:
def quick_run(
    symbol,
    level,
    reaction,
    vwap,
    rsi,
    volume,
    market,
    test,
    key_level,
    timeframe="5m",
    htf_bias="neutral",
    mtf_structure="neutral",
    session="open",
    volatility="medium",
    move_type="unknown",
    quality="B"
):

    trade = {
        "symbol": symbol,
        "asset_type": get_asset_type(symbol),
        "level": level,
        "reaction": reaction,
        "vwap": vwap,
        "rsi": rsi,
        "volume": volume,
        "market": market,
        "test": test,
        "key_level": key_level,

        # STRUCTURE DATA (IMPORTANT FOR LEARNING)
        "timeframe": timeframe,
        "htf_bias": htf_bias,
        "mtf_structure": mtf_structure,
        "session": session,
        "volatility": volatility,
        "move_type": move_type,

        # QUALITY TAG
        "quality": quality
    }

    return full_analysis(trade)

In [ ]:
saved_trades["A_plus"]["hood_break_hold_a1"] = {
    "symbol": "HOOD",
    "asset_type": "stock",
    "level": "resistance",
    "reaction": "break_hold",
    "vwap": "above",
    "rsi": 65,
    "volume": "high",
    "market": "clean",
    "test": "first",
    "key_level": "HOOD 130 resistance break",
    "timeframe": "5m",
    "htf_bias": "bullish",
    "mtf_structure": "higher_highs",
    "session": "open",
    "volatility": "high",
    "quality": "A+",
    "move_type": "expansion breakout"
}

In [ ]:
quick_run(
    "HOOD",
    "resistance",
    "break_hold",
    "above",
    65,
    "high",
    "clean",
    "first",
    "HOOD 130 resistance break",
    timeframe="5m",
    htf_bias="bullish",
    mtf_structure="higher_highs",
    session="open",
    volatility="high",
    quality="A+"
)

=== FULL ANALYSIS ===

=== BEST MATCH ===
NAME: hood_call_a1
CATEGORY: A_plus
MATCH SCORE: 9

--- FINAL OUTPUT ---
BIAS : CALL
SETUP_TYPE : Break and Hold
GRADE : A+
KEY_LEVEL : HOOD 130 resistance break
ENTRY_TRIGGER : Break above resistance holds with continuation
INVALIDATION : Loss of breakout level / loss of VWAP
TARGETS : Next resistance / extension target
CONFIDENCE : 100
REASONS : ['Break and hold above resistance', 'Bullish VWAP control', 'Bullish momentum', 'Volume confirmation', 'First test of level', 'Higher timeframe bullish bias', 'Bullish multi-timeframe structure', 'Momentum-friendly session', 'High-volatility breakout environment']
RISKS : []
FINAL_DECISION : CALL

PATTERN MATCH:
MATCHED SETUP: hood_call_a1
CATEGORY: A_plus
MATCH SCORE: 9

=== PERFORMANCE TRACKING ===

A_plus
Wins: 1
Losses: 0
Win Rate: 100.0 %

B_setups
Wins: 0
Losses: 0
Win Rate: 0 %

No_trade
Wins: 0
Losses: 0
Win Rate: 0 %

=== ADJUSTED CONFIDENCE ===
Base Confidence: 100
Category: A_plus
Category Win Rate: 100.0
Setup Type: Break and Hold
Setup Win Rate: 0
Setup Sample Size: 0
Deep Pattern Signature: asset=stock | timeframe=5m | htf=bullish | structure=higher_highs | session=open | volatility=high | move_type= | reaction=break_hold | vwap=above | volume=high | market=clean | test=first | level=resistance
Deep Pattern Win Rate: 0
Deep Pattern Sample Size: 0
Adjusted Confidence: 100

FINAL CONFIDENCE (ADJUSTED): 100

✅ TRADE ALLOWED

=== POSITION SIZING ===
Grade: A+
Confidence: 100
Risk Per Trade: 3%
Recommended Size: FULL SIZE
FINAL POSITION SIZE: FULL SIZE

In [ ]:
quick_run(...)

TypeError: quick_run() missing 8 required positional arguments: 'level', 'reaction', 'vwap', 'rsi', 'volume', 'market', 'test', and 'key_level'

In [ ]:
saved_trades["A_plus"]["hood_break_hold_a1"] = {
    "level": "resistance",
    "reaction": "break_hold",
    "vwap": "above",
    "volume": "high",
    "market": "clean",
    "test": "first"
}

In [ ]:
def backfill_trade(
    symbol,
    level,
    reaction,
    vwap,
    rsi,
    volume,
    market,
    test,
    key_level,
    result_text,
    pnl,
    notes="",
    timeframe="5m",
    htf_bias="neutral",
    mtf_structure="neutral",
    session="open",
    volatility="medium",
    quality="B",
    move_type=""
):
    trade_input = {
        "symbol": symbol,
        "asset_type": get_asset_type(symbol),
        "level": level,
        "reaction": reaction,
        "vwap": vwap,
        "rsi": rsi,
        "volume": volume,
        "market": market,
        "test": test,
        "key_level": key_level,
        "timeframe": timeframe,
        "htf_bias": htf_bias,
        "mtf_structure": mtf_structure,
        "session": session,
        "volatility": volatility,
        "quality": quality,
        "move_type": move_type
    }

    return log_from_analysis(
        symbol,
        trade_input,
        result_text,
        pnl,
        notes
    )

In [ ]:
quick_run(
    "HOOD",
    "resistance",
    "break_hold",
    "above",
    65,
    "high",
    "clean",
    "first",
    "HOOD 130 resistance break",
    timeframe="5m",
    htf_bias="bullish",
    mtf_structure="higher_highs",
    session="open",
    volatility="high",
    quality="A+",
    move_type="expansion breakout"
)

=== FULL ANALYSIS ===

=== BEST MATCH ===
NAME: hood_break_hold_a1
CATEGORY: A_plus
MATCH SCORE: 12

--- FINAL OUTPUT ---
BIAS : CALL
SETUP_TYPE : Break and Hold
GRADE : A+
KEY_LEVEL : HOOD 130 resistance break
ENTRY_TRIGGER : Break above resistance holds with continuation
INVALIDATION : Loss of breakout level / loss of VWAP
TARGETS : Next resistance / extension target
CONFIDENCE : 100
REASONS : ['Break and hold above resistance', 'Bullish VWAP control', 'Bullish momentum', 'Volume confirmation', 'First test of level', 'Higher timeframe bullish bias', 'Bullish multi-timeframe structure', 'Momentum-friendly session', 'High-volatility breakout environment', 'Expansion breakout / squeeze behavior']
RISKS : []
FINAL_DECISION : CALL

PATTERN MATCH:
MATCHED SETUP: hood_break_hold_a1
CATEGORY: A_plus
MATCH SCORE: 12

=== PERFORMANCE TRACKING ===

A_plus
Wins: 1
Losses: 0
Win Rate: 100.0 %

B_setups
Wins: 0
Losses: 0
Win Rate: 0 %

No_trade
Wins: 0
Losses: 0
Win Rate: 0 %

=== ADJUSTED CONFIDENCE ===
Base Confidence: 100
Category: A_plus
Category Win Rate: 100.0
Setup Type: Break and Hold
Setup Win Rate: 0
Setup Sample Size: 0
Deep Pattern Signature: asset=stock | timeframe=5m | htf=bullish | structure=higher_highs | session=open | volatility=high | move_type=expansion breakout | reaction=break_hold | vwap=above | volume=high | market=clean | test=first | level=resistance
Deep Pattern Win Rate: 0
Deep Pattern Sample Size: 0
Adjusted Confidence: 100

FINAL CONFIDENCE (ADJUSTED): 100

✅ TRADE ALLOWED

=== POSITION SIZING ===
Grade: A+
Confidence: 100
Risk Per Trade: 3%
Recommended Size: FULL SIZE
FINAL POSITION SIZE: FULL SIZE

In [ ]:
saved_trades["A_plus"]["hood_break_hold_a1"] = {
    "symbol": "HOOD",
    "asset_type": "stock",
    "level": "resistance",
    "reaction": "break_hold",
    "vwap": "above",
    "rsi": 65,
    "volume": "high",
    "market": "clean",
    "test": "first",
    "key_level": "HOOD 130 resistance break",
    "timeframe": "5m",
    "htf_bias": "bullish",
    "mtf_structure": "higher_highs",
    "session": "open",
    "volatility": "high",
    "quality": "A+",
    "move_type": "expansion breakout"
}

In [ ]:
def quick_run(symbol, level, reaction, vwap, rsi, volume, market, test, key_level,
              timeframe=None, htf_bias=None, mtf_structure=None, session=None,
              volatility=None, move_type=None, quality=None,
              oil_trend=None, oil_volatility=None, macro_event=None,
              market_sentiment=None, sector_strength=None,
              dark_pool_bias=None, dark_pool_level=None, dark_pool_size=None):

    trade = {
        "symbol": symbol,
        "asset_type": get_asset_type(symbol),
        "level": level,
        "reaction": reaction,
        "vwap": vwap,
        "rsi": rsi,
        "volume": volume,
        "market": market,
        "test": test,
        "key_level": key_level,
        "timeframe": timeframe,
        "htf_bias": htf_bias,
        "mtf_structure": mtf_structure,
        "session": session,
        "volatility": volatility,
        "quality": quality,
        "move_type": move_type,
        "oil_trend": oil_trend,
        "oil_volatility": oil_volatility,
        "macro_event": macro_event,
        "market_sentiment": market_sentiment,
        "sector_strength": sector_strength,
        "dark_pool_bias": dark_pool_bias,
        "dark_pool_level": dark_pool_level,
        "dark_pool_size": dark_pool_size
    }

    full_analysis(trade)

In [ ]:
def pattern_signature(trade):
    return " | ".join([
        f"asset={trade.get('asset_type', 'unknown')}",
        f"timeframe={trade.get('timeframe', 'unknown')}",
        f"htf={trade.get('htf_bias', 'unknown')}",
        f"structure={trade.get('mtf_structure', 'unknown')}",
        f"session={trade.get('session', 'unknown')}",
        f"volatility={trade.get('volatility', 'unknown')}",
        f"move_type={trade.get('move_type', 'unknown')}",
        f"oil={trade.get('oil_trend', 'unknown')}",
        f"oil_volatility={trade.get('oil_volatility', 'unknown')}",
        f"macro={trade.get('macro_event', 'unknown')}",
        f"sentiment={trade.get('market_sentiment', 'unknown')}",
        f"sector={trade.get('sector_strength', 'unknown')}",
        f"trade_window={trade.get('trade_window', 'unknown')}",
        f"environment={trade.get('environment', 'unknown')}",
        f"stop_type={trade.get('stop_type', 'unknown')}",
        f"execution={trade.get('execution_discipline', 'unknown')}",
        f"mistake={trade.get('mistake_tag', 'none')}",
        f"reaction={trade.get('reaction', 'unknown')}",
        f"vwap={trade.get('vwap', 'unknown')}",
        f"volume={trade.get('volume', 'unknown')}",
        f"market={trade.get('market', 'unknown')}",
        f"test={trade.get('test', 'unknown')}",
        f"level={trade.get('level', 'unknown')}",
        f"confluence={','.join(trade.get('confluence_factors', [])) if isinstance(trade.get('confluence_factors', []), list) else 'unknown'}"
    ])

In [ ]:
def analyze_structured_trade(data):
    score = 0
    reasons = []
    risks = []

    bias = "NO TRADE"
    setup_type = "None"
    grade = "C"
    confidence = 0

    level = data.get("level", "").lower()
    reaction = data.get("reaction", "").lower()
    vwap = data.get("vwap", "").lower()
    rsi = data.get("rsi", 50)
    volume = data.get("volume", "").lower()
    market = data.get("market", "").lower()
    test = str(data.get("test", "")).lower()
    key_level = data.get("key_level", "User-defined")
    htf_bias = data.get("htf_bias", "").lower()
    mtf_structure = data.get("mtf_structure", "").lower()
    session = data.get("session", "").lower()
    volatility = data.get("volatility", "").lower()
    move_type = data.get("move_type", "").lower()

    no_trade_words = ["chop", "sideways", "indecision", "news", "extended", "unclear"]
    if market in no_trade_words or vwap == "flip" or level == "unclear" or volume == "low":
        return {
            "bias": "NO TRADE",
            "setup_type": "No Trade",
            "grade": "C",
            "key_level": key_level,
            "entry_trigger": "None",
            "invalidation": "None",
            "targets": "None",
            "confidence": 20,
            "reasons": ["Conditions are not clean enough"],
            "risks": ["Chop / weak structure / poor confirmation"],
            "final_decision": "NO TRADE"
        }

    # Core setup classification
    if level == "resistance" and reaction == "rejection":
        score += 2
        bias = "PUT"
        setup_type = "Rejection"
        reasons.append("Rejection at resistance")

    elif level == "resistance" and reaction == "break_hold":
        score += 3
        bias = "CALL"
        setup_type = "Break and Hold"
        reasons.append("Break and hold above resistance")

    elif level == "support" and reaction == "retest_hold":
        score += 2
        bias = "CALL"
        setup_type = "Retest Hold"
        reasons.append("Retest held at support")

    elif level == "resistance" and reaction == "lower_high":
        score += 2
        bias = "PUT"
        setup_type = "Failed Bounce / Lower High"
        reasons.append("Lower high rejection at resistance")

    # VWAP
    if vwap == "below":
        score += 2
        reasons.append("Bearish VWAP control")
    elif vwap == "above":
        score += 2
        reasons.append("Bullish VWAP control")

    # RSI
    if rsi < 50:
        score += 1
        reasons.append("Bearish momentum")
    elif rsi > 50:
        score += 1
        reasons.append("Bullish momentum")

    # Volume
    if volume == "high":
        score += 2
        reasons.append("Volume confirmation")
    else:
        risks.append("No strong volume confirmation")

    # Test quality
    if test == "first":
        score += 1
        reasons.append("First test of level")
    elif test == "second":
        risks.append("Second test is weaker than first")
    elif test == "third":
        risks.append("Third test may be exhausted")

    # Structure alignment
    if htf_bias == "bullish":
        score += 1
        reasons.append("Higher timeframe bullish bias")
    elif htf_bias == "bearish" and bias == "CALL":
        risks.append("Counter-trend to higher timeframe bias")

    if mtf_structure in ["higher_highs", "higher_lows"] and bias == "CALL":
        score += 1
        reasons.append("Bullish multi-timeframe structure")
    elif mtf_structure in ["lower_highs", "lower_lows"] and bias == "CALL":
        risks.append("Weak multi-timeframe structure for CALL")

    # Session / volatility / move type logic
    if session in ["open", "power_hour"] and bias == "CALL":
        score += 1
        reasons.append("Momentum-friendly session")

    if volatility == "high" and bias == "CALL" and setup_type == "Break and Hold":
        score += 1
        reasons.append("High-volatility breakout environment")

    if move_type in ["expansion breakout", "breakout squeeze"] and setup_type == "Break and Hold":
        score += 2
        reasons.append("Expansion breakout / squeeze behavior")

    # Grade
    if score >= 10:
        grade = "A+"
    elif score >= 7:
        grade = "B"
    else:
        grade = "C"

    confidence = min(100, score * 10)

    # Entry / invalidation / targets
    if bias == "CALL" and setup_type == "Break and Hold":
        entry_trigger = "Break above resistance holds with continuation"
        invalidation = "Loss of breakout level / loss of VWAP"
        targets = "Next resistance / extension target"
    elif bias == "CALL":
        entry_trigger = "Retest bounce confirms"
        invalidation = "Loss of support / retest low"
        targets = "Next resistance / next key level"
    elif bias == "PUT":
        entry_trigger = "Rejection confirms or lower high fails"
        invalidation = "Break above rejection high / reclaimed level"
        targets = "Next support / next key level"
    else:
        entry_trigger = "None"
        invalidation = "None"
        targets = "None"

    if grade == "C":
        final_decision = "NO TRADE"
    else:
        final_decision = bias

    return {
        "bias": bias,
        "setup_type": setup_type,
        "grade": grade,
        "key_level": key_level,
        "entry_trigger": entry_trigger,
        "invalidation": invalidation,
        "targets": targets,
        "confidence": confidence,
        "reasons": reasons,
        "risks": risks,
        "final_decision": final_decision
    }

In [ ]:
learned_pattern_breakdown()
journal_summary()
setup_breakdown()

=== DEEP PATTERN STATS ===

reaction=retest_hold | vwap=above | volume=high | market=clean | test=first | level=support
Wins: 3
Losses: 0
Win Rate: 100.0 %
Sample Size: 3
PnL: 625.5

reaction=retest_hold | vwap=above | volume=low | market=clean | test=second | level=support
Wins: 0
Losses: 1
Win Rate: 0.0 %
Sample Size: 1
PnL: -95.0

=== JOURNAL SUMMARY ===
Total Trades: 5
Wins: 4
Losses: 1
Breakevens: 0
Win Rate: 80.0 %
Total PnL: 776.0

=== SETUP BREAKDOWN ===

Retest Hold
Wins: 4
Losses: 0
Breakevens: 0
Win Rate: 100.0 %
PnL: 871.0

No Trade
Wins: 0
Losses: 1
Breakevens: 0
Win Rate: 0.0 %
PnL: -95.0

{'Retest Hold': {'wins': 4, 'losses': 0, 'breakevens': 0, 'pnl': 871.0},
 'No Trade': {'wins': 0, 'losses': 1, 'breakevens': 0, 'pnl': -95.0}}

In [ ]:
def backfill_trade(
    symbol,
    level,
    reaction,
    vwap,
    rsi,
    volume,
    market,
    test,
    key_level,
    result_text,
    pnl,
    notes="",
    timeframe="5m",
    htf_bias="neutral",
    mtf_structure="neutral",
    session="open",
    volatility="medium",
    quality="B",
    move_type="unknown",
    oil_trend="unknown",
    oil_volatility="unknown",
    macro_event="none",
    market_sentiment="neutral",
    sector_strength="neutral",
    dark_pool_bias="unknown",
    dark_pool_level="unknown",
    dark_pool_size="unknown"
):
    trade_input = {
        "symbol": symbol,
        "asset_type": get_asset_type(symbol),
        "level": level,
        "reaction": reaction,
        "vwap": vwap,
        "rsi": rsi,
        "volume": volume,
        "market": market,
        "test": test,
        "key_level": key_level,
        "timeframe": timeframe,
        "htf_bias": htf_bias,
        "mtf_structure": mtf_structure,
        "session": session,
        "volatility": volatility,
        "quality": quality,
        "move_type": move_type,
        "oil_trend": oil_trend,
        "oil_volatility": oil_volatility,
        "macro_event": macro_event,
        "market_sentiment": market_sentiment,
        "sector_strength": sector_strength,
        "dark_pool_bias": dark_pool_bias,
        "dark_pool_level": dark_pool_level,
        "dark_pool_size": dark_pool_size
    }

    return log_from_analysis(
        symbol,
        trade_input,
        result_text,
        pnl,
        notes
    )

In [ ]:
backfill_trade(
    symbol="QQQ",
    level="resistance",
    reaction="rejection",
    vwap="below",
    rsi=46,
    volume="high",
    market="clean",
    test="second",
    key_level="QQQ 486.00",
    result_text="loss",
    pnl=-110,
    notes="Second-test rejection failed",
    timeframe="5m",
    htf_bias="bearish",
    mtf_structure="lower_highs",
    session="open",
    volatility="medium",
    quality="B"
)

=== PERFORMANCE TRACKING ===

A_plus
Wins: 1
Losses: 0
Win Rate: 100.0 %

B_setups
Wins: 0
Losses: 0
Win Rate: 0 %

No_trade
Wins: 0
Losses: 0
Win Rate: 0 %

=== ADJUSTED CONFIDENCE ===
Base Confidence: 90
Category: A_plus
Category Win Rate: 100.0
Setup Type: Rejection
Setup Win Rate: 0
Setup Sample Size: 0
Deep Pattern Signature: asset=index | reaction=rejection | vwap=below | volume=high | market=clean | test=second | level=resistance
Deep Pattern Win Rate: 0
Deep Pattern Sample Size: 0
Adjusted Confidence: 100

=== POSITION SIZING ===
Grade: A+
Confidence: 100
Risk Per Trade: 3%
Recommended Size: FULL SIZE
✅ Trade logged and saved

{'timestamp': '2026-04-12T18:04:44',
 'symbol': 'QQQ',
 'bias': 'PUT',
 'setup_type': 'Rejection',
 'grade': 'A+',
 'key_level': 'QQQ 486.00',
 'adjusted_confidence': 100,
 'position_size': 'FULL SIZE',
 'result': 'loss',
 'pnl': -110,
 'notes': 'Second-test rejection failed',
 'trade_input': {'symbol': 'QQQ',
  'asset_type': 'index',
  'level': 'resistance',
  'reaction': 'rejection',
  'vwap': 'below',
  'rsi': 46,
  'volume': 'high',
  'market': 'clean',
  'test': 'second',
  'key_level': 'QQQ 486.00',
  'timeframe': '5m',
  'htf_bias': 'bearish',
  'mtf_structure': 'lower_highs',
  'session': 'open',
  'volatility': 'medium',
  'quality': 'B'},
 'pattern_signature': 'asset=index | reaction=rejection | vwap=below | volume=high | market=clean | test=second | level=resistance'}

In [ ]:
backfill_trade(
    symbol="HOOD",
    level="support",
    reaction="retest_hold",
    vwap="above",
    rsi=55,
    volume="low",
    market="clean",
    test="second",
    key_level="HOOD 12.20",
    result_text="loss",
    pnl=-95,
    notes="Weak second-test retest hold, low volume",
    timeframe="5m",
    htf_bias="bullish",
    mtf_structure="higher_lows",
    session="open",
    volatility="high",
    quality="B"
)

=== PERFORMANCE TRACKING ===

A_plus
Wins: 1
Losses: 0
Win Rate: 100.0 %

B_setups
Wins: 0
Losses: 0
Win Rate: 0 %

No_trade
Wins: 0
Losses: 0
Win Rate: 0 %

=== ADJUSTED CONFIDENCE ===
Base Confidence: 20
Category: A_plus
Category Win Rate: 100.0
Setup Type: No Trade
Setup Win Rate: 0.0
Setup Sample Size: 1
Deep Pattern Signature: asset=stock | reaction=retest_hold | vwap=above | volume=low | market=clean | test=second | level=support
Deep Pattern Win Rate: 0
Deep Pattern Sample Size: 0
Adjusted Confidence: 30

=== POSITION SIZING ===
Grade: C
Confidence: 30
Risk Per Trade: 0%
Recommended Size: NO TRADE
✅ Trade logged and saved

{'timestamp': '2026-04-12T18:04:39',
 'symbol': 'HOOD',
 'bias': 'NO TRADE',
 'setup_type': 'No Trade',
 'grade': 'C',
 'key_level': 'HOOD 12.20',
 'adjusted_confidence': 30,
 'position_size': 'NO TRADE',
 'result': 'loss',
 'pnl': -95,
 'notes': 'Weak second-test retest hold, low volume',
 'trade_input': {'symbol': 'HOOD',
  'asset_type': 'stock',
  'level': 'support',
  'reaction': 'retest_hold',
  'vwap': 'above',
  'rsi': 55,
  'volume': 'low',
  'market': 'clean',
  'test': 'second',
  'key_level': 'HOOD 12.20',
  'timeframe': '5m',
  'htf_bias': 'bullish',
  'mtf_structure': 'higher_lows',
  'session': 'open',
  'volatility': 'high',
  'quality': 'B'},
 'pattern_signature': 'asset=stock | reaction=retest_hold | vwap=above | volume=low | market=clean | test=second | level=support'}

In [ ]:
backfill_trade(
    symbol="HOOD",
    level="support",
    reaction="retest_hold",
    vwap="above",
    rsi=60,
    volume="high",
    market="clean",
    test="first",
    key_level="HOOD 12.50",
    result_text="win",
    pnl=180,
    notes="Clean first-test retest hold",
    timeframe="5m",
    htf_bias="bullish",
    mtf_structure="higher_lows",
    session="open",
    volatility="high",
    quality="A"
)

=== PERFORMANCE TRACKING ===

A_plus
Wins: 1
Losses: 0
Win Rate: 100.0 %

B_setups
Wins: 0
Losses: 0
Win Rate: 0 %

No_trade
Wins: 0
Losses: 0
Win Rate: 0 %

=== ADJUSTED CONFIDENCE ===
Base Confidence: 100
Category: A_plus
Category Win Rate: 100.0
Setup Type: Retest Hold
Setup Win Rate: 100.0
Setup Sample Size: 4
Deep Pattern Signature: asset=stock | reaction=retest_hold | vwap=above | volume=high | market=clean | test=first | level=support
Deep Pattern Win Rate: 0
Deep Pattern Sample Size: 0
Adjusted Confidence: 100

=== POSITION SIZING ===
Grade: A+
Confidence: 100
Risk Per Trade: 3%
Recommended Size: FULL SIZE
✅ Trade logged and saved

{'timestamp': '2026-04-12T18:04:30',
 'symbol': 'HOOD',
 'bias': 'CALL',
 'setup_type': 'Retest Hold',
 'grade': 'A+',
 'key_level': 'HOOD 12.50',
 'adjusted_confidence': 100,
 'position_size': 'FULL SIZE',
 'result': 'win',
 'pnl': 180,
 'notes': 'Clean first-test retest hold',
 'trade_input': {'symbol': 'HOOD',
  'asset_type': 'stock',
  'level': 'support',
  'reaction': 'retest_hold',
  'vwap': 'above',
  'rsi': 60,
  'volume': 'high',
  'market': 'clean',
  'test': 'first',
  'key_level': 'HOOD 12.50',
  'timeframe': '5m',
  'htf_bias': 'bullish',
  'mtf_structure': 'higher_lows',
  'session': 'open',
  'volatility': 'high',
  'quality': 'A'},
 'pattern_signature': 'asset=stock | reaction=retest_hold | vwap=above | volume=high | market=clean | test=first | level=support'}

In [ ]:
def backfill_trade(
    symbol,
    level,
    reaction,
    vwap,
    rsi,
    volume,
    market,
    test,
    key_level,
    result_text,
    pnl,
    notes="",
    timeframe="5m",
    htf_bias="neutral",
    mtf_structure="neutral",
    session="open",
    volatility="medium",
    quality="B"
):
    trade_input = {
        "symbol": symbol,
        "asset_type": get_asset_type(symbol),
        "level": level,
        "reaction": reaction,
        "vwap": vwap,
        "rsi": rsi,
        "volume": volume,
        "market": market,
        "test": test,
        "key_level": key_level,
        "timeframe": timeframe,
        "htf_bias": htf_bias,
        "mtf_structure": mtf_structure,
        "session": session,
        "volatility": volatility,
        "quality": quality
    }

    return log_from_analysis(
        symbol,
        trade_input,
        result_text,
        pnl,
        notes
    )

In [ ]:
learned_pattern_breakdown()

=== DEEP PATTERN STATS ===

reaction=retest_hold | vwap=above | volume=high | market=clean | test=first | level=support
Wins: 3
Losses: 0
Win Rate: 100.0 %
Sample Size: 3
PnL: 625.5

reaction=retest_hold | vwap=above | volume=low | market=clean | test=second | level=support
Wins: 0
Losses: 1
Win Rate: 0.0 %
Sample Size: 1
PnL: -95.0

{'reaction=retest_hold | vwap=above | volume=high | market=clean | test=first | level=support': {'wins': 3,
  'losses': 0,
  'breakevens': 0,
  'pnl': 625.5,
  'win_rate': 100.0,
  'sample_size': 3},
 'reaction=retest_hold | vwap=above | volume=low | market=clean | test=second | level=support': {'wins': 0,
  'losses': 1,
  'breakevens': 0,
  'pnl': -95.0,
  'win_rate': 0.0,
  'sample_size': 1}}

In [ ]:
trade_input = {
    "symbol": "HOOD",
    "asset_type": "stock",
    "level": "support",
    "reaction": "retest_hold",
    "vwap": "above",
    "rsi": 55,
    "volume": "low",
    "market": "clean",
    "test": "second",
    "key_level": "HOOD 12.20",
    "timeframe": "5m",
    "htf_bias": "bullish",
    "mtf_structure": "higher_lows",
    "session": "open",
    "volatility": "high",
    "quality": "B"
}

log_from_analysis(
    "HOOD",
    trade_input,
    "loss",
    -95,
    "Weak second-test retest hold, low volume"
)

=== PERFORMANCE TRACKING ===

A_plus
Wins: 1
Losses: 0
Win Rate: 100.0 %

B_setups
Wins: 0
Losses: 0
Win Rate: 0 %

No_trade
Wins: 0
Losses: 0
Win Rate: 0 %

=== ADJUSTED CONFIDENCE ===
Base Confidence: 20
Category: A_plus
Category Win Rate: 100.0
Setup Type: No Trade
Setup Win Rate: 0.0
Setup Sample Size: 1
Deep Pattern Signature: asset=stock | reaction=retest_hold | vwap=above | volume=low | market=clean | test=second | level=support
Deep Pattern Win Rate: 0
Deep Pattern Sample Size: 0
Adjusted Confidence: 30

=== POSITION SIZING ===
Grade: C
Confidence: 30
Risk Per Trade: 0%
Recommended Size: NO TRADE
✅ Trade logged and saved

{'timestamp': '2026-04-12T18:02:26',
 'symbol': 'HOOD',
 'bias': 'NO TRADE',
 'setup_type': 'No Trade',
 'grade': 'C',
 'key_level': 'HOOD 12.20',
 'adjusted_confidence': 30,
 'position_size': 'NO TRADE',
 'result': 'loss',
 'pnl': -95,
 'notes': 'Weak second-test retest hold, low volume',
 'trade_input': {'symbol': 'HOOD',
  'asset_type': 'stock',
  'level': 'support',
  'reaction': 'retest_hold',
  'vwap': 'above',
  'rsi': 55,
  'volume': 'low',
  'market': 'clean',
  'test': 'second',
  'key_level': 'HOOD 12.20',
  'timeframe': '5m',
  'htf_bias': 'bullish',
  'mtf_structure': 'higher_lows',
  'session': 'open',
  'volatility': 'high',
  'quality': 'B'},
 'pattern_signature': 'asset=stock | reaction=retest_hold | vwap=above | volume=low | market=clean | test=second | level=support'}

In [ ]:
quick_run(
    "HOOD",
    "support",
    "retest_hold",
    "above",
    55,
    "low",
    "clean",
    "second",
    "HOOD 12.20"
)

=== FULL ANALYSIS ===

=== BEST MATCH ===
NAME: hood_call_a1
CATEGORY: A_plus
MATCH SCORE: 7

--- FINAL OUTPUT ---
BIAS : NO TRADE
SETUP_TYPE : No Trade
GRADE : C
KEY_LEVEL : HOOD 12.20
ENTRY_TRIGGER : None
INVALIDATION : None
TARGETS : None
CONFIDENCE : 20
REASONS : ['Conditions are not clean enough']
RISKS : ['Chop / weak structure / poor confirmation']
FINAL_DECISION : NO TRADE

PATTERN MATCH:
MATCHED SETUP: hood_call_a1
CATEGORY: A_plus
MATCH SCORE: 7

=== PERFORMANCE TRACKING ===

A_plus
Wins: 1
Losses: 0
Win Rate: 100.0 %

B_setups
Wins: 0
Losses: 0
Win Rate: 0 %

No_trade
Wins: 0
Losses: 0
Win Rate: 0 %

=== ADJUSTED CONFIDENCE ===
Base Confidence: 20
Category: A_plus
Category Win Rate: 100.0
Setup Type: No Trade
Setup Win Rate: 0.0
Setup Sample Size: 1
Deep Pattern Signature: asset=stock | reaction=retest_hold | vwap=above | volume=low | market=clean | test=second | level=support
Deep Pattern Win Rate: 0
Deep Pattern Sample Size: 0
Adjusted Confidence: 30

FINAL CONFIDENCE (ADJUSTED): 30

🚫 TRADE BLOCKED: Confidence too low

In [ ]:
quick_run(
    "HOOD",
    "support",
    "retest_hold",
    "above",
    60,
    "high",
    "clean",
    "first",
    "HOOD 12.50"
)

=== FULL ANALYSIS ===

=== BEST MATCH ===
NAME: hood_call_a1
CATEGORY: A_plus
MATCH SCORE: 9

--- FINAL OUTPUT ---
BIAS : CALL
SETUP_TYPE : Retest Hold
GRADE : A+
KEY_LEVEL : HOOD 12.50
ENTRY_TRIGGER : Break holds or retest bounce confirms
INVALIDATION : Loss of breakout level / retest low
TARGETS : Next resistance / next key level
CONFIDENCE : 100
REASONS : ['Retest held at support', 'Bullish VWAP control', 'Bullish momentum', 'Volume confirmation', 'First test of level']
RISKS : []
FINAL_DECISION : CALL

PATTERN MATCH:
MATCHED SETUP: hood_call_a1
CATEGORY: A_plus
MATCH SCORE: 9

=== PERFORMANCE TRACKING ===

A_plus
Wins: 1
Losses: 0
Win Rate: 100.0 %

B_setups
Wins: 0
Losses: 0
Win Rate: 0 %

No_trade
Wins: 0
Losses: 0
Win Rate: 0 %

=== ADJUSTED CONFIDENCE ===
Base Confidence: 100
Category: A_plus
Category Win Rate: 100.0
Setup Type: Retest Hold
Setup Win Rate: 100.0
Setup Sample Size: 4
Deep Pattern Signature: asset=stock | reaction=retest_hold | vwap=above | volume=high | market=clean | test=first | level=support
Deep Pattern Win Rate: 0
Deep Pattern Sample Size: 0
Adjusted Confidence: 100

FINAL CONFIDENCE (ADJUSTED): 100

✅ TRADE ALLOWED

=== POSITION SIZING ===
Grade: A+
Confidence: 100
Risk Per Trade: 3%
Recommended Size: FULL SIZE
FINAL POSITION SIZE: FULL SIZE

In [ ]:
learned_pattern_breakdown()

=== DEEP PATTERN STATS ===

reaction=retest_hold | vwap=above | volume=high | market=clean | test=first | level=support
Wins: 3
Losses: 0
Win Rate: 100.0 %
Sample Size: 3
PnL: 625.5

reaction=retest_hold | vwap=above | volume=low | market=clean | test=second | level=support
Wins: 0
Losses: 1
Win Rate: 0.0 %
Sample Size: 1
PnL: -95.0

{'reaction=retest_hold | vwap=above | volume=high | market=clean | test=first | level=support': {'wins': 3,
  'losses': 0,
  'breakevens': 0,
  'pnl': 625.5,
  'win_rate': 100.0,
  'sample_size': 3},
 'reaction=retest_hold | vwap=above | volume=low | market=clean | test=second | level=support': {'wins': 0,
  'losses': 1,
  'breakevens': 0,
  'pnl': -95.0,
  'win_rate': 0.0,
  'sample_size': 1}}

In [ ]:
log_from_analysis(
    "HOOD",
    trade_input,
    "win",
    180,
    "Clean first-test retest hold"
)

=== PERFORMANCE TRACKING ===

A_plus
Wins: 1
Losses: 0
Win Rate: 100.0 %

B_setups
Wins: 0
Losses: 0
Win Rate: 0 %

No_trade
Wins: 0
Losses: 0
Win Rate: 0 %

=== ADJUSTED CONFIDENCE ===
Base Confidence: 100
Category: A_plus
Category Win Rate: 100.0
Setup Type: Retest Hold
Setup Win Rate: 100.0
Setup Sample Size: 4
Deep Pattern Signature: asset=stock | reaction=retest_hold | vwap=above | volume=high | market=clean | test=first | level=support
Deep Pattern Win Rate: 0
Deep Pattern Sample Size: 0
Adjusted Confidence: 100

=== POSITION SIZING ===
Grade: A+
Confidence: 100
Risk Per Trade: 3%
Recommended Size: FULL SIZE
✅ Trade logged and saved

{'timestamp': '2026-04-12T17:58:21',
 'symbol': 'HOOD',
 'bias': 'CALL',
 'setup_type': 'Retest Hold',
 'grade': 'A+',
 'key_level': 'HOOD 12.50',
 'adjusted_confidence': 100,
 'position_size': 'FULL SIZE',
 'result': 'win',
 'pnl': 180,
 'notes': 'Clean first-test retest hold',
 'trade_input': {'symbol': 'HOOD',
  'asset_type': 'stock',
  'level': 'support',
  'reaction': 'retest_hold',
  'vwap': 'above',
  'rsi': 60,
  'volume': 'high',
  'market': 'clean',
  'test': 'first',
  'key_level': 'HOOD 12.50',
  'timeframe': '5m',
  'htf_bias': 'bullish',
  'mtf_structure': 'higher_lows',
  'session': 'open',
  'volatility': 'high',
  'quality': 'A'},
 'pattern_signature': 'asset=stock | reaction=retest_hold | vwap=above | volume=high | market=clean | test=first | level=support'}

In [ ]:
log_from_analysis(
    "HOOD",
    trade_input,
    "win",
    180,
    "Clean first-test retest hold"
)

=== PERFORMANCE TRACKING ===

A_plus
Wins: 1
Losses: 0
Win Rate: 100.0 %

B_setups
Wins: 0
Losses: 0
Win Rate: 0 %

No_trade
Wins: 0
Losses: 0
Win Rate: 0 %

=== ADJUSTED CONFIDENCE ===
Base Confidence: 100
Category: A_plus
Category Win Rate: 100.0
Setup Type: Retest Hold
Setup Win Rate: 100.0
Setup Sample Size: 4
Deep Pattern Signature:
Deep Pattern Win Rate: 0
Deep Pattern Sample Size: 0
Adjusted Confidence: 100

=== POSITION SIZING ===
Grade: A+
Confidence: 100
Risk Per Trade: 3%
Recommended Size: FULL SIZE

TypeError: log_trade() takes from 4 to 5 positional arguments but 9 were given

In [ ]:
trade_input = {
    "symbol": "HOOD",
    "asset_type": "stock",
    "level": "support",
    "reaction": "retest_hold",
    "vwap": "above",
    "rsi": 60,
    "volume": "high",
    "market": "clean",
    "test": "first",
    "key_level": "HOOD 12.50",
    "timeframe": "5m",
    "htf_bias": "bullish",
    "mtf_structure": "higher_lows",
    "session": "open",
    "volatility": "high",
    "quality": "A"
}

log_from_analysis(
    "HOOD",
    trade_input,
    "win",
    180,
    "Clean first-test retest hold on HOOD"
)

=== PERFORMANCE TRACKING ===

A_plus
Wins: 1
Losses: 0
Win Rate: 100.0 %

B_setups
Wins: 0
Losses: 0
Win Rate: 0 %

No_trade
Wins: 0
Losses: 0
Win Rate: 0 %

=== ADJUSTED CONFIDENCE ===
Base Confidence: 100
Category: A_plus
Category Win Rate: 100.0
Setup Type: Retest Hold
Setup Win Rate: 100.0
Setup Sample Size: 4
Deep Pattern Signature: asset=stock | reaction=retest_hold | vwap=above | volume=high | market=clean | test=first | level=support
Deep Pattern Win Rate: 0
Deep Pattern Sample Size: 0
Adjusted Confidence: 100

=== POSITION SIZING ===
Grade: A+
Confidence: 100
Risk Per Trade: 3%
Recommended Size: FULL SIZE

TypeError: log_trade() got an unexpected keyword argument 'ticker'

In [ ]:
quick_run(
    "HOOD",
    "support",
    "retest_hold",
    "above",
    60,
    "high",
    "clean",
    "first",
    "HOOD 12.50"
)

=== FULL ANALYSIS ===

=== BEST MATCH ===
NAME: hood_call_a1
CATEGORY: A_plus
MATCH SCORE: 9

--- FINAL OUTPUT ---
BIAS : CALL
SETUP_TYPE : Retest Hold
GRADE : A+
KEY_LEVEL : HOOD 12.50
ENTRY_TRIGGER : Break holds or retest bounce confirms
INVALIDATION : Loss of breakout level / retest low
TARGETS : Next resistance / next key level
CONFIDENCE : 100
REASONS : ['Retest held at support', 'Bullish VWAP control', 'Bullish momentum', 'Volume confirmation', 'First test of level']
RISKS : []
FINAL_DECISION : CALL

PATTERN MATCH:
MATCHED SETUP: hood_call_a1
CATEGORY: A_plus
MATCH SCORE: 9

=== PERFORMANCE TRACKING ===

A_plus
Wins: 1
Losses: 0
Win Rate: 100.0 %

B_setups
Wins: 0
Losses: 0
Win Rate: 0 %

No_trade
Wins: 0
Losses: 0
Win Rate: 0 %

=== ADJUSTED CONFIDENCE ===
Base Confidence: 100
Category: A_plus
Category Win Rate: 100.0
Setup Type: Retest Hold
Setup Win Rate: 100.0
Setup Sample Size: 4
Deep Pattern Signature: asset=stock | reaction=retest_hold | vwap=above | volume=high | market=clean | test=first | level=support
Deep Pattern Win Rate: 0
Deep Pattern Sample Size: 0
Adjusted Confidence: 100

FINAL CONFIDENCE (ADJUSTED): 100

✅ TRADE ALLOWED

=== POSITION SIZING ===
Grade: A+
Confidence: 100
Risk Per Trade: 3%
Recommended Size: FULL SIZE
FINAL POSITION SIZE: FULL SIZE

In [ ]:
def quick_run(symbol, level, reaction, vwap, rsi, volume, market, test, key_level,
              timeframe="5m", htf_bias="neutral", mtf_structure="neutral",
              session="open", volatility="medium", quality="B"):

    trade = {
        "symbol": symbol,
        "asset_type": get_asset_type(symbol),
        "level": level,
        "reaction": reaction,
        "vwap": vwap,
        "rsi": rsi,
        "volume": volume,
        "market": market,
        "test": test,
        "key_level": key_level,
        "timeframe": timeframe,
        "htf_bias": htf_bias,
        "mtf_structure": mtf_structure,
        "session": session,
        "volatility": volatility,
        "quality": quality
    }

    full_analysis(trade)

In [ ]:
saved_trades["A_plus"]["hood_call_a1"] = {
    "symbol": "HOOD",
    "asset_type": "stock",
    "level": "support",
    "reaction": "retest_hold",
    "vwap": "above",
    "rsi": 60,
    "volume": "high",
    "market": "clean",
    "test": "first",
    "key_level": "HOOD 12.50",
    "timeframe": "5m",
    "htf_bias": "bullish",
    "mtf_structure": "higher_lows",
    "session": "open",
    "volatility": "high",
    "quality": "A"
}

In [ ]:
def quick_run(symbol, level, reaction, vwap, rsi, volume, market, test, key_level,
              timeframe="5m", htf_bias="neutral", mtf_structure="neutral",
              session="open", volatility="medium", quality="B"):

    trade = {
        "symbol": symbol,
        "asset_type": get_asset_type(symbol),
        "level": level,
        "reaction": reaction,
        "vwap": vwap,
        "rsi": rsi,
        "volume": volume,
        "market": market,
        "test": test,
        "key_level": key_level,
        "timeframe": timeframe,
        "htf_bias": htf_bias,
        "mtf_structure": mtf_structure,
        "session": session,
        "volatility": volatility,
        "quality": quality
    }

    full_analysis(trade)

In [ ]:
quick_run(
    "HOOD",
    "support",
    "retest_hold",
    "above",
    60,
    "high",
    "clean",
    "first",
    "HOOD 12.50"
)

=== FULL ANALYSIS ===

=== BEST MATCH ===
NAME: qqq_call_a1
CATEGORY: A_plus
MATCH SCORE: 6

--- FINAL OUTPUT ---
BIAS : CALL
SETUP_TYPE : Retest Hold
GRADE : A+
KEY_LEVEL : HOOD 12.50
ENTRY_TRIGGER : Break holds or retest bounce confirms
INVALIDATION : Loss of breakout level / retest low
TARGETS : Next resistance / next key level
CONFIDENCE : 100
REASONS : ['Retest held at support', 'Bullish VWAP control', 'Bullish momentum', 'Volume confirmation', 'First test of level']
RISKS : []
FINAL_DECISION : CALL

PATTERN MATCH:
MATCHED SETUP: qqq_call_a1
CATEGORY: A_plus
MATCH SCORE: 6

=== PERFORMANCE TRACKING ===

A_plus
Wins: 1
Losses: 0
Win Rate: 100.0 %

B_setups
Wins: 0
Losses: 0
Win Rate: 0 %

No_trade
Wins: 0
Losses: 0
Win Rate: 0 %

=== ADJUSTED CONFIDENCE ===
Base Confidence: 100
Category: A_plus
Category Win Rate: 100.0
Setup Type: Retest Hold
Setup Win Rate: 100.0
Setup Sample Size: 4
Deep Pattern Signature: asset=stock | reaction=retest_hold | vwap=above | volume=high | market=clean | test=first | level=support
Deep Pattern Win Rate: 0
Deep Pattern Sample Size: 0
Adjusted Confidence: 100

FINAL CONFIDENCE (ADJUSTED): 100

✅ TRADE ALLOWED

=== POSITION SIZING ===
Grade: A+
Confidence: 100
Risk Per Trade: 3%
Recommended Size: FULL SIZE
FINAL POSITION SIZE: FULL SIZE

In [ ]:
quick_run(
    "QQQ",
    "support",
    "retest_hold",
    "above",
    62,
    "high",
    "clean",
    "first",
    "QQQ 483.40"
)

=== FULL ANALYSIS ===

=== BEST MATCH ===
NAME: qqq_call_a2
CATEGORY: A_plus
MATCH SCORE: 7

--- FINAL OUTPUT ---
BIAS : CALL
SETUP_TYPE : Retest Hold
GRADE : A+
KEY_LEVEL : QQQ 483.40
ENTRY_TRIGGER : Break holds or retest bounce confirms
INVALIDATION : Loss of breakout level / retest low
TARGETS : Next resistance / next key level
CONFIDENCE : 100
REASONS : ['Retest held at support', 'Bullish VWAP control', 'Bullish momentum', 'Volume confirmation', 'First test of level']
RISKS : []
FINAL_DECISION : CALL

PATTERN MATCH:
MATCHED SETUP: qqq_call_a2
CATEGORY: A_plus
MATCH SCORE: 7

=== PERFORMANCE TRACKING ===

A_plus
Wins: 1
Losses: 0
Win Rate: 100.0 %

B_setups
Wins: 0
Losses: 0
Win Rate: 0 %

No_trade
Wins: 0
Losses: 0
Win Rate: 0 %

=== ADJUSTED CONFIDENCE ===
Base Confidence: 100
Category: A_plus
Category Win Rate: 100.0
Setup Type: Retest Hold
Setup Win Rate: 100.0
Setup Sample Size: 4
Deep Pattern Signature: asset=index | reaction=retest_hold | vwap=above | volume=high | market=clean | test=first | level=support
Deep Pattern Win Rate: 0
Deep Pattern Sample Size: 0
Adjusted Confidence: 100

FINAL CONFIDENCE (ADJUSTED): 100

✅ TRADE ALLOWED

=== POSITION SIZING ===
Grade: A+
Confidence: 100
Risk Per Trade: 3%
Recommended Size: FULL SIZE
FINAL POSITION SIZE: FULL SIZE

In [ ]:
def pattern_signature(trade):
    return " | ".join([
        f"asset={trade.get('asset_type', '')}",
        f"reaction={trade.get('reaction', '')}",
        f"vwap={trade.get('vwap', '')}",
        f"volume={trade.get('volume', '')}",
        f"market={trade.get('market', '')}",
        f"test={trade.get('test', '')}",
        f"level={trade.get('level', '')}"
    ])

In [ ]:
def quick_run(symbol, level, reaction, vwap, rsi, volume, market, test, key_level):
    trade = {
        "symbol": symbol,
        "asset_type": get_asset_type(symbol),  # 🔥 auto-detect
        "level": level,
        "reaction": reaction,
        "vwap": vwap,
        "rsi": rsi,
        "volume": volume,
        "market": market,
        "test": test,
        "key_level": key_level
    }

    full_analysis(trade)

In [ ]:
def get_asset_type(symbol):
    index_list = ["QQQ", "SPY", "IWM", "DIA"]

    if symbol.upper() in index_list:
        return "index"
    else:
        return "stock"

In [ ]:
quick_run(
    "HOOD",
    "stock",
    "support",
    "retest_hold",
    "above",
    60,
    "high",
    "clean",
    "first",
    "HOOD 12.50"
)

=== FULL ANALYSIS ===

=== BEST MATCH ===
NAME: qqq_call_a1
CATEGORY: A_plus
MATCH SCORE: 6

--- FINAL OUTPUT ---
BIAS : CALL
SETUP_TYPE : Retest Hold
GRADE : A+
KEY_LEVEL : HOOD 12.50
ENTRY_TRIGGER : Break holds or retest bounce confirms
INVALIDATION : Loss of breakout level / retest low
TARGETS : Next resistance / next key level
CONFIDENCE : 100
REASONS : ['Retest held at support', 'Bullish VWAP control', 'Bullish momentum', 'Volume confirmation', 'First test of level']
RISKS : []
FINAL_DECISION : CALL

PATTERN MATCH:
MATCHED SETUP: qqq_call_a1
CATEGORY: A_plus
MATCH SCORE: 6

=== PERFORMANCE TRACKING ===

A_plus
Wins: 1
Losses: 0
Win Rate: 100.0 %

B_setups
Wins: 0
Losses: 0
Win Rate: 0 %

No_trade
Wins: 0
Losses: 0
Win Rate: 0 %

=== ADJUSTED CONFIDENCE ===
Base Confidence: 100
Category: A_plus
Category Win Rate: 100.0
Setup Type: Retest Hold
Setup Win Rate: 100.0
Setup Sample Size: 4
Deep Pattern Signature: asset=stock | reaction=retest_hold | vwap=above | volume=high | market=clean | test=first | level=support
Deep Pattern Win Rate: 0
Deep Pattern Sample Size: 0
Adjusted Confidence: 100

FINAL CONFIDENCE (ADJUSTED): 100

✅ TRADE ALLOWED

=== POSITION SIZING ===
Grade: A+
Confidence: 100
Risk Per Trade: 3%
Recommended Size: FULL SIZE
FINAL POSITION SIZE: FULL SIZE

In [ ]:
quick_run(
    "QQQ",
    "index",        # 🔥 THIS is where asset_type goes
    "support",
    "retest_hold",
    "above",
    62,
    "high",
    "clean",
    "first",
    "QQQ 483.40"
)

=== FULL ANALYSIS ===

=== BEST MATCH ===
NAME: qqq_call_a2
CATEGORY: A_plus
MATCH SCORE: 7

--- FINAL OUTPUT ---
BIAS : CALL
SETUP_TYPE : Retest Hold
GRADE : A+
KEY_LEVEL : QQQ 483.40
ENTRY_TRIGGER : Break holds or retest bounce confirms
INVALIDATION : Loss of breakout level / retest low
TARGETS : Next resistance / next key level
CONFIDENCE : 100
REASONS : ['Retest held at support', 'Bullish VWAP control', 'Bullish momentum', 'Volume confirmation', 'First test of level']
RISKS : []
FINAL_DECISION : CALL

PATTERN MATCH:
MATCHED SETUP: qqq_call_a2
CATEGORY: A_plus
MATCH SCORE: 7

=== PERFORMANCE TRACKING ===

A_plus
Wins: 1
Losses: 0
Win Rate: 100.0 %

B_setups
Wins: 0
Losses: 0
Win Rate: 0 %

No_trade
Wins: 0
Losses: 0
Win Rate: 0 %

=== ADJUSTED CONFIDENCE ===
Base Confidence: 100
Category: A_plus
Category Win Rate: 100.0
Setup Type: Retest Hold
Setup Win Rate: 100.0
Setup Sample Size: 4
Deep Pattern Signature: asset=index | reaction=retest_hold | vwap=above | volume=high | market=clean | test=first | level=support
Deep Pattern Win Rate: 0
Deep Pattern Sample Size: 0
Adjusted Confidence: 100

FINAL CONFIDENCE (ADJUSTED): 100

✅ TRADE ALLOWED

=== POSITION SIZING ===
Grade: A+
Confidence: 100
Risk Per Trade: 3%
Recommended Size: FULL SIZE
FINAL POSITION SIZE: FULL SIZE

In [ ]:
def quick_run(symbol, asset_type, level, reaction, vwap, rsi, volume, market, test, key_level):
    trade = {
        "symbol": symbol,
        "asset_type": asset_type,   # 🔥 now included
        "level": level,
        "reaction": reaction,
        "vwap": vwap,
        "rsi": rsi,
        "volume": volume,
        "market": market,
        "test": test,
        "key_level": key_level
    }

    full_analysis(trade)

In [ ]:
"asset_type": "index"

SyntaxError: illegal target for annotation (289678640.py, line 1)

In [ ]:
quick_run(
    "QQQ",
    "support",
    "retest_hold",
    "above",
    62,
    "high",
    "clean",
    "first",
    "QQQ 483.40"
)

=== FULL ANALYSIS ===

=== BEST MATCH ===
NAME: qqq_call_a2
CATEGORY: A_plus
MATCH SCORE: 7

--- FINAL OUTPUT ---
BIAS : CALL
SETUP_TYPE : Retest Hold
GRADE : A+
KEY_LEVEL : QQQ 483.40
ENTRY_TRIGGER : Break holds or retest bounce confirms
INVALIDATION : Loss of breakout level / retest low
TARGETS : Next resistance / next key level
CONFIDENCE : 100
REASONS : ['Retest held at support', 'Bullish VWAP control', 'Bullish momentum', 'Volume confirmation', 'First test of level']
RISKS : []
FINAL_DECISION : CALL

PATTERN MATCH:
MATCHED SETUP: qqq_call_a2
CATEGORY: A_plus
MATCH SCORE: 7

=== PERFORMANCE TRACKING ===

A_plus
Wins: 1
Losses: 0
Win Rate: 100.0 %

B_setups
Wins: 0
Losses: 0
Win Rate: 0 %

No_trade
Wins: 0
Losses: 0
Win Rate: 0 %

=== ADJUSTED CONFIDENCE ===
Base Confidence: 100
Category: A_plus
Category Win Rate: 100.0
Setup Type: Retest Hold
Setup Win Rate: 100.0
Setup Sample Size: 4
Deep Pattern Signature: asset= | reaction=retest_hold | vwap=above | volume=high | market=clean | test=first | level=support
Deep Pattern Win Rate: 0
Deep Pattern Sample Size: 0
Adjusted Confidence: 100

FINAL CONFIDENCE (ADJUSTED): 100

✅ TRADE ALLOWED

=== POSITION SIZING ===
Grade: A+
Confidence: 100
Risk Per Trade: 3%
Recommended Size: FULL SIZE
FINAL POSITION SIZE: FULL SIZE

In [ ]:
def pattern_signature(trade):
    return " | ".join([
        f"asset={trade.get('asset_type', '')}",
        f"reaction={trade.get('reaction', '')}",
        f"vwap={trade.get('vwap', '')}",
        f"volume={trade.get('volume', '')}",
        f"market={trade.get('market', '')}",
        f"test={trade.get('test', '')}",
        f"level={trade.get('level', '')}"
    ])

In [ ]:
def log_trade(
    symbol,
    bias,
    setup_type,
    grade,
    key_level,
    adjusted_confidence,
    position_size,
    result,
    pnl,
    notes="",
    trade_input=None
):
    import json
    from datetime import datetime

    global trade_journal

    entry = {
        "timestamp": datetime.now().isoformat(timespec="seconds"),
        "symbol": symbol,
        "bias": bias,
        "setup_type": setup_type,
        "grade": grade,
        "key_level": key_level,
        "adjusted_confidence": adjusted_confidence,
        "position_size": position_size,
        "result": result,
        "pnl": pnl,
        "notes": notes,
        "trade_input": trade_input if trade_input else {},
        "pattern_signature": pattern_signature(trade_input) if trade_input else ""
    }

    trade_journal.append(entry)

    with open("trade_journal.json", "w") as f:
        json.dump(trade_journal, f, indent=4)

    print("✅ Trade logged and saved")
    return entry

In [ ]:
def log_trade(symbol, setup_type, result, pnl, notes=""):
    import json
    from datetime import datetime

    trade = {
        "symbol": symbol,
        "setup": setup_type,
        "result": result,  # win / loss / breakeven
        "pnl": pnl,
        "notes": notes,
        "timestamp": str(datetime.now())
    }

    try:
        with open("trade_journal.json", "r") as f:
            journal = json.load(f)
    except:
        journal = []

    journal.append(trade)

    with open("trade_journal.json", "w") as f:
        json.dump(journal, f, indent=4)

    print("✅ Trade logged")

In [ ]:
quick_run(
    "QQQ",
    "support",
    "retest_hold",
    "above",
    62,
    "high",
    "clean",
    "first",
    "QQQ 483.40"
)

=== FULL ANALYSIS ===

=== BEST MATCH ===
NAME: qqq_call_a2
CATEGORY: A_plus
MATCH SCORE: 7

--- FINAL OUTPUT ---
BIAS : CALL
SETUP_TYPE : Retest Hold
GRADE : A+
KEY_LEVEL : QQQ 483.40
ENTRY_TRIGGER : Break holds or retest bounce confirms
INVALIDATION : Loss of breakout level / retest low
TARGETS : Next resistance / next key level
CONFIDENCE : 100
REASONS : ['Retest held at support', 'Bullish VWAP control', 'Bullish momentum', 'Volume confirmation', 'First test of level']
RISKS : []
FINAL_DECISION : CALL

PATTERN MATCH:
MATCHED SETUP: qqq_call_a2
CATEGORY: A_plus
MATCH SCORE: 7

=== PERFORMANCE TRACKING ===

A_plus
Wins: 1
Losses: 0
Win Rate: 100.0 %

B_setups
Wins: 0
Losses: 0
Win Rate: 0 %

No_trade
Wins: 0
Losses: 0
Win Rate: 0 %

=== ADJUSTED CONFIDENCE ===
Base Confidence: 100
Category: A_plus
Category Win Rate: 100.0
Setup Type: Retest Hold
Setup Win Rate: 100.0
Setup Sample Size: 4
Deep Pattern Signature: reaction=retest_hold | vwap=above | volume=high | market=clean | test=first | level=support
Deep Pattern Win Rate: 100.0
Deep Pattern Sample Size: 3
Adjusted Confidence: 100

FINAL CONFIDENCE (ADJUSTED): 100

✅ TRADE ALLOWED

=== POSITION SIZING ===
Grade: A+
Confidence: 100
Risk Per Trade: 3%
Recommended Size: FULL SIZE
FINAL POSITION SIZE: FULL SIZE

In [ ]:
def quick_run(symbol, level, reaction, vwap, rsi, volume, market, test, key_level):
    trade = {
        "symbol": symbol,
        "level": level,
        "reaction": reaction,
        "vwap": vwap,
        "rsi": rsi,
        "volume": volume,
        "market": market,
        "test": test,
        "key_level": key_level
    }

    full_analysis(trade)

In [ ]:
test_trade = {
    "level": "support",
    "reaction": "retest_hold",
    "vwap": "above",
    "rsi": 60,
    "volume": "high",
    "market": "clean",
    "test": "first",
    "key_level": "QQQ 483.40"
}

log_from_analysis("QQQ", test_trade, "win", 200, "test save")

=== PERFORMANCE TRACKING ===

A_plus
Wins: 1
Losses: 0
Win Rate: 100.0 %

B_setups
Wins: 0
Losses: 0
Win Rate: 0 %

No_trade
Wins: 0
Losses: 0
Win Rate: 0 %

=== ADJUSTED CONFIDENCE ===
Base Confidence: 100
Category: A_plus
Category Win Rate: 100.0
Setup Type: Retest Hold
Setup Win Rate: 100.0
Setup Sample Size: 3
Deep Pattern Signature: reaction=retest_hold | vwap=above | volume=high | market=clean | test=first | level=support
Deep Pattern Win Rate: 100.0
Deep Pattern Sample Size: 2
Adjusted Confidence: 100

=== POSITION SIZING ===
Grade: A+
Confidence: 100
Risk Per Trade: 3%
Recommended Size: FULL SIZE
✅ Trade logged and saved

{'timestamp': '2026-04-12T17:32:20',
 'ticker': 'QQQ',
 'bias': 'CALL',
 'setup_type': 'Retest Hold',
 'grade': 'A+',
 'key_level': 'QQQ 483.40',
 'adjusted_confidence': 100,
 'position_size': 'FULL SIZE',
 'result': 'win',
 'pnl': 200,
 'notes': 'test save',
 'trade_input': {'level': 'support',
  'reaction': 'retest_hold',
  'vwap': 'above',
  'rsi': 60,
  'volume': 'high',
  'market': 'clean',
  'test': 'first',
  'key_level': 'QQQ 483.40'},
 'pattern_signature': 'reaction=retest_hold | vwap=above | volume=high | market=clean | test=first | level=support'}

In [ ]:
def learned_pattern_breakdown():
    stats = learned_pattern_stats()

    print("\n=== DEEP PATTERN STATS ===")
    for sig, s in stats.items():
        print(f"\n{sig}")
        print("Wins:", s["wins"])
        print("Losses:", s["losses"])
        print("Win Rate:", s["win_rate"], "%")
        print("Sample Size:", s["sample_size"])
        print("PnL:", s["pnl"])

In [ ]:
def learned_pattern_stats():
    stats = {}

    for t in trade_journal:
        # SAFE pulls (prevents errors)
        asset = t.get("trade_input", {}).get("asset_type", "unknown")
        timeframe = t.get("trade_input", {}).get("timeframe", "unknown")
        htf = t.get("trade_input", {}).get("htf_bias", "unknown")
        structure = t.get("trade_input", {}).get("mtf_structure", "unknown")
        session = t.get("trade_input", {}).get("session", "unknown")
        volatility = t.get("trade_input", {}).get("volatility", "unknown")

        reaction = t.get("trade_input", {}).get("reaction", "unknown")
        vwap = t.get("trade_input", {}).get("vwap", "unknown")
        volume = t.get("trade_input", {}).get("volume", "unknown")
        market = t.get("trade_input", {}).get("market", "unknown")
        test = t.get("trade_input", {}).get("test", "unknown")
        level = t.get("trade_input", {}).get("level", "unknown")

        move = t.get("trade_input", {}).get("move_type", "unknown")

        # BUILD SIGNATURE
        sig = f"asset={asset} | timeframe={timeframe} | htf={htf} | structure={structure} | session={session} | volatility={volatility} | move_type={move} | reaction={reaction} | vwap={vwap} | volume={volume} | market={market} | test={test} | level={level}"

        if sig not in stats:
            stats[sig] = {
                "wins": 0,
                "losses": 0,
                "pnl": 0.0,
                "sample_size": 0
            }

        result = t.get("result")

        if result == "win":
            stats[sig]["wins"] += 1
        elif result == "loss":
            stats[sig]["losses"] += 1

        stats[sig]["pnl"] += float(t.get("pnl", 0))
        stats[sig]["sample_size"] += 1

    # calculate win rate
    for sig, s in stats.items():
        total = s["wins"] + s["losses"]
        s["win_rate"] = round((s["wins"] / total) * 100, 2) if total > 0 else 0.0

    return stats

In [ ]:
def log_from_analysis(symbol, trade_input, result_text, pnl, notes=""):
    result = analyze_structured_trade(trade_input)
    pattern = best_pattern_match(trade_input)

    result["trade_input"] = trade_input

    adjusted = adjust_confidence(result, pattern)
    size = position_size(adjusted, result["grade"], trade_input)

    return log_trade(
        symbol=symbol,
        bias=result["bias"],
        setup_type=result["setup_type"],
        grade=result["grade"],
        key_level=result["key_level"],
        adjusted_confidence=adjusted,
        position_size=size,
        result=result_text,
        pnl=pnl,
        notes=notes,
        trade_input=trade_input
    )

In [ ]:
def log_trade(
    ticker,
    bias,
    setup_type,
    grade,
    key_level,
    adjusted_confidence,
    position_size,
    result,
    pnl,
    notes="",
    trade_input=None
):
    entry = {
        "timestamp": datetime.now().isoformat(timespec="seconds"),
        "ticker": ticker,
        "bias": bias,
        "setup_type": setup_type,
        "grade": grade,
        "key_level": key_level,
        "adjusted_confidence": adjusted_confidence,
        "position_size": position_size,
        "result": result,
        "pnl": pnl,
        "notes": notes,
        "trade_input": trade_input if trade_input else {},
        "pattern_signature": pattern_signature(trade_input) if trade_input else ""
    }

    trade_journal.append(entry)
    save_trade_journal()

    print("✅ Trade logged and saved")
    return entry

In [ ]:
def pattern_signature(trade):
    return " | ".join([
        f"reaction={trade.get('reaction', '')}",
        f"vwap={trade.get('vwap', '')}",
        f"volume={trade.get('volume', '')}",
        f"market={trade.get('market', '')}",
        f"test={trade.get('test', '')}",
        f"level={trade.get('level', '')}"
    ])

In [ ]:
def save_trade_journal():
    with open("trade_journal.json", "w") as f:
        json.dump(trade_journal, f, indent=4)

In [ ]:
import json
from datetime import datetime

try:
    with open("trade_journal.json", "r") as f:
        trade_journal = json.load(f)
    print("✅ Journal loaded")
except:
    trade_journal = []
    print("⚠️ No journal found, starting fresh")

✅ Journal loaded

In [ ]:
learned_pattern_breakdown()

=== DEEP PATTERN STATS ===

reaction=retest_hold | vwap=above | volume=high | market=clean | test=first | level=support
Wins: 2
Losses: 0
Breakevens: 0
Win Rate: 100.0 %
Sample Size: 2
PnL: 425.5

reaction=retest_hold | vwap=above | volume=low | market=clean | test=second | level=support
Wins: 0
Losses: 1
Breakevens: 0
Win Rate: 0.0 %
Sample Size: 1
PnL: -95.0

{'reaction=retest_hold | vwap=above | volume=high | market=clean | test=first | level=support': {'wins': 2,
  'losses': 0,
  'breakevens': 0,
  'pnl': 425.5,
  'win_rate': 100.0,
  'sample_size': 2},
 'reaction=retest_hold | vwap=above | volume=low | market=clean | test=second | level=support': {'wins': 0,
  'losses': 1,
  'breakevens': 0,
  'pnl': -95.0,
  'win_rate': 0.0,
  'sample_size': 1}}

In [ ]:
trade_1 = {
    "level": "support",
    "reaction": "retest_hold",
    "vwap": "above",
    "rsi": 62,
    "volume": "high",
    "market": "clean",
    "test": "first",
    "key_level": "QQQ 483.40"
}

trade_2 = {
    "level": "support",
    "reaction": "retest_hold",
    "vwap": "above",
    "rsi": 58,
    "volume": "high",
    "market": "clean",
    "test": "first",
    "key_level": "QQQ 482.90"
}

trade_3 = {
    "level": "support",
    "reaction": "retest_hold",
    "vwap": "above",
    "rsi": 55,
    "volume": "low",
    "market": "clean",
    "test": "second",
    "key_level": "QQQ 482.50"
}

log_from_analysis("QQQ", trade_1, "win", 245.5, "clean first test")
log_from_analysis("QQQ", trade_2, "win", 180, "another strong retest")
log_from_analysis("QQQ", trade_3, "loss", -95, "weaker second test low volume")

=== PERFORMANCE TRACKING ===

A_plus
Wins: 1
Losses: 0
Win Rate: 100.0 %

B_setups
Wins: 0
Losses: 0
Win Rate: 0 %

No_trade
Wins: 0
Losses: 0
Win Rate: 0 %

=== ADJUSTED CONFIDENCE ===
Base Confidence: 100
Category: A_plus
Category Win Rate: 100.0
Setup Type: Retest Hold
Setup Win Rate: 100.0
Setup Sample Size: 1
Deep Pattern Signature:
Deep Pattern Win Rate: 0
Deep Pattern Sample Size: 0
Adjusted Confidence: 100

=== POSITION SIZING ===
Grade: A+
Confidence: 100
Risk Per Trade: 3%
Recommended Size: FULL SIZE
✅ Trade journal saved
✅ Trade logged

=== PERFORMANCE TRACKING ===

A_plus
Wins: 1
Losses: 0
Win Rate: 100.0 %

B_setups
Wins: 0
Losses: 0
Win Rate: 0 %

No_trade
Wins: 0
Losses: 0
Win Rate: 0 %

=== ADJUSTED CONFIDENCE ===
Base Confidence: 100
Category: A_plus
Category Win Rate: 100.0
Setup Type: Retest Hold
Setup Win Rate: 100.0
Setup Sample Size: 2
Deep Pattern Signature:
Deep Pattern Win Rate: 0
Deep Pattern Sample Size: 0
Adjusted Confidence: 100

=== POSITION SIZING ===
Grade: A+
Confidence: 100
Risk Per Trade: 3%
Recommended Size: FULL SIZE
✅ Trade journal saved
✅ Trade logged

=== PERFORMANCE TRACKING ===

A_plus
Wins: 1
Losses: 0
Win Rate: 100.0 %

B_setups
Wins: 0
Losses: 0
Win Rate: 0 %

No_trade
Wins: 0
Losses: 0
Win Rate: 0 %

=== ADJUSTED CONFIDENCE ===
Base Confidence: 20
Category: B_setups
Category Win Rate: 0
Setup Type: No Trade
Setup Win Rate: 0
Setup Sample Size: 0
Deep Pattern Signature:
Deep Pattern Win Rate: 0
Deep Pattern Sample Size: 0
Adjusted Confidence: 0

=== POSITION SIZING ===
Grade: C
Confidence: 0
Risk Per Trade: 0%
Recommended Size: NO TRADE
✅ Trade journal saved
✅ Trade logged

{'timestamp': '2026-04-12T17:26:35',
 'ticker': 'QQQ',
 'bias': 'NO TRADE',
 'setup_type': 'No Trade',
 'grade': 'C',
 'key_level': 'QQQ 482.50',
 'adjusted_confidence': 0,
 'position_size': 'NO TRADE',
 'result': 'loss',
 'pnl': -95,
 'notes': 'weaker second test low volume',
 'trade_input': {'level': 'support',
  'reaction': 'retest_hold',
  'vwap': 'above',
  'rsi': 55,
  'volume': 'low',
  'market': 'clean',
  'test': 'second',
  'key_level': 'QQQ 482.50'},
 'pattern_signature': 'reaction=retest_hold | vwap=above | volume=low | market=clean | test=second | level=support'}

In [ ]:
def full_analysis(trade_input):
    print("\n=== FULL ANALYSIS ===")

    result = analyze_structured_trade(trade_input)
    pattern = best_pattern_match(trade_input)

    print("\n=== BEST MATCH ===")
    print("NAME:", pattern["name"])
    print("CATEGORY:", pattern["category"])
    print("MATCH SCORE:", pattern["match_score"])

    print("\n--- FINAL OUTPUT ---")
    for k, v in result.items():
        print(k.upper(), ":", v)

    print("\nPATTERN MATCH:")
    print("MATCHED SETUP:", pattern["name"])
    print("CATEGORY:", pattern["category"])
    print("MATCH SCORE:", pattern["match_score"])

    adjusted = adjust_confidence(result, pattern, trade_input)
    print("\nFINAL CONFIDENCE (ADJUSTED):", adjusted)

    if adjusted < 50:
        print("\n🚫 TRADE BLOCKED: Confidence too low")
        return

    print("\n✅ TRADE ALLOWED")

    size = position_size(adjusted, result["grade"])
    print("FINAL POSITION SIZE:", size)

    if pattern["category"] == "B_setups":
        print("\n⚠️ Pattern suggests weaker setup (B)")
    elif pattern["category"] == "No_trade":
        print("\n🚫 Pattern suggests NO TRADE conditions")

In [ ]:
def adjust_confidence(result, pattern):
    category = pattern["category"]

    performance = track_performance()
    category_win_rate = performance.get(category, {}).get("win_rate", 0)

    setup_stats = learned_setup_stats()
    setup_type = result.get("setup_type", "Unknown")
    setup_win_rate = setup_stats.get(setup_type, {}).get("win_rate", 0)
    setup_sample_size = setup_stats.get(setup_type, {}).get("sample_size", 0)

    trade_input = result.get("trade_input", {})
    sig = pattern_signature(trade_input) if trade_input else None
    pattern_stats = learned_pattern_stats()
    deep_pattern = pattern_stats.get(sig, {})
    deep_pattern_win_rate = deep_pattern.get("win_rate", 0)
    deep_pattern_sample_size = deep_pattern.get("sample_size", 0)

    adjusted_confidence = result["confidence"]

    # Category performance
    if category_win_rate >= 70:
        adjusted_confidence += 10
    elif category_win_rate > 50:
        adjusted_confidence += 0
    elif category_win_rate > 0:
        adjusted_confidence -= 15
    else:
        adjusted_confidence -= 25

    # Setup performance
    if setup_sample_size >= 3:
        if setup_win_rate >= 70:
            adjusted_confidence += 10
        elif setup_win_rate <= 40:
            adjusted_confidence -= 10

    # Deep pattern performance
    if deep_pattern_sample_size >= 2:
        if deep_pattern_win_rate >= 70:
            adjusted_confidence += 10
        elif deep_pattern_win_rate <= 40:
            adjusted_confidence -= 10

    # Priority window boost
    trade_window = trade_input.get("trade_window", "unknown")

    if trade_window in ["priority_morning", "priority_power"]:
        adjusted_confidence += 8
    elif trade_window == "priority_midday":
        adjusted_confidence += 4
    elif trade_window == "off_hours":
        adjusted_confidence -= 10

    # Execution discipline
    execution = trade_input.get("execution_discipline", "unknown")
    if execution == "high":
        adjusted_confidence += 4
    elif execution == "low":
        adjusted_confidence -= 8

    # Mistakes
    mistake = trade_input.get("mistake_tag", "none")
    if mistake != "none":
        adjusted_confidence -= 12

    # Environment preference
    environment = trade_input.get("environment", "unknown")
    if environment == "trend_day" and result.get("setup_type") in ["Break and Hold", "Retest Hold"]:
        adjusted_confidence += 5
    elif environment == "range_day" and result.get("setup_type") == "Break and Hold":
        adjusted_confidence -= 8

    # Clamp
    adjusted_confidence = max(0, min(100, adjusted_confidence))

    print("\n=== ADJUSTED CONFIDENCE ===")
    print("Base Confidence:", result["confidence"])
    print("Category:", category)
    print("Category Win Rate:", category_win_rate)
    print("Setup Type:", setup_type)
    print("Setup Win Rate:", setup_win_rate)
    print("Setup Sample Size:", setup_sample_size)
    print("Deep Pattern Signature:", sig)
    print("Deep Pattern Win Rate:", deep_pattern_win_rate)
    print("Deep Pattern Sample Size:", deep_pattern_sample_size)
    print("Trade Window:", trade_window)
    print("Execution Discipline:", execution)
    print("Environment:", environment)
    print("Mistake Tag:", mistake)
    print("Adjusted Confidence:", adjusted_confidence)

    return adjusted_confidence

In [ ]:
def learned_pattern_breakdown():
    stats = learned_pattern_stats()

    print("\n=== DEEP PATTERN STATS ===")
    for sig, s in stats.items():
        print(f"\n{sig}")
        print("Wins:", s["wins"])
        print("Losses:", s["losses"])
        print("Breakevens:", s["breakevens"])
        print("Win Rate:", s["win_rate"], "%")
        print("Sample Size:", s["sample_size"])
        print("PnL:", s["pnl"])

    return stats

In [ ]:
def learned_pattern_stats():
    stats = {}

    for t in trade_journal:
        sig = t.get("pattern_signature", "")
        if not sig:
            continue

        if sig not in stats:
            stats[sig] = {
                "wins": 0,
                "losses": 0,
                "breakevens": 0,
                "pnl": 0.0
            }

        if t["result"] == "win":
            stats[sig]["wins"] += 1
        elif t["result"] == "loss":
            stats[sig]["losses"] += 1
        elif t["result"] == "breakeven":
            stats[sig]["breakevens"] += 1

        stats[sig]["pnl"] += float(t["pnl"])

    for sig, s in stats.items():
        resolved = s["wins"] + s["losses"]
        s["win_rate"] = round((s["wins"] / resolved) * 100, 2) if resolved > 0 else 0.0
        s["sample_size"] = resolved

    return stats

In [ ]:
def log_from_analysis(ticker, trade_input, result_text, pnl, notes=""):
    result = analyze_structured_trade(trade_input)
    pattern = best_pattern_match(trade_input)
    adjusted = adjust_confidence(result, pattern)
    size = position_size(adjusted, result["grade"])

    return log_trade(
        ticker=ticker,
        bias=result["bias"],
        setup_type=result["setup_type"],
        grade=result["grade"],
        key_level=result["key_level"],
        adjusted_confidence=adjusted,
        position_size=size,
        result=result_text,
        pnl=pnl,
        notes=notes,
        trade_input=trade_input
    )

In [ ]:
def log_trade(
    ticker,
    bias,
    setup_type,
    grade,
    key_level,
    adjusted_confidence,
    position_size,
    result,
    pnl,
    notes="",
    trade_input=None
):
    entry = {
        "timestamp": datetime.now().isoformat(timespec="seconds"),
        "ticker": ticker,
        "bias": bias,
        "setup_type": setup_type,
        "grade": grade,
        "key_level": key_level,
        "adjusted_confidence": adjusted_confidence,
        "position_size": position_size,
        "result": result,
        "pnl": pnl,
        "notes": notes,
        "trade_input": trade_input if trade_input else {},
        "pattern_signature": pattern_signature(trade_input) if trade_input else ""
    }

    trade_journal.append(entry)
    save_trade_journal()
    print("✅ Trade logged")
    return entry

In [ ]:
def pattern_signature(trade):
    return " | ".join([
        f"reaction={trade.get('reaction', '')}",
        f"vwap={trade.get('vwap', '')}",
        f"volume={trade.get('volume', '')}",
        f"market={trade.get('market', '')}",
        f"test={trade.get('test', '')}",
        f"level={trade.get('level', '')}"
    ])

In [ ]:
learned_setup_breakdown()

=== AUTO-LEARNED SETUP STATS ===

Retest Hold
Wins: 1
Losses: 0
Breakevens: 0
Win Rate: 100.0 %
Sample Size: 1
PnL: 245.5

{'Retest Hold': {'wins': 1,
  'losses': 0,
  'breakevens': 0,
  'pnl': 245.5,
  'win_rate': 100.0,
  'sample_size': 1}}

In [ ]:
quick_run(
    "support",
    "retest_hold",
    "above",
    62,
    "high",
    "clean",
    "first",
    "QQQ 483.40"
)

=== FULL ANALYSIS ===

=== BEST MATCH ===
NAME: qqq_call_a2
CATEGORY: A_plus
MATCH SCORE: 7

--- FINAL OUTPUT ---
BIAS : CALL
SETUP_TYPE : Retest Hold
GRADE : A+
KEY_LEVEL : QQQ 483.40
ENTRY_TRIGGER : Break holds or retest bounce confirms
INVALIDATION : Loss of breakout level / retest low
TARGETS : Next resistance / next key level
CONFIDENCE : 100
REASONS : ['Retest held at support', 'Bullish VWAP control', 'Bullish momentum', 'Volume confirmation', 'First test of level']
RISKS : []
FINAL_DECISION : CALL

PATTERN MATCH:
MATCHED SETUP: qqq_call_a2
CATEGORY: A_plus
MATCH SCORE: 7

=== PERFORMANCE TRACKING ===

A_plus
Wins: 1
Losses: 0
Win Rate: 100.0 %

B_setups
Wins: 0
Losses: 0
Win Rate: 0 %

No_trade
Wins: 0
Losses: 0
Win Rate: 0 %

=== ADJUSTED CONFIDENCE ===
Base Confidence: 100
Category: A_plus
Category Win Rate: 100.0
Setup Type: Retest Hold
Setup Win Rate: 100.0
Setup Sample Size: 1
Adjusted Confidence: 100

FINAL CONFIDENCE (ADJUSTED): 100

✅ TRADE ALLOWED

=== POSITION SIZING ===
Grade: A+
Confidence: 100
Risk Per Trade: 3%
Recommended Size: FULL SIZE
FINAL POSITION SIZE: FULL SIZE

In [ ]:
def learned_setup_breakdown():
    stats = learned_setup_stats()

    print("\n=== AUTO-LEARNED SETUP STATS ===")
    for setup, s in stats.items():
        print(f"\n{setup}")
        print("Wins:", s["wins"])
        print("Losses:", s["losses"])
        print("Breakevens:", s["breakevens"])
        print("Win Rate:", s["win_rate"], "%")
        print("Sample Size:", s["sample_size"])
        print("PnL:", s["pnl"])

    return stats

In [ ]:
def adjust_confidence(result, pattern):
    category = pattern["category"]
    base_confidence = result["confidence"]
    adjusted_confidence = base_confidence

    performance = track_performance()
    category_win_rate = performance.get(category, {}).get("win_rate", 0)

    setup_stats = learned_setup_stats()
    setup_type = result["setup_type"]
    setup_win_rate = setup_stats.get(setup_type, {}).get("win_rate", 0)
    sample_size = setup_stats.get(setup_type, {}).get("sample_size", 0)

    # Category adjustment
    if category_win_rate >= 70:
        adjusted_confidence += 10
    elif category_win_rate >= 50:
        adjusted_confidence += 0
    elif category_win_rate > 0:
        adjusted_confidence -= 15
    else:
        adjusted_confidence -= 25

    # Setup-type auto-learning adjustment
    # Only trust setup-level learning once you have enough samples
    if sample_size >= 3:
        if setup_win_rate >= 70:
            adjusted_confidence += 10
        elif setup_win_rate >= 55:
            adjusted_confidence += 5
        elif setup_win_rate >= 40:
            adjusted_confidence += 0
        elif setup_win_rate > 0:
            adjusted_confidence -= 10
        else:
            adjusted_confidence -= 20

    adjusted_confidence = max(0, min(100, adjusted_confidence))

    print("\n=== ADJUSTED CONFIDENCE ===")
    print("Base Confidence:", base_confidence)
    print("Category:", category)
    print("Category Win Rate:", category_win_rate)
    print("Setup Type:", setup_type)
    print("Setup Win Rate:", setup_win_rate)
    print("Setup Sample Size:", sample_size)
    print("Adjusted Confidence:", adjusted_confidence)

    return adjusted_confidence

In [ ]:
def learned_setup_stats():
    stats = {}

    for t in trade_journal:
        setup = t.get("setup_type") or t.get("setup") or "Unknown"

        if setup not in stats:
            stats[setup] = {
                "wins": 0,
                "losses": 0,
                "breakevens": 0,
                "pnl": 0.0
            }

        if t.get("result") == "win":
            stats[setup]["wins"] += 1
        elif t.get("result") == "loss":
            stats[setup]["losses"] += 1
        elif t.get("result") == "breakeven":
            stats[setup]["breakevens"] += 1

        stats[setup]["pnl"] += float(t.get("pnl", 0))

    for setup, s in stats.items():
        resolved = s["wins"] + s["losses"]
        s["win_rate"] = round((s["wins"] / resolved) * 100, 2) if resolved > 0 else 0.0
        s["sample_size"] = resolved

    return stats

In [ ]:
journal_summary()
setup_breakdown()

=== JOURNAL SUMMARY ===
Total Trades: 1
Wins: 1
Losses: 0
Breakevens: 0
Win Rate: 100.0 %
Total PnL: 245.5

=== SETUP BREAKDOWN ===

Retest Hold
Wins: 1
Losses: 0
Breakevens: 0
Win Rate: 100.0 %
PnL: 245.5

{'Retest Hold': {'wins': 1, 'losses': 0, 'breakevens': 0, 'pnl': 245.5}}

In [ ]:
trade_input = {
    "level": "support",
    "reaction": "retest_hold",
    "vwap": "above",
    "rsi": 62,
    "volume": "high",
    "market": "clean",
    "test": "first",
    "key_level": "QQQ 483.40"
}

log_from_analysis(
    ticker="QQQ",
    trade_input=trade_input,
    result_text="win",
    pnl=245.50,
    notes="Strong first-test retest hold"
)

=== PERFORMANCE TRACKING ===

A_plus
Wins: 1
Losses: 0
Win Rate: 100.0 %

B_setups
Wins: 0
Losses: 0
Win Rate: 0 %

No_trade
Wins: 0
Losses: 0
Win Rate: 0 %

=== ADJUSTED CONFIDENCE ===
Base Confidence: 100
Win Rate: 100.0
Adjusted Confidence: 100

=== POSITION SIZING ===
Grade: A+
Confidence: 100
Risk Per Trade: 3%
Recommended Size: FULL SIZE
✅ Trade journal saved
✅ Trade logged

{'timestamp': '2026-04-12T16:45:54',
 'ticker': 'QQQ',
 'bias': 'CALL',
 'setup_type': 'Retest Hold',
 'grade': 'A+',
 'key_level': 'QQQ 483.40',
 'adjusted_confidence': 100,
 'position_size': 'FULL SIZE',
 'result': 'win',
 'pnl': 245.5,
 'notes': 'Strong first-test retest hold'}

In [ ]:
def log_from_analysis(ticker, trade_input, result_text, pnl, notes=""):
    result = analyze_structured_trade(trade_input)
    pattern = best_pattern_match(trade_input)
    adjusted = adjust_confidence(result, pattern)
    size = position_size(adjusted, result["grade"])

    return log_trade(
        ticker=ticker,
        bias=result["bias"],
        setup_type=result["setup_type"],
        grade=result["grade"],
        key_level=result["key_level"],
        adjusted_confidence=adjusted,
        position_size=size,
        result=result_text,
        pnl=pnl,
        notes=notes
    )

In [ ]:
def setup_breakdown():
    stats = {}

    for t in trade_journal:
        key = t.get("setup_type") or t.get("setup") or "Unknown"

        if key not in stats:
            stats[key] = {
                "wins": 0,
                "losses": 0,
                "breakevens": 0,
                "pnl": 0.0
            }

        if t.get("result") == "win":
            stats[key]["wins"] += 1
        elif t.get("result") == "loss":
            stats[key]["losses"] += 1
        elif t.get("result") == "breakeven":
            stats[key]["breakevens"] += 1

        stats[key]["pnl"] += float(t.get("pnl", 0))

    print("\n=== SETUP BREAKDOWN ===")
    for setup, s in stats.items():
        resolved = s["wins"] + s["losses"]
        win_rate = round((s["wins"] / resolved) * 100, 2) if resolved > 0 else 0.0

        print(f"\n{setup}")
        print("Wins:", s["wins"])
        print("Losses:", s["losses"])
        print("Breakevens:", s["breakevens"])
        print("Win Rate:", win_rate, "%")
        print("PnL:", s["pnl"])

    return stats

In [ ]:
def journal_summary():
    total_trades = len(trade_journal)
    wins = sum(1 for t in trade_journal if t["result"] == "win")
    losses = sum(1 for t in trade_journal if t["result"] == "loss")
    breakevens = sum(1 for t in trade_journal if t["result"] == "breakeven")
    total_pnl = sum(float(t["pnl"]) for t in trade_journal)

    resolved = wins + losses
    win_rate = round((wins / resolved) * 100, 2) if resolved > 0 else 0.0

    print("\n=== JOURNAL SUMMARY ===")
    print("Total Trades:", total_trades)
    print("Wins:", wins)
    print("Losses:", losses)
    print("Breakevens:", breakevens)
    print("Win Rate:", win_rate, "%")
    print("Total PnL:", total_pnl)

    return {
        "total_trades": total_trades,
        "wins": wins,
        "losses": losses,
        "breakevens": breakevens,
        "win_rate": win_rate,
        "total_pnl": total_pnl
    }

In [ ]:
def log_trade(
    ticker,
    bias,
    setup_type,
    grade,
    key_level,
    adjusted_confidence,
    position_size,
    result,
    pnl,
    notes=""
):
    entry = {
        "timestamp": datetime.now().isoformat(timespec="seconds"),
        "ticker": ticker,
        "bias": bias,
        "setup_type": setup_type,
        "grade": grade,
        "key_level": key_level,
        "adjusted_confidence": adjusted_confidence,
        "position_size": position_size,
        "result": result,   # "win", "loss", or "breakeven"
        "pnl": pnl,
        "notes": notes
    }

    trade_journal.append(entry)
    save_trade_journal()
    print("✅ Trade logged")
    return entry

In [ ]:
def save_trade_journal():
    with open("trade_journal.json", "w") as f:
        json.dump(trade_journal, f, indent=4)
    print("✅ Trade journal saved")

In [ ]:
import json
from datetime import datetime

try:
    with open("trade_journal.json", "r") as f:
        trade_journal = json.load(f)
    print("✅ Trade journal loaded")
except:
    trade_journal = []
    print("⚠️ No trade journal found, starting fresh")

⚠️ No trade journal found, starting fresh

In [ ]:
quick_run(
    "support",
    "retest_hold",
    "above",
    62,
    "high",
    "clean",
    "first",
    "QQQ 483.40"
)

=== FULL ANALYSIS ===

=== BEST MATCH ===
NAME: qqq_call_a2
CATEGORY: A_plus
MATCH SCORE: 7

--- FINAL OUTPUT ---
BIAS : CALL
SETUP_TYPE : Retest Hold
GRADE : A+
KEY_LEVEL : QQQ 483.40
ENTRY_TRIGGER : Break holds or retest bounce confirms
INVALIDATION : Loss of breakout level / retest low
TARGETS : Next resistance / next key level
CONFIDENCE : 100
REASONS : ['Retest held at support', 'Bullish VWAP control', 'Bullish momentum', 'Volume confirmation', 'First test of level']
RISKS : []
FINAL_DECISION : CALL

PATTERN MATCH:
MATCHED SETUP: qqq_call_a2
CATEGORY: A_plus
MATCH SCORE: 7

=== PERFORMANCE TRACKING ===

A_plus
Wins: 1
Losses: 0
Win Rate: 100.0 %

B_setups
Wins: 0
Losses: 0
Win Rate: 0 %

No_trade
Wins: 0
Losses: 0
Win Rate: 0 %

=== ADJUSTED CONFIDENCE ===
Base Confidence: 100
Win Rate: 100.0
Adjusted Confidence: 100

FINAL CONFIDENCE (ADJUSTED): 100

✅ TRADE ALLOWED

=== POSITION SIZING ===
Grade: A+
Confidence: 100
Risk Per Trade: 3%
Recommended Size: FULL SIZE
FINAL POSITION SIZE: FULL SIZE

In [ ]:
quick_run(
    "support",
    "retest_hold",
    "above",
    62,
    "high",
    "clean",
    "first",
    "QQQ 483.40"
)

=== FULL ANALYSIS ===
=== BEST MATCH ===
NAME: qqq_call_a2
CATEGORY: A_plus
MATCH SCORE: 7

=== BEST MATCH ===
NAME: qqq_call_a2
CATEGORY: A_plus
MATCH SCORE: 7

--- FINAL OUTPUT ---
BIAS : CALL
SETUP_TYPE : Retest Hold
GRADE : A+
KEY_LEVEL : QQQ 483.40
ENTRY_TRIGGER : Break holds or retest bounce confirms
INVALIDATION : Loss of breakout level / retest low
TARGETS : Next resistance / next key level
CONFIDENCE : 100
REASONS : ['Retest held at support', 'Bullish VWAP control', 'Bullish momentum', 'Volume confirmation', 'First test of level']
RISKS : []
FINAL_DECISION : CALL

PATTERN MATCH:
MATCHED SETUP: qqq_call_a2
CATEGORY: A_plus
MATCH SCORE: 7

=== PERFORMANCE TRACKING ===

A_plus
Wins: 1
Losses: 0
Win Rate: 100.0 %

B_setups
Wins: 0
Losses: 0
Win Rate: 0 %

No_trade
Wins: 0
Losses: 0
Win Rate: 0 %

=== ADJUSTED CONFIDENCE ===
Base Confidence: 100
Win Rate: 100.0
Adjusted Confidence: 100

FINAL CONFIDENCE (ADJUSTED): 100

✅ TRADE ALLOWED

=== POSITION SIZING ===
Grade: A+
Confidence: 100
Risk Per Trade: 3%
Recommended Size: FULL SIZE
FINAL POSITION SIZE: FULL SIZE

In [ ]:
quick_run(
    "support",
    "retest_hold",
    "above",
    62,
    "high",
    "clean",
    "first",
    "QQQ 483.40"
)

=== FULL ANALYSIS ===
=== BEST MATCH ===
NAME: qqq_call_a2
CATEGORY: A_plus
MATCH SCORE: 7

--- FINAL OUTPUT ---
BIAS : CALL
SETUP_TYPE : Retest Hold
GRADE : A+
KEY_LEVEL : QQQ 483.40
ENTRY_TRIGGER : Break holds or retest bounce confirms
INVALIDATION : Loss of breakout level / retest low
TARGETS : Next resistance / next key level
CONFIDENCE : 100
REASONS : ['Retest held at support', 'Bullish VWAP control', 'Bullish momentum', 'Volume confirmation', 'First test of level']
RISKS : []
FINAL_DECISION : CALL

PATTERN MATCH:
MATCHED SETUP: qqq_call_a2
CATEGORY: A_plus
MATCH SCORE: 7

=== PERFORMANCE TRACKING ===

A_plus
Wins: 1
Losses: 0
Win Rate: 100.0 %

B_setups
Wins: 0
Losses: 0
Win Rate: 0 %

No_trade
Wins: 0
Losses: 0
Win Rate: 0 %

=== ADJUSTED CONFIDENCE ===
Base Confidence: 100
Win Rate: 100.0
Adjusted Confidence: 100

FINAL CONFIDENCE (ADJUSTED): 100

✅ TRADE ALLOWED

=== POSITION SIZING ===
Grade: A+
Confidence: 100
Recommended Size: FULL SIZE
FINAL POSITION SIZE: FULL SIZE

In [ ]:
quick_run(
    "resistance",
    "rejection",
    "below",
    47,
    "low",
    "clean",
    "second",
    "QQQ 486.00"
)

=== FULL ANALYSIS ===
=== BEST MATCH ===
NAME: qqq_put_b1
CATEGORY: B_setups
MATCH SCORE: 8

--- FINAL OUTPUT ---
BIAS : NO TRADE
SETUP_TYPE : No Trade
GRADE : C
KEY_LEVEL : QQQ 486.00
ENTRY_TRIGGER : None
INVALIDATION : None
TARGETS : None
CONFIDENCE : 20
REASONS : ['Conditions are not clean enough']
RISKS : ['Chop / weak structure / poor confirmation']
FINAL_DECISION : NO TRADE

PATTERN MATCH:
MATCHED SETUP: qqq_put_b1
CATEGORY: B_setups
MATCH SCORE: 8

=== PERFORMANCE TRACKING ===

A_plus
Wins: 1
Losses: 0
Win Rate: 100.0 %

B_setups
Wins: 0
Losses: 0
Win Rate: 0 %

No_trade
Wins: 0
Losses: 0
Win Rate: 0 %

=== ADJUSTED CONFIDENCE ===
Base Confidence: 20
Win Rate: 0
Adjusted Confidence: 0

FINAL CONFIDENCE (ADJUSTED): 0

🚫 TRADE BLOCKED: Confidence too low

In [ ]:
quick_run(
    "support",
    "retest_hold",
    "above",
    62,
    "high",
    "clean",
    "first",
    "QQQ 483.40"
)

=== FULL ANALYSIS ===
=== BEST MATCH ===
NAME: qqq_call_a2
CATEGORY: A_plus
MATCH SCORE: 7

--- FINAL OUTPUT ---
BIAS : CALL
SETUP_TYPE : Retest Hold
GRADE : A+
KEY_LEVEL : QQQ 483.40
ENTRY_TRIGGER : Break holds or retest bounce confirms
INVALIDATION : Loss of breakout level / retest low
TARGETS : Next resistance / next key level
CONFIDENCE : 100
REASONS : ['Retest held at support', 'Bullish VWAP control', 'Bullish momentum', 'Volume confirmation', 'First test of level']
RISKS : []
FINAL_DECISION : CALL

PATTERN MATCH:
MATCHED SETUP: qqq_call_a2
CATEGORY: A_plus
MATCH SCORE: 7

=== PERFORMANCE TRACKING ===

A_plus
Wins: 1
Losses: 0
Win Rate: 100.0 %

B_setups
Wins: 0
Losses: 0
Win Rate: 0 %

No_trade
Wins: 0
Losses: 0
Win Rate: 0 %

=== ADJUSTED CONFIDENCE ===
Base Confidence: 100
Win Rate: 100.0
Adjusted Confidence: 100

FINAL CONFIDENCE (ADJUSTED): 100

✅ TRADE ALLOWED

=== POSITION SIZING ===
Grade: A+
Confidence: 100
Recommended Size: FULL SIZE
FINAL POSITION SIZE: FULL SIZE

In [ ]:
def trade_filter(adjusted_confidence):
    if adjusted_confidence < 50:
        print("\n🚫 TRADE BLOCKED: Confidence too low")
        return False
    else:
        print("\n✅ TRADE ALLOWED")
        return True

In [ ]:
quick_run(
    "resistance",
    "rejection",
    "below",
    47,
    "low",
    "clean",
    "second",
    "QQQ 486.00"
)

=== FULL ANALYSIS ===
=== BEST MATCH ===
NAME: qqq_put_b1
CATEGORY: B_setups
MATCH SCORE: 8

--- FINAL OUTPUT ---
BIAS : NO TRADE
SETUP_TYPE : No Trade
GRADE : C
KEY_LEVEL : QQQ 486.00
ENTRY_TRIGGER : None
INVALIDATION : None
TARGETS : None
CONFIDENCE : 20
REASONS : ['Conditions are not clean enough']
RISKS : ['Chop / weak structure / poor confirmation']
FINAL_DECISION : NO TRADE

PATTERN MATCH:
MATCHED SETUP: qqq_put_b1
CATEGORY: B_setups
MATCH SCORE: 8

=== PERFORMANCE TRACKING ===

A_plus
Wins: 1
Losses: 0
Win Rate: 100.0 %

B_setups
Wins: 0
Losses: 0
Win Rate: 0 %

No_trade
Wins: 0
Losses: 0
Win Rate: 0 %

=== ADJUSTED CONFIDENCE ===
Base Confidence: 20
Win Rate: 0
Adjusted Confidence: 0

FINAL CONFIDENCE (ADJUSTED): 0

⚠️ Pattern suggests weaker setup (B)

In [ ]:
def quick_run(level, reaction, vwap, rsi, volume, market, test, key_level):
    trade = {
        "level": level,
        "reaction": reaction,
        "vwap": vwap,
        "rsi": rsi,
        "volume": volume,
        "market": market,
        "test": test,
        "key_level": key_level
    }

    full_analysis(trade)

In [ ]:
full_analysis({
    "level": "resistance",
    "reaction": "rejection",
    "vwap": "below",
    "rsi": 47,
    "volume": "low",
    "market": "clean",
    "test": "second",
    "key_level": "QQQ 486.00"
})

=== FULL ANALYSIS ===
=== BEST MATCH ===
NAME: qqq_put_b1
CATEGORY: B_setups
MATCH SCORE: 8

--- FINAL OUTPUT ---
BIAS : NO TRADE
SETUP_TYPE : No Trade
GRADE : C
KEY_LEVEL : QQQ 486.00
ENTRY_TRIGGER : None
INVALIDATION : None
TARGETS : None
CONFIDENCE : 20
REASONS : ['Conditions are not clean enough']
RISKS : ['Chop / weak structure / poor confirmation']
FINAL_DECISION : NO TRADE

PATTERN MATCH:
MATCHED SETUP: qqq_put_b1
CATEGORY: B_setups
MATCH SCORE: 8

=== PERFORMANCE TRACKING ===

A_plus
Wins: 1
Losses: 0
Win Rate: 100.0 %

B_setups
Wins: 0
Losses: 0
Win Rate: 0 %

No_trade
Wins: 0
Losses: 0
Win Rate: 0 %

=== ADJUSTED CONFIDENCE ===
Base Confidence: 20
Win Rate: 0
Adjusted Confidence: 0

FINAL CONFIDENCE (ADJUSTED): 0

⚠️ Pattern suggests weaker setup (B)

In [ ]:
def position_size(confidence, grade=None, trade_input=None):
    if grade == "A+":
        base_risk = 3
    elif grade == "A":
        base_risk = 2
    elif grade == "B":
        base_risk = 1
    else:
        base_risk = 0.5

    trade_window = "unknown"
    execution = "unknown"
    mistake = "none"

    if trade_input:
        trade_window = trade_input.get("trade_window", "unknown")
        execution = trade_input.get("execution_discipline", "unknown")
        mistake = trade_input.get("mistake_tag", "none")

    # Window sizing adjustment
    if trade_window in ["priority_morning", "priority_power"]:
        base_risk += 0.5
    elif trade_window == "off_hours":
        base_risk -= 0.5

    # Execution adjustment
    if execution == "high":
        base_risk += 0.25
    elif execution == "low":
        base_risk -= 0.5

    # Mistake penalty
    if mistake != "none":
        base_risk -= 0.75

    base_risk = max(0.25, base_risk)

    if confidence >= 90:
        size = "FULL SIZE"
    elif confidence >= 75:
        size = "HALF SIZE"
    elif confidence >= 60:
        size = "QUARTER SIZE"
    else:
        size = "NO TRADE"

    print("\n=== POSITION SIZING ===")
    print("Grade:", grade)
    print("Confidence:", confidence)
    print("Trade Window:", trade_window)
    print("Execution Discipline:", execution)
    print("Mistake Tag:", mistake)
    print("Risk Per Trade:", f"{base_risk}%")
    print("Recommended Size:", size)

    return size

In [ ]:
full_analysis({
    "level": "resistance",
    "reaction": "rejection",
    "vwap": "below",
    "rsi": 47,
    "volume": "low",
    "market": "clean",
    "test": "second",
    "key_level": "QQQ 486.00"
})

=== FULL ANALYSIS ===
=== BEST MATCH ===
NAME: qqq_put_b1
CATEGORY: B_setups
MATCH SCORE: 8

--- FINAL OUTPUT ---
BIAS : NO TRADE
SETUP_TYPE : No Trade
GRADE : C
KEY_LEVEL : QQQ 486.00
ENTRY_TRIGGER : None
INVALIDATION : None
TARGETS : None
CONFIDENCE : 20
REASONS : ['Conditions are not clean enough']
RISKS : ['Chop / weak structure / poor confirmation']
FINAL_DECISION : NO TRADE

PATTERN MATCH:
MATCHED SETUP: qqq_put_b1
CATEGORY: B_setups
MATCH SCORE: 8

=== PERFORMANCE TRACKING ===

A_plus
Wins: 1
Losses: 0
Win Rate: 100.0 %

B_setups
Wins: 0
Losses: 0
Win Rate: 0 %

No_trade
Wins: 0
Losses: 0
Win Rate: 0 %

=== ADJUSTED CONFIDENCE ===
Base Confidence: 20
Win Rate: 0
Adjusted Confidence: 0

FINAL CONFIDENCE (ADJUSTED): 0

⚠️ Pattern suggests weaker setup (B)

In [ ]:
adjusted = adjust_confidence(result, pattern)

NameError: name 'pattern' is not defined

In [ ]:
def adjust_confidence(result, pattern):
    category = pattern["category"]

    performance = track_performance()

    win_rate = performance.get(category, {}).get("win_rate", 0)

    adjusted_confidence = result["confidence"]

    # Adjust based on performance
    if win_rate >= 70:
        adjusted_confidence += 10
    elif win_rate >= 50:
        adjusted_confidence += 0
    elif win_rate > 0:
        adjusted_confidence -= 15
    else:
        adjusted_confidence -= 25

    # Clamp between 0–100
    adjusted_confidence = max(0, min(100, adjusted_confidence))

    print("\n=== ADJUSTED CONFIDENCE ===")
    print("Base Confidence:", result["confidence"])
    print("Win Rate:", win_rate)
    print("Adjusted Confidence:", adjusted_confidence)

    return adjusted_confidence

In [ ]:
track_performance()

=== PERFORMANCE TRACKING ===

A_plus
Wins: 1
Losses: 0
Win Rate: 100.0 %

B_setups
Wins: 0
Losses: 0
Win Rate: 0 %

No_trade
Wins: 0
Losses: 0
Win Rate: 0 %

{'A_plus': {'wins': 1, 'losses': 0, 'win_rate': 100.0},
 'B_setups': {'wins': 0, 'losses': 0, 'win_rate': 0},
 'No_trade': {'wins': 0, 'losses': 0, 'win_rate': 0}}

In [ ]:
def track_performance():
    print("\n=== PERFORMANCE TRACKING ===")

    performance = {}

    for category, setups in saved_trades.items():
        wins = 0
        losses = 0

        for name, trade in setups.items():
            result = trade.get("result")

            if result == "win":
                wins += 1
            elif result == "loss":
                losses += 1

        total = wins + losses

        if total > 0:
            win_rate = round((wins / total) * 100, 2)
        else:
            win_rate = 0

        performance[category] = {
            "wins": wins,
            "losses": losses,
            "win_rate": win_rate
        }

        print(f"\n{category}")
        print("Wins:", wins)
        print("Losses:", losses)
        print("Win Rate:", win_rate, "%")

    return performance

In [ ]:
saved_trades["A_plus"]["qqq_put_a1"]["result"] = "win"

In [ ]:
def add_saved_trade(category, name, level, reaction, vwap, rsi, volume, market, test, key_level):
    if category not in saved_trades:
        saved_trades[category] = {}

    saved_trades[category][name] = {
        "level": level,
        "reaction": reaction,
        "vwap": vwap,
        "rsi": rsi,
        "volume": volume,
        "market": market,
        "test": test,
        "key_level": key_level
    }

    # Auto-save
    import json
    with open("saved_trades.json", "w") as f:
        json.dump(saved_trades, f, indent=4)

    print(f"✅ Added and saved {name} to {category}")

In [ ]:
import json

try:
    with open("saved_trades.json", "r") as f:
        saved_trades = json.load(f)
    print("✅ Setup library loaded")
except:
    saved_trades = {}
    print("⚠️ No saved file found, starting fresh")

✅ Setup library loaded

In [ ]:
import json

with open("saved_trades.json", "r") as f:
    loaded_trades = json.load(f)

print(loaded_trades.keys())

dict_keys(['A_plus', 'B_setups', 'No_trade'])

In [ ]:
import json

with open("saved_trades.json", "w") as f:
    json.dump(saved_trades, f, indent=4)

print("saved_trades.json created")

saved_trades.json created

In [ ]:
full_analysis_saved("A_plus", "qqq_call_a2")

=== FULL ANALYSIS ===
=== BEST MATCH ===
NAME: qqq_call_a2
CATEGORY: A_plus
MATCH SCORE: 8

--- FINAL OUTPUT ---
BIAS : CALL
SETUP_TYPE : Retest Hold
GRADE : A+
KEY_LEVEL : QQQ 483.40
ENTRY_TRIGGER : Break holds or retest bounce confirms
INVALIDATION : Loss of breakout level / retest low
TARGETS : Next resistance / next key level
CONFIDENCE : 100
REASONS : ['Retest held at support', 'Bullish VWAP control', 'Bullish momentum', 'Volume confirmation', 'First test of level']
RISKS : []
FINAL_DECISION : CALL

PATTERN MATCH:
MATCHED SETUP: qqq_call_a2
CATEGORY: A_plus
MATCH SCORE: 8

In [ ]:
add_saved_trade(
    "A_plus",
    "qqq_call_a2",
    "support",
    "retest_hold",
    "above",
    61,
    "high",
    "clean",
    "first",
    "QQQ 483.40"
)

Added qqq_call_a2 to A_plus

In [ ]:
def add_saved_trade(category, name, level, reaction, vwap, rsi, volume, market, test, key_level):
    if category not in saved_trades:
        saved_trades[category] = {}

    saved_trades[category][name] = {
        "level": level,
        "reaction": reaction,
        "vwap": vwap,
        "rsi": rsi,
        "volume": volume,
        "market": market,
        "test": test,
        "key_level": key_level
    }

    print(f"Added {name} to {category}")

In [ ]:
full_analysis_saved("A_plus", "qqq_put_a1")

=== FULL ANALYSIS ===
=== BEST MATCH ===
NAME: qqq_put_a1
CATEGORY: A_plus
MATCH SCORE: 8

--- FINAL OUTPUT ---
BIAS : PUT
SETUP_TYPE : Rejection
GRADE : A+
KEY_LEVEL : QQQ 485.20
ENTRY_TRIGGER : Rejection candle confirms or lower high fails
INVALIDATION : Break above rejection high / reclaimed level
TARGETS : Next support / next key level
CONFIDENCE : 100
REASONS : ['Rejection at resistance', 'Bearish VWAP control', 'Bearish momentum', 'Volume confirmation', 'First test of level']
RISKS : []
FINAL_DECISION : PUT

PATTERN MATCH:
MATCHED SETUP: qqq_put_a1
CATEGORY: A_plus
MATCH SCORE: 8

In [ ]:
def full_analysis_saved(category, name):
    trade = saved_trades[category][name]
    full_analysis(trade)

In [ ]:
quick_run(
    "support",
    "retest_hold",
    "above",
    62,
    "high",
    "clean",
    "first",
    "QQQ 483.40"
)

=== FULL ANALYSIS ===
=== BEST MATCH ===
NAME: qqq_call_a2
CATEGORY: A_plus
MATCH SCORE: 7

--- FINAL OUTPUT ---
BIAS : CALL
SETUP_TYPE : Retest Hold
GRADE : A+
KEY_LEVEL : QQQ 483.40
ENTRY_TRIGGER : Break holds or retest bounce confirms
INVALIDATION : Loss of breakout level / retest low
TARGETS : Next resistance / next key level
CONFIDENCE : 100
REASONS : ['Retest held at support', 'Bullish VWAP control', 'Bullish momentum', 'Volume confirmation', 'First test of level']
RISKS : []
FINAL_DECISION : CALL

PATTERN MATCH:
MATCHED SETUP: qqq_call_a2
CATEGORY: A_plus
MATCH SCORE: 7

=== PERFORMANCE TRACKING ===

A_plus
Wins: 1
Losses: 0
Win Rate: 100.0 %

B_setups
Wins: 0
Losses: 0
Win Rate: 0 %

No_trade
Wins: 0
Losses: 0
Win Rate: 0 %

=== ADJUSTED CONFIDENCE ===
Base Confidence: 100
Win Rate: 100.0
Adjusted Confidence: 100

FINAL CONFIDENCE (ADJUSTED): 100

✅ TRADE ALLOWED

=== POSITION SIZING ===

=== POSITION SIZING ===
Confidence: 100
Recommended Size: FULL SIZE
FINAL POSITION SIZE: FULL SIZE

In [ ]:
quick_run(
    "resistance",
    "rejection",
    "below",
    47,
    "low",
    "clean",
    "second",
    "QQQ 486.00"
)

=== FULL ANALYSIS ===
=== BEST MATCH ===
NAME: qqq_put_b1
CATEGORY: B_setups
MATCH SCORE: 8

--- FINAL OUTPUT ---
BIAS : NO TRADE
SETUP_TYPE : No Trade
GRADE : C
KEY_LEVEL : QQQ 486.00
ENTRY_TRIGGER : None
INVALIDATION : None
TARGETS : None
CONFIDENCE : 20
REASONS : ['Conditions are not clean enough']
RISKS : ['Chop / weak structure / poor confirmation']
FINAL_DECISION : NO TRADE

PATTERN MATCH:
MATCHED SETUP: qqq_put_b1
CATEGORY: B_setups
MATCH SCORE: 8

=== PERFORMANCE TRACKING ===

A_plus
Wins: 1
Losses: 0
Win Rate: 100.0 %

B_setups
Wins: 0
Losses: 0
Win Rate: 0 %

No_trade
Wins: 0
Losses: 0
Win Rate: 0 %

=== ADJUSTED CONFIDENCE ===
Base Confidence: 20
Win Rate: 0
Adjusted Confidence: 0

FINAL CONFIDENCE (ADJUSTED): 0

🚫 TRADE BLOCKED: Confidence too low

In [ ]:
def quick_run(symbol, level, reaction, vwap, rsi, volume, market, test, key_level,
              timeframe=None, htf_bias=None, mtf_structure=None, session=None,
              volatility=None, move_type=None, quality=None,
              oil_trend=None, oil_volatility=None, macro_event=None,
              market_sentiment=None, sector_strength=None):

SyntaxError: incomplete input (2899554308.py, line 5)

In [ ]:
full_analysis({
    "level": "resistance",
    "reaction": "rejection",
    "vwap": "below",
    "rsi": 47,
    "volume": "low",
    "market": "clean",
    "test": "second",
    "key_level": "QQQ 486.00"
})

=== FULL ANALYSIS ===
=== BEST MATCH ===
NAME: qqq_put_b1
CATEGORY: B_setups
MATCH SCORE: 8

--- FINAL OUTPUT ---
BIAS : NO TRADE
SETUP_TYPE : No Trade
GRADE : C
KEY_LEVEL : QQQ 486.00
ENTRY_TRIGGER : None
INVALIDATION : None
TARGETS : None
CONFIDENCE : 20
REASONS : ['Conditions are not clean enough']
RISKS : ['Chop / weak structure / poor confirmation']
FINAL_DECISION : NO TRADE

PATTERN MATCH:
MATCHED SETUP: qqq_put_b1
CATEGORY: B_setups
MATCH SCORE: 8

⚠️ Pattern suggests weaker setup (B)

In [ ]:
def full_analysis(trade_input):
    print("\n=== FULL ANALYSIS ===")

    result = analyze_structured_trade(trade_input)
    pattern = best_pattern_match(trade_input)

    result["trade_input"] = trade_input

    print("\n--- FINAL OUTPUT ---")
    for k, v in result.items():
        if k != "trade_input":
            print(k.upper(), ":", v)

    print("\nPATTERN MATCH:")
    print("MATCHED SETUP:", pattern["name"])
    print("CATEGORY:", pattern["category"])
    print("MATCH SCORE:", pattern["match_score"])

    adjusted = adjust_confidence(result, pattern)
    print("\nFINAL CONFIDENCE (ADJUSTED):", adjusted)

    if adjusted < 50:
        print("\n🚫 TRADE BLOCKED: Confidence too low")
        return

    print("\n✅ TRADE ALLOWED")

    size = position_size(adjusted, result["grade"], trade_input)
    print("FINAL POSITION SIZE:", size)

In [ ]:
full_analysis({
    "level": "resistance",
    "reaction": "rejection",
    "vwap": "below",
    "rsi": 47,
    "volume": "low",
    "market": "clean",
    "test": "second",
    "key_level": "QQQ 486.00"
})

=== FULL ANALYSIS ===
=== BEST MATCH ===
NAME: qqq_put_b1
CATEGORY: B_setups
MATCH SCORE: 8

--- FINAL OUTPUT ---
BIAS : NO TRADE
SETUP_TYPE : No Trade
GRADE : C
KEY_LEVEL : QQQ 486.00
ENTRY_TRIGGER : None
INVALIDATION : None
TARGETS : None
CONFIDENCE : 20
REASONS : ['Conditions are not clean enough']
RISKS : ['Chop / weak structure / poor confirmation']
FINAL_DECISION : NO TRADE

PATTERN MATCH:
MATCHED SETUP: qqq_put_b1
CATEGORY: B_setups
MATCH SCORE: 8

⚠️ Pattern suggests weaker setup (B)

({'bias': 'NO TRADE',
  'setup_type': 'No Trade',
  'grade': 'C',
  'key_level': 'QQQ 486.00',
  'entry_trigger': 'None',
  'invalidation': 'None',
  'targets': 'None',
  'confidence': 20,
  'reasons': ['Conditions are not clean enough'],
  'risks': ['Chop / weak structure / poor confirmation'],
  'final_decision': 'NO TRADE'},
 {'name': 'qqq_put_b1', 'category': 'B_setups', 'match_score': 8})

In [ ]:
def full_analysis(trade_input):
    print("\n=== FULL ANALYSIS ===")

    # Step 1: Rule-based analysis
    result = analyze_structured_trade(trade_input)

    # Step 2: Pattern match
    pattern = best_pattern_match(trade_input)

    print("\n--- FINAL OUTPUT ---")

    for k, v in result.items():
        print(k.upper(), ":", v)

    print("\nPATTERN MATCH:")
    print("MATCHED SETUP:", pattern["name"])
    print("CATEGORY:", pattern["category"])
    print("MATCH SCORE:", pattern["match_score"])

    # Optional logic: adjust confidence
    if pattern["category"] == "B_setups":
        print("\n⚠️ Pattern suggests weaker setup (B)")
    elif pattern["category"] == "No_trade":
        print("\n🚫 Pattern suggests NO TRADE conditions")

    return result, pattern

In [ ]:
def best_pattern_match(trade_input):
    best_name = None
    best_category = None
    best_score = -1

    keys_to_compare = [
        "asset_type",
        "level",
        "reaction",
        "vwap",
        "volume",
        "market",
        "test",
        "timeframe",
        "htf_bias",
        "mtf_structure",
        "session",
        "volatility"
    ]

    for category, setups in saved_trades.items():
        for name, saved in setups.items():
            match_score = 0

            for key in keys_to_compare:
                if isinstance(saved, dict) and trade_input.get(key) == saved.get(key):
                    match_score += 1

            if match_score > best_score:
                best_score = match_score
                best_name = name
                best_category = category

    return {
        "name": best_name,
        "category": best_category,
        "match_score": best_score
    }

In [ ]:
def best_pattern_match(trade_input):
    best_name = None
    best_category = None
    best_score = -1

    for category, setups in saved_trades.items():
        for name, saved in setups.items():
            match_score = 0

            for key in trade_input:
                if trade_input[key] == saved.get(key):
                    match_score += 1

            if match_score > best_score:
                best_score = match_score
                best_name = name
                best_category = category


    return {
        "name": best_name,
        "category": best_category,
        "match_score": best_score
    }

In [ ]:
compare_to_saved({
    "level": "resistance",
    "reaction": "rejection",
    "vwap": "below",
    "rsi": 47,
    "volume": "low",
    "market": "clean",
    "test": "second",
    "key_level": "QQQ 486.00"
})

=== PATTERN MATCHING ===
qqq_put_a1 (A_plus) → Match Score: 4
qqq_call_a1 (A_plus) → Match Score: 1
qqq_put_b1 (B_setups) → Match Score: 8
qqq_call_b1 (B_setups) → Match Score: 3
chop_1 (No_trade) → Match Score: 2

In [ ]:
def compare_to_saved(trade_input):
    print("\n=== PATTERN MATCHING ===")

    for category, setups in saved_trades.items():
        for name, saved in setups.items():
            match_score = 0

            for key in trade_input:
                if trade_input[key] == saved.get(key):
                    match_score += 1

            print(f"{name} ({category}) → Match Score: {match_score}")

In [ ]:
run_saved_trade("B_setups", "qqq_put_b1")

=== QQQ_PUT_B1 (B_setups) ===
BIAS : NO TRADE
SETUP_TYPE : No Trade
GRADE : C
KEY_LEVEL : QQQ 486.00
ENTRY_TRIGGER : None
INVALIDATION : None
TARGETS : None
CONFIDENCE : 20
REASONS : ['Conditions are not clean enough']
RISKS : ['Chop / weak structure / poor confirmation']
FINAL_DECISION : NO TRADE

In [ ]:
saved_trades = {
    "A_plus": {
        "qqq_put_a1": {
            "level": "resistance",
            "reaction": "rejection",
            "vwap": "below",
            "rsi": 42,
            "volume": "high",
            "market": "clean",
            "test": "first",
            "key_level": "QQQ 485.20"
        },
        "qqq_call_a1": {
            "level": "support",
            "reaction": "retest_hold",
            "vwap": "above",
            "rsi": 58,
            "volume": "high",
            "market": "clean",
            "test": "first",
            "key_level": "QQQ 482.10"
        }
    },

    "B_setups": {
        "qqq_put_b1": {
            "level": "resistance",
            "reaction": "rejection",
            "vwap": "below",
            "rsi": 47,
            "volume": "low",
            "market": "clean",
            "test": "second",
            "key_level": "QQQ 486.00"
        },
        "qqq_call_b1": {
            "level": "support",
            "reaction": "retest_hold",
            "vwap": "above",
            "rsi": 52,
            "volume": "low",
            "market": "clean",
            "test": "second",
            "key_level": "QQQ 481.50"
        }
    },

    "No_trade": {
        "chop_1": {
            "level": "unclear",
            "reaction": "none",
            "vwap": "flip",
            "rsi": 49,
            "volume": "low",
            "market": "chop",
            "test": "second",
            "key_level": "None"
        }
    }
}

In [ ]:
run_saved_trade("B_setups", "qqq_put_b1")

=== QQQ_PUT_B1 (B_setups) ===
BIAS : NO TRADE
SETUP_TYPE : No Trade
GRADE : C
KEY_LEVEL : QQQ 486.00
ENTRY_TRIGGER : None
INVALIDATION : None
TARGETS : None
CONFIDENCE : 20
REASONS : ['Conditions are not clean enough']
RISKS : ['Chop / weak structure / poor confirmation']
FINAL_DECISION : NO TRADE

In [ ]:
saved_trades = {
    "A_plus": {
        "qqq_put_a1": {
            "level": "resistance",
            "reaction": "rejection",
            "vwap": "below",
            "rsi": 42,
            "volume": "high",
            "market": "clean",
            "test": "first",
            "key_level": "QQQ 485.20"
        },
        "qqq_call_a1": {
            "level": "support",
            "reaction": "retest_hold",
            "vwap": "above",
            "rsi": 58,
            "volume": "high",
            "market": "clean",
            "test": "first",
            "key_level": "QQQ 482.10"
        }
    },

    "B_setups": {
        "qqq_put_b1": {
            "level": "resistance",
            "reaction": "rejection",
            "vwap": "below",
            "rsi": 47,
            "volume": "low",
            "market": "clean",
            "test": "second",
            "key_level": "QQQ 486.00"
        },
        "qqq_call_b1": {
            "level": "support",
            "reaction": "retest_hold",
            "vwap": "above",
            "rsi": 52,
            "volume": "low",
            "market": "clean",
            "test": "second",
            "key_level": "QQQ 481.50"
        }
    },

    "No_trade": {
        "chop_1": {
            "level": "unclear",
            "reaction": "none",
            "vwap": "flip",
            "rsi": 49,
            "volume": "low",
            "market": "chop",
            "test": "second",
            "key_level": "None"
        }
    }
}

In [ ]:
"B_setups": {
    "qqq_put_b1": {
        "level": "resistance",
        "reaction": "rejection",
        "vwap": "below",
        "rsi": 47,              # weaker momentum
        "volume": "low",        # missing volume
        "market": "clean",
        "test": "second",       # weaker test
        "key_level": "QQQ 486.00"
    },
    "qqq_call_b1": {
        "level": "support",
        "reaction": "retest_hold",
        "vwap": "above",
        "rsi": 52,              # barely bullish
        "volume": "low",
        "market": "clean",
        "test": "second",
        "key_level": "QQQ 481.50"
    }
}

SyntaxError: illegal target for annotation (3020455379.py, line 1)

In [ ]:
run_saved_trade("A_plus", "qqq_put_a1")

=== QQQ_PUT_A1 (A_plus) ===
BIAS : PUT
SETUP_TYPE : Rejection
GRADE : A+
KEY_LEVEL : QQQ 485.20
ENTRY_TRIGGER : Rejection candle confirms or lower high fails
INVALIDATION : Break above rejection high / reclaimed level
TARGETS : Next support / next key level
CONFIDENCE : 100
REASONS : ['Rejection at resistance', 'Bearish VWAP control', 'Bearish momentum', 'Volume confirmation', 'First test of level']
RISKS : []
FINAL_DECISION : PUT

In [ ]:
def run_saved_trade(category, name):
    trade = saved_trades[category][name]
    result = analyze_structured_trade(trade)

    print(f"\n=== {name.upper()} ({category}) ===")
    for k, v in result.items():
        print(k.upper(), ":", v)

In [ ]:
saved_trades = {
    "A_plus": {
        "qqq_put_a1": {
            "level": "resistance",
            "reaction": "rejection",
            "vwap": "below",
            "rsi": 42,
            "volume": "high",
            "market": "clean",
            "test": "first",
            "key_level": "QQQ 485.20"
        }
    },

    "B_setups": {
        "qqq_put_b1": {
            "level": "resistance",
            "reaction": "rejection",
            "vwap": "below",
            "rsi": 47,
            "volume": "low",
            "market": "clean",
            "test": "second",
            "key_level": "QQQ 486.00"
        }
    },

    "No_trade": {
        "chop_1": {
            "level": "unclear",
            "reaction": "none",
            "vwap": "flip",
            "rsi": 49,
            "volume": "low",
            "market": "chop",
            "test": "second",
            "key_level": "None"
        }
    }
}

In [ ]:
print(saved_trades.keys())

dict_keys(['A_plus', 'No_trade'])

In [ ]:
saved_trades = {
    "A_plus": {
        "qqq_put_a1": {
            "level": "resistance",
            "reaction": "rejection",
            "vwap": "below",
            "rsi": 45,
            "volume": "high",
            "market": "clean",
            "test": "first",
            "key_level": "QQQ 485.20"
        },
        "qqq_call_a1": {
            "level": "support",
            "reaction": "retest_hold",
            "vwap": "above",
            "rsi": 58,
            "volume": "high",
            "market": "clean",
            "test": "first",
            "key_level": "QQQ 482.10"
        }
    },

    "No_trade": {
        "chop_1": {
            "level": "unclear",
            "reaction": "none",
            "vwap": "flip",
            "rsi": 49,
            "volume": "low",
            "market": "chop",
            "test": "second",
            "key_level": "None"
        }
    }
}

In [ ]:
result = analyze_structured_trade(saved_trades["qqq_put_example"])

for k, v in result.items():
    print(k.upper(), ":", v)

BIAS : PUT
SETUP_TYPE : Rejection
GRADE : A+
KEY_LEVEL : QQQ 485.20
ENTRY_TRIGGER : Rejection candle confirms or lower high fails
INVALIDATION : Break above rejection high / reclaimed level
TARGETS : Next support / next key level
CONFIDENCE : 100
REASONS : ['Rejection at resistance', 'Bearish VWAP control', 'Bearish momentum', 'Volume confirmation', 'First test of level']
RISKS : []
FINAL_DECISION : PUT

In [ ]:
saved_trades = {
    "qqq_put_example": {
        "level": "resistance",
        "reaction": "rejection",
        "vwap": "below",
        "rsi": 45,
        "volume": "high",
        "market": "clean",
        "test": "first",
        "key_level": "QQQ 485.20"
    },
    "qqq_call_example": {
        "level": "support",
        "reaction": "retest_hold",
        "vwap": "above",
        "rsi": 58,
        "volume": "high",
        "market": "clean",
        "test": "first",
        "key_level": "QQQ 482.10"
    },
    "no_trade_example": {
        "level": "unclear",
        "reaction": "none",
        "vwap": "flip",
        "rsi": 49,
        "volume": "low",
        "market": "chop",
        "test": "second",
        "key_level": "None"
    }
}

print(saved_trades.keys())

dict_keys(['qqq_put_example', 'qqq_call_example', 'no_trade_example'])

In [ ]:
analyze_from_template(
    "resistance",
    "rejection",
    "below",
    45,
    "high",
    "clean",
    "first",
    "QQQ 485.20"
)

=== ANALYSIS ===
BIAS : PUT
SETUP_TYPE : Rejection
GRADE : A+
KEY_LEVEL : QQQ 485.20
ENTRY_TRIGGER : Rejection candle confirms or lower high fails
INVALIDATION : Break above rejection high / reclaimed level
TARGETS : Next support / next key level
CONFIDENCE : 100
REASONS : ['Rejection at resistance', 'Bearish VWAP control', 'Bearish momentum', 'Volume confirmation', 'First test of level']
RISKS : []
FINAL_DECISION : PUT

In [ ]:
def analyze_from_template(level, reaction, vwap, rsi, volume, market, test, key_level):
    trade = {
        "level": level,
        "reaction": reaction,
        "vwap": vwap,
        "rsi": rsi,
        "volume": volume,
        "market": market,
        "test": test,
        "key_level": key_level
    }

    result = analyze_structured_trade(trade)

    print("\n=== ANALYSIS ===")
    for k, v in result.items():
        print(k.upper(), ":", v)

In [ ]:
def analyze_from_template(level, reaction, vwap, rsi, volume, market, test, key_level):
    trade = {
        "level": level,
        "reaction": reaction,
        "vwap": vwap,
        "rsi": rsi,
        "volume": volume,
        "market": market,
        "test": test,
        "key_level": key_level
    }

    result = analyze_structured_trade(trade)

    print("\n=== ANALYSIS ===")
    for k, v in result.items():
        print(k.upper(), ":", v)

    return result

In [ ]:
quick_trade = {
    "level": "resistance",
    "reaction": "rejection",
    "vwap": "below",
    "rsi": 45,
    "volume": "high",
    "market": "clean",
    "test": "first",
    "key_level": "QQQ 485.20"
}

result = analyze_structured_trade(quick_trade)

print("\n=== QUICK RESULT ===")
for k, v in result.items():
    print(k.upper(), ":", v)

=== QUICK RESULT ===
BIAS : PUT
SETUP_TYPE : Rejection
GRADE : A+
KEY_LEVEL : QQQ 485.20
ENTRY_TRIGGER : Rejection candle confirms or lower high fails
INVALIDATION : Break above rejection high / reclaimed level
TARGETS : Next support / next key level
CONFIDENCE : 100
REASONS : ['Rejection at resistance', 'Bearish VWAP control', 'Bearish momentum', 'Volume confirmation', 'First test of level']
RISKS : []
FINAL_DECISION : PUT

In [ ]:
run_live_analyzer()

=== UnBiased Trades AI Analyzer ===
Level (support/resistance/unclear): resistance
Reaction (rejection/break_hold/retest_hold/lower_high/none): rejection
VWAP (above/below/flip): below
RSI value (number): 45
Volume (high/low): high
Market condition (clean/chop/sideways/news/extended): clean
Test (first/second/third): first
Key level (ex: QQQ 485.20): QQQ 485.20

=== RESULT ===
BIAS : PUT
SETUP_TYPE : Rejection
GRADE : A+
KEY_LEVEL : QQQ 485.20
ENTRY_TRIGGER : Rejection candle confirms or lower high fails
INVALIDATION : Break above rejection high / reclaimed level
TARGETS : Next support / next key level
CONFIDENCE : 100
REASONS : ['Rejection at resistance', 'Bearish VWAP control', 'Bearish momentum', 'Volume confirmation', 'First test of level']
RISKS : []
FINAL_DECISION : PUT

In [ ]:
def run_live_analyzer():
    print("=== UnBiased Trades AI Analyzer ===")

    trade = {}

    trade["level"] = input("Level (support/resistance/unclear): ").lower()
    trade["reaction"] = input("Reaction (rejection/break_hold/retest_hold/lower_high/none): ").lower()
    trade["vwap"] = input("VWAP (above/below/flip): ").lower()
    trade["rsi"] = int(input("RSI value (number): "))
    trade["volume"] = input("Volume (high/low): ").lower()
    trade["market"] = input("Market condition (clean/chop/sideways/news/extended): ").lower()
    trade["test"] = input("Test (first/second/third): ").lower()
    trade["key_level"] = input("Key level (ex: QQQ 485.20): ")

    result = analyze_structured_trade(trade)

    print("\n=== RESULT ===")
    for k, v in result.items():
        print(k.upper(), ":", v)

In [ ]:
# MASTER ANALYZER

In [ ]:
test_trades = [
    {
        "name": "PUT test",
        "trade": {
            "level": "resistance",
            "reaction": "rejection",
            "vwap": "below",
            "rsi": 45,
            "volume": "high",
            "market": "clean",
            "test": "first",
            "key_level": "QQQ 485.20"
        }
    },
    {
        "name": "CALL test",
        "trade": {
            "level": "support",
            "reaction": "retest_hold",
            "vwap": "above",
            "rsi": 58,
            "volume": "high",
            "market": "clean",
            "test": "first",
            "key_level": "QQQ 482.10"
        }
    },
    {
        "name": "NO TRADE test",
        "trade": {
            "level": "unclear",
            "reaction": "none",
            "vwap": "flip",
            "rsi": 49,
            "volume": "low",
            "market": "chop",
            "test": "second",
            "key_level": "None"
        }
    }
]

for item in test_trades:
    print("\n" + "="*50)
    print(item["name"])
    print("="*50)

    result = analyze_structured_trade(item["trade"])

    for k, v in result.items():
        print(k.upper(), ":", v)

==================================================
PUT test
==================================================
BIAS : PUT
SETUP_TYPE : Rejection
GRADE : A+
KEY_LEVEL : QQQ 485.20
ENTRY_TRIGGER : Rejection candle confirms or lower high fails
INVALIDATION : Break above rejection high / reclaimed level
TARGETS : Next support / next key level
CONFIDENCE : 100
REASONS : ['Rejection at resistance', 'Bearish VWAP control', 'Bearish momentum', 'Volume confirmation', 'First test of level']
RISKS : []
FINAL_DECISION : PUT

==================================================
CALL test
==================================================
BIAS : CALL
SETUP_TYPE : Retest Hold
GRADE : A+
KEY_LEVEL : QQQ 482.10
ENTRY_TRIGGER : Break holds or retest bounce confirms
INVALIDATION : Loss of breakout level / retest low
TARGETS : Next resistance / next key level
CONFIDENCE : 100
REASONS : ['Retest held at support', 'Bullish VWAP control', 'Bullish momentum', 'Volume confirmation', 'First test of level']
RISKS : []
FINAL_DECISION : CALL

==================================================
NO TRADE test
==================================================
BIAS : NO TRADE
SETUP_TYPE : No Trade
GRADE : C
KEY_LEVEL : None
ENTRY_TRIGGER : None
INVALIDATION : None
TARGETS : None
CONFIDENCE : 20
REASONS : ['Conditions are not clean enough']
RISKS : ['Chop / weak structure / poor confirmation']
FINAL_DECISION : NO TRADE

In [ ]:
trade = {
    "level": "resistance",
    "reaction": "rejection",
    "vwap": "below",
    "rsi": 45,
    "volume": "high",
    "market": "clean",
    "test": "first",
    "key_level": "QQQ 485.20"
}

result = analyze_structured_trade(trade)

for k, v in result.items():
    print(k.upper(), ":", v)

BIAS : PUT
SETUP_TYPE : Rejection
GRADE : A+
KEY_LEVEL : QQQ 485.20
ENTRY_TRIGGER : Rejection candle confirms or lower high fails
INVALIDATION : Break above rejection high / reclaimed level
TARGETS : Next support / next key level
CONFIDENCE : 100
REASONS : ['Rejection at resistance', 'Bearish VWAP control', 'Bearish momentum', 'Volume confirmation', 'First test of level']
RISKS : []
FINAL_DECISION : PUT

In [ ]:
def analyze_structured_trade(data):
    score = 0
    reasons = []
    risks = []

    bias = "NO TRADE"
    setup_type = "None"
    grade = "C"
    confidence = 0

    level = data.get("level", "").lower()
    reaction = data.get("reaction", "").lower()
    vwap = data.get("vwap", "").lower()
    rsi = data.get("rsi", 50)
    volume = data.get("volume", "").lower()
    market = data.get("market", "").lower()
    test = str(data.get("test", "")).lower()
    key_level = data.get("key_level", "User-defined")

    # No-trade conditions
    no_trade_words = ["chop", "sideways", "indecision", "news", "extended", "unclear"]
    if market in no_trade_words or vwap == "flip" or level == "unclear" or volume == "low":
        return {
            "bias": "NO TRADE",
            "setup_type": "No Trade",
            "grade": "C",
            "key_level": key_level,
            "entry_trigger": "None",
            "invalidation": "None",
            "targets": "None",
            "confidence": 20,
            "reasons": ["Conditions are not clean enough"],
            "risks": ["Chop / weak structure / poor confirmation"],
            "final_decision": "NO TRADE"
        }

    # Level + reaction
    if level == "resistance" and reaction == "rejection":
        score += 2
        bias = "PUT"
        setup_type = "Rejection"
        reasons.append("Rejection at resistance")

    elif level == "resistance" and reaction == "break_hold":
        score += 2
        bias = "CALL"
        setup_type = "Break and Hold"
        reasons.append("Break and hold above resistance")

    elif level == "support" and reaction == "retest_hold":
        score += 2
        bias = "CALL"
        setup_type = "Retest Hold"
        reasons.append("Retest held at support")

    elif level == "resistance" and reaction == "lower_high":
        score += 2
        bias = "PUT"
        setup_type = "Failed Bounce / Lower High"
        reasons.append("Lower high rejection at resistance")

    # VWAP
    if vwap == "below":
        score += 2
        reasons.append("Bearish VWAP control")
    elif vwap == "above":
        score += 2
        reasons.append("Bullish VWAP control")

    # RSI
    if rsi < 50:
        score += 1
        reasons.append("Bearish momentum")
    elif rsi > 50:
        score += 1
        reasons.append("Bullish momentum")

    # Volume
    if volume == "high":
        score += 1
        reasons.append("Volume confirmation")
    elif volume != "high":
        risks.append("No strong volume confirmation")

    # Test number
    if test == "first":
        score += 1
        reasons.append("First test of level")
    elif test == "third":
        risks.append("Third test may be weaker / more likely to break")

    # Grade
    if score >= 6:
        grade = "A+"
    elif score >= 4:
        grade = "B"
    else:
        grade = "C"

    confidence = min(100, score * 15)

    # Entry / invalidation / targets
    if bias == "CALL":
        entry_trigger = "Break holds or retest bounce confirms"
        invalidation = "Loss of breakout level / retest low"
        targets = "Next resistance / next key level"
    elif bias == "PUT":
        entry_trigger = "Rejection candle confirms or lower high fails"
        invalidation = "Break above rejection high / reclaimed level"
        targets = "Next support / next key level"
    else:
        entry_trigger = "None"
        invalidation = "None"
        targets = "None"

    # Final decision
    if grade == "C":
        final_decision = "NO TRADE"
    else:
        final_decision = bias

    return {
        "bias": bias,
        "setup_type": setup_type,
        "grade": grade,
        "key_level": key_level,
        "entry_trigger": entry_trigger,
        "invalidation": invalidation,
        "targets": targets,
        "confidence": confidence,
        "reasons": reasons,
        "risks": risks,
        "final_decision": final_decision
    }

In [ ]:
trade = {
    "level": "resistance",
    "reaction": "rejection",
    "vwap": "below",
    "rsi": 45,
    "volume": "high"
}

result = analyze_structured_trade(trade)

for k, v in result.items():
    print(k.upper(), ":", v)

BIAS : PUT
SETUP_TYPE : Rejection
GRADE : A+
CONFIDENCE : 90
REASONS : ['Rejection at resistance', 'Bearish VWAP control', 'Bearish momentum', 'Volume confirmation']
FINAL_DECISION : PUT

In [ ]:
def analyze_structured_trade(data):
    score = 0
    reasons = []
    risks = []

    # --- LEVEL ---
    if data["level"] == "resistance" and data["reaction"] == "rejection":
        score += 2
        reasons.append("Rejection at resistance")

    if data["level"] == "resistance" and data["reaction"] == "break_hold":
        score += 2
        reasons.append("Break and hold above resistance")

    # --- VWAP ---
    if data["vwap"] == "below":
        score += 2
        reasons.append("Bearish VWAP control")

    elif data["vwap"] == "above":
        score += 2
        reasons.append("Bullish VWAP control")

    # --- RSI ---
    if data["rsi"] < 50:
        score += 1
        reasons.append("Bearish momentum")

    elif data["rsi"] > 50:
        score += 1
        reasons.append("Bullish momentum")

    # --- VOLUME ---
    if data["volume"] == "high":
        score += 1
        reasons.append("Volume confirmation")

    # --- DETERMINE BIAS ---
    if data["reaction"] == "rejection":
        bias = "PUT"
        setup_type = "Rejection"
    elif data["reaction"] == "break_hold":
        bias = "CALL"
        setup_type = "Break and Hold"
    else:
        bias = "NEUTRAL"
        setup_type = "Unclear"

    # --- GRADE ---
    if score >= 6:
        grade = "A+"
    elif score >= 4:
        grade = "B"
    else:
        grade = "C"

    confidence = min(100, score * 15)

    if grade == "C":
        decision = "NO TRADE"
    else:
        decision = bias

    return {
        "bias": bias,
        "setup_type": setup_type,
        "grade": grade,
        "confidence": confidence,
        "reasons": reasons,
        "final_decision": decision
    }

In [ ]:
result = analyze_trade("Resistance, rejection, VWAP reject, RSI below 50, volume spike")

for key, value in result.items():
    print(f"{key.upper()}: {value}")

BIAS: PUT
SETUP_TYPE: Rejection
GRADE: A+
KEY_LEVEL: User-defined
ENTRY_TRIGGER: Confirmation candle / retest
INVALIDATION: Break of level / opposite structure
TARGETS: Next key level
CONFIDENCE: 90
REASONS: ['Bearish VWAP control', 'Bearish momentum', 'Rejection at level', 'Volume confirmation']
RISKS: []
FINAL_DECISION: PUT

In [ ]:
def analyze_trade(setup):
    setup = setup.lower()

    score = 0
    reasons = []
    risks = []

    # --- NO TRADE CONDITIONS ---
    no_trade_conditions = [
        "midday", "chop", "sideways", "vwap flipping", "indecision",
        "no volume", "no level", "extended", "news"
    ]

    for cond in no_trade_conditions:
        if cond in setup:
            return {
                "bias": "NEUTRAL",
                "setup_type": "NONE",
                "grade": "N/A",
                "key_level": "unclear",
                "entry_trigger": "none",
                "invalidation": "none",
                "targets": "none",
                "confidence": 20,
                "reasons": ["Market conditions not tradable"],
                "risks": ["Chop / no structure"],
                "final_decision": "NO TRADE"
            }

    # --- VWAP ---
    if "above vwap" in setup or "vwap support" in setup:
        score += 2
        reasons.append("Bullish VWAP control")

    if "below vwap" in setup or "vwap reject" in setup:
        score += 2
        reasons.append("Bearish VWAP control")

    # --- RSI ---
    if "rsi above 50" in setup or "rsi 55" in setup or "rsi 60" in setup:
        score += 1
        reasons.append("Bullish momentum")

    if "rsi below 50" in setup or "rsi 40" in setup:
        score += 1
        reasons.append("Bearish momentum")

    # --- PRICE ACTION ---
    if "break and hold" in setup or "breakout" in setup:
        score += 2
        reasons.append("Break and hold behavior")

    if "retest hold" in setup:
        score += 2
        reasons.append("Successful retest")

    if "rejection" in setup or "wick" in setup:
        score += 2
        reasons.append("Rejection at level")

    if "lower high" in setup:
        score += 1
        reasons.append("Weak structure")

    # --- VOLUME ---
    if "volume" in setup:
        score += 1
        reasons.append("Volume confirmation")

    # --- DETERMINE BIAS ---
    if "rejection" in setup or "lower high" in setup:
        bias = "PUT"
        setup_type = "Rejection"

    elif "break" in setup or "hold" in setup:
        bias = "CALL"
        setup_type = "Break and Hold"

    else:
        bias = "NEUTRAL"
        setup_type = "Unclear"

    # --- GRADE ---
    if score >= 6:
        grade = "A+"
    elif score >= 4:
        grade = "B"
    else:
        grade = "C"

    # --- CONFIDENCE ---
    confidence = min(100, score * 15)

    # --- RISK FLAGS ---
    if score < 4:
        risks.append("Weak confluence")

    if "extended" in setup:
        risks.append("Late entry risk")

    # --- FINAL DECISION ---
    if grade == "C":
        decision = "NO TRADE"
    elif bias == "CALL":
        decision = "CALL"
    elif bias == "PUT":
        decision = "PUT"
    else:
        decision = "NO TRADE"

    return {
        "bias": bias,
        "setup_type": setup_type,
        "grade": grade,
        "key_level": "User-defined",
        "entry_trigger": "Confirmation candle / retest",
        "invalidation": "Break of level / opposite structure",
        "targets": "Next key level",
        "confidence": confidence,
        "reasons": reasons,
        "risks": risks,
        "final_decision": decision
    }

In [ ]:
while True:
    user_input = input("Describe the setup (or type 'exit'): ")

    if user_input.lower() == "exit":
        print("Exiting analyzer.")
        break

    result = analyze_setup(user_input)
    print(result)

KeyboardInterrupt: Interrupted by user

In [ ]:
print(analyze_setup("Price rejects resistance, VWAP reject, RSI below 50, volume spike"))

Setup: PUT
Grade: A+
Confidence Score: 5/7

Reasons:
- VWAP bearish control
- Bearish momentum
- Rejection at level

In [ ]:
def analyze_setup(user_input):
    user_input = user_input.lower()

    score = 0
    reasons = []

    # VWAP logic
    if "vwap reject" in user_input or "below vwap" in user_input:
        score += 2
        reasons.append("VWAP bearish control")

    if "vwap support" in user_input or "above vwap" in user_input:
        score += 2
        reasons.append("VWAP bullish control")

    # RSI logic
    if "rsi below 50" in user_input:
        score += 1
        reasons.append("Bearish momentum")

    if "rsi above 50" in user_input:
        score += 1
        reasons.append("Bullish momentum")

    # Price action
    if "reject" in user_input:
        score += 2
        reasons.append("Rejection at level")

    if "break" in user_input and "hold" in user_input:
        score += 2
        reasons.append("Break and hold")

    # Market condition
    if "sideways" in user_input or "chop" in user_input:
        return "❌ No Trade — Market is in chop (low probability)"

    # Determine bias
    if "reject" in user_input:
        bias = "PUT"
    elif "break" in user_input:
        bias = "CALL"
    else:
        bias = "NEUTRAL"

    # Grade setup
    if score >= 5:
        grade = "A+"
    elif score >= 3:
        grade = "B"
    else:
        grade = "C"

    return f"""
Setup: {bias}
Grade: {grade}
Confidence Score: {score}/7

Reasons:
- {"\n- ".join(reasons)}
"""

In [ ]:
print(analyze_setup("Price rejects resistance, VWAP rejects, RSI below 50"))

Bearish bias → Possible PUT setup. Wait for confirmation.

In [ ]:
def analyze_setup(user_input):
    user_input = user_input.lower()

    if "reject" in user_input and "vwap" in user_input:
        return "Bearish bias → Possible PUT setup. Wait for confirmation."

    elif "break" in user_input and "hold" in user_input:
        return "Bullish bias → Possible CALL setup. Look for continuation."

    elif "sideways" in user_input or "chop" in user_input:
        return "No trade → Market conditions are not clean."

    elif "first test" in user_input:
        return "High probability level → Watch reaction closely."

    else:
        return "No clear setup → Wait for better structure."

In [ ]:
training_data = [
    {
        "input": "Price rejects resistance with wick, closes below, VWAP rejects, RSI below 50",
        "output": "Bearish rejection. Look for put entries. Sellers in control."
    },
    {
        "input": "Strong break above resistance, holds above level, VWAP support, RSI above 50",
        "output": "Bullish breakout. Look for call entries. Buyers in control."
    },
    {
        "input": "Price moving sideways, VWAP flipping, small candles, no volume",
        "output": "No trade. Market is in chop, no institutional control."
    },
    {
        "input": "First test of key level with strong rejection and volume spike",
        "output": "High probability reaction. Consider entry based on direction of rejection."
    }
]

print(training_data)

[{'input': 'Price rejects resistance with wick, closes below, VWAP rejects, RSI below 50', 'output': 'Bearish rejection. Look for put entries. Sellers in control.'}, {'input': 'Strong break above resistance, holds above level, VWAP support, RSI above 50', 'output': 'Bullish breakout. Look for call entries. Buyers in control.'}, {'input': 'Price moving sideways, VWAP flipping, small candles, no volume', 'output': 'No trade. Market is in chop, no institutional control.'}, {'input': 'First test of key level with strong rejection and volume spike', 'output': 'High probability reaction. Consider entry based on direction of rejection.'}]

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving JT313_strategy.pdf to JT313_strategy (1).pdf

In [ ]:
 !pip install pypdf

from pypdf import PdfReader

reader = PdfReader("JT313_strategy.pdf")
text = ""

for page in reader.pages:
    page_text = page.extract_text()
    if page_text:
        text += page_text + "\n\n"

print(text[:3000])

Requirement already satisfied: pypdf in /usr/local/lib/python3.12/dist-packages (6.10.0)
Elite Trading Analyzer
Strategy Diagnostic Report — Client JT313
April 9, 2026 · Confidential · 7 diagnostic exchanges · Coverage 100%
Section 01 — Instruments & Markets
JT313 trades exclusively large-cap index ETF options with a primary focus on QQQ (Invesco QQQ Trust,
NASDAQ) and secondary use of SPY (SPDR S&P; 500 ETF Trust, NYSE Arca). Options are traded via OPRA.
The core instrument is 0DTE (zero days to expiration) and weekly expiration contracts, specifically ATM or
slightly ITM calls and puts traded intraday.
Secondary instruments are used for market sentiment and sector strength confirmation rather than primary
trading. These include large-cap tech and momentum equities — Meta, Tesla, NVIDIA, and C3.ai — as well as
energy sector names (ExxonMobil, Chevron, ConocoPhillips, XLE) for macro-driven directional bias. Airlines
(American, Delta, Southwest, United) are watched as inverse oil trade setups. Macro instruments including WTI
crude oil futures, SPDR Gold Shares, and iShares Silver Trust serve as institutional behavior predictors.
Crypto-linked equities (IREN, iShares Bitcoin Trust) are monitored for sentiment and volatility context only.
The client explicitly avoids forex, small caps, low float stocks, direct crypto trading, and illiquid options chains.
The system identity in one line: trading large-cap index ETF options using institutional flow, macro correlations,
and key liquidity levels to execute high-probability intraday setups.
Section 02 — Setup Identification Process
Setup identification follows a strict top-down process with six sequential steps. The process never begins with
chart scanning — it begins with macro narrative.
Step 1 — Macro narrative
Before any chart is opened, the client assesses what is moving the market. This includes WTI crude oil price
movement, breaking news (geopolitics, Fed decisions, economic data releases), and overnight futures
sentiment. Platforms used: Bloomberg and Reuters feeds via Discord automation, TradingView for futures and
oil charts, and browser tabs for fast news scanning. The goal is understanding the story institutions are reacting
to.
Step 2 — Key level identification
Charts are opened with specific intent — immediately marking previous day high and low, premarket high and
low, strong support and resistance levels, and institutional levels identified through large prints and liquidity


zones. Platforms: TradingView as primary charting tool, Tradytics for options flow and dark pool data. The key
question at this stage: where is the money most likely sitting.
Step 3 — Price behavior at levels
The client does not chase price. After marking levels, the approach is to wait and observe how price reacts
when it arrives. Three behaviors are watched: hard rejection (wicks and failure), break and hold (continuation),
or fakeout (liquidity grab). Setups are born at this stage, not before.
Step 4 — Momentum and confirmation
Confirmation indicators are layered on top of price behavior: VWAP (above

In [ ]:
sections = text.split("Section ")
for s in sections[:5]:
    print("SECTION:")
    print(s[:1000])
    print("\n" + "="*80 + "\n")

SECTION:
Elite Trading Analyzer
Strategy Diagnostic Report — Client JT313
April 9, 2026 · Confidential · 7 diagnostic exchanges · Coverage 100%


================================================================================

SECTION:
01 — Instruments & Markets
JT313 trades exclusively large-cap index ETF options with a primary focus on QQQ (Invesco QQQ Trust,
NASDAQ) and secondary use of SPY (SPDR S&P; 500 ETF Trust, NYSE Arca). Options are traded via OPRA.
The core instrument is 0DTE (zero days to expiration) and weekly expiration contracts, specifically ATM or
slightly ITM calls and puts traded intraday.
Secondary instruments are used for market sentiment and sector strength confirmation rather than primary
trading. These include large-cap tech and momentum equities — Meta, Tesla, NVIDIA, and C3.ai — as well as
energy sector names (ExxonMobil, Chevron, ConocoPhillips, XLE) for macro-driven directional bias. Airlines
(American, Delta, Southwest, United) are watched as inverse oil trade setups. Macro instruments including WTI
crude oil futures, SPDR Gold Shares, and iShares Silver Trust serve as institutional behavior predictors.
Crypto-linked equities (IREN, iShares Bitcoin Trust) are monitored for sentiment and v

================================================================================

SECTION:
02 — Setup Identification Process
Setup identification follows a strict top-down process with six sequential steps. The process never begins with
chart scanning — it begins with macro narrative.
Step 1 — Macro narrative
Before any chart is opened, the client assesses what is moving the market. This includes WTI crude oil price
movement, breaking news (geopolitics, Fed decisions, economic data releases), and overnight futures
sentiment. Platforms used: Bloomberg and Reuters feeds via Discord automation, TradingView for futures and
oil charts, and browser tabs for fast news scanning. The goal is understanding the story institutions are reacting
to.
Step 2 — Key level identification
Charts are opened with specific intent — immediately marking previous day high and low, premarket high and
low, strong support and resistance levels, and institutional levels identified through large prints and liquidity


zones. Platforms: TradingView as primary charting tool, Tradytics for options flow and d

================================================================================

SECTION:
03 — Timeframe Framework
The core principle governing timeframe use: levels do not change, timeframes only change perspective. Three
timeframes are used simultaneously, each with a distinct role.
4-hour chart provides market structure context — major support and resistance, overall trend direction (bullish,
bearish, or ranging), and key institutional zones. This answers where we are in the bigger picture.
15-minute chart frames the actual setup. It shows intraday trend, consolidation zones, breakout or rejection
areas, and alignment with 4H levels. This is where the trade idea forms. Three things must be confirmed on the
15M before an entry is valid: price location relative to 15M levels, structure (higher highs and higher lows for
bullish bias, lower highs and lower lows for bearish), and signs of strength versus weakness (strong bullish
candles and VWAP holds versus long upper wicks and momentum slowing).
5-minute chart is the primary entry chart. It provides entry confirmation, reac

================================================================================

SECTION:
04 — Entry Criteria
The governing principle: entries are based on how price behaves at a level, not merely that price has reached a
level. Minimum 3 of 5 criteria must align for a valid setup.
Put setup — rejection criteria
A true rejection requires at least 3 of the following 5: (1) wick through the resistance level with close back below
— signals liquidity grab and failure; (2) follow-through weakness where the next candle does not reclaim the
level and often forms a lower high, confirming sellers are present; (3) VWAP rejection where price loses VWAP
or rejects near it, indicating institutions are not supporting higher prices; (4) volume spike on the rejection
candle confirming real selling rather than random price movement; (5) momentum shift where RSI rolls over
and MACD begins flattening or crossing down.
Entry trigger for puts: rejection candle closes AND next candle confirms weakness. Entry point is the break of
the rejection candle low or a failed retest of the level.
Call set

================================================================================

In [ ]:
!pip install pypdf

from pypdf import PdfReader

reader = PdfReader("JT313_strategy.pdf")
text = ""

for page in reader.pages:
    page_text = page.extract_text()
    if page_text:
        text += page_text + "\n\n"

print(text[:5000])

Collecting pypdf
  Downloading pypdf-6.10.0-py3-none-any.whl.metadata (7.1 kB)
Downloading pypdf-6.10.0-py3-none-any.whl (334 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 334.5/334.5 kB 8.5 MB/s eta 0:00:00
Installing collected packages: pypdf
Successfully installed pypdf-6.10.0
Elite Trading Analyzer
Strategy Diagnostic Report — Client JT313
April 9, 2026 · Confidential · 7 diagnostic exchanges · Coverage 100%
Section 01 — Instruments & Markets
JT313 trades exclusively large-cap index ETF options with a primary focus on QQQ (Invesco QQQ Trust,
NASDAQ) and secondary use of SPY (SPDR S&P; 500 ETF Trust, NYSE Arca). Options are traded via OPRA.
The core instrument is 0DTE (zero days to expiration) and weekly expiration contracts, specifically ATM or
slightly ITM calls and puts traded intraday.
Secondary instruments are used for market sentiment and sector strength confirmation rather than primary
trading. These include large-cap tech and momentum equities — Meta, Tesla, NVIDIA, and C3.ai — as well as
energy sector names (ExxonMobil, Chevron, ConocoPhillips, XLE) for macro-driven directional bias. Airlines
(American, Delta, Southwest, United) are watched as inverse oil trade setups. Macro instruments including WTI
crude oil futures, SPDR Gold Shares, and iShares Silver Trust serve as institutional behavior predictors.
Crypto-linked equities (IREN, iShares Bitcoin Trust) are monitored for sentiment and volatility context only.
The client explicitly avoids forex, small caps, low float stocks, direct crypto trading, and illiquid options chains.
The system identity in one line: trading large-cap index ETF options using institutional flow, macro correlations,
and key liquidity levels to execute high-probability intraday setups.
Section 02 — Setup Identification Process
Setup identification follows a strict top-down process with six sequential steps. The process never begins with
chart scanning — it begins with macro narrative.
Step 1 — Macro narrative
Before any chart is opened, the client assesses what is moving the market. This includes WTI crude oil price
movement, breaking news (geopolitics, Fed decisions, economic data releases), and overnight futures
sentiment. Platforms used: Bloomberg and Reuters feeds via Discord automation, TradingView for futures and
oil charts, and browser tabs for fast news scanning. The goal is understanding the story institutions are reacting
to.
Step 2 — Key level identification
Charts are opened with specific intent — immediately marking previous day high and low, premarket high and
low, strong support and resistance levels, and institutional levels identified through large prints and liquidity


zones. Platforms: TradingView as primary charting tool, Tradytics for options flow and dark pool data. The key
question at this stage: where is the money most likely sitting.
Step 3 — Price behavior at levels
The client does not chase price. After marking levels, the approach is to wait and observe how price reacts
when it arrives. Three behaviors are watched: hard rejection (wicks and failure), break and hold (continuation),
or fakeout (liquidity grab). Setups are born at this stage, not before.
Step 4 — Momentum and confirmation
Confirmation indicators are layered on top of price behavior: VWAP (above = bullish control, below = bearish
control), RSI for entry timing, Bollinger Bands (expansion signals move happening, compression signals move
coming), and volume to confirm institutional participation. All via TradingView.
Step 5 — Institutional context
This is described as the real edge. The client evaluates where large orders hit, whether price has returned to
those levels, and whether the behavior indicates accumulation, distribution, or a liquidity sweep. Tradytics is the
primary tool for flow and dark pool analysis. Core mental model: if institutions bought here yesterday, they will
defend or retest this level today.
Step 6 — Single trade idea
The process narrows to one trade on QQQ, sometimes SPY. The questions asked: where is price relative to
key levels, what is the most likely next move, and where is risk smallest relative to reward. The client explicitly
does not scan multiple tickers, chase trending stocks, rely on indicators alone, or enter without a defined level.


Section 03 — Timeframe Framework
The core principle governing timeframe use: levels do not change, timeframes only change perspective. Three
timeframes are used simultaneously, each with a distinct role.
4-hour chart provides market structure context — major support and resistance, overall trend direction (bullish,
bearish, or ranging), and key institutional zones. This answers where we are in the bigger picture.
15-minute chart frames the actual setup. It shows intraday trend, consolidation zones, breakout or rejection
areas, and alignment with 4H levels. This is where the trade idea forms. Three things must be confirmed on the
15M before an entry is valid: price location relative to 15M levels, structure (higher highs and higher lows for
bullish bias, lower highs and lower lows for bearish), and signs of strength versus weakness (strong bullish
candles and VWAP holds versus long upper wicks and momentum slowing).
5-minute chart is the primary entry chart. It provides entry confirmation,

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving JT313_strategy.pdf to JT313_strategy.pdf